'use strict';
(function(){
  const ROOT=document.querySelector('#portal'),CFG=window.MCLAY_CONFIG||{},DEVICE_KEY='msos_swimmer_device_token_v1',ATHLETE_KEY='msos_swimmer_athlete_id_v1';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const clock=v=>{const n=Number(v);if(!Number.isFinite(n))return'—';const m=Math.floor(n/60),s=n-m*60,txt=s.toFixed(Math.abs(s-Math.round(s))>.001?2:0);return m?`${m}:${txt.padStart(txt.includes('.')?5:2,'0')}`:txt};
  async function rpc(name,body){if(!CFG.supabaseUrl||!CFG.supabaseAnonKey)throw new Error('Secure swimming service is not configured.');const res=await fetch(`${String(CFG.supabaseUrl).replace(/\/$/,'')}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:CFG.supabaseAnonKey,Authorization:`Bearer ${CFG.supabaseAnonKey}`,'Content-Type':'application/json'},body:JSON.stringify(body||{})});const raw=await res.text();let data=null;try{data=raw?JSON.parse(raw):null}catch{data=raw}if(!res.ok)throw new Error(data?.message||data?.hint||`Secure access failed (${res.status})`);return data;}
  let SNAP=null,TAB='performance';
  const kind=k=>({qualifying:'QT',finalist:'Final',medal:'Medal',winner:'Win',record:'Record',benchmark:'Benchmark'})[k]||'Step';
  function pathwayDetail(e,c){const main=e.pathway?.[c]||[],otherC=c==='SCM'?'LCM':'SCM',other=e.pathway?.[otherC]||[],useful=[...main.filter(s=>s.achieved).slice(-1),...main.filter(s=>!s.achieved).slice(0,5)],race=e.race||{};const splits=race.splits&&typeof race.splits==='object'?race.splits:null;const step=s=>`<div class="sp-step"><b>${esc(kind(s.kind))} · ${esc(s.label||'Benchmark')}</b><span>${clock(s.seconds)}</span><em>${s.achieved?'✓ achieved':`${Number(s.gapSeconds).toFixed(2)}s away`}</em></div>`;return `<div class="sp-detail">${race.date||race.meet?`<p class="muted">PB race · ${esc([race.date,race.meet].filter(Boolean).join(' · '))}</p>`:''}${splits?`<div class="sp-splits">${Array.isArray(splits)?splits.map((x,i)=>`<span><b>${esc(x.distance?`${x.distance}m`:`Split ${i+1}`)}</b> ${clock(x.seconds??x.time_seconds??x.time??x)}</span>`).join(''):Object.entries(splits).map(([k,v])=>`<span><b>${esc(k)}</b> ${clock(typeof v==='object'?(v.seconds??v.time_seconds??v.time):v)}</span>`).join('')}</div>`:'<p class="muted">No splits loaded for this PB.</p>'}<h4>${esc(c)} pathway</h4>${useful.length?useful.map(step).join(''):'<p class="muted">No pathway marks loaded.</p>'}${other.some(s=>!s.achieved)?`<details class="sp-outlook"><summary>${esc(otherC)} outlook</summary>${other.filter(s=>!s.achieved).slice(0,4).map(step).join('')}</details>`:''}</div>`;}
  function performance(p){const c=p.performance?.course||'SCM',events=p.performance?.events||[];return `<section class="portal-card"><div class="eyebrow">${esc(c)} · PERFORMANCE</div><h2>${events.length} events</h2><p class="muted">Strongest performance first. Tap an event for pathway, PB race and splits.</p><div class="sp-events">${events.map((e,i)=>`<details class="sp-event"><summary><span>#${i+1}</span><span class="sp-main"><b>${esc(`${e.distance} ${e.stroke}`)}</b><small>${e.next?`${esc(e.next.label)}${e.next.targetSeason?` ${e.next.targetSeason}`:''} · ${Number(e.next.gapSeconds).toFixed(2)}s`:'Tap for pathway'}</small></span><strong>${clock(e.seconds)}</strong><em>${Number.isFinite(Number(e.points))?`${Math.floor(Number(e.points))} ${esc(e.pointSystem||'WA')}`:'—'}</em></summary>${pathwayDetail(e,c)}</details>`).join('')}</div></section>`;}
  function training(p){const t=p.training||{},w=t.week||{},m=t.month||{},today=t.today;return `<section class="portal-card"><div class="eyebrow">TRAINING</div><h2>Your work</h2><div class="sp-kpis">${today?`<div><small>Current / latest</small><b>${Number(today.deliveredMetres||today.prescribedMetres||0).toLocaleString()}m</b><span>${esc(today.title||'Session')}</span></div>`:''}<div><small>7 days</small><b>${Number(w.confirmedDeliveredMetres||0).toLocaleString()}m</b><span>${Number(w.sessions||0)} sessions</span></div><div><small>30 days</small><b>${Number(m.confirmedDeliveredMetres||0).toLocaleString()}m</b><span>${Number(m.sessions||0)} sessions</span></div></div>${(p.sharedEvidence||[]).length?`<h3>From your coach</h3>${p.sharedEvidence.slice(0,6).map(x=>`<div class="sp-note"><b>${esc(x.title||x.type||'Coach note')}</b><span>${esc(x.text||'')}</span></div>`).join('')}:''}</section>`;}
  function tests(p){const rows=p.tests||[];return `<section class="portal-card"><div class="eyebrow">TESTS</div><h2>Your test history</h2>${rows.length?rows.map(x=>`<div class="sp-row"><b>${esc(x.label||'Test')}</b><strong>${clock(x.seconds)}</strong><small>${esc([x.date,x.course].filter(Boolean).join(' · '))}</small></div>`).join(''):'<p class="muted">No test history loaded yet.</p>'}</section>`;}
  function meet(p){const rows=p.meet||[];return `<section class="portal-card"><div class="eyebrow">MEET</div><h2>Your racing</h2>${rows.length?rows.map(x=>`<div class="sp-row"><b>${esc(x.event||'Event')}</b><span>${esc(x.meet||'')}</span><small>${esc([x.date,x.status].filter(Boolean).join(' · '))}</small></div>`).join(''):'<p class="muted">No meet entries currently loaded.</p>'}</section>`;}
  function draw(){const p=SNAP?.payload||{},a=p.athlete||{};ROOT.innerHTML=`<section class="portal-card sp-head"><div><p class="eyebrow">MCLAY SWIMMING OS · MY SWIMMING</p><h1>${esc(a.preferred_name||a.full_name||'Swimmer')}</h1><p class="muted">${esc(a.squad||'')} · private swimmer view</p></div></section><nav class="sp-tabs"><button data-tab="performance" class="${TAB==='performance'?'active':''}">Performance</button><button data-tab="training" class="${TAB==='training'?'active':''}">Training</button><button data-tab="tests" class="${TAB==='tests'?'active':''}">Tests</button><button data-tab="meet" class="${TAB==='meet'?'active':''}">Meet</button></nav>${TAB==='training'?training(p):TAB==='tests'?tests(p):TAB==='meet'?meet(p):performance(p)}<p class="portal-foot">Private swimmer view · ${esc(a.full_name||'')}</p>`;ROOT.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{TAB=b.dataset.tab;draw();});}
  function injectStyle(){if(document.querySelector('#sp-style'))return;const s=document.createElement('style');s.id='sp-style';s.textContent=`.sp-tabs{position:sticky;top:0;z-index:5;display:grid;grid-template-columns:repeat(4,1fr);gap:4px;padding:6px;background:#eef6f8}.sp-tabs button{padding:9px 3px;border-radius:10px;border:1px solid #cbdde5;background:#fff;font-weight:800;font-size:12px}.sp-tabs button.active{background:#0d4566;color:#fff}.sp-events{display:grid;gap:6px}.sp-event{border:1px solid #d8e4ea;border-radius:12px;overflow:hidden;background:#fff}.sp-event>summary{display:grid;grid-template-columns:26px minmax(0,1fr) 72px 58px;gap:6px;align-items:center;padding:10px 8px;list-style:none}.sp-event>summary::-webkit-details-marker{display:none}.sp-main{min-width:0;display:grid}.sp-main b{font-size:14px;white-space:nowrap}.sp-main small{font-size:10px;color:#617783;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.sp-event summary strong,.sp-event summary em{text-align:right}.sp-event summary em{font-size:11px;font-style:normal}.sp-detail{border-top:1px solid #e6eef2;padding:10px;display:grid;gap:6px}.sp-detail h4{margin:4px 0}.sp-step{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:3px 8px;border-top:1px solid #edf2f4;padding:6px 0;font-size:12px}.sp-step em{grid-column:2;font-style:normal}.sp-splits{display:flex;flex-wrap:wrap;gap:5px}.sp-splits span{font-size:11px;background:#f3f7f9;padding:5px 7px;border-radius:8px}.sp-outlook summary{font-weight:800;padding:6px 0}.sp-kpis{display:grid;grid-template-columns:repeat(3,1fr);gap:6px}.sp-kpis>div{border:1px solid #dce7eb;border-radius:10px;padding:8px;display:grid}.sp-kpis b{font-size:18px}.sp-kpis small,.sp-kpis span{font-size:11px}.sp-row,.sp-note{display:grid;grid-template-columns:1fr auto;gap:2px 8px;border-top:1px solid #e5edf1;padding:8px 0}.sp-row small,.sp-note span{grid-column:1/-1}@media(max-width:430px){.sp-kpis{grid-template-columns:1fr}}`;document.head.appendChild(s);}
  function fail(err){ROOT.innerHTML=`<section class="portal-card error"><p class="eyebrow">SECURE ACCESS</p><h1>We couldn't open your swimmer view.</h1><p>${esc(err?.message||err)}</p><p class="muted">Ask your coach for a fresh QR code.</p></section>`;}
  async function start(){try{injectStyle();const params=new URLSearchParams(location.search),invite=params.get('invite');let device=localStorage.getItem(DEVICE_KEY)||'';if(invite){const claimed=await rpc('msos_claim_swimmer_invite',{p_invite_token:invite,p_device_label:[navigator.platform,navigator.userAgent].filter(Boolean).join(' · ').slice(0,120)});device=claimed?.device_token||'';if(!device)throw new Error('The QR code could not be claimed.');localStorage.setItem(DEVICE_KEY,device);if(claimed?.athlete_id)localStorage.setItem(ATHLETE_KEY,claimed.athlete_id);history.replaceState({},'',location.pathname);}if(!device)throw new Error('No swimmer access is set up on this phone yet.');SNAP=await rpc('msos_swimmer_portal_snapshot',{p_device_token:device});draw();}catch(err){if(/invalid|revoked/i.test(String(err?.message||''))){localStorage.removeItem(DEVICE_KEY);localStorage.removeItem(ATHLETE_KEY);}fail(err)}}
  start();
})();
