'use strict';
const assert=require('assert');
const Truth=require('../engines/session-truth.js');
const Entities=require('../engines/entity-registry.js');
const Adapt=require('../engines/adaptation.js');
let fails=0;
function test(name,fn){try{fn();console.log('PASS',name)}catch(e){fails++;console.error('FAIL',name,'\n ',e.stack||e.message)}}
const identity={id:'adapt-session',date:'2026-08-18',dayPart:'AM',course:'SCM',squads:['National','Development'],venue:'AquaGym'};
const entities=Entities.create({sources:[{id:'athletes',priority:100,trust:'verified',data:{athletes:[
 {id:'mk',full_name:'McKenzie Drage',active:true},{id:'charlotte',full_name:'Charlotte Murphy',active:true},{id:'conor',full_name:'Conor Fischer',active:true},{id:'amber',full_name:'Amber Proudfoot',active:true},{id:'std',full_name:'Standard Swimmer',active:true}
]}}]});
const engine=()=>Adapt.create({evidence:entities});
function set(src,id=identity){const s=Truth.parse(src,id);return{s,item:s.blocks[0].items[0]}}

test('standard swimmer with no profile remains exactly on group work',()=>{const a=engine(),{s,item}=set('Main set\n6 x 100 Free Development 10 sr'),r=a.forItem(s,item,'std');assert.equal(r.status,'ok');assert.equal(r.sameAsGroup,true);assert.deepEqual(r.prescription,item)});
test('McKenzie 400 continuous becomes 300 in SCM and returns to starting end',()=>{const a=engine(),{s,item}=set('Main set\n400 Pull'),r=a.forItem(s,item,'mk');assert.equal(r.sameAsGroup,false);assert.equal(r.prescription.distance,300);assert(/returns to starting end/.test(r.reason))});
test('McKenzie 200 continuous becomes 150 in SCM, never 125',()=>{const a=engine(),{s,item}=set('Warm down\n200 Easy Choice'),r=a.forItem(s,item,'mk');assert.equal(r.prescription.distance,150);assert.notEqual(r.prescription.distance,125)});
test('McKenzie aerobic 6 x 100 Development reduces to 4 reps',()=>{const a=engine(),{s,item}=set('Main set\n6 x 100 Free Development 10 sr'),r=a.forItem(s,item,'mk');assert.equal(r.prescription.reps,4);assert.equal(r.prescription.distance,100);assert.equal(r.sameAsGroup,false)});
test('McKenzie aerobic 3 x 200 Development reduces to 2 reps',()=>{const a=engine(),{s,item}=set('Main set\n3 x 200 Development 10 sr'),r=a.forItem(s,item,'mk');assert.equal(r.prescription.reps,2);assert.equal(r.prescription.distance,200)});
test('McKenzie 4 x 100 IM Descend 1-4 keeps all four pattern-dependent quality reps',()=>{const a=engine(),{s,item}=set('Main set\n4 x 100 IM Descend 1-4\n@ 1:40'),r=a.forItem(s,item,'mk');assert.equal(r.prescription.reps,4);assert.equal(r.sameAsGroup,true);assert(/quality exposure preserved/.test(r.reason))});
test('McKenzie 2 x 100 Build/Fast keeps the two-rep pattern intact',()=>{const a=engine(),{s,item}=set('Main set\n2 x 100 Paddles + Fins @ 2:00\n1 Build\n1 Fast'),r=a.forItem(s,item,'mk');assert.equal(r.prescription.reps,2);assert.deepEqual(r.prescription.pattern.map(x=>x.text),['Build','Fast']);assert.equal(r.sameAsGroup,true)});
test('short 4 x 25 Max work stays with the team for modified swimmers',()=>{const a=engine(),{s,item}=set('Pre set\n4 x 25 Max @ 1:00'),r=a.forItem(s,item,'charlotte');assert.equal(r.prescription.reps,4);assert.equal(r.sameAsGroup,true)});
test('Charlotte aerobic volume follows half-volume guide where stimulus is aerobic',()=>{const a=engine(),{s,item}=set('Main set\n10 x 100 Free Threshold 10 sr'),r=a.forItem(s,item,'charlotte');assert.equal(r.prescription.reps,5);assert.equal(r.sameAsGroup,false)});
test('repeating three-rep pattern reduces only by whole pattern cycles',()=>{const a=engine(),{s,item}=set('Pre set\n12 x 50 #1 @ 1:10\n1 Scull / 1 Drill / 1 Swim'),r=a.forItem(s,item,'charlotte');assert.equal(r.prescription.reps,6);assert.equal(r.prescription.reps%3,0);assert.equal(r.prescription.pattern.length,3)});
test('Conor Breaststroke with fins is replaced by safe non-Breaststroke choice before volume logic',()=>{const a=engine(),{s,item}=set('Main set\n4 x 50 Breaststroke with Fins Fast @ 1:00'),r=a.forItem(s,item,'conor');assert.equal(r.prescription.stroke,'Choice');assert(/non-Breaststroke/.test(r.prescription.raw));assert(/No Breaststroke kick with fins/.test(r.reason))});
test('Amber kick/fins/underwater constraint becomes upper-body equivalent at same work window',()=>{const a=engine(),{s,item}=set('Main set\n4 x 50 Kick with Fins Fast @ 1:00'),r=a.forItem(s,item,'amber');assert.equal(r.prescription.stroke,'Choice');assert(!r.prescription.equipment.some(x=>/Fins/i.test(x)));assert.equal(r.prescription.reps,4);assert(/Upper-body equivalent/.test(r.reason))});
test('explicit coach override outranks derived athlete profile logic',()=>{const {s,item}=set('Main set\n6 x 100 Free Development 10 sr');const a=Adapt.create({evidence:entities,overrides:[{sessionId:s.id,itemId:item.id,athleteId:'mk',active:true,reason:'Coach deck decision',prescription:{reps:5,distance:100}}]});const r=a.forItem(s,item,'mk');assert.equal(r.prescription.reps,5);assert.equal(r.source,'override');assert.equal(r.reason,'Coach deck decision')});
test('stored profile outranks fallback ratio without changing athlete identity',()=>{const {s,item}=set('Main set\n8 x 100 Free Development 10 sr');const a=Adapt.create({evidence:entities,profiles:[{athlete_id:'mk',active:true,default_volume_ratio:.5,profile_label:'Current coach profile',return_to_starting_end:true}]});const r=a.forItem(s,item,'mk');assert.equal(r.prescription.reps,4);assert.equal(r.profile.source,'stored');assert.equal(r.profile.label,'Current coach profile')});
test('one-pass 16 x 50 phases stay structured instead of being flattened into arbitrary reps',()=>{const {s,item}=set(`Post set\n16 x 50 @ 1:15\n8 x 50 Bands Only\n4 Build\n4 Descend 1-4\n8 x 50 Swim\nDescend 1-4 twice\n#4 + #8 @ 100 Pace`);const r=engine().forItem(s,item,'mk');assert.equal(r.prescription.phases.length,2);assert.equal(r.prescription.phases[0].reps,8);assert.equal(r.prescription.phases[1].reps,8);assert.equal(r.prescription.reps,16);assert.deepEqual(r.prescription.phases[1].repInstructions.map(x=>x.rep),[4,8])});
test('LCM return-to-start geometry never creates a distance that leaves swimmer at far end',()=>{const id={...identity,id:'lcm-adapt',course:'LCM'},{s,item}=set('Main set\n400 Pull',id),r=engine().forItem(s,item,'mk');assert.equal(r.prescription.distance%100,0);assert.equal(r.prescription.distance,300)});
test('Adaptation Engine does not mutate canonical Session Truth or Entity Registry',()=>{const {s,item}=set('Main set\n6 x 100 Free Development 10 sr'),beforeSession=JSON.stringify(s),beforeAth=JSON.stringify(entities.resolveAthlete('mk'));engine().forItem(s,item,'mk');assert.equal(JSON.stringify(s),beforeSession);assert.equal(JSON.stringify(entities.resolveAthlete('mk')),beforeAth)});
if(fails){console.error(`\n${fails} Adaptation regression(s) failed`);process.exit(1)}console.log('\nALL ADAPTATION REGRESSIONS PASS');
