'use strict';
const assert=require('assert');
const App=require('../rebuild/app-composition.js');
const Portal=require('../rebuild/engine-portal.js');
const Schedule=require('../engines/session-schedule.js');
const Lifecycle=require('../engines/session-lifecycle.js');
const Attendance=require('../engines/attendance.js');
const Capture=require('../engines/capture-evidence.js');
const Delivered=require('../engines/delivered-session.js');
const Timing=require('../engines/timing.js');
const Protocol=require('../engines/test-protocol.js');
const TestResults=require('../engines/test-result-input.js');

let failures=0;
function test(name,fn){try{fn();console.log(`PASS ${name}`)}catch(e){failures++;console.error(`FAIL ${name}\n  ${e.stack||e.message}`)}}
let tick=0;const clock=()=>`2026-08-18T06:${String(tick++%60).padStart(2,'0')}:00+12:00`;
const calendar={calendar_id:'aug26',title:'AquaGym August',coverage_start:'2026-08-01',coverage_end:'2026-08-31',published_at:'2026-08-01T00:00:00+12:00',rules:{empty_date_means_no_training:true},dates:[{date:'2026-08-18',status:'training',sessions:[{day_part:'AM',start_time:'05:20',end_time:'07:20',squads:['National'],venue:'AquaGym',pool_course:'SCM'},{day_part:'AM',start_time:'05:30',end_time:'07:00',squads:['Development'],venue:'AquaGym',pool_course:'SCM'}],events:[]}]};
const source=`WARM UP\n400 Choice\nMAIN SET\n400 Pull\n6 x 100 Freestyle Development\n10s Rest\n4 x 25 Free @ 100 Pace\nWARM DOWN\n200 Easy\nTOTAL: 1,700m`;
function fixture(stores={}){return App.create({
 scheduleStorage:stores.schedule||new Schedule.MemoryStorage(),lifecycleStorage:stores.lifecycle||new Lifecycle.MemoryStorage(),attendanceStorage:stores.attendance||new Attendance.MemoryStorage(),captureStorage:stores.capture||new Capture.MemoryStorage(),deliveryStorage:stores.delivery||new Delivered.MemoryStorage(),timingStorage:stores.timing||new Timing.MemoryStorage(),protocolStorage:stores.protocols||new Protocol.MemoryStorage(),testResultStorage:stores.testResults||new TestResults.MemoryStorage(),clock,calendarSources:[calendar],
 squads:[{id:'squad-national',name:'National',active:true},{id:'squad-development',name:'Development',active:true},{id:'squad-intermediate',name:'Intermediate',active:true}],
 profiles:[{athlete_id:'mk',volume_ratio:0.75,return_to_start:true}],
 evidenceSources:[{id:'verified',priority:100,trust:'verified',data:{athletes:[{id:'mk',full_name:'McKenzie Drage',squad:'National',active:true,sex:'F'},{id:'molly',full_name:'Molly McKernan',squad:'Development',active:true,sex:'F'},{id:'int',full_name:'Intermediate Swimmer',squad:'Intermediate',active:true}],training_test_types:[{id:'tt',test_key:'t400_freestyle'}],training_test_results:[{id:'molly-old',athlete_id:'molly',test_type_id:'tt',result_seconds:320,result_date:'2026-06-01',pool_course:'SCM',valid_for_anchor:true},{id:'molly-t',athlete_id:'molly',test_type_id:'tt',result_seconds:324.6,result_date:'2026-08-12',pool_course:'SCM',valid_for_anchor:true},{id:'mk-t',athlete_id:'mk',test_type_id:'tt',result_seconds:450.1,result_date:'2026-06-01',pool_course:'SCM',valid_for_anchor:true}],coach_results:[{id:'molly100',athlete_id:'molly',distance:100,stroke:'Freestyle',pool_course:'SCM',result_seconds:60,result_date:'2026-07-01'}]}}]
})}
function buildAccepted(app){const slots=app.slotsForDate('2026-08-18'),begun=app.beginFromSlots(slots.map(x=>x.id),{title:'Tuesday AM',inputMode:'text'});app.updateDraft(begun.draft.id,{source});return app.acceptDraft(begun.draft.id)}
function findBoardSet(board,pred){for(const block of board.blocks||[])for(const item of block.items||[]){if(item.kind==='set'&&pred(item))return item;if(item.kind==='group')for(const child of item.items||[])if(child.kind==='set'&&pred(child))return child}return null}
function findSessionSet(session,pred){for(const block of session.blocks||[]){const stack=[...(block.items||[])];while(stack.length){const item=stack.shift();if(item?.kind==='set'&&pred(item))return item;if(item?.kind==='group')stack.unshift(...(item.items||[]))}}return null}

console.log(`App Composition ${App.VERSION}`);

test('one sealed portal contains Calendar Board poolside Timing Test and publication owner graph',()=>{const app=fixture(),services=Object.fromEntries(app.graph.services.map(x=>[x.id,x]));for(const id of ['session-schedule','session-lifecycle','session-truth','session-edit','delivered-session','session-intake-flow','poolside-session-flow','timing','test-protocol','test-result-input','evidence-publication','measurement-publication-flow','attendance','targets','adaptation','capture-evidence','board-projection','calendar-surface','coach-board-surface','measurement-surface','app-shell'])assert(services[id],`missing ${id}`);assert.strictEqual(app.portal.snapshot().sealed,true);assert.throws(()=>app.portal.register({id:'late-owner'}),e=>e instanceof Portal.PortalError&&e.code==='PORTAL_SEALED')});
test('Calendar accepted session is the exact canonical session projected by Board',()=>{const app=fixture(),accepted=buildAccepted(app),occ=app.occurrenceForSession(accepted.record.id),board=app.boardForSession(accepted.record.id);assert.strictEqual(occ.sessionId,accepted.record.id);assert.strictEqual(occ.squadEntries.find(x=>x.squadId==='squad-development').startOffsetMinutes,10);assert.strictEqual(board.sessionId,accepted.record.id);assert.strictEqual(board.totalDistance,1700);assert.strictEqual(app.session(accepted.record.id).current.id,board.sessionId)});
test('Roll command and Board read travel through the same portal and exact accepted session',()=>{const app=fixture(),accepted=buildAccepted(app);app.markAttendance(accepted.record.id,'molly','present');const roll=app.rollForSession(accepted.record.id),board=app.boardForSession(accepted.record.id);assert.strictEqual(roll.here.length,1);assert.strictEqual(roll.here[0].id,'molly');assert.strictEqual(board.attendance.here,1);assert.strictEqual(board.attendance.athletes[0].name,'Molly McKernan')});
test('Times T400 read uses latest valid evidence through Evidence Retrieval rather than browser-side selection',()=>{const app=fixture(),accepted=buildAccepted(app),answer=app.t400Evidence(accepted.record.id,'molly');assert.strictEqual(answer.status,'ok');assert.strictEqual(answer.seconds,324.6);assert.strictEqual(answer.date,'2026-08-12')});
test('Target and adaptation remain delegated while Calendar schedule truth stays unchanged',()=>{const app=fixture(),accepted=buildAccepted(app),before=JSON.stringify(app.occurrenceForSession(accepted.record.id));app.markAttendance(accepted.record.id,'molly','present');app.markAttendance(accepted.record.id,'mk','modified');const board=app.boardForSession(accepted.record.id),dev=findBoardSet(board,x=>x.groupWork?.zone==='Development'),pull=findBoardSet(board,x=>x.groupWork?.distance===400&&/Pull/i.test(x.groupWork?.raw||''));assert(dev&&dev.targets.some(x=>x.athleteId==='molly'&&x.status==='ok'));assert(pull&&pull.modifications.some(x=>x.athleteId==='mk'));assert.strictEqual(JSON.stringify(app.occurrenceForSession(accepted.record.id)),before)});
test('Capture writes exact Board point through same portal without editing canonical session',()=>{const app=fixture(),accepted=buildAccepted(app),board0=app.boardForSession(accepted.record.id),dev=findBoardSet(board0,x=>x.groupWork?.zone==='Development'),block=board0.blocks.find(b=>(b.items||[]).some(x=>x.id===dev.id)),before=JSON.stringify(app.session(accepted.record.id).current);app.capture(accepted.record.id,{type:'note',blockId:block.id,itemId:dev.id,athleteIds:['molly'],text:'Held shape'});assert.strictEqual(app.evidenceAt(accepted.record.id,{blockId:block.id,itemId:dev.id,athleteId:'molly'}).length,1);assert.strictEqual(JSON.stringify(app.session(accepted.record.id).current),before)});
test('group Edit routes through Session Edit and preserves original plan',()=>{const app=fixture(),accepted=buildAccepted(app),session=app.session(accepted.record.id),dev=findSessionSet(session.current,x=>x.zone==='Development'),beforeOriginal=JSON.stringify(session.originalPlan);app.editSet(accepted.record.id,dev.id,{reps:5},{note:'Deck volume adjustment'});assert.strictEqual(app.boardForSession(accepted.record.id).totalDistance,1600);assert.strictEqual(JSON.stringify(app.session(accepted.record.id).originalPlan),beforeOriginal)});
test('swimmer Edit writes Adaptation only and can be cleared without changing canonical session',()=>{const app=fixture(),accepted=buildAccepted(app);app.markAttendance(accepted.record.id,'mk','modified');const session=app.session(accepted.record.id),pull=findSessionSet(session.current,x=>x.distance===400&&/Pull/i.test(x.raw||'')),before=JSON.stringify(session.current);app.setAdaptationForItem(accepted.record.id,pull.id,'mk',{distance:250},{reason:'Deck override'});assert.strictEqual(app.adaptationFor(accepted.record.id,pull.id,'mk').prescription.distance,250);assert.strictEqual(JSON.stringify(app.session(accepted.record.id).current),before);app.clearAdaptationForItem(accepted.record.id,pull.id,'mk')});
test('Finish creates delivered truth only once',()=>{const app=fixture(),accepted=buildAccepted(app);assert.strictEqual(app.deliveryForSession(accepted.record.id),null);const delivery=app.finishSession(accepted.record.id,{point:{full:true},coachId:'andy',note:'Completed'});assert.strictEqual(delivery.delivered_distance,1700);assert.throws(()=>app.finishSession(accepted.record.id,{point:{full:true}}),/already finished/i)});

test('cross-squad Timing assignment never mutates canonical training-session squad identity',()=>{const app=fixture(),accepted=buildAccepted(app),sid=accepted.record.id,before=JSON.stringify(app.session(sid).current.identity);const timer=app.createTimingSession({id:'cross-squad-timer',context:{training_session_id:sid,test_protocol_id:'protocol-t400-freestyle'},course:'SCM',poolLength:25,label:'T400'});app.assignTimingAthlete(timer.id,'int',{lane:4});assert.strictEqual(app.timingSession(timer.id).assignments[0].athlete_id,'int');assert.strictEqual(JSON.stringify(app.session(sid).current.identity),before);assert.deepStrictEqual(app.measurementAthletes().map(x=>x.id).sort(),['int','mk','molly'])});
test('multi-swimmer Timing stores independent raw finish measurements and no T400 validity flags',()=>{const app=fixture(),accepted=buildAccepted(app),sid=accepted.record.id,t=app.createTimingSession({id:'multi-t400',context:{training_session_id:sid,test_protocol_id:'protocol-t400-freestyle'},course:'SCM',poolLength:25,label:'T400'});app.assignTimingAthlete(t.id,'molly',{lane:1});app.assignTimingAthlete(t.id,'int',{lane:2});app.startTiming(t.id);app.recordTimingSplit(t.id,'molly',{distance:200,elapsedSeconds:160});app.recordTimingSplit(t.id,'int',{distance:200,elapsedSeconds:170});app.finishTimingAthlete(t.id,'molly',{distance:400,elapsedSeconds:319.5});app.finishTimingAthlete(t.id,'int',{distance:400,elapsedSeconds:339.8});const row=app.timingSession(t.id);assert.strictEqual(row.measurements.filter(x=>x.kind==='finish').length,2);assert(!/valid_for_anchor|development|threshold/i.test(JSON.stringify(row)))});
test('T400 verification publishes local evidence and immediately refreshes Target evidence without browser mutation',()=>{const app=fixture(),accepted=buildAccepted(app),sid=accepted.record.id,t=app.createTimingSession({id:'publish-t400',context:{training_session_id:sid,test_protocol_id:'protocol-t400-freestyle'},course:'SCM',poolLength:25,label:'T400'});app.assignTimingAthlete(t.id,'int');app.startTiming(t.id);app.recordTimingSplit(t.id,'int',{distance:200,elapsedSeconds:165});app.finishTimingAthlete(t.id,'int',{distance:400,elapsedSeconds:330});assert.strictEqual(app.t400Evidence(sid,'int').status,'missing');const published=app.captureAndPublishTimingTest(t.id,'int','t400_freestyle',{coachId:'andy',resultDate:'2026-08-18'});assert.strictEqual(published.result.evidence_status,'verified');assert.strictEqual(app.t400Evidence(sid,'int').seconds,330);const dev=findSessionSet(app.session(sid).current,x=>x.zone==='Development'),target=app.targetFor(sid,dev.id,'int');assert.strictEqual(target.status,'ok');assert(/T400/i.test(target.source));const trail=app.portal.auditTrail();assert(trail.some(x=>x.caller==='measurement-publication-flow'&&x.target==='evidence-publication'&&x.operation==='verifiedSource'));assert(trail.some(x=>x.caller==='measurement-publication-flow'&&x.target==='evidence-retrieval'&&x.operation==='rebuildSources'))});
test('invalid 300m timing remains intact when T400 protocol rejects result creation',()=>{const app=fixture(),accepted=buildAccepted(app),sid=accepted.record.id,t=app.createTimingSession({id:'invalid-t400',context:{training_session_id:sid},course:'SCM',poolLength:25});app.assignTimingAthlete(t.id,'int');app.startTiming(t.id);app.finishTimingAthlete(t.id,'int',{distance:300,elapsedSeconds:250});assert.throws(()=>app.captureAndPublishTimingTest(t.id,'int','t400_freestyle'),/Distance must be 400m/);assert.strictEqual(app.timingSession(t.id).measurements.at(-1).distance_m,300);assert.strictEqual(app.testResults({}).length,0)});
test('app shell cannot bypass Calendar Board Timing or test-result surfaces',()=>{const app=fixture();for(const [kind,target,op] of [['query','session-schedule','day'],['query','board-projection','project'],['command','attendance','mark'],['command','poolside-session-flow','finish'],['command','timing','createSession'],['command','test-result-input','verify'],['command','measurement-publication-flow','verifyAndPublish']])assert.throws(()=>app.shell[kind](target,op,{args:[]}),e=>e instanceof Portal.PortalError&&e.code==='CALL_NOT_ALLOWED')});
test('portal audit stores routing metadata but not timing result payloads',()=>{const app=fixture(),accepted=buildAccepted(app),sid=accepted.record.id,t=app.createTimingSession({id:'audit-timer',context:{training_session_id:sid},course:'SCM',poolLength:25});app.assignTimingAthlete(t.id,'molly');app.startTiming(t.id);app.finishTimingAthlete(t.id,'molly',{distance:400,elapsedSeconds:321.23});const json=JSON.stringify(app.portal.auditTrail());assert(!json.includes('321.23'));assert(!json.includes('McKenzie Drage'))});

if(failures){console.error(`\n${failures} App Composition regression(s) failed`);process.exit(1)}
console.log('\nALL APP COMPOSITION REGRESSIONS PASS');
