'use strict';
const assert=require('assert');
const Presenter=require('../assembly/poolside-presenter.js');
let failures=0;
function test(name,fn){try{fn();console.log(`PASS ${name}`)}catch(e){failures++;console.error(`FAIL ${name}\n  ${e.stack||e.message}`)}}
console.log(`Assembly Poolside Presenter ${Presenter.VERSION}`);
test('Roll sheet is compact and exposes attendance actions without duplicating Board work',()=>{const html=Presenter.panelHtml({type:'roll',eligible:[{id:'a1',full_name:'Alex Auer'}],here:[{id:'a1',full_name:'Alex Auer',status:'present'}],summary:{here:1}},{answers:new Map()});assert(/Roll · 1 here/.test(html));assert(/data-status="present"/.test(html));assert(/Modified/.test(html));assert(!/MAIN SET|Warm-up/.test(html))});
test('Times sheet renders verified T400 answer only after the action supplies it',()=>{const answers=new Map([['a1',{status:'ok',seconds:324.6,date:'2026-08-12'}]]),html=Presenter.panelHtml({type:'times',athletes:[{id:'a1',full_name:'Molly McKernan'}]},{answers});assert(/5:24\.6/.test(html));assert(/2026-08-12/.test(html));assert(/T400/.test(html))});
test('Times setup can select swimmers across squads without presenting a squad change',()=>{const html=Presenter.panelHtml({type:'times',startT400:()=>{},athletes:[{id:'n',full_name:'National Swimmer',squad:'National'},{id:'i',full_name:'Intermediate Swimmer',squad:'Intermediate'}]},{answers:new Map(),timing:null,saved:new Set()});assert(/name="timing-athlete"/.test(html));assert(/National Swimmer/.test(html));assert(/Intermediate Swimmer/.test(html));assert(/squad does not change/i.test(html));assert(/Set up T400/.test(html))});
test('running multi-swimmer T400 shows independent next-distance actions',()=>{const timing={id:'t1',status:'running',course:'SCM',pool_length_m:25,assignments:[{athlete_id:'a1',active:true},{athlete_id:'a2',active:true}],measurements:[{athlete_id:'a1',kind:'split',distance_m:100,elapsed_seconds:80,status:'active'}]},html=Presenter.renderTiming({athletes:[{id:'a1',full_name:'One'},{id:'a2',full_name:'Two'}]},{timing,saved:new Set()});assert(/data-stopwatch/.test(html));assert(/data-athlete-id="a1" data-distance="200"/.test(html));assert(/data-athlete-id="a2" data-distance="100"/.test(html))});
test('finished unsaved T400 is recoverable after Times sheet closes but fully saved timing is not',()=>{const timing={id:'timer-1',status:'finished',assignments:[{athlete_id:'a1',active:true}],measurements:[{athlete_id:'a1',kind:'finish',distance_m:400,elapsed_seconds:320,status:'active'}]},unsaved={timingSessions:[timing],testResults:[]},saved={timingSessions:[timing],testResults:[{source_ref:'timer-1:a1',evidence_status:'verified'}]};assert.strictEqual(Presenter.recoverableTiming(unsaved).id,'timer-1');assert.strictEqual(Presenter.recoverableTiming(saved),null);assert(Presenter.savedForTiming(saved,timing).has('a1'))});
test('media capture fails visibly if local media adapter is unavailable',()=>{for(const mode of ['voice','photo','video']){const html=Presenter.panelHtml({type:'capture',mode,textMode:mode,roll:{eligible:[]}},{mediaAvailable:false});assert(/adapter unavailable/.test(html));assert(/will not claim media saved/i.test(html))}});
test('photo video and voice put explicit touch swimmer tags before media and keep local-first save wording',()=>{for(const mode of ['voice','photo','video']){const html=Presenter.panelHtml({type:'capture',mode,textMode:mode,roll:{here:[{id:'a1',full_name:'Molly McKernan'}]}},{mediaAvailable:true});assert(/data-panel-action="capture-athlete-toggle"/.test(html));assert(/data-athlete-id="a1"/.test(html));assert(/aria-pressed="false"/.test(html));assert(/Molly McKernan/.test(html));assert(/poolside-media-file/.test(html));assert(new RegExp(`Save ${mode}`).test(html));assert(/Media saves locally first/.test(html));assert(html.indexOf('capture-athlete-toggle')<html.indexOf('poolside-media-file'))}});
test('voice capture retains an explicit transcript field instead of dropping the working note layer',()=>{const html=Presenter.panelHtml({type:'capture',mode:'voice',textMode:'voice',roll:{here:[]}},{mediaAvailable:true});assert(/Transcript \/ note/.test(html));assert(/Add transcript or short voice-note summary/.test(html));assert(/accept="audio\/\*"/.test(html))});
test('note capture also asks for swimmer tags before note entry',()=>{const html=Presenter.panelHtml({type:'capture',mode:'note',textMode:'note',roll:{here:[{id:'a1',full_name:'Alex Auer'},{id:'a2',full_name:'Molly McKernan'}]}},{answers:new Map()});assert.strictEqual((html.match(/data-panel-action="capture-athlete-toggle"/g)||[]).length,2);assert(/Alex Auer/.test(html));assert(/Molly McKernan/.test(html));assert(html.indexOf('capture-athlete-toggle')<html.indexOf('poolside-note-text'));assert(/Save note/.test(html))});
test('selected capture athletes are read only from explicit pressed tag state',()=>{const rows=[{dataset:{athleteId:'a1'}},{dataset:{athleteId:'a2'}}],host={querySelectorAll:q=>q.includes('aria-pressed="true"')?rows:[]};assert.deepStrictEqual(Presenter.selectedCaptureAthletes(host),['a1','a2'])});
test('capture confirmation carries swimmer names and exact Board scope without copying session content',()=>{const summary=Presenter.captureSummary({context:{sessionId:'s1',blockId:'b1',itemId:'i1'},roll:{here:[{id:'a1',full_name:'Alex Auer'}]}},'photo',['a1']);assert.deepStrictEqual(summary.athleteNames,['Alex Auer']);assert.strictEqual(summary.scope,'set');assert.strictEqual(summary.sessionId,'s1');assert.strictEqual(summary.blockId,'b1');assert.strictEqual(summary.itemId,'i1');assert(!JSON.stringify(summary).includes('MAIN SET'))});
test('group and swimmer edit sheets expose only explicit editable fields',()=>{const group=Presenter.panelHtml({type:'editSet',item:{raw:'6 x 100 Freestyle Development',reps:6,distance:100,restSeconds:10}},{answers:new Map()}),athlete=Presenter.panelHtml({type:'editAthleteSet',athlete:{id:'mk',name:'McKenzie Drage'},item:{raw:'400 Pull',reps:1,distance:400},current:{work:{reps:1,distance:300}}},{answers:new Map()});assert(/Reps/.test(group)&&/Distance/.test(group)&&/Rest seconds/.test(group));assert(/Individual within team/.test(athlete));assert(/300/.test(athlete));assert(!/T400 formula|qualification logic/i.test(group+athlete))});
test('Finish sheet requires an explicit confirm action and states planned work is preserved',()=>{const html=Presenter.panelHtml({type:'finish'},{answers:new Map()});assert(/Confirm full session finished/.test(html));assert(/planned session stays preserved/i.test(html));assert(/data-panel-action="finish-confirm"/.test(html))});
test('all coach text is escaped before insertion into panel HTML',()=>{const html=Presenter.panelHtml({type:'evidence',items:[{type:'note',text:'<img src=x onerror=alert(1)>'}]},{answers:new Map()});assert(!html.includes('<img src=x'));assert(html.includes('&lt;img'))});
if(failures){console.error(`\n${failures} poolside presenter regression(s) failed`);process.exit(1)}
console.log('\nALL ASSEMBLY POOLSIDE PRESENTER REGRESSIONS PASS');
