'use strict';
const assert=require('assert');
const Data=require('../assembly/programme-data-adapter.js');
const App=require('../rebuild/app-composition.js');
const Schedule=require('../engines/session-schedule.js');
const Lifecycle=require('../engines/session-lifecycle.js');
const Attendance=require('../engines/attendance.js');
const Capture=require('../engines/capture-evidence.js');
const Delivered=require('../engines/delivered-session.js');
const Timing=require('../engines/timing.js');
const Protocol=require('../engines/test-protocol.js');
const TestResults=require('../engines/test-result-input.js');
let failures=0;
function test(name,fn){try{const r=fn();if(r&&typeof r.then==='function')return r.then(()=>console.log(`PASS ${name}`)).catch(e=>{failures++;console.error(`FAIL ${name}\n  ${e.stack||e.message}`)});console.log(`PASS ${name}`)}catch(e){failures++;console.error(`FAIL ${name}\n  ${e.stack||e.message}`)}}
class FakeStorage{constructor(){this.m=new Map([['mclay_swimming_v1_auth',JSON.stringify({access_token:'token'})],['mclay_swimming_os_v4',JSON.stringify({settings:{organisationId:'org-live'}})]])}getItem(k){return this.m.get(k)||null}}
class FakeCache{constructor(){this.row=null}get(){return this.row}put(name,value,meta){this.row={value:JSON.parse(JSON.stringify(value)),savedAt:meta.savedAt};return this.row}}
const remote={athletes:[{id:'alex',full_name:'Alex Auer',squad:'National',active:true,sex:'M'},{id:'molly',full_name:'Molly McKernan',squad:'Development',active:true,sex:'F'}],training_test_types:[{id:'t400',test_key:'t400_freestyle',name:'T400 Freestyle'}],training_test_results:[{id:'alex400',athlete_id:'alex',test_type_id:'t400',result_seconds:323,result_date:'2026-06-20',pool_course:'SCM',valid_for_anchor:true},{id:'molly400',athlete_id:'molly',test_type_id:'t400',result_seconds:324.6,result_date:'2026-08-12',pool_course:'SCM',valid_for_anchor:true}],athlete_adaptation_profiles:[],coach_results:[{id:'molly100',athlete_id:'molly',distance:100,stroke:'Freestyle',pool_course:'SCM',result_seconds:60,result_date:'2026-07-01'}],results_pb_board:[],results_event_history:[],pathway_standards:[],world_aquatics_base_times:[]};
function table(url){return decodeURIComponent(url.match(/\/rest\/v1\/([^?]+)/)?.[1]||'')}
const fetchImpl=async(url,opts={})=>{assert.strictEqual(opts.method,'GET');const rows=remote[table(url)]||[],u=new URL(url),off=Number(u.searchParams.get('offset')||0),lim=Number(u.searchParams.get('limit')||1000);return{ok:true,status:200,json:async()=>JSON.parse(JSON.stringify(rows.slice(off,off+lim)))}};
const calendar={calendar_id:'aug26',coverage_start:'2026-08-01',coverage_end:'2026-08-31',published_at:'2026-08-01T00:00:00+12:00',dates:[{date:'2026-08-18',status:'training',sessions:[{day_part:'PM',start_time:'17:30',end_time:'19:30',squads:['National'],venue:'AquaGym',pool_course:'SCM'},{day_part:'PM',start_time:'17:40',end_time:'19:10',squads:['Development'],venue:'AquaGym',pool_course:'SCM'}],events:[]}]};
const source=`WARM UP\n300 Choice\nMAIN SET\n4 x 100 Freestyle Development\n10s Rest\nWARM DOWN\n200 Easy\nTOTAL: 900m`;
const pending=[];
console.log('Assembly live programme data flow');
pending.push(test('read-only programme load becomes the actual Roll roster T400 evidence and Board identity',async()=>{const data=await Data.loadProgrammeData({fetchImpl,cache:new FakeCache(),storage:new FakeStorage(),config:{supabaseUrl:'https://example.supabase.co',supabaseAnonKey:'publishable'},clock:()=> '2026-08-18T07:40:00Z'});assert.strictEqual(data.source,'network');assert.deepStrictEqual(data.evidenceSources[0].data.athletes.map(x=>x.id),['alex','molly']);const app=App.create({scheduleStorage:new Schedule.MemoryStorage(),lifecycleStorage:new Lifecycle.MemoryStorage(),attendanceStorage:new Attendance.MemoryStorage(),captureStorage:new Capture.MemoryStorage(),deliveryStorage:new Delivered.MemoryStorage(),timingStorage:new Timing.MemoryStorage(),protocolStorage:new Protocol.MemoryStorage(),testResultStorage:new TestResults.MemoryStorage(),calendarSources:[calendar],evidenceSources:data.evidenceSources,profiles:data.profiles,standards:data.standards,baseTimes:data.baseTimes,squads:[{id:'squad-national',name:'National',active:true},{id:'squad-development',name:'Development',active:true}],clock:()=> '2026-08-18T07:41:00Z'});const begun=app.beginFromSlots(app.slotsForDate('2026-08-18').map(x=>x.id),{title:'Tuesday PM'});app.updateDraft(begun.draft.id,{source});const accepted=app.acceptDraft(begun.draft.id),sid=accepted.record.id;const roll=app.rollForSession(sid);assert.deepStrictEqual(roll.eligible.map(x=>x.id).sort(),['alex','molly']);assert.strictEqual(app.t400Evidence(sid,'alex').seconds,323);assert.strictEqual(app.t400Evidence(sid,'molly').seconds,324.6);app.markAttendance(sid,'alex','present');app.markAttendance(sid,'molly','present');const board=app.boardForSession(sid);assert.strictEqual(board.attendance.here,2);assert.deepStrictEqual(board.attendance.athletes.map(x=>x.id).sort(),['alex','molly']);const dev=board.blocks.flatMap(b=>b.items||[]).find(x=>x.kind==='set'&&x.groupWork?.zone==='Development');assert(dev,'Development set missing');assert(dev.targets.some(x=>x.athleteId==='alex'&&x.status==='ok'),'Alex target was not derived from loaded T400');assert(dev.targets.some(x=>x.athleteId==='molly'&&x.status==='ok'),'Molly target was not derived from loaded T400')}));
Promise.all(pending.filter(Boolean)).then(()=>{if(failures){console.error(`\n${failures} live data flow regression(s) failed`);process.exit(1)}console.log('\nALL ASSEMBLY LIVE DATA FLOW REGRESSIONS PASS')});
