'use strict';
const assert=require('assert');
const Storage=require('../assembly/browser-storage.js');
const Loader=require('../assembly/data-loader.js');
let failures=0;
function test(name,fn){try{const r=fn();if(r&&typeof r.then==='function')return r.then(()=>console.log(`PASS ${name}`)).catch(e=>{failures++;console.error(`FAIL ${name}\n  ${e.stack||e.message}`)});console.log(`PASS ${name}`)}catch(e){failures++;console.error(`FAIL ${name}\n  ${e.stack||e.message}`)}}
class FakeStorage{constructor(){this.m=new Map()}getItem(k){return this.m.has(k)?this.m.get(k):null}setItem(k,v){this.m.set(k,String(v))}removeItem(k){this.m.delete(k)}}
const asyncTests=[];
console.log(`Assembly Browser Storage ${Storage.VERSION} · Loader ${Loader.VERSION}`);
test('JSON adapter is explicit local persistence and reload returns cloned state',()=>{const backing=new FakeStorage(),a=new Storage.JsonStorageAdapter({storage:backing,key:'x'}),value={sessions:[{id:'s1'}]};a.save(value);value.sessions[0].id='changed';assert.strictEqual(a.load().sessions[0].id,'s1');assert.strictEqual(a.status().ok,true)});
test('unreadable stored state fails explicitly instead of silently replacing it',()=>{const backing=new FakeStorage();backing.setItem('x','{bad json');const a=new Storage.JsonStorageAdapter({storage:backing,key:'x'});assert.throws(()=>a.load(),/unreadable/);assert.strictEqual(a.status().ok,false)});
test('storage write failure remains visible',()=>{const backing={getItem:()=>null,setItem:()=>{throw new Error('quota')},removeItem:()=>{}};const a=new Storage.JsonStorageAdapter({storage:backing,key:'x'});assert.throws(()=>a.save({a:1}),/local save failed/);assert.strictEqual(a.status().error.operation,'save')});
test('assembly storage keys keep every truth owner in a separate local record',()=>{const k=Storage.keys('test');assert.strictEqual(new Set(Object.values(k)).size,Object.keys(k).length);for(const suffix of ['schedule','lifecycle','attendance','capture','delivery','timing','protocols','navigation','resources'])assert(k[suffix]?.includes(`.${suffix}`),`missing ${suffix}`);assert(k.testResults.endsWith('.test-results'))});
test('resource cache preserves last good calendar separately from engine-owned schedule state',()=>{const backing=new FakeStorage(),cache=new Storage.ResourceCache({storage:backing,key:'resources'});cache.put('calendar',{dates:[{date:'2026-08-18'}]},{source:'monthly_calendar.json',savedAt:'2026-08-18T06:00:00Z'});const row=cache.get('calendar');assert.strictEqual(row.value.dates[0].date,'2026-08-18');assert.strictEqual(row.source,'monthly_calendar.json')});
asyncTests.push(test('calendar loader prefers valid network data and caches it',async()=>{const backing=new FakeStorage(),cache=new Storage.ResourceCache({storage:backing,key:'resources'}),calendar={dates:[{date:'2026-08-18'}]},fetchImpl=async()=>({ok:true,status:200,json:async()=>calendar});const out=await Loader.loadCalendar({fetchImpl,cache,url:'calendar.json'});assert.strictEqual(out.source,'network');assert.deepStrictEqual(cache.get('monthly_calendar').value,calendar)}));
asyncTests.push(test('calendar loader uses last known good cache when network is unavailable',async()=>{const backing=new FakeStorage(),cache=new Storage.ResourceCache({storage:backing,key:'resources'});cache.put('monthly_calendar',{dates:[{date:'2026-08-18'}]},{savedAt:'2026-08-18T05:00:00Z'});const out=await Loader.loadCalendar({fetchImpl:async()=>{throw new Error('offline')},cache,url:'calendar.json'});assert.strictEqual(out.source,'cache');assert(/Using cached calendar/.test(out.warning));assert.strictEqual(out.value.dates[0].date,'2026-08-18')}));
asyncTests.push(test('calendar loader fails closed if neither network nor a valid cache exists',async()=>{const backing=new FakeStorage(),cache=new Storage.ResourceCache({storage:backing,key:'resources'});await assert.rejects(()=>Loader.loadCalendar({fetchImpl:async()=>{throw new Error('offline')},cache}),/no safe cached copy/)}));
Promise.all(asyncTests.filter(Boolean)).then(()=>{if(failures){console.error(`\n${failures} assembly browser infrastructure regression(s) failed`);process.exit(1)}console.log('\nALL ASSEMBLY BROWSER INFRASTRUCTURE REGRESSIONS PASS')});
