'use strict';
const assert=require('assert');
const Data=require('../assembly/programme-data-adapter.js');
let failures=0;
function test(name,fn){try{const r=fn();if(r&&typeof r.then==='function')return r.then(()=>console.log(`PASS ${name}`)).catch(e=>{failures++;console.error(`FAIL ${name}\n  ${e.stack||e.message}`)});console.log(`PASS ${name}`)}catch(e){failures++;console.error(`FAIL ${name}\n  ${e.stack||e.message}`)}}
class FakeStorage{constructor(rows={}){this.rows=new Map(Object.entries(rows).map(([k,v])=>[k,typeof v==='string'?v:JSON.stringify(v)]))}getItem(k){return this.rows.get(k)||null}}
class FakeCache{constructor(value=null){this.row=value?{value:JSON.parse(JSON.stringify(value)),savedAt:value.loadedAt||'2026-08-18T06:00:00Z'}:null;this.puts=[]}get(name){assert.strictEqual(name,Data.CACHE_NAME);return this.row&&JSON.parse(JSON.stringify(this.row))}put(name,value,meta){this.puts.push({name,value:JSON.parse(JSON.stringify(value)),meta});this.row={value:JSON.parse(JSON.stringify(value)),savedAt:meta.savedAt};return this.row}}
const config={supabaseUrl:'https://example.supabase.co',supabaseAnonKey:'publishable'};
const storage=()=>new FakeStorage({mclay_swimming_v1_auth:{access_token:'secret-token',user:{id:'u'}},mclay_swimming_os_v4:{settings:{organisationId:'org-1'}}});
const required={athletes:[{id:'a1',full_name:'One Swimmer',squad:'National',active:true},{id:'a2',full_name:'Two Swimmer',squad:'Development',active:true},{id:'a3',full_name:'Three Swimmer',squad:'National',active:true}],training_test_types:[{id:'tt',test_key:'t400_freestyle'}],training_test_results:[{id:'r1',athlete_id:'a1',test_type_id:'tt',result_seconds:300,result_date:'2026-08-01',pool_course:'SCM'}],athlete_adaptation_profiles:[{id:'p',athlete_id:'a1',default_volume_ratio:.75}],coach_results:[{id:'c',athlete_id:'a1',distance:100,stroke:'Freestyle',pool_course:'SCM',result_seconds:60}],results_pb_board:[{id:'pb',athlete_id:'a1',distance:100,stroke:'Freestyle',course:'SCM',result_seconds:60}],results_event_history:[],pathway_standards:[{id:'s',active:true,course:'SCM',distance:100,stroke:'Freestyle'}],world_aquatics_base_times:[{id:'b',active:true,course:'SCM',distance:100,stroke:'Freestyle',base_seconds:46}]};
function routeTable(url){const m=url.match(/\/rest\/v1\/([^?]+)/);return m&&decodeURIComponent(m[1])}
function offset(url){return Number(new URL(url).searchParams.get('offset')||0)}
function limit(url){return Number(new URL(url).searchParams.get('limit')||1000)}
function fakeFetch({failTables=new Set(),networkFailTables=new Set(),calls=[]}={}){return async(url,opts={})=>{calls.push({url,opts});const table=routeTable(url);if(networkFailTables.has(table))throw new TypeError('offline');if(failTables.has(table))return{ok:false,status:404,json:async()=>({message:`${table} unavailable`})};const rows=required[table]||[],slice=rows.slice(offset(url),offset(url)+limit(url));return{ok:true,status:200,json:async()=>JSON.parse(JSON.stringify(slice))}}}
function cachedSnapshot(){return{schema:'msos.assembly.programme-data.v1',organisationId:'org-cache',loadedAt:'2026-08-17T20:00:00Z',tables:{athletes:[{id:'cached',full_name:'Cached Swimmer',squad:'National'}],training_test_types:[{id:'tt',test_key:'t400_freestyle'}],training_test_results:[],athlete_adaptation_profiles:[],coach_results:[],results_pb_board:[],results_event_history:[],pathway_standards:[],world_aquatics_base_times:[]},errors:{}}}
const pending=[];
console.log(`Assembly Programme Data ${Data.VERSION}`);

test('existing MSOS auth and organisation context are read without importing legacy app logic',()=>{const ctx=Data.contextFrom({storage:storage(),config});assert.strictEqual(ctx.organisationId,'org-1');assert.strictEqual(ctx.accessToken,'secret-token');assert.deepStrictEqual(Data.publicContext(ctx),{organisationId:'org-1',authenticated:true,configured:true})});
pending.push(test('network load pages current athletes and builds only engine input data',async()=>{const calls=[],cache=new FakeCache(),out=await Data.loadProgrammeData({fetchImpl:fakeFetch({calls}),cache,storage:storage(),config,pageSize:2,clock:()=> '2026-08-18T07:30:00Z'});assert.strictEqual(out.source,'network');assert.strictEqual(out.counts.athletes,3);assert.strictEqual(out.evidenceSources[0].data.training_test_results[0].result_seconds,300);assert.strictEqual(out.profiles[0].athlete_id,'a1');assert.strictEqual(out.standards[0].id,'s');assert.strictEqual(out.baseTimes[0].id,'b');assert(calls.filter(x=>routeTable(x.url)==='athletes').length===2,'athletes were not paged');assert(calls.every(x=>(x.opts.method||'GET')==='GET'),'adapter attempted a non-GET request');assert(calls.filter(x=>!['pathway_standards','world_aquatics_base_times'].includes(routeTable(x.url))).every(x=>new URL(x.url).searchParams.get('organisation_id')==='eq.org-1'),'organisation filter missing');assert(!JSON.stringify(out).includes('secret-token'),'access token leaked into engine input/output');assert.strictEqual(cache.puts.length,1)}));
pending.push(test('optional pathway source failure is visible but cannot remove core swimmer and T400 data',async()=>{const out=await Data.loadProgrammeData({fetchImpl:fakeFetch({failTables:new Set(['pathway_standards','results_pb_board'])}),cache:new FakeCache(),storage:storage(),config});assert.strictEqual(out.source,'network');assert.strictEqual(out.counts.athletes,3);assert.strictEqual(out.counts.training_test_results,1);assert.deepStrictEqual(out.standards,[]);assert(/pathway_standards/.test(out.warning));assert(/results_pb_board/.test(out.warning))}));
pending.push(test('missing live credentials uses last safe cached programme snapshot rather than inventing empty swimmers',async()=>{const out=await Data.loadProgrammeData({fetchImpl:fakeFetch(),cache:new FakeCache(cachedSnapshot()),storage:new FakeStorage(),config});assert.strictEqual(out.source,'cache');assert.strictEqual(out.evidenceSources[0].data.athletes[0].id,'cached');assert(/Using cached swimmer\/performance data/.test(out.warning))}));
pending.push(test('required-table network failure falls back to the complete cached snapshot',async()=>{const out=await Data.loadProgrammeData({fetchImpl:fakeFetch({networkFailTables:new Set(['athletes'])}),cache:new FakeCache(cachedSnapshot()),storage:storage(),config});assert.strictEqual(out.source,'cache');assert.strictEqual(out.organisationId,'org-cache');assert.strictEqual(out.counts.athletes,1);assert(/cloud read failed/i.test(out.warning))}));
pending.push(test('required cloud failure with no cache fails closed instead of booting an empty Roll',async()=>{await assert.rejects(()=>Data.loadProgrammeData({fetchImpl:fakeFetch({failTables:new Set(['athletes'])}),cache:new FakeCache(),storage:storage(),config}),/athletes unavailable/)}));
pending.push(test('missing credentials and no cache fail explicitly',async()=>{await assert.rejects(()=>Data.loadProgrammeData({fetchImpl:fakeFetch(),cache:new FakeCache(),storage:new FakeStorage(),config}),/no safe cached programme data/)}));
Promise.all(pending.filter(Boolean)).then(()=>{if(failures){console.error(`\n${failures} programme data regression(s) failed`);process.exit(1)}console.log('\nALL ASSEMBLY PROGRAMME DATA REGRESSIONS PASS')});
