'use strict';
const assert=require('assert');
const Truth=require('../engines/session-truth.js');
const Entities=require('../engines/entity-registry.js');
const Capture=require('../engines/capture-evidence.js');
let fails=0;
function test(name,fn){try{fn();console.log('PASS',name)}catch(e){fails++;console.error('FAIL',name,'\n ',e.stack||e.message)}}
function clock(){let n=0;return()=>`2026-08-18T06:00:${String(n++).padStart(2,'0')}+12:00`}
const entities=Entities.create({sources:[{id:'athletes',priority:100,trust:'verified',data:{athletes:[{id:'yana',full_name:'Yana Shakhnovich',active:true},{id:'molly',full_name:'Molly McKernan',active:true}]}}]});
const session=Truth.parse(`Warm up\n400 Choice\nMain set\n3 Rounds:\n5 x 100 Free Threshold 10 sr\n400 Easy`,{id:'capture-session',date:'2026-08-18',dayPart:'AM',course:'SCM',squads:['National','Development'],venue:'AquaGym'});
const main=session.blocks.find(b=>b.type==='main_set'),group=main.items[0],threshold=group.items[0];
function engine(initial=null){return Capture.create({storage:new Capture.MemoryStorage(initial),evidence:entities,clock:clock()})}

test('boot is read-only',()=>{const storage=new Capture.MemoryStorage({schema:Capture.SCHEMA,captures:[],journal:[],updatedAt:'old'});Capture.create({storage,evidence:entities,clock:clock()});assert.equal(storage.reads,1);assert.equal(storage.writes,0)});
test('note at current Board item stores permanent session/block/item/athlete address',()=>{const c=engine(),row=c.create(session,{type:'note',blockId:main.id,itemId:threshold.id,athleteIds:['yana'],coachId:'andy',text:'Lost shape over final 15m'});assert.equal(row.session_id,session.id);assert.equal(row.block_id,main.id);assert.equal(row.item_id,threshold.id);assert.deepEqual(row.athlete_ids,['yana']);assert.equal(row.coach_id,'andy');assert.equal(c.atBoardPoint(session,{blockId:main.id,itemId:threshold.id,athleteId:'yana'}).length,1)});
test('group note can be session/block scoped without a swimmer',()=>{const c=engine(),row=c.create(session,{type:'observation',blockId:main.id,coachId:'andy',text:'Whole group held Threshold shape well'});assert.equal(row.item_id,null);assert.deepEqual(row.athlete_ids,[]);assert.equal(c.query({sessionId:session.id,blockId:main.id}).length,1)});
test('voice photo and video require an explicit saved media reference',()=>{const c=engine();for(const type of ['voice','photo','video'])assert.throws(()=>c.create(session,{type,blockId:main.id,itemId:threshold.id,coachId:'andy'}),/requires mediaRef/);const voice=c.create(session,{type:'voice',blockId:main.id,itemId:threshold.id,athleteIds:['molly'],coachId:'andy',mediaRef:{localId:'media-1'},text:'Transcript later'});assert.deepEqual(voice.media_ref,{localId:'media-1'})});
test('capture rejects an item that does not belong to the supplied block',()=>{const c=engine(),warm=session.blocks.find(b=>b.type==='warm_up');assert.throws(()=>c.create(session,{type:'note',blockId:warm.id,itemId:threshold.id,text:'bad context'}),/does not belong/)});
test('capture rejects unknown session node instead of inventing an attachment location',()=>{const c=engine();assert.throws(()=>c.create(session,{type:'note',itemId:'missing-item',text:'bad'}),/Item not found/)});
test('capture athlete identities come through canonical identity contract and unknown names fail',()=>{const c=engine(),row=c.create(session,{type:'note',itemId:threshold.id,athleteIds:['Yana Shakhnovich'],text:'cue'});assert.deepEqual(row.athlete_ids,['yana']);assert.throws(()=>c.create(session,{type:'note',itemId:threshold.id,athleteIds:['Imaginary Swimmer'],text:'cue'}),/Athlete not found/)});
test('amend is revisioned and original journal evidence is retained',()=>{const c=engine(),row=c.create(session,{id:'cap-1',type:'note',itemId:threshold.id,athleteIds:['yana'],text:'First wording'});const changed=c.amend(row.id,{text:'Corrected wording',note:'coach corrected note'});assert.equal(changed.revision,2);assert.equal(changed.text,'Corrected wording');const history=c.history(row.id);assert.deepEqual(history.map(x=>x.action),['create','amend']);assert.equal(history[1].before.text,'First wording');assert.equal(history[1].after.text,'Corrected wording')});
test('retire is a tombstone, not destructive deletion',()=>{const c=engine(),row=c.create(session,{id:'cap-retire',type:'note',itemId:threshold.id,text:'Wrong swimmer'});c.retire(row.id,{note:'entered in error'});assert.equal(c.get(row.id).status,'retired');assert.equal(c.query({sessionId:session.id}).length,0);assert.equal(c.query({sessionId:session.id,status:''}).length,1);assert.equal(c.history(row.id).at(-1).action,'retire')});
test('query by swimmer returns evidence from any exact board point in the session',()=>{const c=engine();c.create(session,{type:'note',itemId:threshold.id,athleteIds:['yana'],text:'A'});c.create(session,{type:'photo',blockId:main.id,athleteIds:['yana'],mediaRef:{localId:'photo-1'}});c.create(session,{type:'note',itemId:threshold.id,athleteIds:['molly'],text:'B'});assert.equal(c.query({sessionId:session.id,athleteId:'yana'}).length,2);assert.equal(c.query({sessionId:session.id,athleteId:'molly'}).length,1)});
test('capture operations never mutate canonical Session Truth',()=>{const before=JSON.stringify(session),c=engine();c.create(session,{type:'note',itemId:threshold.id,athleteIds:['yana'],text:'A'});c.amend(c.query({sessionId:session.id})[0].id,{text:'B'});assert.equal(JSON.stringify(session),before)});
test('media reference is metadata only and remains opaque to Capture Engine',()=>{const c=engine(),media={localId:'video-1',mime:'video/mp4',bytes:123456,opaqueHandle:'xyz'},row=c.create(session,{type:'video',itemId:threshold.id,mediaRef:media});media.localId='mutated';assert.equal(row.media_ref.localId,'video-1');assert.equal(c.get(row.id).media_ref.opaqueHandle,'xyz')});
if(fails){console.error(`\n${fails} Capture Evidence regression(s) failed`);process.exit(1)}console.log('\nALL CAPTURE EVIDENCE REGRESSIONS PASS');
