'use strict';
const assert=require('assert');
const Publication=require('../engines/evidence-publication.js');
const Entities=require('../engines/entity-registry.js');
const Evidence=require('../engines/evidence-retrieval.js');
let fails=0;function test(name,fn){try{fn();console.log('PASS',name)}catch(e){fails++;console.error('FAIL',name,'\n ',e.stack||e.message)}}
const testRows=[{id:'test-prov',athlete_id:'molly',test_key:'t400_freestyle',result_seconds:320,result_date:'2026-08-18',pool_course:'SCM',distance:400,stroke:'Freestyle',evidence_status:'provisional'},{id:'test-ver',athlete_id:'molly',test_key:'t400_freestyle',result_seconds:325,result_date:'2026-08-01',pool_course:'SCM',distance:400,stroke:'Freestyle',evidence_status:'verified',valid_for_anchor:true}];
const meetRows=[{id:'meet-prov',athlete_id:'molly',distance:100,stroke:'Freestyle',pool_course:'SCM',result_seconds:59,result_date:'2026-08-18',evidence_status:'provisional'},{id:'meet-ver',athlete_id:'molly',distance:100,stroke:'Freestyle',pool_course:'SCM',result_seconds:61,result_date:'2026-07-20',evidence_status:'verified'}];
const testResults={query:()=>JSON.parse(JSON.stringify(testRows)),evidenceRows:({verifiedOnly=true}={})=>JSON.parse(JSON.stringify(testRows.filter(x=>!verifiedOnly||x.evidence_status==='verified')))};
const meetResults={query:()=>JSON.parse(JSON.stringify(meetRows)),evidenceRows:({verifiedOnly=true}={})=>JSON.parse(JSON.stringify(meetRows.filter(x=>!verifiedOnly||x.evidence_status==='verified')))};
const p=Publication.create({testResults,meetResults});

test('provisional evidence remains visible operationally',()=>{const x=p.provisional({athleteRef:'molly'});assert.equal(x.count,2);assert(x.tests.some(r=>r.id==='test-prov'&&r.truth_scope==='operational'&&!r.permanent_eligible));assert(x.meet_results.some(r=>r.id==='meet-prov'&&!r.permanent_eligible))});
test('verified source publishes verified evidence only',()=>{const s=p.verifiedSource();assert.equal(s.publication.verified_only,true);assert.deepEqual(s.data.training_test_results.map(x=>x.id),['test-ver']);assert.deepEqual(s.data.coach_results.map(x=>x.id),['meet-ver']);assert.equal(s.trust,'verified')});
test('publisher does not mutate result-input rows',()=>{const before=JSON.stringify({testRows,meetRows});p.operationalTests({});p.operationalMeetResults({});p.verifiedSource();assert.equal(JSON.stringify({testRows,meetRows}),before)});
test('Evidence Retrieval built from publication source cannot see provisional meet PB',()=>{const identity={id:'identity',priority:300,trust:'current',data:{athletes:[{id:'molly',full_name:'Molly McKernan',active:true}]}};const source=p.verifiedSource(),entities=Entities.create({sources:[identity,source]}),e=Evidence.create({sources:[identity,source],entities});const pb=e.personalBest('molly',{distance:100,stroke:'Freestyle',course:'SCM'});assert(pb);assert.equal(pb.result_seconds,61);assert.equal(pb.id,'meet-ver');assert(!e.results('molly',{}).some(x=>x.id==='meet-prov'))});
test('Evidence Retrieval test anchor cannot see provisional faster test',()=>{const identity={id:'identity',priority:300,trust:'current',data:{athletes:[{id:'molly',full_name:'Molly McKernan',active:true}]}};const source=p.verifiedSource(),entities=Entities.create({sources:[identity,source]}),e=Evidence.create({sources:[identity,source],entities});const latest=e.latestTrainingTestEvidence('molly',{testKey:'t400_freestyle'});assert.equal(latest.status,'ok');assert.equal(latest.seconds,325);assert.equal(latest.row.id,'test-ver')});
test('status reports operational and published counts separately',()=>{const x=p.status();assert.equal(x.operational.training_tests,2);assert.equal(x.operational.meet_results,2);assert.equal(x.operational.provisional,2);assert.equal(x.published.training_tests,1);assert.equal(x.published.meet_results,1)});
if(fails){console.error(`\n${fails} Evidence Publication regression(s) failed`);process.exit(1)}console.log('\nALL EVIDENCE PUBLICATION REGRESSIONS PASS');
