'use strict';
const assert=require('assert');
const Core=require('../rebuild/portal-core.js');
const Attendance=require('../engines/attendance.js');
const Capture=require('../engines/capture-evidence.js');
let fails=0;
function test(name,fn){try{fn();console.log('PASS',name)}catch(e){fails++;console.error('FAIL',name,'\n ',e.stack||e.message)}}
function core(){let n=0;const clock=()=>`2026-08-18T15:45:${String(n++).padStart(2,'0')}+12:00`;return Core.create({clock,attendanceStorage:new Attendance.MemoryStorage(),captureStorage:new Capture.MemoryStorage(),evidenceSources:[{id:'roster',priority:100,trust:'current',data:{athletes:[{id:'molly',full_name:'Molly McKernan',active:true,squad:'Development'},{id:'mk',full_name:'McKenzie Drage',active:true,squad:'National'}]}}]})}

test('portal routes multi-swimmer timing as raw measurement with no T400 validity inside Timing',()=>{const c=core();c.createTimingSession({id:'timer-1',context:{sessionId:'training-1',blockId:'b-test',itemId:'i-test',testProtocolId:'protocol-t400-freestyle'},course:'SCM',poolLength:25,label:'T400'});c.assignTimingAthlete('timer-1','molly',{lane:1});c.assignTimingAthlete('timer-1','mk',{lane:2});c.startTiming('timer-1');c.recordTimingSplit('timer-1','molly',{distance:100,elapsedSeconds:80});c.recordTimingSplit('timer-1','mk',{distance:100,elapsedSeconds:110});c.finishTimingAthlete('timer-1','molly',{distance:400,elapsedSeconds:324.6});c.finishTimingAthlete('timer-1','mk',{distance:400,elapsedSeconds:450.1});const timing=c.timingSession('timer-1');assert.equal(timing.measurements.filter(x=>x.kind==='finish').length,2);assert(!/valid_for_anchor|threshold|development|aerobic/i.test(JSON.stringify(timing)));const trail=c.portal.auditTrail();assert(trail.some(x=>x.caller==='measurement-surface'&&x.target==='timing'&&x.kind==='command'));assert(trail.some(x=>x.caller==='timing'&&x.target==='entity-registry'&&x.operation==='resolveAthlete'))});

test('Test Protocol owns whether timing observation qualifies as T400, then Test Result Input creates provisional evidence',()=>{const c=core();c.createTimingSession({id:'timer-2',context:{testProtocolId:'protocol-t400-freestyle'},course:'SCM',poolLength:25});c.assignTimingAthlete('timer-2','molly');c.startTiming('timer-2');c.recordTimingSplit('timer-2','molly',{distance:100,elapsedSeconds:80});c.recordTimingSplit('timer-2','molly',{distance:200,elapsedSeconds:161});c.recordTimingSplit('timer-2','molly',{distance:300,elapsedSeconds:243});c.finishTimingAthlete('timer-2','molly',{distance:400,elapsedSeconds:324.6});const r=c.captureTestFromTiming('timer-2','molly','t400_freestyle',{coachId:'andy'});assert.equal(r.evidence_status,'provisional');assert.equal(r.test_key,'t400_freestyle');assert.equal(r.result_seconds,324.6);const trail=c.portal.auditTrail();assert(trail.some(x=>x.caller==='test-result-input'&&x.target==='timing'&&x.operation==='get'));assert(trail.some(x=>x.caller==='test-result-input'&&x.target==='timing'&&x.operation==='timeline'));assert(trail.some(x=>x.caller==='test-result-input'&&x.target==='test-protocol'&&x.operation==='validateObservation'));assert(trail.some(x=>x.caller==='test-result-input'&&x.target==='entity-registry'&&x.operation==='resolveAthlete'))});

test('verification is explicit and creates evidence-shaped export without hidden mutation of Evidence Retrieval',()=>{const c=core();c.createTimingSession({id:'timer-3',course:'SCM',poolLength:25});c.assignTimingAthlete('timer-3','molly');c.startTiming('timer-3');c.finishTimingAthlete('timer-3','molly',{distance:400,elapsedSeconds:324.6});const r=c.captureTestFromTiming('timer-3','molly','t400_freestyle');assert.equal(c.testEvidenceRows().length,0);c.verifyTestResult(r.id,{coachId:'andy'});const rows=c.testEvidenceRows();assert.equal(rows.length,1);assert.equal(rows[0].athlete_id,'molly');assert.equal(rows[0].valid_for_anchor,true);assert.equal(c.t400('molly').status,'missing');assert(!c.portal.auditTrail().some(x=>x.caller==='test-result-input'&&x.target==='evidence-retrieval'))});

test('invalid timing remains intact when protocol/result conversion fails',()=>{const c=core();c.createTimingSession({id:'timer-short',course:'SCM',poolLength:25});c.assignTimingAthlete('timer-short','molly');c.startTiming('timer-short');c.finishTimingAthlete('timer-short','molly',{distance:300,elapsedSeconds:240});assert.throws(()=>c.captureTestFromTiming('timer-short','molly','t400_freestyle'),/Distance must be 400m/);assert.equal(c.timingSession('timer-short').measurements.at(-1).distance_m,300);assert.equal(c.testResults({}).length,0)});

test('Test Protocol is independently authorable while measurement surface cannot rewrite protocols',()=>{const c=core(),p=c.updateTestProtocol({id:'protocol-200-kick',test_key:'t200_kick',name:'200 Kick',distance_m:200,stroke:'Freestyle',allowed_courses:['SCM']},{coachId:'andy'});assert.equal(p.id,'protocol-200-kick');assert.equal(c.testProtocol('t200_kick').distance_m,200);assert.throws(()=>c.measurement.command('test-protocol','upsert',{args:[{}]}),e=>e.code==='CALL_NOT_ALLOWED')});

test('app shell has no timing or test-result write authority',()=>{const c=core();assert.throws(()=>c.shell.command('timing','createSession',{args:[{}]}),e=>e.code==='CALL_NOT_ALLOWED');assert.throws(()=>c.shell.command('test-result-input','verify',{args:['x']}),e=>e.code==='CALL_NOT_ALLOWED')});

if(fails){console.error(`\n${fails} measurement pipeline regression(s) failed`);process.exit(1)}
console.log('\nALL MEASUREMENT PIPELINE INTEGRATION REGRESSIONS PASS');
