'use strict';
const assert=require('assert');
const Entities=require('../engines/entity-registry.js');
const Meet=require('../engines/meet-lifecycle.js');
let fails=0;function test(name,fn){try{fn();console.log('PASS',name)}catch(e){fails++;console.error('FAIL',name,'\n ',e.stack||e.message)}}
let tick=0;const clock=()=>`2026-08-18T15:30:${String(tick++%60).padStart(2,'0')}+12:00`;
const entities=Entities.create({sources:[{id:'current',priority:100,trust:'current',data:{athletes:[{id:'luke',full_name:'Luke Thompson',active:true},{id:'coral',full_name:'Coral Sturls',active:true},{id:'alex',full_name:'Alex Gibson',active:true}]}}]});
function engine(storage=new Meet.MemoryStorage()){return Meet.create({storage,entities,clock})}
function seed(m){m.upsertMeet({id:'canty-sc',name:'Canterbury SC Champs',start_date:'2026-08-20',course:'SCM',venue:'Parakiore'});m.upsertSession({id:'day1-am',meet_id:'canty-sc',date:'2026-08-20',name:'Day 1 AM'});m.upsertEvent({id:'e100fly-f',meet_id:'canty-sc',meet_session_id:'day1-am',event_no:'12',distance_m:100,stroke:'Butterfly',sex:'F'});m.upsertEvent({id:'e100free-m',meet_id:'canty-sc',meet_session_id:'day1-am',event_no:'15',distance_m:100,stroke:'Freestyle',sex:'M'});m.upsertEntry({id:'entry-coral',meet_id:'canty-sc',event_id:'e100fly-f',athlete_id:'coral'});m.upsertEntry({id:'entry-luke',meet_id:'canty-sc',event_id:'e100free-m',athlete_id:'luke'});m.upsertRace({id:'race-coral-heat',meet_id:'canty-sc',event_id:'e100fly-f',entry_id:'entry-coral',athlete_id:'coral',round:'heat',heat:'2',lane:'5'});m.upsertRace({id:'race-luke-heat',meet_id:'canty-sc',event_id:'e100free-m',entry_id:'entry-luke',athlete_id:'luke',round:'heat',heat:'3',lane:'4'});return m}

test('boot is read-only and owns meet truth separately from training-session truth',()=>{const storage=new Meet.MemoryStorage({schema:Meet.SCHEMA,meets:[],sessions:[],events:[],entries:[],races:[],journal:[]});Meet.create({storage,entities,clock});assert.equal(storage.reads,1);assert.equal(storage.writes,0)});
test('meet lineage is explicit meet -> session -> event -> entry -> race',()=>{const m=seed(engine()),x=m.lineage('race-coral-heat');assert.equal(x.meet.id,'canty-sc');assert.equal(x.session.id,'day1-am');assert.equal(x.event.id,'e100fly-f');assert.equal(x.entry.id,'entry-coral');assert.equal(x.race.id,'race-coral-heat');assert.equal(x.race.athlete_id,'coral')});
test('event and race matching are exact and do not guess swimmer identity',()=>{const m=seed(engine()),e=m.matchEvent({meetId:'canty-sc',distance:100,stroke:'Butterfly'}),r=m.matchRace({meetId:'canty-sc',athleteRef:'Coral Sturls',distance:100,stroke:'Fly',round:'heat'});assert.equal(e.status,'ok');assert.equal(e.event.id,'e100fly-f');assert.equal(r.status,'ok');assert.equal(r.race.id,'race-coral-heat');assert.equal(m.matchRace({meetId:'canty-sc',athleteRef:'Imaginary',distance:100,stroke:'Fly'}).status,'missing_athlete')});
test('entry and race writes reject cross-meet or wrong-athlete lineage',()=>{const m=seed(engine());m.upsertMeet({id:'other',name:'Other Meet'});assert.throws(()=>m.upsertEntry({id:'bad',meet_id:'other',event_id:'e100fly-f',athlete_id:'coral'}),/does not belong/);assert.throws(()=>m.upsertRace({id:'bad-race',meet_id:'canty-sc',event_id:'e100fly-f',entry_id:'entry-coral',athlete_id:'luke'}),/matching meet entry/)});
test('missing race can be added later without inventing a result',()=>{const m=seed(engine());m.upsertEntry({id:'entry-alex',meet_id:'canty-sc',event_id:'e100free-m',athlete_id:'alex'});const r=m.upsertRace({meet_id:'canty-sc',event_id:'e100free-m',entry_id:'entry-alex',athlete_id:'alex',round:'heat',heat:'4',lane:'6'});assert(r.id);assert.equal(Object.prototype.hasOwnProperty.call(r,'result_seconds'),false);assert.equal(Object.prototype.hasOwnProperty.call(r,'place'),false)});
test('ambiguous event/race matching fails explicitly',()=>{const m=seed(engine());m.upsertEvent({id:'e100fly-f2',meet_id:'canty-sc',distance_m:100,stroke:'Butterfly',sex:'F'});assert.equal(m.matchEvent({meetId:'canty-sc',distance:100,stroke:'Butterfly'}).status,'ambiguous')});
test('retiring a race preserves history and removes it from normal matching',()=>{const m=seed(engine());m.retire('race','race-luke-heat',{coachId:'coach'});assert.equal(m.getRace('race-luke-heat').status,'retired');assert.equal(m.matchRace({meetId:'canty-sc',raceId:'race-luke-heat'}).status,'ok');assert(m.history('race','race-luke-heat').some(x=>x.action==='update'))});
test('reload preserves exact meet state without writes',()=>{const storage=new Meet.MemoryStorage(),m=seed(engine(storage)),writes=storage.writes,reopened=engine(storage);assert.equal(storage.writes,writes);assert.equal(reopened.getRace('race-coral-heat').lane,'5');assert.equal(reopened.getEvent('e100fly-f').distance_m,100)});
if(fails){console.error(`\n${fails} Meet Lifecycle regression(s) failed`);process.exit(1)}console.log('\nALL MEET LIFECYCLE REGRESSIONS PASS');
