'use strict';
const assert=require('assert');
const Portal=require('../rebuild/engine-portal.js');
const Entities=require('../engines/entity-registry.js');
const Meet=require('../engines/meet-lifecycle.js');
const Results=require('../engines/meet-result-input.js');
const Recon=require('../engines/official-results-reconciliation.js');
let fails=0;function test(name,fn){try{fn();console.log('PASS',name)}catch(e){fails++;console.error('FAIL',name,'\n ',e.stack||e.message)}}
let tick=0;const clock=()=>`2026-08-18T16:00:${String(tick++%60).padStart(2,'0')}+12:00`;
const call=(instance,method,input)=>instance[method](...(input?.args||[]));
const proxy=(client,target,methods,kind='query')=>Object.freeze(Object.fromEntries(methods.map(name=>[name,(...args)=>client[kind](target,name,{args})])));
function core(){const portal=Portal.create({clock}),I={};
 portal.register({id:'entity-registry',version:Entities.VERSION,queries:{resolveAthlete:i=>call(I.entities,'resolveAthlete',i),athleteId:i=>call(I.entities,'athleteId',i)}});
 portal.register({id:'meet-lifecycle',version:Meet.VERSION,calls:{query:{'entity-registry':['resolveAthlete','athleteId']}},queries:{getMeet:i=>call(I.meets,'getMeet',i),getEvent:i=>call(I.meets,'getEvent',i),getEntry:i=>call(I.meets,'getEntry',i),getRace:i=>call(I.meets,'getRace',i),matchEvent:i=>call(I.meets,'matchEvent',i),matchRace:i=>call(I.meets,'matchRace',i),entryFor:i=>call(I.meets,'entryFor',i),lineage:i=>call(I.meets,'lineage',i),athleteRaces:i=>call(I.meets,'athleteRaces',i)},commands:{upsertMeet:i=>call(I.meets,'upsertMeet',i),upsertEvent:i=>call(I.meets,'upsertEvent',i),upsertEntry:i=>call(I.meets,'upsertEntry',i),upsertRace:i=>call(I.meets,'upsertRace',i)}});
 portal.register({id:'meet-result-input',version:Results.VERSION,calls:{query:{'entity-registry':['resolveAthlete'],'meet-lifecycle':['matchRace','lineage']},command:{}},queries:{get:i=>call(I.results,'get',i),byRace:i=>call(I.results,'byRace',i),query:i=>call(I.results,'query',i),evidenceRows:i=>call(I.results,'evidenceRows',i)},commands:{capturePaste:i=>call(I.results,'capturePaste',i),captureImage:i=>call(I.results,'captureImage',i),captureManual:i=>call(I.results,'captureManual',i),captureOfficial:i=>call(I.results,'captureOfficial',i),applyOfficial:i=>call(I.results,'applyOfficial',i),amendProvisional:i=>call(I.results,'amendProvisional',i)}});
 portal.register({id:'official-reconciliation',version:Recon.VERSION,calls:{query:{'meet-lifecycle':['matchRace','matchEvent','entryFor'],'meet-result-input':['byRace','query']},command:{'meet-lifecycle':['upsertEntry','upsertRace'],'meet-result-input':['applyOfficial','captureOfficial']}},queries:{preview:i=>call(I.recon,'preview',i),get:i=>call(I.recon,'get',i)},commands:{apply:i=>call(I.recon,'apply',i)}});
 portal.register({id:'meet-deck-surface',version:'1.0.0',kind:'surface',calls:{query:{'meet-lifecycle':['getMeet','athleteRaces','lineage'],'meet-result-input':['get','byRace','query'],'official-reconciliation':['preview','get']},command:{'meet-lifecycle':['upsertMeet','upsertEvent','upsertEntry','upsertRace'],'meet-result-input':['capturePaste','captureImage','captureManual'],'official-reconciliation':['apply']}}});
 portal.register({id:'app-shell',version:'1.0.0',kind:'shell'});
 I.entities=Entities.create({sources:[{id:'current',priority:100,trust:'current',data:{athletes:[{id:'coral',full_name:'Coral Sturls',active:true},{id:'luke',full_name:'Luke Thompson',active:true},{id:'ruby',full_name:'Ruby Lee',active:true}]}}]});
 const entityFor=caller=>proxy(portal.client(caller),'entity-registry',['resolveAthlete','athleteId']);
 I.meets=Meet.create({storage:new Meet.MemoryStorage(),entities:entityFor('meet-lifecycle'),clock});
 const meetsForResults=proxy(portal.client('meet-result-input'),'meet-lifecycle',['matchRace','lineage']);
 I.results=Results.create({storage:new Results.MemoryStorage(),entities:entityFor('meet-result-input'),meets:meetsForResults,clock});
 const meetsForRecon={...proxy(portal.client('official-reconciliation'),'meet-lifecycle',['matchRace','matchEvent','entryFor']),...proxy(portal.client('official-reconciliation'),'meet-lifecycle',['upsertEntry','upsertRace'],'command')};
 const resultsForRecon={...proxy(portal.client('official-reconciliation'),'meet-result-input',['byRace','query']),...proxy(portal.client('official-reconciliation'),'meet-result-input',['applyOfficial','captureOfficial'],'command')};
 I.recon=Recon.create({storage:new Recon.MemoryStorage(),meets:meetsForRecon,results:resultsForRecon,clock});
 portal.seal();const deck=portal.client('meet-deck-surface'),shell=portal.client('app-shell');
 function seed(){deck.command('meet-lifecycle','upsertMeet',{args:[{id:'meet',name:'Canterbury SC Champs',course:'SCM'}]});deck.command('meet-lifecycle','upsertEvent',{args:[{id:'fly',meet_id:'meet',distance_m:100,stroke:'Butterfly'}]});deck.command('meet-lifecycle','upsertEvent',{args:[{id:'free',meet_id:'meet',distance_m:100,stroke:'Freestyle'}]});deck.command('meet-lifecycle','upsertEntry',{args:[{id:'ec',meet_id:'meet',event_id:'fly',athlete_id:'coral'}]});deck.command('meet-lifecycle','upsertEntry',{args:[{id:'el',meet_id:'meet',event_id:'free',athlete_id:'luke'}]});deck.command('meet-lifecycle','upsertEntry',{args:[{id:'er',meet_id:'meet',event_id:'free',athlete_id:'ruby'}]});deck.command('meet-lifecycle','upsertRace',{args:[{id:'rc',meet_id:'meet',event_id:'fly',entry_id:'ec',athlete_id:'coral',round:'heat'}]});deck.command('meet-lifecycle','upsertRace',{args:[{id:'rl',meet_id:'meet',event_id:'free',entry_id:'el',athlete_id:'luke',round:'heat'}]})}
 return{portal,deck,shell,seed}}

test('Meet Deck captures copied result through portal as provisional, not official truth',()=>{const c=core();c.seed();const r=c.deck.command('meet-result-input','capturePaste',{args:[{meetId:'meet',raceId:'rc',resultSeconds:70.23},{sourceType:'swimify',sourceRef:'copy'}]});assert.equal(r.evidence_status,'provisional');const trail=c.portal.auditTrail();assert(trail.some(x=>x.caller==='meet-result-input'&&x.target==='meet-lifecycle'&&x.operation==='matchRace'));assert(trail.some(x=>x.caller==='meet-lifecycle'&&x.target==='entity-registry'&&x.operation==='resolveAthlete'))});
test('official reconciliation routes through portal and corrects poolside result without destroying observation',()=>{const c=core();c.seed();const r=c.deck.command('meet-result-input','capturePaste',{args:[{meetId:'meet',raceId:'rl',resultSeconds:50.98,place:1},{sourceRef:'pool'}]});const report=c.deck.command('official-reconciliation','apply',{args:[{meetId:'meet',sourceRef:'official.tm',officialRows:[{race_id:'rl',result_seconds:51.02,place:2}]}]});const after=c.deck.query('meet-result-input','get',{args:[r.id]});assert.equal(report.counts.corrected,1);assert.equal(after.result_seconds,51.02);assert.equal(after.captured_observation.result_seconds,50.98);const trail=c.portal.auditTrail();assert(trail.some(x=>x.caller==='official-reconciliation'&&x.target==='meet-result-input'&&x.kind==='command'&&x.operation==='applyOfficial'))});
test('official reconciliation can recover a missed race using Meet Lifecycle command ownership',()=>{const c=core();c.seed();const report=c.deck.command('official-reconciliation','apply',{args:[{meetId:'meet',sourceRef:'official.tm',officialRows:[{athlete_id:'ruby',event_id:'free',round:'heat',result_seconds:60.5}]}]});assert.equal(report.counts.unresolved,0);const trail=c.portal.auditTrail();assert(trail.some(x=>x.caller==='official-reconciliation'&&x.target==='meet-lifecycle'&&x.kind==='command'&&x.operation==='upsertRace'))});
test('app shell has no Meet Lifecycle or result authority',()=>{const c=core();assert.throws(()=>c.shell.query('meet-result-input','query',{args:[{}]}),e=>e.code==='CALL_NOT_ALLOWED');assert.throws(()=>c.shell.command('official-reconciliation','apply',{args:[{}]}),e=>e.code==='CALL_NOT_ALLOWED')});
test('portal audit contains routing metadata but not race times',()=>{const c=core();c.seed();c.deck.command('meet-result-input','capturePaste',{args:[{meetId:'meet',raceId:'rc',resultSeconds:70.23},{sourceRef:'pool'}]});const json=JSON.stringify(c.portal.auditTrail());assert(!/70\.23/.test(json));assert(/capturePaste/.test(json))});
if(fails){console.error(`\n${fails} Meet pipeline integration regression(s) failed`);process.exit(1)}console.log('\nALL MEET PIPELINE INTEGRATION REGRESSIONS PASS');
