'use strict';
const assert=require('assert');
const Portal=require('../rebuild/engine-portal.js');
const Entities=require('../engines/entity-registry.js');
const Standards=require('../engines/standards-records.js');
const Race=require('../engines/race-model.js');
const Publication=require('../engines/evidence-publication.js');
const Evidence=require('../engines/evidence-retrieval.js');
let fails=0;function test(name,fn){try{fn();console.log('PASS',name)}catch(e){fails++;console.error('FAIL',name,'\n ',e.stack||e.message)}}
const call=(instance,method,input)=>instance[method](...(input?.args||[]));
const proxy=(client,target,methods)=>Object.freeze(Object.fromEntries(methods.map(name=>[name,(...args)=>client.query(target,name,{args})])));
function core(){
 const portal=Portal.create({clock:()=> '2026-08-18T16:45:00+12:00'}),I={};
 const testRows=[{id:'t-prov',athlete_id:'molly',test_key:'t400_freestyle',result_seconds:320,result_date:'2026-08-18',pool_course:'SCM',distance:400,stroke:'Freestyle',evidence_status:'provisional'},{id:'t-ver',athlete_id:'molly',test_key:'t400_freestyle',result_seconds:325,result_date:'2026-08-01',pool_course:'SCM',distance:400,stroke:'Freestyle',evidence_status:'verified',valid_for_anchor:true}];
 const meetRows=[{id:'m-prov',athlete_id:'molly',distance:100,stroke:'Freestyle',pool_course:'SCM',result_seconds:61.8,result_date:'2026-08-18',evidence_status:'provisional'},{id:'m-ver',athlete_id:'molly',distance:100,stroke:'Freestyle',pool_course:'SCM',result_seconds:63.8,result_date:'2026-07-01',evidence_status:'verified',wa_points:532}];
 portal.register({id:'entity-registry',version:Entities.VERSION,queries:{resolveAthlete:i=>call(I.entities,'resolveAthlete',i),athleteId:i=>call(I.entities,'athleteId',i),sourceAthleteId:i=>call(I.entities,'sourceAthleteId',i),listAthletes:i=>call(I.entities,'listAthletes',i)}});
 portal.register({id:'test-result-input',version:'fixture',queries:{query:i=>call(I.testResults,'query',i),evidenceRows:i=>call(I.testResults,'evidenceRows',i)}});
 portal.register({id:'meet-result-input',version:'fixture',queries:{query:i=>call(I.meetResults,'query',i),evidenceRows:i=>call(I.meetResults,'evidenceRows',i)}});
 portal.register({id:'standards-records',version:Standards.VERSION,queries:{classificationStatus:i=>call(I.standards,'classificationStatus',i),forEvent:i=>call(I.standards,'forEvent',i),statusForResult:i=>call(I.standards,'statusForResult',i),points:i=>call(I.standards,'points',i),pointSteps:i=>call(I.standards,'pointSteps',i),milestones:i=>call(I.standards,'milestones',i)}});
 portal.register({id:'race-model',version:Race.VERSION,queries:{match:i=>call(I.race,'match',i),target:i=>call(I.race,'target',i),compare:i=>call(I.race,'compare',i)}});
 portal.register({id:'evidence-publication',version:Publication.VERSION,calls:{query:{'test-result-input':['query','evidenceRows'],'meet-result-input':['query','evidenceRows']}},queries:{operationalTests:i=>call(I.publication,'operationalTests',i),operationalMeetResults:i=>call(I.publication,'operationalMeetResults',i),provisional:i=>call(I.publication,'provisional',i),verifiedSource:i=>call(I.publication,'verifiedSource',i),status:i=>call(I.publication,'status',i)}});
 portal.register({id:'performance-surface',version:'1.0.0',kind:'surface',calls:{query:{'entity-registry':['resolveAthlete'],'standards-records':['classificationStatus','forEvent','statusForResult','points','pointSteps','milestones'],'race-model':['match','target','compare'],'evidence-publication':['operationalTests','operationalMeetResults','provisional','verifiedSource','status']}}});
 portal.register({id:'app-shell',version:'1.0.0',kind:'shell'});
 const identity={id:'identity',priority:300,trust:'current',data:{athletes:[{id:'molly',full_name:'Molly McKernan',sex:'F',date_of_birth:'2011-05-01',active:true}]}};
 I.entities=Entities.create({sources:[identity]});
 I.testResults={query:()=>JSON.parse(JSON.stringify(testRows)),evidenceRows:({verifiedOnly=true}={})=>JSON.parse(JSON.stringify(testRows.filter(x=>!verifiedOnly||x.evidence_status==='verified')))};
 I.meetResults={query:()=>JSON.parse(JSON.stringify(meetRows)),evidenceRows:({verifiedOnly=true}={})=>JSON.parse(JSON.stringify(meetRows.filter(x=>!verifiedOnly||x.evidence_status==='verified')))};
 I.standards=Standards.create({today:()=> '2026-08-18',standards:[{id:'nzsc',programme:'NZSC National Qualifier',standard_kind:'qualifying',course:'SCM',distance:100,stroke:'Freestyle',sex:'F',age_min:15,age_max:15,qualifying_seconds:62,active:true},{id:'final',programme:'NZ Age Finalist Benchmark',standard_kind:'benchmark',course:'SCM',distance:100,stroke:'Freestyle',sex:'F',age_min:15,age_max:15,target_seconds:59,active:true}],baseTimes:[{course:'SCM',distance:100,stroke:'Freestyle',sex:'F',base_seconds:51.71,active:true}]});
 I.race=Race.create({models:[{id:'approved-100-free',course:'SCM',distance_m:100,stroke:'Freestyle',source:'approved fixture',segments:[{distance_m:25,fraction:.22},{distance_m:25,fraction:.25},{distance_m:25,fraction:.26},{distance_m:25,fraction:.27}]}]});
 I.publication=Publication.create({testResults:proxy(portal.client('evidence-publication'),'test-result-input',['query','evidenceRows']),meetResults:proxy(portal.client('evidence-publication'),'meet-result-input',['query','evidenceRows'])});
 portal.seal();return{portal,surface:portal.client('performance-surface'),shell:portal.client('app-shell'),identity};
}

test('provisional meet result can signal a provisional qualifier without entering permanent evidence',()=>{const c=core(),ath=c.surface.query('entity-registry','resolveAthlete',{args:['molly']}),ops=c.surface.query('evidence-publication','operationalMeetResults',{args:[{}]}),prov=ops.find(x=>x.id==='m-prov'),signal=c.surface.query('standards-records','statusForResult',{args:[ath,{course:prov.pool_course,distance:prov.distance,stroke:prov.stroke},prov.result_seconds,{asOfDate:'2026-08-18'}]});assert.equal(prov.permanent_eligible,false);assert(signal.achieved.some(x=>x.id==='nzsc'));const source=c.surface.query('evidence-publication','verifiedSource',{args:[{}]}),entities=Entities.create({sources:[c.identity,source]}),evidence=Evidence.create({sources:[c.identity,source],entities});assert.equal(evidence.personalBest('molly',{course:'SCM',distance:100,stroke:'Freestyle'}).result_seconds,63.8)});
test('verified publication routes reads through portal and excludes provisional test anchor',()=>{const c=core(),source=c.surface.query('evidence-publication','verifiedSource',{args:[{}]});assert.deepEqual(source.data.training_test_results.map(x=>x.id),['t-ver']);const trail=c.portal.auditTrail();assert(trail.some(x=>x.caller==='evidence-publication'&&x.target==='test-result-input'&&x.operation==='evidenceRows'));assert(trail.some(x=>x.caller==='evidence-publication'&&x.target==='meet-result-input'&&x.operation==='evidenceRows'))});
test('standards converts real qualifier and finalist times onto the same WA ladder',()=>{const c=core(),ath=c.surface.query('entity-registry','resolveAthlete',{args:['molly']}),m=c.surface.query('standards-records','milestones',{args:[ath,{course:'SCM',distance:100,stroke:'Freestyle'},{result_seconds:63.8,wa_points:532},{asOfDate:'2026-08-18',pointStepCount:2}]});assert(m.steps.find(x=>x.id==='nzsc').points>532);assert(m.steps.find(x=>x.id==='final').points>m.steps.find(x=>x.id==='nzsc').points);assert(m.steps.some(x=>x.type==='points_step'&&x.points===550))});
test('race model returns only loaded approved split model and no implicit fallback',()=>{const c=core(),ok=c.surface.query('race-model','target',{args:[{targetSeconds:60,course:'SCM',distance:100,stroke:'Freestyle'}]}),missing=c.surface.query('race-model','target',{args:[{targetSeconds:60,course:'LCM',distance:100,stroke:'Freestyle'}]});assert.equal(ok.status,'ok');assert.equal(ok.model.source,'approved fixture');assert.equal(missing.status,'model_missing')});
test('app shell has no standards race-model or evidence-publication authority',()=>{const c=core();for(const target of ['standards-records','race-model','evidence-publication'])assert.throws(()=>c.shell.query(target,'statusForResult',{args:[]}),e=>e.code==='CALL_NOT_ALLOWED')});
test('portal audit never stores result time payload values',()=>{const c=core();c.surface.query('evidence-publication','operationalMeetResults',{args:[{}]});const json=JSON.stringify(c.portal.auditTrail());assert(!/61\.8|63\.8/.test(json));assert(/operationalMeetResults/.test(json))});
if(fails){console.error(`\n${fails} Performance pipeline integration regression(s) failed`);process.exit(1)}console.log('\nALL PERFORMANCE PIPELINE INTEGRATION REGRESSIONS PASS');
