'use strict';
const assert=require('assert');
const Core=require('../rebuild/portal-core.js');
const Attendance=require('../engines/attendance.js');
const Capture=require('../engines/capture-evidence.js');
const Plan=require('../engines/plan-context.js');
let fails=0;function test(name,fn){try{fn();console.log('PASS',name)}catch(e){fails++;console.error('FAIL',name,'\n ',e.stack||e.message)}}
let tick=0;const clock=()=>`2026-08-18T14:30:${String(tick++%60).padStart(2,'0')}+12:00`;
function core(){return Core.create({clock,attendanceStorage:new Attendance.MemoryStorage(),captureStorage:new Capture.MemoryStorage(),planStorage:new Plan.MemoryStorage(),
 evidenceAliases:[{canonicalName:'Alexandra Hanson',aliases:['Alex Hanson']}],
 evidenceSources:[{id:'current',priority:100,trust:'current',data:{athletes:[{id:'a1',full_name:'Alexandra Hanson',squad:'National',club_id:'club-a',sex:'F',active:true}],squads:[{id:'sq-national',name:'National'}]}},{id:'legacy',priority:20,trust:'legacy',data:{athletes:[{id:'old-a1',full_name:'Alex Hanson'}]}}],
 clubs:[{id:'club-a',name:'AquaGym'}],coaches:[{id:'coach-andy',name:'Andy McLay'}],
 methodologyModels:[{id:'base',scope:'programme',physiology:{framework:'rushton_swimformation_cone'},adaptation:{inclusionFirst:true},sessionDesign:{protectPrimaryStimulus:true}},{id:'national',scope:'squad',squad_id:'sq-national',dose:{qualityRecoveryDoesNotDilutePrimary:true}},{id:'andy',scope:'coach',coach_id:'coach-andy',raceModel:{preferred100FreeModel:'john_pike'}}],
 plan:{seasons:[{id:'season',start_date:'2026-05-01',end_date:'2026-10-31',active:true}],phases:[{id:'phase',season_id:'season',start_date:'2026-08-01',end_date:'2026-08-31',active:true}],cycles:[{id:'cycle',phase_id:'phase',start_date:'2026-08-10',end_date:'2026-08-30',active:true}],weeks:[{id:'week',season_id:'season',cycle_id:'cycle',start_date:'2026-08-17',end_date:'2026-08-23',planned_exposure:{aerobic_capacity:2},active:true}],sessionIntents:[{id:'intent',session_id:'s1',week_id:'week',purpose:'Aerobic capacity',primary_stimulus:'Aerobic Capacity',active:true}],squadObjectives:[{id:'obj',squad_id:'sq-national',objective:'Build aerobic capacity',active:true}]}
})}
const session={id:'s1',identity:{date:'2026-08-18',dayPart:'AM',course:'SCM',squads:['National']}};

test('Entity Registry is the canonical identity owner across current and legacy source ids',()=>{const c=core();assert.equal(c.entity('old-a1').id,'a1');assert.equal(c.entity('Alex Hanson').id,'a1');const trail=c.portal.auditTrail();assert(trail.some(x=>x.target==='entity-registry'&&x.operation==='resolveAthlete'))});
test('Methodology resolves programme squad and coach overlays through portal and Entity Registry context',()=>{const c=core(),m=c.methodology({athleteId:'a1',coachId:'coach-andy',asOfDate:'2026-08-18'});assert.equal(m.status,'ok');assert.equal(m.context.squadId,'sq-national');assert.equal(m.model.physiology.framework,'rushton_swimformation_cone');assert.equal(m.model.dose.qualityRecoveryDoesNotDilutePrimary,true);assert.equal(m.model.raceModel.preferred100FreeModel,'john_pike');const trail=c.portal.auditTrail();assert(trail.some(x=>x.caller==='methodology'&&x.target==='entity-registry'&&x.operation==='dimensions'))});
test('Programme Plan resolves season phase cycle week and squad objective through portal',()=>{const c=core(),p=c.planContext(session);assert.equal(p.status,'ok');assert.equal(p.season.id,'season');assert.equal(p.phase.id,'phase');assert.equal(p.cycle.id,'cycle');assert.equal(p.week.id,'week');assert.equal(p.squadObjectives[0].id,'obj');const trail=c.portal.auditTrail();assert(trail.some(x=>x.caller==='programme-plan'&&x.target==='entity-registry'&&x.operation==='resolveSquad'))});
test('planning surface may write programme plan but app shell may not',()=>{const c=core();const row=c.updatePlan('sessionIntents',{id:'new-intent',date:'2026-08-19',dayPart:'PM',squads:['National'],purpose:'Regeneration',primary_stimulus:'Regeneration',active:true},{coachId:'coach-andy'});assert.equal(row.id,'new-intent');assert.equal(c.weeklyPlan({date:'2026-08-18',squadId:'sq-national'}).intents.some(x=>x.id==='new-intent'),true);assert.throws(()=>c.shell.command('programme-plan','upsert',{args:[]}),e=>e.code==='CALL_NOT_ALLOWED')});
test('portal graph exposes explicit dependencies rather than shared object access',()=>{const c=core(),graph=c.portal.graph();const evidence=graph.find(x=>x.id==='evidence-retrieval'),method=graph.find(x=>x.id==='methodology'),plan=graph.find(x=>x.id==='programme-plan');assert(evidence.calls.query['entity-registry'].includes('sourceAthleteId'));assert(method.calls.query['entity-registry'].includes('dimensions'));assert(plan.calls.query['entity-registry'].includes('resolveSquad'))});
if(fails){console.error(`\n${fails} next-three portal regression(s) failed`);process.exit(1)}console.log('\nALL NEXT-THREE PORTAL REGRESSIONS PASS');
