'use strict';
const assert=require('assert');
const Core=require('../rebuild/portal-core.js');
const Attendance=require('../engines/attendance.js');
const Capture=require('../engines/capture-evidence.js');
let fails=0;
function test(name,fn){try{fn();console.log('PASS',name)}catch(e){fails++;console.error('FAIL',name,'\n ',e.stack||e.message)}}
let tick=0;const clock=()=>`2026-08-18T13:50:${String(tick++%60).padStart(2,'0')}+12:00`;
const identity={id:'portal-session',date:'2026-08-18',dayPart:'PM',course:'SCM',squads:['National','Development'],venue:'AquaGym'};
const source=`Warm up\n400 Choice\nMain set\n400 Pull\n6 x 100 Freestyle Development\n10s Rest\n4 x 25 Free @ 100 Pace\nWarm down\n200 Easy\nTOTAL: 1,700m`;
function core(){return Core.create({
 attendanceStorage:new Attendance.MemoryStorage(),captureStorage:new Capture.MemoryStorage(),clock,
 evidenceSources:[{id:'verified',priority:100,trust:'verified',data:{
  athletes:[{id:'mk',full_name:'McKenzie Drage',squad:'National',active:true,sex:'F'},{id:'molly',full_name:'Molly McKernan',squad:'Development',active:true,sex:'F'}],
  training_test_types:[{id:'tt',test_key:'t400_freestyle'}],
  training_test_results:[{id:'molly-t',athlete_id:'molly',test_type_id:'tt',result_seconds:324.6,result_date:'2026-08-12',pool_course:'SCM',valid_for_anchor:true},{id:'mk-t',athlete_id:'mk',test_type_id:'tt',result_seconds:450.1,result_date:'2026-06-01',pool_course:'SCM',valid_for_anchor:true}],
  coach_results:[{id:'molly100',athlete_id:'molly',distance:100,stroke:'Freestyle',pool_course:'SCM',result_seconds:60,result_date:'2026-07-01'}]
 }}]
})}
function findSet(session,pred){for(const b of session.blocks||[])for(const n of b.items||[]){if(n.kind==='set'&&pred(n))return n;if(n.kind==='group')for(const x of n.items||[])if(x.kind==='set'&&pred(x))return x}return null}

test('coach surface parses through Session Truth and Board receives the same canonical session',()=>{const c=core(),s=c.parse(source,identity),v=c.validate(s);assert.equal(v.ok,true);assert.equal(s.metadata.parsedTotal,1700);const b=c.board(s);assert.equal(b.sessionId,s.id);assert.equal(b.totalDistance,1700);assert.equal(b.attendance.here,0)});
test('Roll routes surface -> Attendance -> Entity Registry and Board reads the exact-session result',()=>{const c=core(),s=c.parse(source,identity);c.mark(s,'molly','present');const b=c.board(s);assert.equal(b.attendance.here,1);assert.equal(b.attendance.athletes[0].name,'Molly McKernan');const trail=c.portal.auditTrail();assert(trail.some(x=>x.kind==='command'&&x.target==='attendance'&&x.operation==='mark'));assert(trail.some(x=>x.caller==='attendance'&&x.target==='entity-registry'&&x.operation==='resolveAthlete'));assert(!trail.some(x=>x.caller==='attendance'&&x.target==='evidence-retrieval'))});
test('Board target request routes Board -> Targets -> Evidence and Evidence identity routes through Entity Registry',()=>{const c=core(),s=c.parse(source,identity);c.mark(s,'molly','present');const b=c.board(s),dev=b.blocks.find(x=>x.type==='main_set').items.find(x=>x.kind==='set'&&x.groupWork.zone==='Development');assert(dev.targets.some(x=>x.athleteId==='molly'&&x.status==='ok'));const trail=c.portal.auditTrail();assert(trail.some(x=>x.caller==='board-projection'&&x.target==='targets'&&x.operation==='forItem'));assert(trail.some(x=>x.caller==='targets'&&x.target==='evidence-retrieval'&&x.operation==='latestTrainingTestEvidence'));assert(trail.some(x=>x.caller==='evidence-retrieval'&&x.target==='entity-registry')) ;assert(!trail.some(x=>x.caller==='board-projection'&&x.target==='evidence-retrieval'))});
test('modified work routes Board -> Adaptation -> Entity Registry and remains separate from squad truth',()=>{const c=core(),s=c.parse(source,identity);c.mark(s,'mk','modified');const pull=findSet(s,x=>x.distance===400&&/Pull/i.test(x.raw)),before=JSON.stringify(pull),b=c.board(s),row=b.blocks.find(x=>x.type==='main_set').items.find(x=>x.id===pull.id),mod=row.modifications.find(x=>x.athleteId==='mk');assert(mod);assert.equal(mod.work.distance,300);assert.equal(JSON.stringify(pull),before);const trail=c.portal.auditTrail();assert(trail.some(x=>x.caller==='board-projection'&&x.target==='adaptation'&&x.operation==='forItem'));assert(trail.some(x=>x.caller==='adaptation'&&x.target==='entity-registry'&&x.operation==='resolveAthlete'))});
test('coach override command is owned by Adaptation and Board only reads the resulting prescription',()=>{const c=core(),s=c.parse(source,identity);c.mark(s,'mk','modified');const pull=findSet(s,x=>x.distance===400&&/Pull/i.test(x.raw));c.setAdaptation(s,pull,'mk',{distance:250},{reason:'deck test'});const row=c.board(s).blocks.find(x=>x.type==='main_set').items.find(x=>x.id===pull.id).modifications.find(x=>x.athleteId==='mk');assert.equal(row.work.distance,250);const trail=c.portal.auditTrail();assert(trail.some(x=>x.kind==='command'&&x.target==='adaptation'&&x.operation==='setOverride'));assert(!trail.some(x=>x.caller==='board-projection'&&x.kind==='command'))});
test('captured note routes to Capture Evidence and exact athlete identity is resolved by Entity Registry',()=>{const c=core(),s=c.parse(source,identity),dev=findSet(s,x=>x.zone==='Development'),main=s.blocks.find(x=>x.type==='main_set');c.capture(s,{type:'note',blockId:main.id,itemId:dev.id,athleteIds:['molly'],text:'Held shape'});const row=c.board(s).blocks.find(x=>x.type==='main_set').items.find(x=>x.id===dev.id);assert.equal(row.captures.count,1);assert.equal(row.captures.byType.note,1);const trail=c.portal.auditTrail();assert(trail.some(x=>x.kind==='command'&&x.target==='capture-evidence'&&x.operation==='create'));assert(trail.some(x=>x.caller==='capture-evidence'&&x.target==='entity-registry'&&x.operation==='resolveAthlete'))});
test('Pathway reads result evidence through its declared portal dependency',()=>{const c=core(),p=c.pathway('molly',{course:'SCM'});assert.equal(p.status,'ok');assert(p.pbs.some(x=>x.distance===100&&x.result_seconds===60));const trail=c.portal.auditTrail();assert(trail.some(x=>x.caller==='results-pathway'&&x.target==='evidence-retrieval'&&x.operation==='results'))});
test('app shell has no direct swimming or identity authority',()=>{const c=core();assert.throws(()=>c.shell.query('entity-registry','resolveAthlete',{args:['molly']}),e=>e.code==='CALL_NOT_ALLOWED');assert.throws(()=>c.shell.query('evidence-retrieval','results',{args:['molly',{}]}),e=>e.code==='CALL_NOT_ALLOWED');assert.throws(()=>c.shell.command('attendance','mark',{args:[]}),e=>e.code==='CALL_NOT_ALLOWED')});
test('portal is sealed so a late parser target or Board wrapper cannot attach after composition',()=>{const c=core();assert.equal(c.portal.snapshot().sealed,true);assert.throws(()=>c.portal.register({id:'late-board'}),e=>e.code==='PORTAL_SEALED')});
test('audit proves communication routes without storing performance payload values',()=>{const c=core();c.t400('molly',{course:'SCM'});const json=JSON.stringify(c.portal.auditTrail());assert(!/324\.6/.test(json));assert(/latestTrainingTestEvidence/.test(json))});
if(fails){console.error(`\n${fails} Portal Core integration regression(s) failed`);process.exit(1)}console.log('\nALL PORTAL CORE INTEGRATION REGRESSIONS PASS');
