'use strict';
const assert=require('assert');
const Core=require('../rebuild/portal-core.js');
const Attendance=require('../engines/attendance.js');
const Capture=require('../engines/capture-evidence.js');
let fails=0;function test(name,fn){try{fn();console.log('PASS',name)}catch(e){fails++;console.error('FAIL',name,'\n ',e.stack||e.message)}}
function core(){return Core.create({attendanceStorage:new Attendance.MemoryStorage(),captureStorage:new Capture.MemoryStorage(),clock:()=> '2026-08-18T16:55:00+12:00',evidenceSources:[{id:'verified',priority:100,trust:'verified',data:{athletes:[{id:'molly',full_name:'Molly McKernan',sex:'F',date_of_birth:'2011-05-01',active:true}],coach_results:[{id:'pb',athlete_id:'molly',distance:100,stroke:'Freestyle',pool_course:'SCM',result_seconds:63.8,result_date:'2026-08-01'}]}}],standards:[{id:'nzsc',programme:'NZSC National Qualifier',standard_kind:'qualifying',course:'SCM',distance:100,stroke:'Freestyle',sex:'F',age_min:15,age_max:15,qualifying_seconds:62,active:true}],baseTimes:[{course:'SCM',distance:100,stroke:'Freestyle',sex:'F',base_seconds:51.71,active:true}]})}

test('Portal Core exposes Pathway without giving it a sibling engine implementation',()=>{const c=core(),p=c.pathway('molly',{course:'SCM',asOfDate:'2026-08-18'});assert.equal(p.status,'ok');assert.equal(p.events[0].nextNational.row.id,'nzsc');assert.equal(p.events[0].points.source,'loaded WA base time')});
test('Pathway event normalization and standards meaning route through Standards Records',()=>{const c=core();c.pathway('molly',{course:'SCM',asOfDate:'2026-08-18'});const trail=c.portal.auditTrail();assert(trail.some(x=>x.caller==='results-pathway'&&x.target==='standards-records'&&x.operation==='normalizeCourse'));assert(trail.some(x=>x.caller==='results-pathway'&&x.target==='standards-records'&&x.operation==='normalizeEvent'));assert(trail.some(x=>x.caller==='results-pathway'&&x.target==='standards-records'&&x.operation==='statusForResult'));assert(trail.some(x=>x.caller==='results-pathway'&&x.target==='standards-records'&&x.operation==='milestones'))});
test('Pathway still gets PB/result facts only through Evidence Retrieval',()=>{const c=core();c.pathway('molly',{course:'SCM'});const trail=c.portal.auditTrail();assert(trail.some(x=>x.caller==='results-pathway'&&x.target==='evidence-retrieval'&&x.operation==='results'));assert(!trail.some(x=>x.caller==='standards-records'&&x.target==='evidence-retrieval'))});
test('app shell cannot call Standards Records directly',()=>{const c=core();assert.throws(()=>c.shell.query('standards-records','statusForResult',{args:[]}),e=>e.code==='CALL_NOT_ALLOWED')});
if(fails){console.error(`\n${fails} Portal Standards/Pathway integration regression(s) failed`);process.exit(1)}console.log('\nALL PORTAL STANDARDS / PATHWAY INTEGRATION REGRESSIONS PASS');
