'use strict';
const assert=require('assert');
const Roles=require('../engines/roles-permissions.js');
let fails=0;function test(name,fn){try{fn();console.log('PASS',name)}catch(e){fails++;console.error('FAIL',name,'\n ',e.stack||e.message)}}
const r=Roles.create({clock:()=> '2026-08-18T17:00:00+12:00',principals:[{id:'andy',role:'owner'},{id:'assistant',role:'assistant'},{id:'assistant2',role:'assistant'},{id:'molly-user',role:'swimmer',athlete_id:'molly'},{id:'tv',role:'display'}],assignments:[{id:'a1',principal_id:'assistant',role:'assistant',squad_ids:['National'],session_ids:['s1'],meet_ids:[],grants:[],denies:[]},{id:'a2',principal_id:'assistant2',role:'assistant',squad_ids:['Development'],grants:['finish_session','private_notes'],denies:['timing']},{id:'tv1',principal_id:'tv',role:'display',session_ids:['s1']}]});

test('owner retains all capabilities without assignment',()=>{assert.equal(r.can('andy','cloud_repair',{}),true);assert.equal(r.can('andy','finish_session',{}),true)});
test('assistant is deny-by-default without matching squad/session assignment',()=>{assert.equal(r.can('assistant','board',{squadId:'Development',sessionId:'s1'}),false);assert.equal(r.decision('assistant','board',{squadId:'Development',sessionId:'s1'}).reason,'no_matching_assignment')});
test('assistant default poolside capabilities work only inside assigned scope',()=>{const c={squadId:'National',sessionId:'s1'};for(const cap of ['board','roll','timing','capture','meet'])assert.equal(r.can('assistant',cap,c),true);assert.equal(r.can('assistant','board',{squadId:'National',sessionId:'s2'}),false)});
test('sensitive actions require an explicit grant for assistant',()=>{const c={squadId:'National',sessionId:'s1'};for(const cap of ['author_session','edit_session','finish_session','release_session','admin','cloud_repair','private_notes'])assert.equal(r.decision('assistant',cap,c).reason,'sensitive_requires_explicit_grant')});
test('explicit sensitive grants are narrow and do not grant adjacent owner actions',()=>{const c={squadId:'Development'};assert.equal(r.can('assistant2','finish_session',c),true);assert.equal(r.can('assistant2','private_notes',c),true);assert.equal(r.can('assistant2','release_session',c),false);assert.equal(r.can('assistant2','admin',c),false)});
test('explicit deny beats assistant role default',()=>{const d=r.decision('assistant2','timing',{squadId:'Development'});assert.equal(d.allowed,false);assert.equal(d.reason,'explicit_deny')});
test('swimmer device is self-only even when another athlete id is requested',()=>{assert.equal(r.can('molly-user','pathway_self',{athleteId:'molly'}),true);assert.equal(r.can('molly-user','pathway_self',{athleteId:'alex'}),false);assert.equal(r.can('molly-user','private_notes',{athleteId:'molly'}),false)});
test('filterAthletes never exposes another athlete to swimmer principal',()=>{const rows=r.filterAthletes('molly-user',[{id:'molly'},{id:'alex'},{id:'luke'}]);assert.deepEqual(rows,[{id:'molly'}])});
test('display role does not inherit assistant or owner actions',()=>{assert.equal(r.can('tv','board_display',{sessionId:'s1'}),true);assert.equal(r.can('tv','capture',{sessionId:'s1'}),false);assert.equal(r.can('tv','private_notes',{sessionId:'s1'}),false)});
test('surface answers are derived from capabilities rather than special bypasses',()=>{const x=r.surface('assistant','assistant_coach',{squadId:'National',sessionId:'s1'});assert.equal(x.allowed,true);assert(x.capabilities.some(c=>c.capability==='roll'&&c.allowed));const y=r.surface('assistant','coach_authoring',{squadId:'National',sessionId:'s1'});assert.equal(y.allowed,false)});
test('inactive principal fails closed',()=>{const x=Roles.create({principals:[{id:'x',role:'assistant',active:false}],assignments:[{principal_id:'x',role:'assistant',grants:['*']}]});assert.equal(x.can('x','board',{}),false)});
if(fails){console.error(`\n${fails} Roles and Permissions regression(s) failed`);process.exit(1)}console.log('\nALL ROLES / PERMISSIONS REGRESSIONS PASS');
