'use strict';
const assert=require('assert');
const Context=require('./context-core');
const Interaction=require('./interaction-core');
const Evidence=require('./evidence-core');
const Projection=require('./projection-core');
const Reporting=require('./report-core');
const Entitlements=require('./entitlement-core');
const Events=require('./event-core');
const Delivery=require('./delivery-core');
const Remote=require('./remote-core');
const AI=require('./ai-orchestrator-core');
const session={id:'sat',identity:{date:'2026-08-22',time:'05:30',course:'SCM'},blocks:[{id:'warm',title:'Warm Up',items:[{id:'w1',kind:'set',reps:4,distance:100,cycleSeconds:90,raw:'4 x 100 @ 1:30'}]},{id:'main',title:'Main Set',items:[{id:'m1',kind:'set',reps:4,distance:150,restSeconds:30,zone:'Overload',raw:'4 x 150 Overload to Threshold 30 sec Rest'}]}]};
const timeline=Context.plannedTimeline(session,{startAt:1000000});
assert.equal(timeline.rows.length,2);
const tracker=new Context.ContextTracker({session,timeline,now:()=>1300000});
tracker.anchor({at:1250000,source:'coach',itemId:'m1',rep:2});
const frame=tracker.frame(1300000);assert.equal(frame.itemId,'m1');assert.equal(frame.rep,2);assert(frame.confidence>.9);
const athletes=[{id:'henry',full_name:'Henry Crump'},{id:'seth',full_name:'Seth Doe'}];
let p=Interaction.parseDeterministic('Henry 100 fly PB',{athletes,context:frame});assert.equal(p.intent,'query_pb');assert.equal(p.destination,'private_earbud');assert.deepEqual(p.payload.event,{distance:100,stroke:'Butterfly'});
p=Interaction.parseDeterministic('TV Henry last freestyle video',{athletes,context:frame});assert.equal(p.intent,'query_media');assert.equal(p.destination,'tv');
p=Interaction.parseDeterministic('Henry fourth 50 34.2 stroke rate 56',{athletes,context:frame});assert.equal(p.intent,'capture_metric_note');assert.equal(p.payload.metrics.strokeRate,56);assert.equal(p.payload.metrics.timeSeconds,34.2);
const ledger=Evidence.createLedger(),raw=Evidence.appendRaw(ledger,{id:'e1',type:'voice',athleteIds:['henry'],context:{sessionId:'sat',itemId:'m1'},raw:{text:'better pressure'},metrics:{strokeRate:56}});assert(Object.isFrozen(raw));
Evidence.appendTranscript(ledger,{evidenceId:'e1',text:'Better pressure',engine:'device'});Evidence.appendInterpretation(ledger,{evidenceIds:['e1'],claims:[{kind:'technique',text:'Back-end pressure observed'}],carryForward:[{athleteId:'henry',text:'Recheck finish pressure'}]});assert.equal(ledger.raw[0].raw.text,'better pressure');
assert.equal(Projection.timingOwnership({zone:'Development',raw:'3 x 200 Development'}),'athlete');assert.equal(Projection.timingOwnership({raceIntent:{distance:200},raw:'3 x 50 200 Pace'}),'coach');
const groups=Projection.groupPrescriptions([{athlete:{id:'a'},item:{reps:6,distance:100,stroke:'Free'}},{athlete:{id:'b'},item:{reps:6,distance:100,stroke:'Free'}},{athlete:{id:'c'},item:{reps:4,distance:100,stroke:'Free'}}]);assert.equal(groups.length,2);assert.equal(groups[0].athletes.length,2);
const projected=Projection.projectAthleteSession(session,{id:'henry'},(_s,item)=>({item:{...item,reps:item.id==='m1'?3:item.reps}}));assert.equal(projected.canonicalSessionId,'sat');assert.equal(projected.blocks[1].items[0].canonicalItemId,'m1');
const report=Reporting.sessionReport({session,ledger,events:[{type:'context_anchor',sessionId:'sat'}]});assert.equal(report.evidenceCount,1);assert.equal(report.athletes.henry.evidence,1);assert.equal(report.carryForward.length,1);
const core=Entitlements.plan('core'),intel=Entitlements.plan('intelligence');assert(Entitlements.can(core,Entitlements.CAPABILITIES.TV_BOARD));assert(!Entitlements.can(core,Entitlements.CAPABILITIES.AI_INTERPRETATION));assert(Entitlements.can(intel,Entitlements.CAPABILITIES.AI_INTERPRETATION));
const evLedger=new Events.EventLedger();const ev=evLedger.append({type:'context_anchor',sessionId:'sat',itemId:'m1'});assert.equal(evLedger.forSession('sat').length,1);evLedger.correct(ev.id,{itemId:'w1'});assert.equal(evLedger.activeEvents('sat').length,1);
const privateRoute=Delivery.authorizeDestination({destination:'tv'},{explicitPublic:false,role:'coach'});assert.equal(privateRoute.ok,false);const publicRoute=Delivery.authorizeDestination({destination:'tv'},{explicitPublic:true,role:'coach'});assert.equal(publicRoute.ok,true);
const msg=Delivery.message({athleteIds:['ruby'],text:'Hold body line',audioEvidenceId:'e-audio'});const rubyProjection=Delivery.projectMessage(msg,{id:'ruby',delivery_preferences:{audio_first:true}});assert.equal(rubyProjection.primary,'audio');
const remoteProjection=Projection.projectAthleteSession(session,{id:'henry'},(_s,item)=>({item}));const run=Remote.createRun({session,athlete:{id:'henry'},projection:remoteProjection});assert.equal(run.canonicalSessionId,'sat');assert(run.sourceItemIds.includes('m1'));
const unknown=Interaction.parseDeterministic('make sense of what I am seeing',{athletes});assert.equal(AI.shouldEscalate(unknown),true);const aiJob=AI.job({input:{transcript:unknown.raw}});assert.equal(aiJob.status,'queued');
console.log('architecture-aw: context, voice, evidence, projection, reporting, events, delivery, remote and AI assertions passed');
