'use strict';
(function(g){const M=g.MSOS4,E=g.MSOSEngines;if(!M||!E?.Modification||!E?.Aerobic||!E?.RacePace||!E?.Coordinator||!M.boardEngine)return;const results=[],assert=(name,cond,detail='')=>results.push({name,ok:!!cond,detail:cond?'':detail});
  const cm={id:'cm',full_name:'Charlotte Murphy'},ap={id:'ap',full_name:'Amber Proudfoot'},cf={id:'cf',full_name:'Conor Fischer',primary_stroke:'Breaststroke'},md={id:'md',full_name:'Mackenzie Drage'},henry={id:'h',full_name:'Henry Test',primary_stroke:'Freestyle',sex:'M'};
  const state={athletes:[cm,ap,cf,md,henry],adaptationProfiles:[],adaptationOverrides:[],trainingTestTypes:[{id:'tf',test_key:'T400 Freestyle'},{id:'tb',test_key:'T400 Backstroke'},{id:'tbr',test_key:'T400 Breaststroke'}],trainingTestResults:[{athlete_id:'cm',test_type_id:'tf',result_seconds:360,valid_for_anchor:true},{athlete_id:'cm',test_type_id:'tb',result_seconds:562.8,valid_for_anchor:true},{athlete_id:'ap',test_type_id:'tf',result_seconds:300,valid_for_anchor:true},{athlete_id:'cf',test_type_id:'tbr',result_seconds:545.2,valid_for_anchor:true},{athlete_id:'h',test_type_id:'tf',result_seconds:300,valid_for_anchor:true}],resultsPbBoard:[{athlete_id:'cm',distance:100,stroke:'Backstroke',course:'SCM',result_seconds:70,wa_points:500},{athlete_id:'cf',distance:100,stroke:'Breaststroke',course:'SCM',result_seconds:80,wa_points:500},{athlete_id:'h',distance:100,stroke:'Freestyle',course:'SCM',result_seconds:60,wa_points:500}],resultsEventHistory:[],coachResults:[],courseConversions:[],worldAquaticsBaseTimes:[]};
  const session={id:'fixture',identity:{course:'SCM'}};
  const set=(id,reps,distance,extra={})=>({id,kind:'set',reps,distance,stroke:extra.stroke||'',raw:extra.raw||`${reps} x ${distance}`,text:extra.raw||`${reps} x ${distance}`,cues:extra.cues||[],pattern:extra.pattern||[],repPattern:extra.repPattern||[],repInstructions:extra.repInstructions||[],raceIntent:extra.raceIntent||null,zone:extra.zone||'',restSeconds:extra.restSeconds??10,cycleSeconds:extra.cycleSeconds||null,equipment:extra.equipment||[],composition:extra.composition||[]});
  const a400=set('a400',2,400,{stroke:'Freestyle',raw:'2 x 400 Freestyle',repPattern:[{rep:1,zone:'Regeneration'},{rep:2,zone:'Development'}]});
  const c400=E.Modification.adaptItem(a400,cm,state,session),a400ap=E.Modification.adaptItem(a400,ap,state,session);assert('Charlotte preserves both aerobic phases at half distance',c400.reps===2&&c400.distance===200,JSON.stringify(c400));assert('Amber preserves both aerobic phases near two-thirds distance',a400ap.reps===2&&a400ap.distance===250,JSON.stringify(a400ap));
  const a100=set('a100',8,100,{stroke:'Freestyle',raw:'8 x 100 Freestyle',repPattern:[1,2,3,4].map(rep=>({rep,zone:'Overload'})).concat([5,6,7,8].map(rep=>({rep,zone:'Threshold'})))});const c100=E.Modification.adaptItem(a100,cm,state,session),ap100=E.Modification.adaptItem(a100,ap,state,session);assert('Charlotte 8x100 becomes 4x100',c100.reps===4&&c100.repPattern.length===4,JSON.stringify(c100));assert('Charlotte phases remain 2 OL / 2 THR',c100.repPattern.filter(x=>x.zone==='Overload').length===2&&c100.repPattern.filter(x=>x.zone==='Threshold').length===2,JSON.stringify(c100.repPattern));assert('Amber 8x100 becomes 5x100',ap100.reps===5&&ap100.repPattern.length===5,JSON.stringify(ap100));
  state.adaptationOverrides=[{sessionId:'fixture',itemId:'a100',athleteId:'cm',active:true,patch:{stroke:'Backstroke'}}];const c100bk=E.Modification.adaptItem(a100,cm,state,session);assert('Stroke override never erases automatic modification shape',c100bk.reps===4&&c100bk.distance===100&&c100bk.stroke==='Backstroke',JSON.stringify(c100bk));state.adaptationOverrides=[];
  const im=set('im',5,100,{stroke:'IM',raw:'5 x 100 IM @ 1:45',cycleSeconds:105}),cim=E.Modification.adaptItem(im,cm,state,session);assert('IM stays complete 100m units',cim.distance===100&&cim.reps===3,JSON.stringify(cim));assert('Reduced IM keeps the same total team work window',cim.cycleSeconds===175,/^3\s*×\s*100/.test(cim.raw)?String(cim.cycleSeconds):JSON.stringify(cim));
  const quality=set('q',6,25,{raw:'6 x 25 #1 Stroke @ 1:00',cycleSeconds:60,repInstructions:[{rep:1,label:'Build',raceIntent:null},...Array.from({length:5},(_,i)=>({rep:i+2,label:'100m Race Pace',raceIntent:{distance:100}}))]}),cq=E.Modification.adaptItem(quality,cm,state,session);assert('Short race-quality work keeps team reps',cq.reps===6&&cq.distance===25,JSON.stringify(cq));
  const s75=set('s75',8,75,{raw:'8 x 75 with Fins 50 technique / 25 fast',equipment:['Fins']}),m75=E.Modification.adaptItem(s75,md,state,session),a75=E.Modification.adaptItem(s75,ap,state,session);assert('Mackenzie 75s return to starting end',m75.reps===6&&((m75.reps*m75.distance/25)%2===0),JSON.stringify(m75));assert('Amber upper-body 75s remain pool-end aligned',a75.reps===6&&/Upper-body/i.test(a75.raw),JSON.stringify(a75));
  const kick=set('kick',5,50,{raw:'5 x 50 Kick Build @ 1:00',cycleSeconds:60}),ck=E.Modification.adaptItem(kick,cm,state,session);assert('Charlotte 50 kick uses coach-confirmed 2:10–2:20 base',ck.reps===3&&ck.cycleSeconds===135&&ck.kickCycleRange?.min===130&&ck.kickCycleRange?.max===140,JSON.stringify(ck));
  const pattern=set('pattern',12,50,{raw:'12 x 50 #1 Stroke',pattern:[{count:1,text:'Scull'},{count:1,text:'Drill'},{count:1,text:'Swim — Perfect Technique'}]}),patternCue=M.boardEngine.cueText(pattern);assert('12x50 pattern stays grouped under the parent set',/1 Scull/.test(patternCue)&&/1 Drill/.test(patternCue)&&/1 Swim/.test(patternCue),patternCue);
  if(M.parser?.parse&&M.session?.total){const parsed=M.parser.parse('WARM-UP\n12 x 50 #1 Stroke\n1 Scull\n1 Drill\n1 Swim — Perfect Technique',{id:'pattern-parse',date:'2026-08-15'}),item=parsed.blocks?.[0]?.items?.[0];assert('Pattern cues do not add phantom 50s',M.session.total(parsed)===600&&item?.reps===12&&item?.pattern?.length===3,`${M.session.total(parsed)} · ${JSON.stringify(item)}`);}
  if(M.waPointsEngine?.pointsFor){const coral={id:'coral',full_name:'Coral Sturla'},row={athlete_id:'coral',sex:'F',course:'SCM',distance:50,stroke:'Butterfly',result_seconds:34.56},info=M.waPointsEngine.pointsFor(coral,row,state);assert('WA ranking can use result sex when roster sex is blank',Number.isFinite(info?.points)&&info.points>0,JSON.stringify(info));}
  const cmA=E.Aerobic.forItem(session,c400,cm,state),sumA=M.boardEngine.targetSummary(cmA);assert('Aerobic target is one compact phase summary',/REG/.test(sumA)&&/DEV/.test(sumA)&&!/(REG.*REG|DEV.*DEV)/.test(sumA),sumA);
  const rp=E.RacePace.forItem(session,quality,cm,state,''),sumR=M.boardEngine.targetSummary(rp);assert('#1 resolves from PB evidence',rp.stroke==='Backstroke'||(rp.rows||[]).some(x=>x.stroke==='Backstroke'),JSON.stringify(rp));assert('Race targets collapse repeated reps',!/#2.*#3.*#4.*#5.*#6/.test(sumR),sumR);
  const hr=E.Aerobic.forItem(session,a100,cf,state),sumH=M.boardEngine.targetSummary(hr);assert('No matching Free T400 falls back to HR/SR',/HR/.test(sumH),sumH);
  M.engineAcceptance={build:'20260820v',ok:results.every(x=>x.ok),results,ranAt:new Date().toISOString()};if(!M.engineAcceptance.ok)console.error('[MSOS acceptance FAIL]',results.filter(x=>!x.ok));else console.info('[MSOS acceptance PASS]',results.length,'checks');
})(globalThis);