'use strict';
(function(g){
  const M=g.MSOS4,E=g.MSOSEngines;if(!M?.ui||!E?.Coordinator||!E?.Modification||!E?.Evidence)return;
  const S=M.boardStateEngine={build:'v4-board-state-20260820u'},U=M.util;
  const saveUi=()=>{try{M.storageEngine?.saveUi?.(M.state)}catch{}};
  const saveData=()=>{try{M.store?.save?.(M.state)}catch{}};
  const esc=v=>U?.escape?U.escape(String(v??'')):String(v??''),short=v=>String(v??'').replace('Freestyle','Fr').replace('Backstroke','Bk').replace('Breaststroke','Br').replace('Butterfly','Fly');
  function findItem(session,id){let hit=null;const walk=items=>{for(const n of items||[]){if(n?.id===id){hit=n;return;}if(n?.kind==='group')walk(n.items);if(hit)return;}};for(const b of session?.blocks||[]){walk(b.items);if(hit)break;}return hit;}
  function present(){return M.ui.presentAthletes?.()||[];}
  function mods(){const p=present(),ids=new Set(p.map(a=>a.id)),m=M.ui.modifiedAthletes?.();if(Array.isArray(m)&&m.length)return m.filter(a=>ids.has(a.id));return p.filter(a=>Number(E.Modification.profile(a,M.state).ratio)<.98||String(a.modifications||'').trim());}
  function groupAthletes(){const m=new Set(mods().map(a=>a.id));return present().filter(a=>!m.has(a.id));}
  function targetCard(session,item,a){const B=M.boardEngine,r=E.Coordinator.targetForItem(session,item,a,M.state),stroke=B?.displayStroke?.(session,item,a)||E.Evidence.stroke(item?.stroke||'')||'Auto',label=stroke==='Auto'?'Auto':short(stroke),name=B?.name?.(a,present())||String(a.full_name||'').split(' ')[0]||'?';return `<div class="msos-target-card"><div><button class="msos-name" data-msos-ath="${esc(a.id)}">${esc(name)}</button><button class="msos-stroke-pill" data-msos-fast-stroke="${esc(item.id)}:${esc(a.id)}">${esc(label)}</button></div><span>${esc(B?.targetSummary?.(r)||'—')}</span></div>`;}
  function panelShell(item){return `<div class="msos-target-panel" data-msos-panel="${esc(item.id)}"><section><label>TIMES</label><div class="msos-target-matrix" data-msos-target-matrix><span class="msos-none">Loading targets…</span></div></section></div>`;}
  function fillPanel(panel,session,item,group=groupAthletes()){const box=panel?.querySelector?.('[data-msos-target-matrix]');if(!box)return;if(!group.length){box.innerHTML='<span class="msos-none">Modified swimmers are shown beside their own work.</span>';return;}box.innerHTML='';let i=0;const step=()=>{if(!panel.isConnected)return;const frag=[];const end=Math.min(group.length,i+4);for(;i<end;i++)frag.push(targetCard(session,item,group[i]));box.insertAdjacentHTML('beforeend',frag.join(''));if(i<group.length)requestAnimationFrame(step);};requestAnimationFrame(step);}
  function panelHtml(session,item){return panelShell(item);}
  function setButtons(openId=''){document.querySelectorAll('#boardView [data-msos-times],#tvView [data-msos-times]').forEach(b=>b.textContent=b.dataset.msosTimes===openId?'Close':'Times');}
  function closePanels(){document.querySelectorAll('#boardView .msos-target-panel,#tvView .msos-target-panel').forEach(x=>x.remove());}
  function openPanel(btn){const session=M.currentSession?.(),item=findItem(session,btn.dataset.msosTimes),row=btn.closest('.msos-work-row');if(!session||!item||!row)return;const wasOpen=M.state.settings.boardExpandedTargetId===item.id;closePanels();M.state.settings.boardExpandedTargetId=wasOpen?'':item.id;saveUi();setButtons(M.state.settings.boardExpandedTargetId);if(wasOpen)return;row.insertAdjacentHTML('beforeend',panelShell(item));const panel=row.querySelector(`[data-msos-panel="${g.CSS?.escape?g.CSS.escape(item.id):item.id}"]`)||row.querySelector('.msos-target-panel');fillPanel(panel,session,item);}
  function refreshPanel(session,item){const safe=g.CSS?.escape?g.CSS.escape(item.id):String(item.id).replace(/["\\]/g,'\\$&'),row=document.querySelector(`#boardView [data-item="${safe}"],#tvView [data-item="${safe}"]`);if(!row)return;const old=row.querySelector('.msos-target-panel');if(!old)return;old.remove();row.insertAdjacentHTML('beforeend',panelShell(item));fillPanel(row.querySelector('.msos-target-panel'),session,item);}
  function setStroke(session,item,ath,value){const rows=M.state.adaptationOverrides=M.state.adaptationOverrides||[],x=rows.find(r=>r.sessionId===session.id&&r.itemId===item.id&&r.athleteId===ath.id&&r.active!==false),stroke=value==='AUTO'?'':E.Evidence.stroke(value);if(stroke){if(x){x.patch=x.patch||{};x.patch.stroke=stroke;x.active=true;x.updatedAt=new Date().toISOString();}else rows.push({id:U.uid?.('mod')||`mod-${Date.now()}`,sessionId:session.id,itemId:item.id,athleteId:ath.id,patch:{stroke},active:true,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});}else if(x){x.patch=x.patch||{};delete x.patch.stroke;if(!Object.keys(x.patch).length)x.active=false;x.updatedAt=new Date().toISOString();}E.Coordinator.clearCache?.();saveData();refreshPanel(session,item);}
  function strokeMenu(btn){const [itemId,athId]=btn.dataset.msosFastStroke.split(':'),session=M.currentSession?.(),item=findItem(session,itemId),ath=present().find(a=>a.id===athId);if(!session||!item||!ath)return;document.querySelectorAll('.msos-stroke-menu').forEach(x=>x.remove());const menu=document.createElement('div');menu.className='msos-stroke-menu';for(const [v,l] of [['AUTO','Auto'],['Freestyle','Fr'],['Backstroke','Bk'],['Breaststroke','Br'],['Butterfly','Fly'],['IM','IM']]){const b=document.createElement('button');b.textContent=l;b.onclick=e=>{e.stopPropagation();setStroke(session,item,ath,v);menu.remove();};menu.appendChild(b);}btn.parentElement.appendChild(menu);setTimeout(()=>document.addEventListener('click',()=>menu.remove(),{once:true}),0);}
  function targetItems(session){const out=[],walk=items=>{for(const x of items||[]){if(x?.kind==='set'&&(x?.targetSeconds||x?.zone||(x?.repPattern||[]).length||x?.raceIntent||(x?.repInstructions||[]).some(r=>r.raceIntent)))out.push(x);if(x?.kind==='group')walk(x.items);}};for(const b of session?.blocks||[])walk(b.items);return out;}
  let prewarmToken=0;function prewarm(){const session=M.currentSession?.(),group=groupAthletes();if(!session||!group.length)return;const jobs=[];for(const item of targetItems(session))for(const a of group)jobs.push([item,a]);const token=++prewarmToken;let i=0;const run=deadline=>{if(token!==prewarmToken)return;let n=0;while(i<jobs.length&&n<8&&(!deadline||deadline.timeRemaining?.()>2)){const [item,a]=jobs[i++];try{E.Coordinator.targetForItem(session,item,a,M.state);}catch{}n++;}if(i<jobs.length){if(g.requestIdleCallback)g.requestIdleCallback(run,{timeout:800});else setTimeout(()=>run(null),16);}};if(g.requestIdleCallback)g.requestIdleCallback(run,{timeout:1000});else setTimeout(()=>run(null),30);}
  function render(){M.ui?.renderBoard?.();prewarm();}
  document.addEventListener('click',e=>{
    const times=e.target.closest?.('#boardView [data-msos-times],#tvView [data-msos-times]');if(times){e.preventDefault();e.stopImmediatePropagation();M.state.settings=M.state.settings||{};openPanel(times);return;}
    const fastStroke=e.target.closest?.('[data-msos-fast-stroke]');if(fastStroke){e.preventDefault();e.stopImmediatePropagation();strokeMenu(fastStroke);return;}
    const mode=e.target.closest?.('#boardView [data-msos-mode]');if(mode){e.preventDefault();e.stopImmediatePropagation();M.state.settings=M.state.settings||{};M.state.settings.boardFocusMode=M.state.settings.boardFocusMode===false;M.state.settings.boardExpandedTargetId='';saveUi();render();return;}
    const block=e.target.closest?.('#boardView [data-msos-block]');if(block){e.preventDefault();e.stopImmediatePropagation();const session=M.currentSession?.();if(!session)return;M.state.settings=M.state.settings||{};M.state.settings.boardFocusMode=true;M.state.settings.boardExpandedTargetId='';M.state.settings.boardBlockBySession=M.state.settings.boardBlockBySession||{};M.state.settings.boardBlockBySession[session.id]=block.dataset.msosBlock;saveUi();render();}
  },true);
  addEventListener('msos:data-updated',()=>{prewarmToken++;if((M.state?.settings?.view||'')==='board')prewarm();});
  const boot=()=>{if((M.state?.settings?.view||'')==='board')prewarm();};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,120),{once:true});else setTimeout(boot,120);
  S.saveUi=saveUi;S.openPanel=openPanel;S.panelHtml=panelHtml;S.fillPanel=fillPanel;S.prewarm=prewarm;
})(globalThis);
