'use strict';
(function(g){
  const M=g.MSOS4,E=g.MSOSEngines;if(!M?.ui||!E?.Coordinator||!E?.Modification||!E?.Evidence)return;
  const S=M.boardStateEngine={build:'v4-board-state-20260820x'},U=M.util;
  const saveUi=()=>{try{M.storageEngine?.saveUi?.(M.state)}catch{}};
  const saveData=()=>{try{M.store?.save?.(M.state)}catch{}};
  const esc=v=>U?.escape?U.escape(String(v??'')):String(v??''),short=v=>String(v??'').replace('Freestyle','Fr').replace('Backstroke','Bk').replace('Breaststroke','Br').replace('Butterfly','Fly');
  function findItem(session,id){let hit=null;const walk=items=>{for(const n of items||[]){if(n?.id===id){hit=n;return;}if(n?.kind==='group')walk(n.items);if(hit)return;}};for(const b of session?.blocks||[]){walk(b.items);if(hit)break;}return hit;}
  function present(){return M.ui.presentAthletes?.()||[];}
  function mods(){const p=present(),ids=new Set(p.map(a=>a.id)),m=M.ui.modifiedAthletes?.();if(Array.isArray(m)&&m.length)return m.filter(a=>ids.has(a.id));return p.filter(a=>Number(E.Modification.profile(a,M.state).ratio)<.98||String(a.modifications||'').trim());}
  function groupAthletes(){const m=new Set(mods().map(a=>a.id));return present().filter(a=>!m.has(a.id));}
  function targetCard(session,item,a){const B=M.boardEngine,r=E.Coordinator.targetForItem(session,item,a,M.state),resolved=r?.stroke||'',stroke=resolved||B?.displayStroke?.(session,item,a)||E.Evidence.stroke(item?.stroke||'')||'Auto',label=stroke==='Auto'?'Auto':short(stroke),name=B?.name?.(a,present())||String(a.full_name||'').split(' ')[0]||'?';return `<div class="msos-target-card"><div><button class="msos-name" data-msos-ath="${esc(a.id)}">${esc(name)}</button><button class="msos-stroke-pill" data-msos-fast-stroke="${esc(item.id)}:${esc(a.id)}">${esc(label)}</button></div><span>${esc(B?.targetSummary?.(r)||'—')}</span></div>`;}
  function panelShell(item,message='Loading targets…'){return `<div class="msos-target-panel" data-msos-panel="${esc(item.id)}"><section><label>TIMES</label><div class="msos-target-matrix" data-msos-target-matrix><span class="msos-none">${esc(message)}</span></div></section></div>`;}
  let panelToken=0,modToken=0;
  function activeDeckView(){const v=M.state?.settings?.view||'';return v==='board'||v==='tv';}
  function cancelWork(){panelToken++;modToken++;}
  function needsPerformanceEvidence(item){return !!(item?.raceIntent||(item?.repInstructions||[]).some(x=>x?.raceIntent));}
  function fillPanel(panel,session,item,group=groupAthletes()){const box=panel?.querySelector?.('[data-msos-target-matrix]');if(!box)return;if(needsPerformanceEvidence(item)&&M.engineBridge&&!M.engineBridge.hydrated){box.innerHTML='<span class="msos-none">Loading PB / WA evidence…</span>';return;}if(!group.length){box.innerHTML='<span class="msos-none">Modified swimmers are shown beside their own work.</span>';return;}box.innerHTML='';let i=0;const token=++panelToken;const step=()=>{if(token!==panelToken||!panel.isConnected||!activeDeckView())return;const frag=[];const end=Math.min(group.length,i+3);for(;i<end;i++){try{frag.push(targetCard(session,item,group[i]));}catch{frag.push(`<div class="msos-target-card"><span>Target unavailable</span></div>`);}}box.insertAdjacentHTML('beforeend',frag.join(''));if(i<group.length)requestAnimationFrame(step);};requestAnimationFrame(step);}
  function panelHtml(_session,item){return panelShell(item);}
  function setButtons(openId=''){document.querySelectorAll('#boardView [data-msos-times],#tvView [data-msos-times]').forEach(b=>b.textContent=b.dataset.msosTimes===openId?'Close':'Times');}
  function closePanels(){document.querySelectorAll('#boardView .msos-target-panel,#tvView .msos-target-panel').forEach(x=>x.remove());panelToken++;}
  function openPanel(btn){const session=M.currentSession?.(),item=findItem(session,btn.dataset.msosTimes),row=btn.closest('.msos-work-row');if(!session||!item||!row)return;const wasOpen=M.state.settings.boardExpandedTargetId===item.id;closePanels();M.state.settings.boardExpandedTargetId=wasOpen?'':item.id;saveUi();setButtons(M.state.settings.boardExpandedTargetId);if(wasOpen)return;const waiting=needsPerformanceEvidence(item)&&M.engineBridge&&!M.engineBridge.hydrated;row.insertAdjacentHTML('beforeend',panelShell(item,waiting?'Loading PB / WA evidence…':'Loading targets…'));const panel=row.querySelector(`[data-msos-panel="${g.CSS?.escape?g.CSS.escape(item.id):item.id}"]`)||row.querySelector('.msos-target-panel');if(waiting){const wanted=item.id;Promise.resolve(M.engineBridge.hydrate()).finally(()=>{if(M.state?.settings?.boardExpandedTargetId!==wanted||!panel.isConnected||!activeDeckView())return;fillPanel(panel,session,item);});}else fillPanel(panel,session,item);}
  function refreshPanel(session,item){const safe=g.CSS?.escape?g.CSS.escape(item.id):String(item.id).replace(/["\\]/g,'\\$&'),row=document.querySelector(`#boardView [data-item="${safe}"],#tvView [data-item="${safe}"]`);if(!row)return;const old=row.querySelector('.msos-target-panel');if(!old)return;old.remove();row.insertAdjacentHTML('beforeend',panelShell(item));fillPanel(row.querySelector('.msos-target-panel'),session,item);}
  function setStroke(session,item,ath,value){const rows=M.state.adaptationOverrides=M.state.adaptationOverrides||[],x=rows.find(r=>r.sessionId===session.id&&r.itemId===item.id&&r.athleteId===ath.id&&r.active!==false),stroke=value==='AUTO'?'':E.Evidence.stroke(value);if(stroke){if(x){x.patch=x.patch||{};x.patch.stroke=stroke;x.active=true;x.updatedAt=new Date().toISOString();}else rows.push({id:U.uid?.('mod')||`mod-${Date.now()}`,sessionId:session.id,itemId:item.id,athleteId:ath.id,patch:{stroke},active:true,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});}else if(x){x.patch=x.patch||{};delete x.patch.stroke;if(!Object.keys(x.patch).length)x.active=false;x.updatedAt=new Date().toISOString();}E.Coordinator.clearCache?.();E.RacePace?.invalidate?.(M.state);M.performanceEngine?.invalidate?.(M.state);saveData();refreshPanel(session,item);hydrateVisibleModTargets();}
  function strokeMenu(btn){const [itemId,athId]=btn.dataset.msosFastStroke.split(':'),session=M.currentSession?.(),item=findItem(session,itemId),ath=present().find(a=>a.id===athId);if(!session||!item||!ath)return;document.querySelectorAll('.msos-stroke-menu').forEach(x=>x.remove());const menu=document.createElement('div');menu.className='msos-stroke-menu';for(const [v,l] of [['AUTO','Auto'],['Freestyle','Fr'],['Backstroke','Bk'],['Breaststroke','Br'],['Butterfly','Fly'],['IM','IM']]){const b=document.createElement('button');b.textContent=l;b.onclick=e=>{e.stopPropagation();setStroke(session,item,ath,v);menu.remove();};menu.appendChild(b);}btn.parentElement.appendChild(menu);setTimeout(()=>document.addEventListener('click',()=>menu.remove(),{once:true}),0);}
  function hydrateVisibleModTargets(){const session=M.currentSession?.();if(!session||!activeDeckView())return;const host=document.querySelector((M.state.settings.view==='tv'?'#tvView':'#boardView')),nodes=[...(host?.querySelectorAll?.('[data-msos-mod-item][data-msos-mod-ath]')||[])];if(!nodes.length)return;let i=0;const token=++modToken,athletes=present();const step=()=>{if(token!==modToken||!activeDeckView())return;let n=0;while(i<nodes.length&&n<2){const el=nodes[i++];if(!el.isConnected){n++;continue;}const item=findItem(session,el.dataset.msosModItem),ath=athletes.find(a=>a.id===el.dataset.msosModAth);if(item&&ath){if(needsPerformanceEvidence(item)&&M.engineBridge&&!M.engineBridge.hydrated){el.textContent='Loading PB / WA evidence…';}else try{const actual=E.Modification.adaptItem(item,ath,M.state,session),r=E.Coordinator.targetForItem(session,actual,ath,M.state);el.textContent=M.boardEngine?.targetSummary?.(r)||'—';}catch{el.textContent='Target unavailable';}}n++;}if(i<nodes.length)requestAnimationFrame(step);};requestAnimationFrame(step);}
  function render(){cancelWork();M.ui?.renderBoard?.();requestAnimationFrame(hydrateVisibleModTargets);}
  document.addEventListener('click',e=>{
    const times=e.target.closest?.('#boardView [data-msos-times],#tvView [data-msos-times]');if(times){e.preventDefault();e.stopImmediatePropagation();M.state.settings=M.state.settings||{};openPanel(times);return;}
    const fastStroke=e.target.closest?.('[data-msos-fast-stroke]');if(fastStroke){e.preventDefault();e.stopImmediatePropagation();strokeMenu(fastStroke);return;}
    const mode=e.target.closest?.('#boardView [data-msos-mode]');if(mode){e.preventDefault();e.stopImmediatePropagation();M.state.settings=M.state.settings||{};M.state.settings.boardFocusMode=M.state.settings.boardFocusMode===false;M.state.settings.boardExpandedTargetId='';saveUi();render();return;}
    const block=e.target.closest?.('#boardView [data-msos-block]');if(block){e.preventDefault();e.stopImmediatePropagation();const session=M.currentSession?.();if(!session)return;M.state.settings=M.state.settings||{};M.state.settings.boardFocusMode=true;M.state.settings.boardExpandedTargetId='';M.state.settings.boardBlockBySession=M.state.settings.boardBlockBySession||{};M.state.settings.boardBlockBySession[session.id]=block.dataset.msosBlock;saveUi();render();return;}
  },true);
  addEventListener('msos:data-updated',()=>{if(activeDeckView())requestAnimationFrame(hydrateVisibleModTargets);});
  addEventListener('msos:evidence-ready',()=>{if(!activeDeckView())return;requestAnimationFrame(hydrateVisibleModTargets);if(M.state?.settings?.boardExpandedTargetId){const s=M.currentSession?.(),item=findItem(s,M.state.settings.boardExpandedTargetId);if(s&&item)refreshPanel(s,item);}});
  const boot=()=>{if(activeDeckView())requestAnimationFrame(hydrateVisibleModTargets);};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,80),{once:true});else setTimeout(boot,80);
  S.saveUi=saveUi;S.openPanel=openPanel;S.panelHtml=panelHtml;S.fillPanel=fillPanel;S.hydrateVisibleModTargets=hydrateVisibleModTargets;S.cancelWork=cancelWork;S.prewarm=()=>{};
})(globalThis);
