'use strict';
(function(g){
  const M=g.MSOS4,E=g.MSOSEngines;if(!M?.ui||!E?.Coordinator||!E?.Modification||!E?.Evidence||!E?.RacePace)return;
  const UI=M.ui,U=M.util,B=M.boardEngine={build:'v4-board-whiteboard-20260820ab'};
  const text=v=>String(v??'').replace(/\s+/g,' ').trim(),esc=v=>U?.escape?U.escape(v):text(v),clock=s=>U?.clock?U.clock(Number(s)):text(s);
  const short=v=>text(v).replace(/\bFreestyle\b/gi,'Fr').replace(/\bBackstroke\b/gi,'Bk').replace(/\bBreaststroke\b/gi,'Br').replace(/\bButterfly\b/gi,'Fly').replace(/\bRegeneration\b/gi,'REG').replace(/\bDevelopment\b/gi,'DEV').replace(/\bOverload\b/gi,'OL').replace(/\bThreshold\b/gi,'THR').replace(/\bClearance\b/gi,'CL').replace(/\bRace Pace\b/gi,'RP').replace(/\bDescend\b/gi,'Desc').replace(/\bStroke Count\b/gi,'SC');
  const preferred=a=>text(a?.board_name||a?.boardName||a?.nickname||a?.preferred_name||a?.preferredName);
  const firstDisplay=first=>/^Matthew$/i.test(first)?'Matt':first;
  const nameParts=a=>text(a?.full_name).split(/\s+/).filter(Boolean);
  const suffixSource=a=>{const p=nameParts(a),surname=p.length>1?p.at(-1):'',fallback=text(a?.squad)||String(a?.id||'').replace(/[^a-z0-9]/gi,'');return surname||fallback||'?';};
  function uniqueSuffix(a,group){const src=suffixSource(a),others=group.filter(x=>x?.id!==a.id).map(suffixSource);for(let n=1;n<=src.length;n++){const p=src.slice(0,n).toUpperCase();if(others.every(s=>s.slice(0,n).toUpperCase()!==p))return p;}return src.toUpperCase();}
  function name(a,pool=[]){if(!a)return'?';const nick=preferred(a);if(nick)return nick;const parts=nameParts(a),first=parts[0]||'?',same=pool.filter(x=>x?.id!==a.id&&!preferred(x)&&nameParts(x)[0]?.toLowerCase()===first.toLowerCase());if(!same.length)return firstDisplay(first);const group=[a,...same];return`${firstDisplay(first)} ${uniqueSuffix(a,group)}`;}
  B.name=name;
  const zoneShort=z=>({Regeneration:'REG',Development:'DEV',Overload:'OL',Threshold:'THR',Clearance:'CL'})[z]||short(z);
  function itemDistance(n){if(!n)return 0;if(n.kind==='set')return Math.max(1,Number(n.reps)||1)*(Number(n.distance)||0);if(n.kind==='group')return Math.max(1,Number(n.rounds)||1)*(n.items||[]).reduce((s,x)=>s+itemDistance(x),0);return 0;}
  const blockDistance=b=>(b?.items||[]).reduce((s,x)=>s+itemDistance(x),0),sessionDistance=s=>(s?.blocks||[]).reduce((n,b)=>n+blockDistance(b),0);
  function compactPattern(item){const p=item?.repPattern||[];if(!p.length)return'';const groups=[];for(const x of p){const z=zoneShort(x.zone),last=groups.at(-1);if(last&&last.z===z)last.n++;else groups.push({z,n:1});}return groups.map(x=>`${x.n>1?x.n+' ':''}${x.z}`).join(' / ');}
  function compactSequence(item){const p=item?.pattern||[];if(!p.length)return'';return p.map(x=>`${Math.max(1,Number(x.count)||1)} ${short(x.text||'')}`.trim()).join(' / ');}
  function compactRace(item){const rows=item?.repInstructions||[];if(!rows.some(x=>x.raceIntent))return'';const non=rows.filter(x=>!x.raceIntent),race=rows.filter(x=>x.raceIntent),bits=[];if(non.length)bits.push(non.length===1?`#${non[0].rep} ${short(non[0].label||'Build')}`:`#${non[0].rep}-${non.at(-1).rep} ${short(non[0].label||'Build')}`);if(race.length){const d=race[0].raceIntent?.distance||item?.raceIntent?.distance||'';bits.push(`#${race[0].rep}${race.length>1?`-${race.at(-1).rep}`:''} RP${d}`);}return bits.join(' · ');}
  function composition(item){const c=item?.composition||[];return c.length?c.map(x=>`${x.distance} ${short(x.text)}`).join(' / '):'';}
  function tidyCues(cues=[]){let s=cues.map(short).filter(Boolean).join(' · ');s=s.replace(/Build through each \d+/ig,'Build').replace(/Strong final 25 Fr/ig,'Last 25 strong').replace(/Attack last turn and underwater/ig,'Attack last turn').replace(/Hold the line and finish strong/ig,'Finish strong');return s;}
  function cueText(item){const pat=compactPattern(item),race=compactRace(item),seq=compactSequence(item),comp=composition(item),repeat=short(item?.repeatBreakdownCue||''),cues=tidyCues((item?.cues||[]).filter(c=>text(c)!==text(item?.repeatBreakdownCue)));if(pat)return pat;if(race)return race;const bits=[];if(comp)bits.push(comp);if(repeat)bits.push(repeat);else if(seq)bits.push(seq);if(cues)bits.push(cues);if(bits.length)return bits.join(' · ');return short(item?.raw||item?.text).replace(/^\d+\s*[x×]\s*\d+(?:\.5)?\s*/i,'').replace(/^\d+(?:\.5)?\s*/,'').replace(/^(Fr|Bk|Br|Fly|IM|Choice)\b\s*/,'').replace(/^(Pull|Upper-body)\b\s*/i,'').replace(/^·\s*/, '');}
  function workLabel(item){const reps=Math.max(1,Number(item?.reps)||1),d=Number(item?.distance)||0,raw=short(item?.raw||item?.text),st=short(E.Evidence.stroke(item?.stroke||'')),eq=(item?.equipment||[]).map(short).join('+');if(/Upper-body equivalent/i.test(raw))return`${reps}×${d} Upper-body${item?.cycleSeconds?` @ ${clock(item.cycleSeconds)}`:''}`;let label=`${reps>1?reps+'×':''}${d}`;if(st&&st!=='Choice')label+=` ${st}`;else if(/#\s*1F\b/i.test(raw))label+=' #1F';else if(/#\s*1\s*Stroke\b/i.test(raw))label+=' #1 Stroke';if(eq&&!new RegExp(`\\b${eq}\\b`,'i').test(label))label+=` ${eq}`;if(/\bPull\b/i.test(raw)&&!/Pull/i.test(label))label+=' Pull';if(/\bMAX\b/i.test(raw)&&!/MAX/i.test(label))label+=' MAX';if(item?.cycleSeconds)label+=` @ ${clock(item.cycleSeconds)}`;else if(Number.isFinite(Number(item?.restSeconds))&&Number(item.restSeconds)>0)label+=` · ${Number(item.restSeconds)}sr`;return label;}
  function targetIntent(item){return !!(item?.targetSeconds||item?.zone||(item?.repPattern||[]).length||item?.raceIntent||(item?.repInstructions||[]).some(x=>x.raceIntent));}
  function targetAtom(seconds,sendOff){const a=clock(seconds);return sendOff?`${a}/${clock(sendOff)}`:a;}
  function targetSummary(r){if(!r||r.status==='none')return'';if(r.status==='ok')return targetAtom(r.seconds,r.sendOff);if(r.status==='fallback')return[`HR ${r.hr||''}`,r.sr?`SR ${r.sr}`:''].filter(Boolean).join(' · ');if(r.status==='missing')return short(r.message||'Target needed');if(r.status==='pattern'){const seen=new Map();for(const x of r.rows||[]){const k=zoneShort(x.zone),v=targetAtom(x.seconds,x.sendOff);if(!seen.has(k))seen.set(k,v);}return[...seen].map(([k,v])=>`${k} ${v}`).join(' · ');}if(r.status==='pattern_fallback'){const seen=new Map();for(const x of r.rows||[]){const k=zoneShort(x.zone),v=[x.hr?`HR ${x.hr}`:'',x.sr?`SR ${x.sr}`:''].filter(Boolean).join(' ');if(!seen.has(k))seen.set(k,v);}return[...seen].map(([k,v])=>`${k} ${v}`).join(' · ');}if(r.status==='rep_race'){const rows=r.rows||[],bits=[],non=rows.filter(x=>x.status==='none'),ok=rows.filter(x=>x.status==='ok'),missing=rows.filter(x=>x.status==='missing');if(non.length)bits.push(non.length===1?`#${non[0].rep} ${short(non[0].label||'Build')}`:`#${non[0].rep}-${non.at(-1).rep} Build`);if(ok.length){const groups=[];for(const x of ok){const v=targetAtom(x.seconds,x.sendOff),last=groups.at(-1);if(last&&last.v===v)last.end=x.rep;else groups.push({start:x.rep,end:x.rep,v});}for(const x of groups)bits.push(`#${x.start}${x.end>x.start?'-'+x.end:''} ${x.v}`);}if(missing.length)bits.push([...new Set(missing.map(x=>short(x.message||'PB needed')))].join(' / '));return bits.join(' · ');}return'';}
  function present(){return UI.presentAthletes?.()||[];}
  function modified(){const p=present(),ids=new Set(p.map(a=>a.id)),m=UI.modifiedAthletes?.();if(Array.isArray(m)&&m.length)return m.filter(a=>ids.has(a.id));return p.filter(a=>Number(E.Modification.profile(a,M.state).ratio)<.98||text(a.modifications));}
  function activeOverride(session,item,ath){return(M.state?.adaptationOverrides||[]).find(r=>r.sessionId===session.id&&r.itemId===item.id&&r.athleteId===ath.id&&r.active!==false)||null;}
  function selectedStroke(session,item,ath){return activeOverride(session,item,ath)?.patch?.stroke||'';}
  function strokeInfo(session,item,ath){const override=selectedStroke(session,item,ath);if(override)return{stroke:E.Evidence.stroke(override),source:'coach'};const raw=text(item?.raw||item?.text),ambiguous=/#\s*1/i.test(raw);if(item?.raceIntent||(item?.repInstructions||[]).some(x=>x.raceIntent)||ambiguous){const v=E.RacePace.resolveStroke(item,ath,M.state,session?.identity?.course||'SCM','')||'Auto';let source='auto';if(ambiguous&&v!=='Auto'){try{if(M.performanceEngine?.profile?.(ath,M.state,session?.identity?.course||'SCM')?.medleyPrimary)source='im';}catch{}}return{stroke:v,source};}const st=E.Evidence.stroke(item?.stroke||'');if(st&&st!=='Choice')return{stroke:st,source:'authored'};if(item?.zone||(item?.repPattern||[]).length)return{stroke:'Freestyle',source:'aerobic'};return{stroke:st||'Auto',source:'auto'};}
  function displayStroke(session,item,ath){return strokeInfo(session,item,ath).stroke;}
  function strokeLabel(session,item,ath){const info=strokeInfo(session,item,ath),base=info.stroke==='Auto'?'Auto':short(info.stroke);if(info.source==='coach')return`${base} ·C`;if(info.source==='im'&&info.stroke!=='IM')return`${base} ·IM`;return base;}
  function athleteLink(a,pool){return`<button class="msos-name" data-msos-ath="${esc(a.id)}">${esc(name(a,pool))}</button>`;}
  function strokePill(session,item,a){const info=strokeInfo(session,item,a),lab=strokeLabel(session,item,a),why=info.source==='coach'?'Coach-selected stroke':info.source==='im'?'IM-primary contextual stroke':'Resolved stroke';return`<button class="msos-stroke-pill" data-msos-stroke="${esc(item.id)}:${esc(a.id)}" aria-label="Change stroke for ${esc(name(a,present()))}" title="${esc(why)}">${esc(lab)}</button>`;}
  function setStroke(session,item,ath,value){const rows=M.state.adaptationOverrides=M.state.adaptationOverrides||[],x=rows.find(r=>r.sessionId===session.id&&r.itemId===item.id&&r.athleteId===ath.id&&r.active!==false),stroke=value==='AUTO'?'':E.Evidence.stroke(value);if(stroke){if(x){x.patch=x.patch||{};x.patch.stroke=stroke;x.active=true;x.updatedAt=new Date().toISOString();}else rows.push({id:U.uid?.('mod')||`mod-${Date.now()}`,sessionId:session.id,itemId:item.id,athleteId:ath.id,patch:{stroke},active:true,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});}else if(x){x.patch=x.patch||{};delete x.patch.stroke;if(!Object.keys(x.patch).length)x.active=false;x.updatedAt=new Date().toISOString();}E.Coordinator.clearCache?.();E.RacePace?.invalidate?.(M.state);M.performanceEngine?.invalidate?.(M.state);M.store?.save?.(M.state);M.cloud?.stageAdaptationsForSession?.(session);UI.renderBoard?.();}
  function targetCard(session,item,a){const r=E.Coordinator.targetForItem(session,item,a,M.state);return`<div class="msos-target-card"><div>${athleteLink(a,present())}${strokePill(session,item,a)}</div><span>${esc(targetSummary(r)||'—')}</span></div>`;}
  function targetPanel(_session,item,_groupAth){return`<div class="msos-target-panel" data-msos-panel="${esc(item.id)}"><section><label>TIMES</label><div class="msos-target-matrix" data-msos-target-matrix><span class="msos-none">Loading targets…</span></div></section></div>`;}
  function captures(session,{itemId='',blockId='',sessionOnly=false}={}){return(M.state?.captures||[]).filter(c=>c?.session_id===session?.id&&(sessionOnly?(!c.item_id&&!c.block_id):(itemId?c.item_id===itemId:(blockId?c.block_id===blockId&&!c.item_id:false)))).sort((a,b)=>String(a.created_at||'').localeCompare(String(b.created_at||'')));}
  function evidenceStrip(rows=[]){if(!rows.length)return'';return`<div class="msos-evidence-strip">${rows.map(c=>{const t=text(c.capture_type||'note').toLowerCase(),icon=t==='video'?'▶':t==='photo'?'▣':t==='voice'?'♪':'✎',label=t==='video'?'Video':t==='photo'?'Photo':t==='voice'?'Voice':'Note';return`<button class="msos-evidence-thumb ${t}" data-msos-capture="${esc(c.id)}" aria-label="Open ${esc(label)} capture"><span>${icon}</span><small>${esc(label)}</small></button>`;}).join('')}</div>`;}
  function modCell(session,item,mods){if(!mods.length)return'';const rows=[];for(const a of mods){const actual=E.Modification.adaptItem(item,a,M.state,session),changed=!E.Modification.samePrescription(item,actual),needsTarget=targetIntent(actual);if(!changed&&!needsTarget)continue;const cue=cueText(actual),cached=needsTarget?E.Coordinator.peekTarget?.(session,actual,a,M.state):null,target=cached?targetSummary(cached):'';rows.push(`<div class="msos-mod-row" data-msos-mod-row="${esc(item.id)}:${esc(a.id)}"><div class="msos-mod-top">${athleteLink(a,mods)}<button class="msos-mod-edit" data-msos-mod-edit="${esc(item.id)}:${esc(a.id)}" aria-label="Edit ${esc(name(a,mods))} modification">Edit</button>${needsTarget?strokePill(session,item,a):''}</div><b>${esc(workLabel(actual))}</b>${cue?`<small class="msos-mod-cue">${esc(cue)}</small>`:''}${needsTarget?`<span class="msos-mod-target" data-msos-mod-item="${esc(item.id)}" data-msos-mod-ath="${esc(a.id)}">${esc(target||'…')}</span>`:''}</div>`);}return rows.join('');}
  function setRow(session,item,groupAth,mods){const intent=targetIntent(item),id=esc(item.id),open=M.state?.settings?.boardExpandedTargetId===item.id,ev=evidenceStrip(captures(session,{itemId:item.id}));return`<div class="msos-work-row" data-item="${id}"><div class="msos-group-cell"><div class="msos-work-head"><b>${esc(workLabel(item))}</b>${intent?`<button class="msos-times-btn" data-msos-times="${id}">${open?'Close':'Times'}</button>`:''}</div>${cueText(item)?`<small>${esc(cueText(item))}</small>`:''}${ev}</div><div class="msos-mod-cell">${modCell(session,item,mods)}</div>${intent&&open?targetPanel(session,item,groupAth):''}</div>`;}
  function nodeRows(session,node,groupAth,mods){if(node?.kind==='set')return setRow(session,node,groupAth,mods);if(node?.kind==='group')return`<div class="msos-rounds"><div class="msos-round-label">${Math.max(1,Number(node.rounds)||1)} ROUNDS${node.label?` · ${esc(short(node.label))}`:''}</div>${(node.items||[]).map(x=>nodeRows(session,x,groupAth,mods)).join('')}</div>`;if(node?.kind==='cue')return`<div class="msos-board-cue">${esc(short(node.text||node.raw))}</div>`;return'';}
  function blockCode(b){const t=text(b?.type||b?.title).toLowerCase();if(/warm.?up/.test(t))return'WU';if(/pre/.test(t))return'PRE';if(/main/.test(t))return'MAIN';if(/post/.test(t))return'POST';if(/warm.?down|cool/.test(t))return'WD';return text(b?.title).slice(0,4).toUpperCase();}
  function blockHtml(session,b,groupAth,mods){const ev=evidenceStrip(captures(session,{blockId:b.id}));return`<section class="msos-board-block" data-block="${esc(b.id)}"><header><div><small>${esc(blockCode(b))}</small><h2>${esc(b.title||'Set')}</h2></div><b>${blockDistance(b).toLocaleString()}m</b><span>${mods.length?`MOD ${mods.length}`:''}</span></header>${ev}<div class="msos-board-grid">${(b.items||[]).map(x=>nodeRows(session,x,groupAth,mods)).join('')}</div></section>`;}
  function route(view){if(M.navigationEngine?.go)return M.navigationEngine.go(view,{restore:false});if(M.nav?.show)return M.nav.show(view,{restoreScroll:false});M.state.settings=M.state.settings||{};M.state.settings.view=view;M.storageEngine?.saveUi?.(M.state);UI.renderCurrent?.();}
  function findItem(session,id){let hit=null;const walk=items=>{for(const n of items||[]){if(n?.id===id){hit=n;return;}if(n?.kind==='group')walk(n.items);if(hit)return;}};for(const b of session?.blocks||[]){walk(b.items);if(hit)break;}return hit;}
  function rememberTargetAnchor(btn){const row=btn.closest?.('.msos-work-row');M.state.settings.boardTargetAnchor={itemId:btn.dataset.msosTimes,top:row?.getBoundingClientRect?.().top??null,y:window.scrollY||0};}
  function restoreTargetAnchor(host){const a=M.state?.settings?.boardTargetAnchor;if(!a)return;M.state.settings.boardTargetAnchor=null;requestAnimationFrame(()=>{const selector=`[data-item="${String(a.itemId).replace(/"/g,'\\"')}"]`,row=host.querySelector(selector);if(row&&Number.isFinite(Number(a.top))){window.scrollBy(0,row.getBoundingClientRect().top-Number(a.top));}else window.scrollTo(0,Number(a.y)||0);});}
  function bind(host,session){
    host.querySelectorAll('[data-msos-times]').forEach(btn=>btn.onclick=()=>{if(M.boardStateEngine?.openPanel)return M.boardStateEngine.openPanel(btn);M.state.settings=M.state.settings||{};rememberTargetAnchor(btn);M.state.settings.boardExpandedTargetId=M.state.settings.boardExpandedTargetId===btn.dataset.msosTimes?'':btn.dataset.msosTimes;M.storageEngine?.saveUi?.(M.state);UI.renderBoard();});
    host.querySelectorAll('[data-msos-ath]').forEach(btn=>btn.onclick=e=>{e.stopPropagation();M.state.settings=M.state.settings||{};M.state.settings.selectedAthleteId=btn.dataset.msosAth;M.state.settings.selectedSwimmerId=btn.dataset.msosAth;route('athletes');});
    host.querySelectorAll('[data-msos-stroke]').forEach(btn=>btn.onclick=e=>{e.stopPropagation();host.querySelectorAll('.msos-stroke-menu').forEach(x=>x.remove());const [itemId,athId]=btn.dataset.msosStroke.split(':'),item=findItem(session,itemId),ath=present().find(a=>a.id===athId);if(!item||!ath)return;const menu=document.createElement('div');menu.className='msos-stroke-menu';for(const [v,l] of [['AUTO','Auto'],['Freestyle','Fr'],['Backstroke','Bk'],['Breaststroke','Br'],['Butterfly','Fly'],['IM','IM']]){const b=document.createElement('button');b.textContent=l;b.onclick=ev=>{ev.stopPropagation();setStroke(session,item,ath,v);};menu.appendChild(b);}btn.parentElement.appendChild(menu);setTimeout(()=>document.addEventListener('click',()=>menu.remove(),{once:true}),0);});
    host.querySelector('[data-msos-mode]')?.addEventListener('click',()=>{M.state.settings.boardFocusMode=M.state.settings.boardFocusMode===false;M.state.settings.boardExpandedTargetId='';M.storageEngine?.saveUi?.(M.state);UI.renderBoard();});
    host.querySelectorAll('[data-msos-block]').forEach(btn=>btn.onclick=()=>{M.state.settings.boardFocusMode=true;M.state.settings.boardExpandedTargetId='';M.state.settings.boardBlockBySession=M.state.settings.boardBlockBySession||{};M.state.settings.boardBlockBySession[session.id]=btn.dataset.msosBlock;M.storageEngine?.saveUi?.(M.state);UI.renderBoard();});
    host.querySelector('[data-msos-roll]')?.addEventListener('click',()=>route('roll'));host.querySelector('[data-msos-t400]')?.addEventListener('click',()=>route('times'));host.querySelector('[data-msos-swimmers]')?.addEventListener('click',()=>route('athletes'));
  }
  function context(session){const athletes=present(),mods=modified(),modIds=new Set(mods.map(a=>a.id)),groupAth=athletes.filter(a=>!modIds.has(a.id));M.state.settings=M.state.settings||{};M.state.settings.boardBlockBySession=M.state.settings.boardBlockBySession||{};let active=(session.blocks||[]).find(b=>b.id===M.state.settings.boardBlockBySession[session.id]);if(!active)active=(session.blocks||[]).find(b=>b.type==='main_set')||(session.blocks||[])[0];if(active)M.state.settings.boardBlockBySession[session.id]=active.id;return{athletes,mods,groupAth,active};}
  function afterPaint(host){requestAnimationFrame(()=>{M.boardStateEngine?.hydrateVisibleModTargets?.();M.captureUI?.hydrateBoardEvidence?.(host);});}
  function render(){const host=document.querySelector('#boardView'),session=M.currentSession?.();if(!host)return;if(!session){host.innerHTML='<div class="empty">No session selected.</div>';return;}const {athletes,mods,groupAth,active}=context(session),focus=M.state.settings.boardFocusMode!==false,blocks=focus&&active?[active]:(session.blocks||[]),title=session.identity?.title||`${session.identity?.dayPart||''} · ${(session.identity?.squads||[]).join(' + ')}`||'Session',sev=evidenceStrip(captures(session,{sessionOnly:true}));host.className='view msos-whiteboard-engine';host.innerHTML=`<div class="msos-board-top"><div><small>${focus?'CURRENT SET':'WHOLE SESSION'}</small><h1>${esc(title)}</h1></div><b>${sessionDistance(session).toLocaleString()}m</b></div>${sev}<div class="msos-board-quick"><button data-msos-roll>Roll · ${athletes.length}</button><button data-msos-t400>T400 / Times</button><button data-msos-swimmers>Swimmers</button></div><div class="msos-board-nav"><button data-msos-mode>${focus?'WHOLE':'SET'}</button>${(session.blocks||[]).map(b=>`<button data-msos-block="${esc(b.id)}" class="${focus&&b.id===active?.id?'active':''}">${esc(blockCode(b))}</button>`).join('')}</div>${blocks.map(b=>blockHtml(session,b,groupAth,mods)).join('')}`;bind(host,session);if(M.state?.settings?.view==='board')host.classList.add('active');restoreTargetAnchor(host);afterPaint(host);}
  function renderTV(){const host=document.querySelector('#tvView'),session=M.currentSession?.();if(!host)return;if(!session){host.innerHTML='<div class="empty">No session selected.</div>';return;}const {mods,groupAth,active}=context(session),title=session.identity?.title||'Session';host.className='view msos-tv-board-engine';host.innerHTML=`<div class="msos-tv-top"><h1>${esc(title)}</h1><b>${sessionDistance(session).toLocaleString()}m</b></div>${active?blockHtml(session,active,groupAth,mods):''}`;bind(host,session);if(M.state?.settings?.view==='tv')host.classList.add('active');afterPaint(host);}
  UI.renderBoard=render;UI.renderTV=renderTV;B.render=render;B.renderTV=renderTV;B.targetSummary=targetSummary;B.workLabel=workLabel;B.cueText=cueText;B.displayStroke=displayStroke;B.strokeInfo=strokeInfo;B.strokeLabel=strokeLabel;B.selectedStroke=selectedStroke;B.findItem=findItem;B.evidenceStrip=evidenceStrip;
})(globalThis);
