'use strict';
(function(g){const M=g.MSOS4,E=g.MSOSEngines;if(!M?.ui||!E?.Coordinator||!E?.Evidence)return;const UI=M.ui,U=M.util,B=M.boardEngine={build:'v4-board-whiteboard-20260820g'};
  const text=v=>String(v??'').replace(/\s+/g,' ').trim(),clock=s=>U?.clock?U.clock(Number(s)):text(s);
  const short=v=>text(v).replace(/\bFreestyle\b/gi,'Fr').replace(/\bBackstroke\b/gi,'Bk').replace(/\bBreaststroke\b/gi,'Br').replace(/\bButterfly\b/gi,'Fly').replace(/\bRegeneration\b/gi,'REG').replace(/\bDevelopment\b/gi,'DEV').replace(/\bOverload\b/gi,'OL').replace(/\bThreshold\b/gi,'THR').replace(/\bClearance\b/gi,'CL');
  const preferred=a=>text(a?.board_name||a?.boardName||a?.nickname||a?.preferred_name||a?.preferredName);
  function name(a,pool=[]){if(!a)return'?';const nick=preferred(a);if(nick)return nick;const parts=text(a.full_name).split(/\s+/),first=parts[0]||'?',same=pool.filter(x=>x?.id!==a.id&&!preferred(x)&&text(x.full_name).split(/\s+/)[0]?.toLowerCase()===first.toLowerCase());return same.length?`${first} ${(parts.at(-1)||'').slice(0,3).toUpperCase()}`:first}
  B.name=name;
  function replaceSelect(row,sel){const value=sel.value||'AUTO',pill=document.createElement('button');pill.type='button';pill.className='msos-stroke-pill';pill.textContent=value==='AUTO'?'Auto':short(value);pill.onclick=e=>{e.stopPropagation();const choices=['AUTO','Freestyle','Backstroke','Breaststroke','Butterfly','IM'],i=choices.indexOf(sel.value),next=choices[(i<0?0:i+1)%choices.length];sel.value=next;sel.dispatchEvent(new Event('change',{bubbles:true}))};sel.hidden=true;sel.insertAdjacentElement('afterend',pill)}
  function compactTargetGrid(host){const athletes=UI.presentAthletes?.()||[];host.querySelectorAll('.thu2-target-grid').forEach(grid=>{grid.classList.add('msos-target-matrix');grid.querySelectorAll('.thu2-target-row').forEach(row=>{const sel=row.querySelector('[data-thu2-stroke]'),id=sel?.dataset.thu2Stroke?.split(':')[0],ath=athletes.find(a=>a.id===id),n=row.querySelector('b');if(n&&ath){n.textContent=name(ath,athletes);n.classList.add('msos-swimmer-link');n.onclick=e=>{e.stopPropagation();M.state.settings=M.state.settings||{};M.state.settings.selectedAthleteId=ath.id;M.state.settings.view='swimmer';M.store?.save?.(M.state);UI.renderCurrent?.()}}if(sel&&!row.querySelector('.msos-stroke-pill'))replaceSelect(row,sel);const span=row.querySelector('span');if(span)span.textContent=short(span.textContent).replace(/#1 target needed/gi,'—')})})}
  function compressBoard(host){host.querySelectorAll('.thu2-line-head strong,.thu2-line-head small,.thu2-cue,.thu3-mod-ath b,.thu3-mod-ath em').forEach(x=>x.textContent=short(x.textContent));host.querySelectorAll('.thu3-mod-ath small').forEach(x=>x.hidden=true);host.querySelectorAll('.thu2-block footer,.thu2-block-actions').forEach(x=>{if(/Capture/i.test(x.textContent)&&/Finish here/i.test(x.textContent))x.classList.add('msos-secondary-actions')});host.querySelectorAll('.thu2-line-head em').forEach(x=>{const t=text(x.textContent);if(/Targets/i.test(t)||/^T›?$/.test(t))x.textContent='Times';else if(/Close|×/.test(t))x.textContent='Close'});compactTargetGrid(host)}
  const base=UI.renderBoard?.bind(UI);if(base)UI.renderBoard=()=>{base();const host=document.querySelector('#boardView');if(host){host.classList.add('msos-whiteboard-engine');compressBoard(host)}};
})(globalThis);