'use strict';
(function(g){
  const M=g.MSOS4,E=g.MSOSEngines;if(!M||!E?.Evidence||!E?.Aerobic||!E?.RacePace||!E?.Modification||!E?.Coordinator)throw new Error('MSOS engine bridge dependencies missing');
  const PB_META_KEY='mclay_swimming_v4_pb_roster_meta';
  const readMeta=()=>{try{return JSON.parse(localStorage.getItem(PB_META_KEY)||'null')||null}catch{return null}};
  const org=()=>M.cloud?.org?.()||M.state?.settings?.organisationId||'';
  const initialMeta=readMeta(),metaCurrent=initialMeta?.complete===true&&String(initialMeta.organisationId||'')===String(org()||'');
  const B={build:'v4-engine-silos-board-20260821ah',hydrated:false,hydrating:null,pathwayPbCache:new Map(),athleteEvidencePulls:new Map(),pbRosterSync:metaCurrent?{status:'done',rows:Number(initialMeta.rows)||0,error:'',at:initialMeta.at||'',cached:true}:{status:'idle',rows:0,error:''}};M.engineBridge=B;M.BUILD=B.build;M.CORE='20260821-engine-silos-ah';
  const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
  const zoneIntent=item=>/\b(?:Regeneration|Development|Overload|Threshold|Clearance|Aerobic|VO2)\b/i.test(clean([item?.raw,item?.text,...(item?.cues||[])].join(' ')));
  function preserveRepeatingDescent(item,out){
    if(!item||!out)return out;const base=Math.max(1,Number(item.reps)||1),rows=[...(item.cues||[]),item.raw,item.text].filter(Boolean),keep=[];
    for(const row of rows){const m=clean(row).match(/\bDesc(?:end|ending)?\s+1\s*[-–—]\s*(\d+)\b/i);if(!m)continue;const n=Number(m[1]);if(n>1&&n<base&&base%n===0)keep.push(clean(row));}
    if(!keep.length)return out;const delivered=Math.max(1,Number(out.reps)||1),generated=new RegExp(`\\bDesc(?:end|ending)?\\s+1\\s*[-–—]\\s*${delivered}\\b`,'i');out.cues=[...(out.cues||[])].filter(c=>!generated.test(clean(c)));for(const cue of [...new Set(keep)])if(!out.cues.some(c=>clean(c)===cue))out.cues.push(cue);if(generated.test(clean(out.raw||out.text))){const authored=keep[0].match(/Desc(?:end|ending)?\s+1\s*[-–—]\s*\d+/i)?.[0]||'Desc 1-3';out.raw=clean(out.raw||out.text).replace(generated,authored);out.text=out.raw;}out.authoredPatternPreserved=true;return out;
  }
  M.targets.t400=(ath,state=M.state,_course='',stroke='Freestyle')=>E.Aerobic.t400(ath,state,stroke);
  M.targets.pb=(ath,state=M.state,spec={})=>E.RacePace.pb(ath,state,spec);
  M.targets.forItem=(session,item,ath,state=M.state)=>{const suppressed=E.Coordinator.suppress?.(item);if(suppressed)return E.Coordinator.targetForItem(session,item,ath,state);if(zoneIntent(item)&&!item?.targetSeconds&&!item?.raceIntent){const stroke=E.Evidence.stroke?.(item?.stroke)||item?.stroke||'Freestyle',wanted=/^(?:Freestyle|Backstroke|Breaststroke|Butterfly|IM)$/i.test(clean(stroke))?stroke:'Freestyle',anchor=E.Aerobic.t400(ath,state,wanted);if(!anchor)return{status:'missing',message:`No ${wanted} T400 target loaded`};}return E.Coordinator.targetForItem(session,item,ath,state);};
  M.adapt.profile=(ath,state=M.state)=>E.Modification.profile(ath,state);
  M.adapt.item=(item,ath,state=M.state,session=null)=>preserveRepeatingDescent(item,E.Modification.adaptItem(item,ath,state,session));
  M.adapt.samePrescription=(a,b)=>E.Modification.samePrescription(a,b);
  M.performanceBridge={ask:(kind,p={})=>kind==='t400'?E.Aerobic.t400(p.athlete,p.state||M.state,p.stroke):kind==='pb'?E.RacePace.pb(p.athlete,p.state||M.state,p):kind==='bestStroke'?(M.performanceEngine?.bestStroke?.(p.athlete,p.state||M.state,p.course||'',!!p.nonFree)?.stroke||E.RacePace.bestStroke(p.athlete,p.state||M.state,p.course||'',!!p.nonFree)):kind==='bestEvent'?M.performanceEngine?.bestEvent?.(p.athlete,p.state||M.state,p.course||''):kind==='bestFormStroke'?M.performanceEngine?.bestFormStroke?.(p.athlete,p.state||M.state,p.course||''):null};
  const writeMeta=rows=>{const m={complete:true,organisationId:org(),rows:Number(rows)||0,at:new Date().toISOString(),build:B.build};try{localStorage.setItem(PB_META_KEY,JSON.stringify(m))}catch{}return m;};
  B.canAttemptCloudRead=()=>!!(M.cloudSessionEngine?.canRead?.()||M.cloud?.ready?.());
  B.localPbReferenceCount=()=>{try{return (M.refs?.get?.('results_pb_board')||[]).length}catch{return 0}};
  function mergeReferenceEvidence(){const R=M.refs;if(!R?.get)return{pb:0,history:0,coach:0,base:0};const pb=R.get('results_pb_board')||[],history=R.get('results_event_history')||[],coach=R.get('coach_results')||[],base=R.get('world_aquatics_base_times')||[];M.state.resultsPbBoard=E.Evidence.merge(M.state.resultsPbBoard||M.state.results_pb_board||[],pb);M.state.resultsEventHistory=E.Evidence.merge(M.state.resultsEventHistory||M.state.results_event_history||[],history);M.state.coachResults=E.Evidence.merge(M.state.coachResults||M.state.coach_results||[],coach);if(!M.dataRegistry?.activeMeta?.('wa_points'))M.state.worldAquaticsBaseTimes=E.Evidence.merge(M.state.worldAquaticsBaseTimes||[],base);return{pb:pb.length,history:history.length,coach:coach.length,base:base.length};}
  function invalidatePerformance(reason='evidence'){B.pathwayPbCache.clear();g.MSOSEvidenceIndex?.invalidate?.(M.state);E.RacePace?.invalidate?.(M.state);E.Coordinator.clearCache?.();M.performanceEngine?.invalidate?.(M.state);M.waPointsEngine?.invalidate?.();M.state._evidenceBridge={...(M.state._evidenceBridge||{}),hydratedAt:new Date().toISOString(),reason};try{dispatchEvent(new CustomEvent('msos:evidence-ready',{detail:M.state._evidenceBridge}));}catch{}}
  async function cloudPages(path){if(M.cloudSessionEngine?.fetchPages)return M.cloudSessionEngine.fetchPages(path);if(M.cloud?.ready?.()&&M.cloud?.fetchPages)return M.cloud.fetchPages(path);throw Object.assign(new Error('PB/result connection is unavailable'),{code:'pb_connection'});}
  async function mergeCloudRows(key,stateKey,rows){if(!Array.isArray(rows)||!rows.length)return 0;M.refs?.merge?.(key,rows);try{await M.refs?.save?.()}catch{}M.referenceBridge?.invalidate?.(key);M.state[stateKey]=E.Evidence.merge(M.state[stateKey]||[],rows);return rows.length;}
  B.ensurePathwayAthlete=(ath,course='SCM')=>{if(!ath||!M.pathway?.pbRows)return 0;const c=String(course||'SCM').toUpperCase(),key=`${ath.id||E.Evidence.key?.(ath.full_name)||ath.full_name}|${c}|${M.state?._evidenceBridge?.hydratedAt||''}`;if(B.pathwayPbCache.has(key))return B.pathwayPbCache.get(key);let source=[];try{source=M.pathway.pbRows(ath)||[]}catch{B.pathwayPbCache.set(key,0);return 0}const stable=M.util?.stableId||((p,...v)=>`${p}-${v.join('-')}`),rows=[];for(const pb of source){const seconds=E.Evidence.seconds(pb),distance=E.Evidence.distance(pb),stroke=E.Evidence.rowStroke(pb),pool=E.Evidence.course(pb)||c;if(!Number.isFinite(seconds)||seconds<=0||!distance||!stroke||pool!==c)continue;rows.push({...pb,id:pb.id||stable('pathway-pb',ath.id,c,distance,stroke,seconds),athlete_id:ath.id,distance,stroke,pool_course:pool,result_seconds:seconds,source_type:pb.source_type||'pathway',source_label:pb.source_label||'Swimmer pathway PB evidence'});}if(rows.length){M.state.resultsPbBoard=E.Evidence.merge(M.state.resultsPbBoard||[],rows);g.MSOSEvidenceIndex?.invalidate?.(M.state);M.performanceEngine?.invalidate?.(M.state)}B.pathwayPbCache.set(key,rows.length);return rows.length;};
  B.athletePbCount=(ath,course='')=>{if(!ath)return 0;const c=String(course||'').toUpperCase();let rows=[];try{rows=E.Evidence.pbRows(ath,M.state)||[]}catch{}return c?rows.filter(r=>!E.Evidence.course(r)||E.Evidence.course(r)===c).length:rows.length;};
  B.refreshPbRoster=async({force=false}={})=>{if(B.pbRosterSync.status==='running')return B.pbRosterSync.promise;const localRefs=B.localPbReferenceCount();if(B.pbRosterSync.status==='done'&&!force&&localRefs>0)return B.pbRosterSync.rows||localRefs;if(!B.canAttemptCloudRead()){B.pbRosterSync={status:'unavailable',rows:localRefs,error:M.cloudSessionEngine?.status?.().message||'PB/result sign-in required',at:new Date().toISOString()};return localRefs;}const p=(async()=>{B.pbRosterSync={status:'running',rows:localRefs,error:'',promise:null,at:new Date().toISOString()};try{const organisation=encodeURIComponent(org()),rows=await cloudPages(`/rest/v1/results_pb_board?select=*&organisation_id=eq.${organisation}`);if(Array.isArray(rows)){await mergeCloudRows('results_pb_board','resultsPbBoard',rows);const refs=mergeReferenceEvidence(),meta=writeMeta(rows.length);B.pbRosterSync={status:'done',rows:rows.length,error:'',at:meta.at,cached:false};M.state._evidenceBridge={...(M.state._evidenceBridge||{}),...refs};invalidatePerformance('pb-roster-sync');return rows.length}B.pbRosterSync={status:'error',rows:localRefs,error:'PB/result roster returned an invalid response',at:new Date().toISOString()};return localRefs;}catch(err){B.pbRosterSync={status:'error',rows:localRefs,error:String(err?.message||err),at:new Date().toISOString()};console.warn('[MSOS] PB roster sync deferred',err);invalidatePerformance('pb-roster-error');return localRefs}})();B.pbRosterSync.promise=p;return p;};
  async function directAthleteRecovery(ath){if(!B.canAttemptCloudRead())return 0;const id=encodeURIComponent(String(ath?.id||'')),name=encodeURIComponent(String(ath?.full_name||'')),jobs=[];if(id)jobs.push(['results_pb_board','resultsPbBoard',`/rest/v1/results_pb_board?select=*&athlete_id=eq.${id}`],['coach_results','coachResults',`/rest/v1/coach_results?select=*&athlete_id=eq.${id}`],['results_event_history','resultsEventHistory',`/rest/v1/results_event_history?select=*&athlete_id=eq.${id}`]);if(name)jobs.push(['results_pb_board','resultsPbBoard',`/rest/v1/results_pb_board?select=*&full_name=eq.${name}`]);let added=0;for(const [key,stateKey,path] of jobs){try{const rows=await cloudPages(path);added+=await mergeCloudRows(key,stateKey,rows)}catch(err){if(!/column .*full_name|does not exist/i.test(String(err?.message||'')))console.warn('[MSOS] athlete evidence query deferred',key,err)}}if(added){mergeReferenceEvidence();invalidatePerformance('athlete-pb-direct')}return added;}
  B.ensureAthleteEvidence=async(ath,{course='SCM',force=false}={})=>{if(!ath)return 0;const c=String(course||'SCM').toUpperCase(),key=`${ath.id||E.Evidence.key?.(ath.full_name)||ath.full_name}|${c}`,local=B.athletePbCount(ath,c);if(local&&!force)return local;if(B.athleteEvidencePulls.has(key))return B.athleteEvidencePulls.get(key);const p=(async()=>{try{await B.refreshPbRoster({force});let count=B.athletePbCount(ath,c);if(count)return count;if(B.canAttemptCloudRead()){await directAthleteRecovery(ath);count=B.athletePbCount(ath,c)}return count;}catch(err){console.warn('[MSOS] athlete PB recovery deferred',ath.full_name||ath.id,err);return B.athletePbCount(ath,c)}finally{B.athleteEvidencePulls.delete(key)}})();B.athleteEvidencePulls.set(key,p);return p;};
  B.evidenceStatus=(ath=null,course='')=>{const local=ath?B.athletePbCount(ath,course):B.localPbReferenceCount(),s=B.pbRosterSync;if(local>0)return{status:'ready',message:`${local} PB event${local===1?'':'s'} available`,rows:local};if(s.status==='running')return{status:'loading',message:'Loading PB / results…',rows:0};if(s.status==='error')return{status:'error',message:s.error||'PB/result store unavailable',rows:0};if(s.status==='unavailable')return{status:'unavailable',message:s.error||M.cloudSessionEngine?.status?.().message||'PB/result store unavailable',rows:0};if(s.status==='done')return{status:'complete',message:'PB roster checked · no matching result evidence',rows:0};if(!B.canAttemptCloudRead())return{status:'unavailable',message:M.cloudSessionEngine?.status?.().message||'PB/result sign-in required',rows:0};return{status:'idle',message:'PB/results not checked yet',rows:0};};
  B.evidenceUnavailable=(ath=null,course='')=>['error','unavailable'].includes(B.evidenceStatus(ath,course).status);
  B.whenRaceEvidenceReady=async()=>{if(!B.hydrated)await B.hydrate();if(B.pbRosterSync.status==='done'&&B.localPbReferenceCount()>0)return true;if(B.canAttemptCloudRead())await B.refreshPbRoster();else if(B.pbRosterSync.status==='idle')B.pbRosterSync={status:'unavailable',rows:B.localPbReferenceCount(),error:M.cloudSessionEngine?.status?.().message||'PB/result sign-in required',at:new Date().toISOString()};return true;};
  function refreshOwnerView(){const v=M.state?.settings?.view||'board';if(v==='athletes')M.performanceUI?.render?.();else if(v==='reports')M.reportingUI?.render?.();else if(v==='times')M.ui?.renderTimes?.();else if(v==='swimmer')M.ui?.renderSwimmer?.();else if(v==='data')M.dataAdminUI?.render?.();}
  B.hydrate=async({force=false}={})=>{if(B.hydrated&&!force)return true;if(B.hydrating&&!force)return B.hydrating;B.hydrating=(async()=>{try{try{await M.storageEngine?.readyPromise}catch{}const snap=await E.Evidence.hydrate(M.state||{});for(const k of ['athletes','trainingTestTypes','trainingTestResults','adaptationProfiles','adaptationOverrides','coachResults','resultsEventHistory','resultsPbBoard','courseConversions','worldAquaticsBaseTimes'])if(Array.isArray(snap[k])&&!(k==='worldAquaticsBaseTimes'&&M.dataRegistry?.activeMeta?.('wa_points')))M.state[k]=E.Evidence.merge(M.state[k],snap[k]);M.state._refs=snap._refs||M.state._refs||{};let refs={pb:0,history:0,coach:0,base:0};try{await M.refs?.boot?.();refs=mergeReferenceEvidence()}catch{}E.Evidence.ensureVerified?.(M.state);M.state._evidenceBridge={...refs,hydratedAt:new Date().toISOString(),reason:'local-hydrate'};B.pathwayPbCache.clear();g.MSOSEvidenceIndex?.invalidate?.(M.state);E.Coordinator.clearCache?.();M.performanceEngine?.invalidate?.(M.state);M.waPointsEngine?.invalidate?.();B.hydrated=true;try{dispatchEvent(new CustomEvent('msos:evidence-ready',{detail:M.state._evidenceBridge}));}catch{}requestAnimationFrame(refreshOwnerView);return true}catch(err){console.warn('[MSOS] evidence hydration failed',err);return false}finally{B.hydrating=null}})();return B.hydrating;};
  const boot=()=>{B.hydrated=false;B.hydrate({force:true})};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})(globalThis);
