'use strict';
(function(g){
  const M=g.MSOS4;if(!M?.cloud||!M?.store)return;
  const C=M.cloudSessionEngine={build:'v4-cloud-session-20260820z',authStatus:{status:'idle',error:'',at:''}};
  const text=v=>String(v??'').trim();
  const config=()=>M.store.config?.()||{};
  const auth=()=>M.store.auth?.()||{};
  const org=()=>M.cloud.org?.()||M.state?.settings?.organisationId||'';
  function jwtExp(token){try{const p=String(token||'').split('.')[1];if(!p)return 0;const s=p.replace(/-/g,'+').replace(/_/g,'/'),pad=s+'='.repeat((4-s.length%4)%4);return Number(JSON.parse(atob(pad))?.exp)||0}catch{return 0}}
  function saveAuth(next){try{localStorage.setItem(M.AUTH_KEY,JSON.stringify(next||{}));return true}catch{return false}}
  C.canRead=()=>{const cfg=config(),a=auth();return !!(text(cfg.supabaseUrl)&&text(cfg.supabaseAnonKey)&&text(org())&&(text(a.access_token)||text(a.refresh_token)));};
  C.sessionState=()=>{const a=auth(),exp=Number(a.expires_at)||jwtExp(a.access_token);return{hasAccess:!!a.access_token,hasRefresh:!!a.refresh_token,expiresAt:exp||0,expired:!!(exp&&exp<=Date.now()/1000),organisationId:org()};};
  C.ensureFresh=async({force=false}={})=>{const cfg=config(),a=auth(),now=Math.floor(Date.now()/1000),exp=Number(a.expires_at)||jwtExp(a.access_token);if(!force&&a.access_token&&(!exp||exp>now+90)){C.authStatus={status:'ready',error:'',at:new Date().toISOString()};return a;}if(!cfg.supabaseUrl||!cfg.supabaseAnonKey)throw Object.assign(new Error('Cloud connection is not configured'),{code:'cloud_config'});if(!a.refresh_token){if(a.access_token&&!force&&!exp)return a;const e=Object.assign(new Error('PB/result connection needs sign-in'),{code:'auth_required'});C.authStatus={status:'error',error:e.message,at:new Date().toISOString()};throw e;}C.authStatus={status:'refreshing',error:'',at:new Date().toISOString()};try{const res=await fetch(`${String(cfg.supabaseUrl).replace(/\/$/,'')}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:cfg.supabaseAnonKey,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:a.refresh_token})});const body=await res.json().catch(()=>({}));if(!res.ok||!body?.access_token){const e=Object.assign(new Error(body?.msg||body?.message||`Sign-in refresh failed (${res.status})`),{status:res.status,code:'auth_refresh'});throw e;}const next={...a,...body,expires_at:body.expires_at||Math.floor(Date.now()/1000)+Number(body.expires_in||3600)};saveAuth(next);C.authStatus={status:'ready',error:'',at:new Date().toISOString()};return next;}catch(err){C.authStatus={status:'error',error:String(err?.message||err),at:new Date().toISOString()};throw err;}};
  const authError=err=>Number(err?.status)===401||/jwt|token|auth|unauthor/i.test(String(err?.message||''));
  C.fetch=async(path,opts={})=>{await C.ensureFresh();try{return await M.cloud.fetch(path,opts)}catch(err){if(!authError(err))throw err;await C.ensureFresh({force:true});return M.cloud.fetch(path,opts);}};
  C.fetchPages=async(path,pageSize=1000,maxRows=8000)=>{const rows=[];for(let from=0;from<maxRows;from+=pageSize){const sep=path.includes('?')?'&':'?',page=await C.fetch(`${path}${sep}limit=${pageSize}&offset=${from}`);if(!Array.isArray(page))break;rows.push(...page);if(page.length<pageSize)break;}return rows;};
  C.status=()=>{if(C.authStatus.status==='error')return{status:'error',message:C.authStatus.error||'PB/result connection unavailable'};if(!C.canRead()){const s=C.sessionState();return{status:'unavailable',message:s.organisationId?'PB/result sign-in required':'PB/result organisation not selected'};}return{status:C.authStatus.status==='refreshing'?'loading':'ready',message:C.authStatus.status==='refreshing'?'Refreshing PB/result connection…':'PB/result connection ready'};};
})(globalThis);
