'use strict';
(function(root,factory){const api=factory(root.MSOSEngines||{},root);if(typeof module==='object'&&module.exports)module.exports=api;else{root.MSOSEngines=root.MSOSEngines||{};root.MSOSEngines.Coordinator=api;}})(typeof globalThis!=='undefined'?globalThis:this,function(E,root){
  const VERSION='2.8.0-prescription-truth',text=v=>String(v??'').replace(/\s+/g,' ').trim();
  const cache=new Map();
  const clock=s=>{const n=Math.round(Number(s)||0),m=Math.floor(n/60);return `${m}:${String(n%60).padStart(2,'0')}`};
  function normalizeIntent(item){try{return E.RaceTargetIntent?.resolve?.(item)||item}catch{return item}}
  function overrideStroke(item,ath,state,session){const ov=(state?.adaptationOverrides||[]).find(x=>x.sessionId===session?.id&&x.itemId===item?.id&&x.athleteId===ath?.id&&x.active!==false),s=ov?.patch?.stroke;return s||''}
  function explicitStroke(raw){const s=text(raw);if(/\b(?:free(?:style)?|fr)\s+kick\b/i.test(s))return'Freestyle';if(/\b(?:back(?:stroke)?|bk)\s+kick\b/i.test(s))return'Backstroke';if(/\b(?:breast(?:stroke)?|br)\s+kick\b/i.test(s))return'Breaststroke';if(/\b(?:fly|butterfly)\s+kick\b/i.test(s))return'Butterfly';if(/\b(?:im|medley)\s+kick\b/i.test(s))return'IM';return''}
  function needsContext(item){const raw=text(item?.raw||item?.text);return (/\bKick\b/i.test(raw)&&!explicitStroke(raw))||/#\s*1(?:\b|F\b)/i.test(raw)}
  function contextualStroke(session,item,ath,state){const raw=text(item?.raw||item?.text),explicit=explicitStroke(raw);if(explicit)return explicit;const over=overrideStroke(item,ath,state,session);if(over)return E.Evidence?.stroke?E.Evidence.stroke(over):over;if(!needsContext(item))return item?.stroke||'';try{const p=root.MSOS4?.performanceEngine?.selectStrokeForContext?.(ath,item,state,session,{formOnly:/#\s*1F\b/i.test(raw)});if(p?.stroke)return E.Evidence?.stroke?E.Evidence.stroke(p.stroke):p.stroke}catch{}return item?.stroke||'Freestyle'}
  function resolvePrescriptionContext(session,item,ath,state){if(!item||!ath||!needsContext(item))return item;const stroke=contextualStroke(session,item,ath,state);if(!stroke)return item;return{...item,stroke,strokeResolution:{kind:'number-one',source:overrideStroke(item,ath,state,session)?'coach':'performance-context',stroke}}}
  function suppress(item){const raw=[item?.raw,item?.text,...(item?.cues||[])].filter(Boolean).join(' '),hasRace=!!item?.raceIntent||item?.repInstructions?.some(x=>x.raceIntent);if(hasRace)return'';if(/\bHR\s*Gauge\b/i.test(raw))return'HR Gauge';if(/^Choice$/i.test(text(item?.stroke))||/\bChoice\b/i.test(raw))return'Choice';if(/\b(?:Drill|Scull|Technique|Easy|Recovery|Reset|Warm\s*-?down|Cool\s*-?down|5HR|Kick|Underwater|Dive|Start|Finish|Max|Sprint)\b/i.test(raw)&&!item?.zone)return'Non-target work';return''}
  function itemKey(item){return [item?.id,item?.reps,item?.distance,item?.stroke,item?.zone,item?.restSeconds,item?.cycleSeconds,item?.raw,item?.text,JSON.stringify(item?.repPattern||[]),JSON.stringify(item?.repInstructions||[]),JSON.stringify(item?.raceIntent||null)].join('|')}
  function cacheKey(session,item,ath,state,ov){return [Number(state?.settings?.storageRevision||0),session?.id||'',ath?.id||'',ov||'',itemKey(item)].join('::')}
  function compute(session,item,ath,state,ov){if(item?.targetSeconds)return{status:'ok',seconds:Number(item.targetSeconds),sendOff:item.cycleSeconds||null,source:'Coach target'};const reason=suppress(item);if(reason)return{status:'none',reason};if(item?.raceIntent||item?.repInstructions?.some(x=>x.raceIntent))return E.RacePace.forItem(session,item,ath,state,ov);if(item?.zone||item?.repPattern?.length)return E.Aerobic.forItem(session,item,ath,state,ov);return{status:'none'}}
  function executableRows(target){if(!target)return[];if(target.status==='ok')return[target];return Array.isArray(target.rows)?target.rows.filter(r=>r?.status==='ok'||Number.isFinite(Number(r?.seconds))):[]}
  function targetConflict(target,item){const fallbackCycle=Number(item?.cycleSeconds)||0;for(const row of executableRows(target)){const seconds=Number(row?.seconds),sendOff=Number(row?.sendOff)||fallbackCycle;if(Number.isFinite(seconds)&&seconds>0&&sendOff>0&&seconds>sendOff)return{seconds,sendOff,rep:row?.rep||null,label:row?.label||''}}return null}
  function enforceExecutable(target,item){const conflict=targetConflict(target,item);if(!conflict)return target;return{status:'missing',message:'Adjust work/send-off · target exceeds cycle',conflict:'target_exceeds_sendoff',seconds:conflict.seconds,sendOff:conflict.sendOff,rep:conflict.rep,label:conflict.label,source:target?.source||'',originalTarget:target}}
  function referenceWork(target){const rows=executableRows(target).map(r=>Number(r.seconds)).filter(v=>Number.isFinite(v)&&v>0);return rows.length?Math.min(...rows):null}
  function policyPlan(item,target,ath,state){if(!E.TrainingPolicy)return null;const rows=executableRows(target),seconds=rows.length?Math.max(...rows.map(r=>Number(r.seconds)||0)):Number(target?.seconds)||0,ratio=Number(E.Modification?.profile?.(ath,state)?.ratio)||1;return E.TrainingPolicy.safeCycle({item,targetSeconds:seconds,referenceWorkSeconds:referenceWork(target),athlete:ath,volumeRatio:ratio})}
  function rewriteCycleText(value,oldCycle,newCycle){let s=String(value??'');const old=Number(oldCycle)||0,next=Number(newCycle)||0;if(!(old>0&&next>0&&old!==next))return s;const o=clock(old),n=clock(next),re=new RegExp(`((?:@|on)\\s*)${o.replace(':','[:.]')}(?!\\d)`,'ig');return s.replace(re,`$1${n}`)}
  function syncDerivedTiming(item,newCycle){const old=Number(item?.cycleSeconds)||0,next=Number(newCycle)||0;if(!(next>0))return item;const out={...item,cycleSeconds:next};if(old>0&&old!==next){out.raw=rewriteCycleText(item?.raw,old,next);out.text=rewriteCycleText(item?.text??item?.raw,old,next);if(Array.isArray(item?.cues))out.cues=item.cues.map(x=>rewriteCycleText(x,old,next));if(Array.isArray(item?.repInstructions))out.repInstructions=item.repInstructions.map(x=>({...x,label:rewriteCycleText(x?.label,old,next)}));if(Array.isArray(item?.repPattern))out.repPattern=item.repPattern.map(x=>({...x,text:rewriteCycleText(x?.text,old,next)}));if(Array.isArray(item?.pattern))out.pattern=item.pattern.map(x=>({...x,text:rewriteCycleText(x?.text,old,next)}));if(item?.repeatBreakdownCue)out.repeatBreakdownCue=rewriteCycleText(item.repeatBreakdownCue,old,next);}return out}
  function applyPolicy(item,target,ath,state){const plan=policyPlan(item,target,ath,state);if(!plan)return{item,target,plan:null};const timed=syncDerivedTiming(item,plan.cycleSeconds),nextItem={...timed,prescriptionTiming:{...plan,source:'TrainingPolicy'}};let nextTarget=target;if(target?.status==='ok')nextTarget={...target,sendOff:plan.cycleSeconds,prescriptionTiming:plan};else if(Array.isArray(target?.rows)){const ratio=Number(E.Modification?.profile?.(ath,state)?.ratio)||1,ref=referenceWork(target);nextTarget={...target,rows:target.rows.map(r=>{const sec=Number(r?.seconds);if(!(Number.isFinite(sec)&&sec>0))return r;const p=E.TrainingPolicy.safeCycle({item,targetSeconds:sec,referenceWorkSeconds:ref,athlete:ath,volumeRatio:ratio});return p?{...r,sendOff:p.cycleSeconds,prescriptionTiming:p}:r}),prescriptionTiming:plan};}return{item:nextItem,target:nextTarget,plan};}
  function targetForItem(session,item,ath,state){const intent=normalizeIntent(item),ov=overrideStroke(intent,ath,state,session),k=cacheKey(session,intent,ath,state,ov);if(cache.has(k))return cache.get(k);const contextual=resolvePrescriptionContext(session,intent,ath,state),raw=compute(session,contextual,ath,state,ov),planned=applyPolicy(contextual,raw,ath,state),out=enforceExecutable(planned.target,planned.item);cache.set(k,out);if(cache.size>1500){const first=cache.keys().next().value;cache.delete(first)}return out}
  function peekTarget(session,item,ath,state){const intent=normalizeIntent(item),ov=overrideStroke(intent,ath,state,session),k=cacheKey(session,intent,ath,state,ov);return cache.get(k)||null}
  function prescription(session,item,ath,state){const intent=normalizeIntent(item),contextual=resolvePrescriptionContext(session,intent,ath,state),modified=E.Modification.adaptItem(contextual,ath,state,session),rawTarget=compute(session,modified,ath,state,overrideStroke(modified,ath,state,session)),planned=applyPolicy(modified,rawTarget,ath,state),target=enforceExecutable(planned.target,planned.item);return{item:planned.item,target,athlete:ath,sessionId:session?.id,prescriptionTiming:planned.plan,evidence:{source:target?.source||'',status:target?.status||'none',conflict:target?.conflict||''}}}
  function clearCache(){cache.clear()}
  return{VERSION,targetForItem,peekTarget,prescription,normalizeIntent,overrideStroke,explicitStroke,needsContext,contextualStroke,resolvePrescriptionContext,suppress,targetConflict,enforceExecutable,applyPolicy,policyPlan,syncDerivedTiming,rewriteCycleText,clearCache};
});