'use strict';
(function(root,factory){const api=factory(root.MSOSEngines||{},root);if(typeof module==='object'&&module.exports)module.exports=api;else{root.MSOSEngines=root.MSOSEngines||{};root.MSOSEngines.Coordinator=api;}})(typeof globalThis!=='undefined'?globalThis:this,function(E,root){
  const VERSION='2.6.0-stroke-authority',text=v=>String(v??'').replace(/\s+/g,' ').trim();
  const cache=new Map();
  function overrideStroke(item,ath,state,session){if(!ath)return'';const ov=(state?.adaptationOverrides||[]).find(x=>x.sessionId===session?.id&&x.itemId===item?.id&&x.athleteId===ath?.id&&x.active!==false),s=ov?.patch?.stroke;return s||''}
  function normalStroke(value){const raw=text(value);if(!raw)return'';const via=E.Evidence?.stroke?.(raw)||raw;if(/^(?:Freestyle|Backstroke|Breaststroke|Butterfly|IM|Choice)$/i.test(via)){if(/^free/i.test(via))return'Freestyle';if(/^back/i.test(via))return'Backstroke';if(/^breast/i.test(via))return'Breaststroke';if(/^(?:butter|fly)/i.test(via))return'Butterfly';if(/^im$/i.test(via))return'IM';return'Choice'}return''}
  function explicitStroke(raw){const s=text(raw);if(/\b(?:free(?:style)?|fr)\s+kick\b/i.test(s))return'Freestyle';if(/\b(?:back(?:stroke)?|bk)\s+kick\b/i.test(s))return'Backstroke';if(/\b(?:breast(?:stroke)?|br)\s+kick\b/i.test(s))return'Breaststroke';if(/\b(?:fly|butterfly)\s+kick\b/i.test(s))return'Butterfly';if(/\b(?:im|medley)\s+kick\b/i.test(s))return'IM';return''}
  function needsContext(item){const raw=text(item?.raw||item?.text);return (/\bKick\b/i.test(raw)&&!explicitStroke(raw))||/#\s*1(?:\b|F\b)/i.test(raw)}
  function aerobicDefaultStroke(item){const explicit=normalStroke(item?.stroke);if(explicit)return'';const raw=text(item?.raw||item?.text);if(/\bChoice\b/i.test(raw))return'';const zones=[item?.zone,...(item?.repPattern||[]).map(x=>x?.zone)].map(text).filter(Boolean);return zones.some(z=>/^(?:Development|Overload|Threshold|Clearance)$/i.test(z))?'Freestyle':''}
  function contextualStroke(session,item,ath,state){const raw=text(item?.raw||item?.text),over=normalStroke(overrideStroke(item,ath,state,session));if(over)return over;const direct=normalStroke(item?.stroke);if(direct)return direct;const explicit=explicitStroke(raw);if(explicit)return explicit;if(!needsContext(item))return aerobicDefaultStroke(item);if(ath){try{const p=root.MSOS4?.performanceEngine?.selectStrokeForContext?.(ath,item,state,session,{formOnly:/#\s*1F\b/i.test(raw)});if(p?.stroke)return normalStroke(p.stroke)||p.stroke}catch{}}return aerobicDefaultStroke(item)||(ath?'Freestyle':'')}
  function resolveStroke(session,item,ath,state){if(!item)return'';const over=normalStroke(overrideStroke(item,ath,state,session));if(over)return over;const direct=normalStroke(item?.stroke);if(direct)return direct;const explicit=explicitStroke(item?.raw||item?.text);if(explicit)return explicit;if(needsContext(item))return contextualStroke(session,item,ath,state);return aerobicDefaultStroke(item)}
  function resolvePrescriptionContext(session,item,ath,state){if(!item)return item;const stroke=resolveStroke(session,item,ath,state);if(!stroke||stroke===item?.stroke)return item;const coach=!!normalStroke(overrideStroke(item,ath,state,session)),context=needsContext(item),kind=coach?'coach':context?'number-one':'aerobic-default';return{...item,stroke,strokeResolution:{kind,source:coach?'coach':context?'performance-context':'canonical-aerobic-default',stroke}}}
  function suppress(item){const raw=[item?.raw,item?.text,...(item?.cues||[])].filter(Boolean).join(' '),hasRace=!!item?.raceIntent||item?.repInstructions?.some(x=>x.raceIntent);if(hasRace)return'';if(/\bHR\s*Gauge\b/i.test(raw))return'HR Gauge';if(/^Choice$/i.test(text(item?.stroke))||/\bChoice\b/i.test(raw))return'Choice';if(/\b(?:Drill|Scull|Technique|Easy|Recovery|Reset|Warm\s*-?down|Cool\s*-?down|5HR|Kick|Underwater|Dive|Start|Finish|Max|Sprint)\b/i.test(raw)&&!item?.zone)return'Non-target work';return''}
  function itemKey(item){return [item?.id,item?.reps,item?.distance,item?.stroke,item?.zone,item?.restSeconds,item?.cycleSeconds,item?.raw,item?.text,JSON.stringify(item?.repPattern||[]),JSON.stringify(item?.repInstructions||[]),JSON.stringify(item?.raceIntent||null)].join('|')}
  function cacheKey(session,item,ath,state,ov){return [Number(state?.settings?.storageRevision||0),session?.id||'',ath?.id||'',ov||'',itemKey(item)].join('::')}
  function compute(session,item,ath,state,ov){if(item?.targetSeconds)return{status:'ok',seconds:Number(item.targetSeconds),sendOff:item.cycleSeconds||null,source:'Coach target'};const reason=suppress(item);if(reason)return{status:'none',reason};if(item?.raceIntent||item?.repInstructions?.some(x=>x.raceIntent))return E.RacePace.forItem(session,item,ath,state,ov);if(item?.zone||item?.repPattern?.length)return E.Aerobic.forItem(session,item,ath,state,ov);return{status:'none'}}
  function executableRows(target){if(!target)return[];if(target.status==='ok')return[target];return Array.isArray(target.rows)?target.rows.filter(r=>r?.status==='ok'||Number.isFinite(Number(r?.seconds))):[]}
  function targetConflict(target,item){const fallbackCycle=Number(item?.cycleSeconds)||0;for(const row of executableRows(target)){const seconds=Number(row?.seconds),sendOff=Number(row?.sendOff)||fallbackCycle;if(Number.isFinite(seconds)&&seconds>0&&sendOff>0&&seconds>sendOff)return{seconds,sendOff,rep:row?.rep||null,label:row?.label||''}}return null}
  function enforceExecutable(target,item){const conflict=targetConflict(target,item);if(!conflict)return target;return{status:'missing',message:'Adjust work/send-off · target exceeds cycle',conflict:'target_exceeds_sendoff',seconds:conflict.seconds,sendOff:conflict.sendOff,rep:conflict.rep,label:conflict.label,source:target?.source||'',originalTarget:target}}
  function targetForItem(session,item,ath,state){const contextual=resolvePrescriptionContext(session,item,ath,state),ov=overrideStroke(contextual,ath,state,session),k=cacheKey(session,contextual,ath,state,ov);if(cache.has(k))return cache.get(k);const out=enforceExecutable(compute(session,contextual,ath,state,ov),contextual);cache.set(k,out);if(cache.size>1500){const first=cache.keys().next().value;cache.delete(first)}return out}
  function peekTarget(session,item,ath,state){const contextual=resolvePrescriptionContext(session,item,ath,state),ov=overrideStroke(contextual,ath,state,session),k=cacheKey(session,contextual,ath,state,ov);return cache.get(k)||null}
  function prescription(session,item,ath,state){const contextual=resolvePrescriptionContext(session,item,ath,state),modified=E.Modification.adaptItem(contextual,ath,state,session),target=targetForItem(session,modified,ath,state);return{item:modified,target,athlete:ath,sessionId:session?.id,evidence:{source:target?.source||'',status:target?.status||'none',conflict:target?.conflict||''}}}
  function clearCache(){cache.clear()}
  return{VERSION,targetForItem,peekTarget,prescription,overrideStroke,normalStroke,explicitStroke,needsContext,aerobicDefaultStroke,contextualStroke,resolveStroke,resolvePrescriptionContext,suppress,targetConflict,enforceExecutable,clearCache};
});
