'use strict';
(function(g){
  const M=g.MSOS4;if(!M?.dosageEngine||!M?.util)return;
  const D=M.dosageEngine,U=M.util,X=M.dosageUI={build:'v4-dosage-ui-20260825a'};
  const esc=v=>U.escape?U.escape(String(v??'')):String(v??'');
  const num=v=>Math.round(Number(v)||0).toLocaleString();
  const pct=v=>`${Math.round(Number(v)||0)}%`;
  const shortStroke=s=>String(s||'').replace('Freestyle','Fr').replace('Backstroke','Bk').replace('Breaststroke','Br').replace('Butterfly','Fly').replace('Choice / unspecified','Choice');
  function rows(map,kind='system'){
    const list=D.top(map,'pctDose',kind==='system'?6:6);if(!list.length)return'<p class="muted">No classified dose yet.</p>';
    return`<div class="summary-grid">${list.map(r=>`<span>${esc(kind==='stroke'?shortStroke(r.label):r.label)}</span><b>${pct(r.pctDose)} · ${num(r.metres)}m · ${num(r.units)}u</b>`).join('')}</div>`;
  }
  function method(d){const unknown=Number(d?.unclassifiedMetres)||0;return`<p class="muted">Confirmed ${esc(d?.delivery||'dose')} · raw metres stay visible beside weighted stimulus. ${unknown?`${num(unknown)}m remains unclassified rather than being given a made-up system. `:''}Weighting is provisional and auditable: REG .25 · DEV .45 · OL .70 · THR .85 · CL/RP 1.00 · Sprint/Max 1.10 · technical .70.</p>`;}
  function sessionCard(){
    const s=M.currentSession?.();if(!s)return'';const scope=D.scopeSummary(s,M.state,{delivered:!!s.finish}),d=scope.session,label=s.finish?'DELIVERED DOSAGE':'PRESCRIBED DOSAGE';
    const people=scope.individual.length?`<details><summary>Individual / squad / team load</summary><div class="report-table">${scope.individual.map(r=>{const top=D.top(r.dose.systems,'pctDose',1)[0],st=D.top(r.dose.strokes,'pctDose',1)[0];return`<div class="report-row"><span><b>${esc(r.name)}</b><small>${esc(r.squad)} · ${esc(r.status)}</small></span><span><b>${num(r.dose.rawMetres)}m · ${num(r.dose.stimulusUnits)}u</b><small>${esc(top?.label||'Unclassified')} ${pct(top?.pctDose||0)} · ${esc(shortStroke(st?.label||'Choice'))} ${pct(st?.pctDose||0)}</small></span></div>`;}).join('')}</div>${Object.entries(scope.squad).map(([name,v])=>`<p><b>${esc(name)}</b> · ${v.swimmers} swimmer${v.swimmers===1?'':'s'} · ${num(v.dose.rawMetres)} person-metres · ${num(v.dose.stimulusUnits)} stimulus units</p>`).join('')}<p><b>Team present</b> · ${scope.team.swimmers} swimmer${scope.team.swimmers===1?'':'s'} · ${num(scope.team.dose.rawMetres)} person-metres · ${num(scope.team.dose.stimulusUnits)} stimulus units</p></details>`:'';
    return`<section class="page-card" data-msos-dosage="hub"><div class="eyebrow">${label}</div><h2>Energy-system stimulus / stroke dose</h2><div class="perf-kpis"><div><span>${s.finish?'Delivered':'Planned'}</span><b>${num(d.rawMetres)}m</b></div><div><span>Weighted stimulus</span><b>${num(d.stimulusUnits)}u</b></div><div><span>Classified</span><b>${pct(d.rawMetres?100-(d.unclassifiedMetres/d.rawMetres*100):0)}</b></div></div><div class="perf-two"><div><h3>Energy-system stimulus</h3>${rows(d.systems,'system')}</div><div><h3>Weighted stroke focus</h3>${rows(d.strokes,'stroke')}</div></div>${people}${method({...d,delivery:s.finish?'delivered':'prescribed'})}</section>`;
  }
  function paintHub(){const h=document.querySelector('#hubView');if(!h||M.state?.settings?.view!=='hub'||h.querySelector('[data-msos-dosage="hub"]'))return;const anchor=h.querySelector('.loop-intelligence')||h.querySelector('.page-card:last-of-type');const html=sessionCard();if(!html)return;if(anchor)anchor.insertAdjacentHTML('afterend',html);else h.insertAdjacentHTML('beforeend',html);}
  function reportSpec(){const role=M.access?.role?.()||'owner',scope=role==='swimmer'?'swimmer':(M.state.settings.reportScope||'squad'),days=M.state.settings.reportDays===undefined?7:Number(M.state.settings.reportDays),course=M.state.settings.reportCourse||M.state.settings.pathwayCourse||'SCM';return{scope,days,course,squad:scope==='squad'?(M.state.settings.reportSquad||''):'',athleteId:scope==='swimmer'?(role==='swimmer'?M.state.settings.activeUserAthleteId:(M.state.settings.reportAthleteId||M.state.settings.selectedAthleteId||'')):''};}
  function paintReports(){
    const h=document.querySelector('#reportsView'),out=h?.querySelector('#reportOutput');if(!h||!out||M.state?.settings?.view!=='reports'||out.querySelector('[data-msos-dosage="report"]'))return;const check=h.querySelector('[data-report-metric][value="dosage"]');if(check&&!check.checked)return;const report=M.reportingEngine?.run?.(reportSpec(),M.state);if(!report)return;const doses=report.rows.map(r=>r.extras?.dosage).filter(Boolean),d=D.merge(doses);
    const detail=report.rows.length?`<div class="report-table">${report.rows.map(r=>{const x=r.extras?.dosage||D.merge([]),sys=D.top(x.systems,'pctDose',1)[0],st=D.top(x.strokes,'pctDose',1)[0];return`<button class="report-row" data-dose-ath="${esc(r.athleteId)}"><span><b>${esc(r.name)}</b><small>${esc(r.squad)}</small></span><span><b>${num(x.rawMetres)}m · ${num(x.stimulusUnits)}u</b><small>${esc(sys?.label||'Unclassified')} ${pct(sys?.pctDose||0)} · ${esc(shortStroke(st?.label||'Choice'))} ${pct(st?.pctDose||0)}</small></span></button>`;}).join('')}</div>`:'<p class="muted">No delivered swimmer dose in this window.</p>';
    out.insertAdjacentHTML('afterbegin',`<section class="page-card" data-msos-dosage="report"><h2>Energy-system / dosage · ${report.spec.days||'all'} day${report.spec.days===1?'':'s'}</h2><div class="perf-two"><div><h3>Energy-system stimulus</h3>${rows(d.systems,'system')}</div><div><h3>Weighted stroke focus</h3>${rows(d.strokes,'stroke')}</div></div>${detail}${method({...d,delivery:'confirmed delivered training'})}</section>`);out.querySelectorAll('[data-dose-ath]').forEach(b=>b.onclick=()=>{M.state.settings.selectedAthleteId=b.dataset.doseAth;M.storageEngine?.saveUi?.(M.state);M.nav?.show?.('athletes',{restoreScroll:false});});
  }
  function athleteCard(a,days){const d=D.athleteWindow(a,M.state,days);return`<div><h3>${days} days · ${d.sessions} finished session${d.sessions===1?'':'s'}</h3><div class="perf-two"><div>${rows(d.systems,'system')}</div><div>${rows(d.strokes,'stroke')}</div></div><p class="muted">${num(d.rawMetres)}m confirmed · ${num(d.stimulusUnits)} weighted stimulus units</p></div>`;}
  function paintAthlete(){const h=document.querySelector('#athletesView');if(!h||M.state?.settings?.view!=='athletes'||h.querySelector('[data-msos-dosage="athlete"]'))return;const id=M.state.settings.selectedAthleteId,a=(M.state.athletes||[]).find(x=>String(x.id)===String(id));if(!a)return;h.insertAdjacentHTML('beforeend',`<section class="page-card" data-msos-dosage="athlete"><div class="eyebrow">TRAINING EXPOSURE</div><h2>${esc(a.full_name)} · dosage / stroke balance</h2>${athleteCard(a,7)}${athleteCard(a,28)}<p class="muted">Exposure can support a coaching explanation; it does not prove causation. Low stroke dose is surfaced as a possible contributor, not “the reason” for performance change.</p></section>`);}
  function paint(){paintHub();paintReports();paintAthlete();}
  let painting=false;const schedule=()=>{if(painting)return;painting=true;requestAnimationFrame(()=>{try{paint()}finally{painting=false;}});};
  const boot=()=>{const root=document.querySelector('#appMain');if(root)new MutationObserver(schedule).observe(root,{childList:true,subtree:true});schedule();};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
  addEventListener('msos:data-updated',schedule);X.paint=paint;X.sessionCard=sessionCard;
})(globalThis);
