'use strict';
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else{root.MSOSEngines=root.MSOSEngines||{};root.MSOSEngines.Evidence=api;}})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const VERSION='2.0.0';
  const STORAGE_KEY='mclay_swimming_os_v4',LEGACY_KEY='mclay_swimming_os_v1',REF_DB='mclay_swimming_v4_reference_cache',LEGACY_REF_DB='mclay_swimming_v374_heavy_cache';
  const text=v=>String(v??'').replace(/\s+/g,' ').trim(), key=v=>text(v).toLowerCase().replace(/[^a-z0-9]+/g,'');
  const stroke=v=>{const s=text(v).toLowerCase();if(/^(free|freestyle|fr)$/.test(s))return'Freestyle';if(/^(back|backstroke|bk)$/.test(s))return'Backstroke';if(/^(breast|breaststroke|br)$/.test(s))return'Breaststroke';if(/^(fly|butterfly)$/.test(s))return'Butterfly';if(/^(im|medley|individual medley)$/.test(s))return'IM';return text(v)};
  const seconds=r=>Number(r?.result_seconds??r?.time_seconds??r?.seconds??r?.result_time_seconds??r?.pb_seconds??r?.best_time_seconds);
  const course=r=>text(r?.pool_course||r?.course).toUpperCase(),distance=r=>Number(r?.distance||r?.event_distance),rowStroke=r=>stroke(r?.stroke||r?.event_stroke||'');
  const rowName=r=>r?.full_name||r?.athlete_name||r?.swimmer_name||r?.match_name||r?.source_swimmer_name||r?.name||'';
  const points=r=>Number(r?.wa_points??r?.world_aquatics_points??r?.world_para_points??r?.para_points??r?.fina_points??r?.points??r?.point_score);
  const merge=(a=[],b=[])=>{const m=new Map();for(const x of [...(a||[]),...(b||[])]){if(!x)continue;const id=x.id||JSON.stringify([x.athlete_id,x.test_type_id,x.result_date,x.distance,x.stroke,seconds(x),rowName(x)]);m.set(id,x)}return[...m.values()]};
  function blank(){return{athletes:[],trainingTestTypes:[],trainingTestResults:[],adaptationProfiles:[],adaptationOverrides:[],coachResults:[],resultsEventHistory:[],resultsPbBoard:[],courseConversions:[],worldAquaticsBaseTimes:[],_refs:{}}}
  function readDb(name){return new Promise(resolve=>{try{const req=indexedDB.open(name);req.onerror=()=>resolve(null);req.onupgradeneeded=()=>{try{req.transaction.abort()}catch{}resolve(null)};req.onsuccess=()=>{const db=req.result;if(!db.objectStoreNames.contains('state')){db.close();resolve(null);return}const q=db.transaction('state','readonly').objectStore('state').get('latest');q.onerror=()=>{db.close();resolve(null)};q.onsuccess=()=>{const row=q.result||null;db.close();resolve(row?.payload||null)}}}catch{resolve(null)}})}
  async function hydrate(baseState={}){let out={...blank(),...(baseState||{})};try{const x=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');if(x)out={...out,...x}}catch{}try{const l=JSON.parse(localStorage.getItem(LEGACY_KEY)||'null');if(l){out.athletes=merge(out.athletes,l.athletes);out.trainingTestTypes=merge(out.trainingTestTypes||out.training_test_types,l.training_test_types);out.trainingTestResults=merge(out.trainingTestResults||out.training_test_results,l.training_test_results);out.adaptationProfiles=merge(out.adaptationProfiles||out.athlete_adaptation_profiles,l.athlete_adaptation_profiles);out.coachResults=merge(out.coachResults||out.coach_results,l.coach_results)}}catch{}
    let refs=await readDb(REF_DB);if(!refs)refs=await readDb(LEGACY_REF_DB);refs=refs||{};out._refs=refs;
    out.trainingTestTypes=merge(out.trainingTestTypes,refs.training_test_types);out.trainingTestResults=merge(out.trainingTestResults,refs.training_test_results);out.adaptationProfiles=merge(out.adaptationProfiles,refs.athlete_adaptation_profiles);out.coachResults=merge(out.coachResults,refs.coach_results);out.resultsEventHistory=merge(out.resultsEventHistory,refs.results_event_history);out.resultsPbBoard=merge(out.resultsPbBoard,refs.results_pb_board);out.courseConversions=merge(out.courseConversions,refs.xlr8_course_conversions);out.worldAquaticsBaseTimes=merge(out.worldAquaticsBaseTimes,refs.world_aquatics_base_times);return out}
  function athleteAliases(ath,state){const ids=new Set(ath?.id?[ath.id]:[]),n=key(ath?.full_name);for(const a of state?.athletes||[])if(n&&key(a?.full_name)===n&&a?.id)ids.add(a.id);return ids}
  function sameAthlete(row,ath,state){const ids=athleteAliases(ath,state);return ids.has(row?.athlete_id)||(key(rowName(row))&&key(rowName(row))===key(ath?.full_name))}
  function pbRows(ath,state){return[...(state?.resultsPbBoard||state?.results_pb_board||[]),...(state?.resultsEventHistory||state?.results_event_history||[]),...(state?.coachResults||state?.coach_results||[])].filter(r=>sameAthlete(r,ath,state)&&Number.isFinite(seconds(r))&&seconds(r)>0)}
  function typeText(state,row){const types=state?.trainingTestTypes||state?.training_test_types||[],type=types.find(x=>x.id===row?.test_type_id)||{};return[type.test_key,type.name,type.label,type.test_name,row?.test_key,row?.name,row?.label,row?.test_name,row?.source_label,row?.metadata?.test_key,row?.metadata?.test_name].map(text).filter(Boolean).join(' ')}
  function isT400(state,row){const k=typeText(state,row).toLowerCase().replace(/[_-]+/g,' ');return /\bt\s*400\b/.test(k)||/\b400\s*m?\s*(?:time\s*trial|tt)\b/.test(k)}
  function t400Stroke(state,row){if(!isT400(state,row))return'';const explicit=text(row?.stroke||row?.event_stroke||row?.metadata?.stroke);if(explicit)return stroke(explicit);const k=typeText(state,row).toLowerCase();if(/back/.test(k))return'Backstroke';if(/breast/.test(k))return'Breaststroke';if(/(?:fly|butterfly)/.test(k))return'Butterfly';if(/(?:^|[_\s-])im(?:$|[_\s-])|medley/.test(k))return'IM';return'Freestyle'}
  function t400Rows(ath,state,wantedStroke='Freestyle'){const wanted=stroke(wantedStroke);return(state?.trainingTestResults||state?.training_test_results||[]).filter(r=>sameAthlete(r,ath,state)&&isT400(state,r)&&t400Stroke(state,r)===wanted&&r.valid_for_anchor!==false&&Number.isFinite(seconds(r))&&seconds(r)>0).sort((a,b)=>seconds(a)-seconds(b)||String(b.result_date||'').localeCompare(String(a.result_date||'')))}
  return{VERSION,hydrate,merge,key,text,stroke,seconds,course,distance,rowStroke,rowName,points,athleteAliases,sameAthlete,pbRows,t400Rows,t400Stroke,isT400};
});