'use strict';
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else{root.MSOSEngines=root.MSOSEngines||{};root.MSOSEngines.Evidence=api;}})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const VERSION='2.4.2-current-t400';
  const STORAGE_KEY='mclay_swimming_os_v4',LEGACY_KEY='mclay_swimming_os_v1',REF_DB='mclay_swimming_v4_reference_cache',LEGACY_REF_DB='mclay_swimming_v374_heavy_cache';
  const VERIFIED_T400=[{name:'Conor Fischer',stroke:'Breaststroke',seconds:545.2,source_label:'Coach-confirmed Breaststroke T400'}];
  const text=v=>String(v??'').replace(/\s+/g,' ').trim(),key=v=>text(v).toLowerCase().replace(/[^a-z0-9]+/g,'');
  const nameTokens=v=>text(v).toLowerCase().replace(/[-_]+/g,' ').replace(/[^a-z0-9 ]+/g,' ').split(/\s+/).filter(Boolean);
  const sameName=(a,b)=>{if(!a||!b)return false;if(key(a)===key(b))return true;const x=nameTokens(a),y=nameTokens(b);if(x.length<2||y.length<2)return false;return x[0]===y[0]&&x.at(-1)===y.at(-1);};
  const stroke=v=>{const s=text(v).toLowerCase();if(/^(free|freestyle|fr)$/.test(s))return'Freestyle';if(/^(back|backstroke|bk)$/.test(s))return'Backstroke';if(/^(breast|breaststroke|br)$/.test(s))return'Breaststroke';if(/^(fly|butterfly)$/.test(s))return'Butterfly';if(/^(im|medley|individual medley)$/.test(s))return'IM';if(/^choice$/.test(s))return'Choice';return text(v);};
  const seconds=r=>Number(r?.result_seconds??r?.time_seconds??r?.seconds??r?.result_time_seconds??r?.pb_seconds??r?.best_time_seconds);
  const course=r=>text(r?.pool_course||r?.course).toUpperCase(),distance=r=>Number(r?.distance||r?.event_distance),rowStroke=r=>stroke(r?.stroke||r?.event_stroke||'');
  const rowName=r=>r?.full_name||r?.athlete_name||r?.swimmer_name||r?.match_name||r?.source_swimmer_name||r?.name||'';
  const points=r=>Number(r?.wa_points??r?.world_aquatics_points??r?.world_para_points??r?.para_points??r?.fina_points??r?.points??r?.point_score);
  const merge=(a=[],b=[])=>{const m=new Map();for(const x of [...(a||[]),...(b||[])]){if(!x)continue;const id=x.id||JSON.stringify([x.athlete_id,x.test_type_id,x.result_date,x.distance,x.stroke,seconds(x),rowName(x)]);const old=m.get(id);m.set(id,old?{...old,...x}:x);}return[...m.values()];};
  function blank(){return{athletes:[],trainingTestTypes:[],trainingTestResults:[],adaptationProfiles:[],adaptationOverrides:[],coachResults:[],resultsEventHistory:[],resultsPbBoard:[],courseConversions:[],worldAquaticsBaseTimes:[],_refs:{}};}
  function readDb(name){return new Promise(resolve=>{try{const req=indexedDB.open(name);req.onerror=()=>resolve(null);req.onupgradeneeded=()=>{try{req.transaction.abort();}catch{}resolve(null);};req.onsuccess=()=>{const db=req.result;if(!db.objectStoreNames.contains('state')){db.close();resolve(null);return;}const q=db.transaction('state','readonly').objectStore('state').get('latest');q.onerror=()=>{db.close();resolve(null);};q.onsuccess=()=>{const row=q.result||null;db.close();resolve(row?.payload||null);};};}catch{resolve(null);}});}
  function aliasNames(ath){const out=new Set();for(const v of [ath?.full_name,ath?.display_name,ath?.preferred_name,ath?.match_name])if(v)out.add(text(v));for(const list of [ath?.aliases,ath?.match_names,ath?.matchNames]){if(Array.isArray(list))for(const v of list)if(v)out.add(text(v));else if(typeof list==='string')for(const v of list.split(/\s*\|\s*/))if(v)out.add(text(v));}return out;}
  function athleteAliases(ath,state){const ids=new Set();for(const v of [ath?.id,ath?.athlete_id,ath?.legacy_id,ath?.legacy_athlete_id,ath?.source_id,ath?.membership_number])if(v)ids.add(v);const names=aliasNames(ath);for(const a of state?.athletes||[]){const matched=[...names].some(n=>[...aliasNames(a)].some(m=>sameName(n,m)));if(!matched)continue;for(const v of [a?.id,a?.athlete_id,a?.legacy_id,a?.legacy_athlete_id,a?.source_id,a?.membership_number])if(v)ids.add(v);}return ids;}
  function identityFor(ath,state){const ids=athleteAliases(ath,state),names=aliasNames(ath),nameKeys=new Set([...names].map(key));return{ids,names,nameKeys};}
  function sameAthleteWithIdentity(row,identity){if(identity.ids.has(row?.athlete_id)||identity.ids.has(row?.swimmer_id)||identity.ids.has(row?.athleteId)||identity.ids.has(row?.membership_number))return true;const rn=rowName(row);if(rn&&(identity.nameKeys.has(key(rn))||[...identity.names].some(n=>sameName(rn,n))))return true;for(const n of row?.match_names||row?.aliases||[])if(identity.nameKeys.has(key(n))||[...identity.names].some(a=>sameName(n,a)))return true;return false;}
  function sameAthlete(row,ath,state){return sameAthleteWithIdentity(row,identityFor(ath,state));}
  function typeText(state,row){const types=state?.trainingTestTypes||state?.training_test_types||[],type=types.find(x=>x.id===row?.test_type_id)||{};return[type.test_key,type.name,type.label,type.test_name,type.test_type,row?.test_key,row?.name,row?.label,row?.test_name,row?.test_type,row?.source_label,row?.notes,row?.metadata?.test_key,row?.metadata?.test_name,row?.metadata?.test_type].map(text).filter(Boolean).join(' ');}
  function isT400(state,row){const k=typeText(state,row).toLowerCase().replace(/[_-]+/g,' ');return /\bt\s*400\b/.test(k)||/\btime\s*400\b/.test(k)||/\b400\s*m?\s*(?:time\s*trial|tt|test)\b/.test(k)||Number(row?.distance||row?.test_distance)===400&&/training|test/i.test(text(row?.source_type||row?.source||row?.source_label));}
  function t400Stroke(state,row){if(!isT400(state,row))return'';const explicit=text(row?.stroke||row?.event_stroke||row?.metadata?.stroke);if(explicit)return stroke(explicit);const k=typeText(state,row).toLowerCase();if(/back/.test(k))return'Backstroke';if(/breast/.test(k))return'Breaststroke';if(/(?:fly|butterfly)/.test(k))return'Butterfly';if(/(?:^|[_\s-])im(?:$|[_\s-])|medley/.test(k))return'IM';return'Freestyle';}
  function ensureVerified(state){state.trainingTestTypes=state.trainingTestTypes||state.training_test_types||[];state.trainingTestResults=state.trainingTestResults||state.training_test_results||[];for(const v of VERIFIED_T400){const ath=(state.athletes||[]).find(a=>sameName(a?.full_name,v.name));if(!ath)continue;const typeId=`verified-t400-${key(v.stroke)}`;if(!state.trainingTestTypes.some(x=>x.id===typeId))state.trainingTestTypes.push({id:typeId,test_key:`T400 ${v.stroke}`,name:`T400 ${v.stroke}`});const ident=identityFor(ath,state),exists=state.trainingTestResults.some(r=>sameAthleteWithIdentity(r,ident)&&isT400(state,r)&&t400Stroke(state,r)===stroke(v.stroke)&&Math.abs(seconds(r)-v.seconds)<.01);if(!exists)state.trainingTestResults.push({id:`verified-${key(v.name)}-${key(v.stroke)}-${String(v.seconds).replace('.','_')}`,athlete_id:ath.id,test_type_id:typeId,result_seconds:v.seconds,stroke:stroke(v.stroke),distance:400,valid_for_anchor:true,source:'coach_verified_fallback',source_type:'training_test',source_label:v.source_label});}}
  async function hydrate(baseState={}){let out={...blank(),...(baseState||{})};try{const x=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');if(x)out={...out,...x};}catch{}try{const l=JSON.parse(localStorage.getItem(LEGACY_KEY)||'null');if(l){out.athletes=merge(out.athletes,l.athletes);out.trainingTestTypes=merge(out.trainingTestTypes||out.training_test_types,l.training_test_types);out.trainingTestResults=merge(out.trainingTestResults||out.training_test_results,l.training_test_results);out.adaptationProfiles=merge(out.adaptationProfiles||out.athlete_adaptation_profiles,l.athlete_adaptation_profiles);out.coachResults=merge(out.coachResults||out.coach_results,l.coach_results);out.resultsEventHistory=merge(out.resultsEventHistory,l.results_event_history);out.resultsPbBoard=merge(out.resultsPbBoard,l.results_pb_board);}}catch{}let refs=await readDb(REF_DB);if(!refs)refs=await readDb(LEGACY_REF_DB);refs=refs||{};out._refs=refs;out.athletes=merge(out.athletes,refs.athletes);out.trainingTestTypes=merge(out.trainingTestTypes,refs.training_test_types);out.trainingTestResults=merge(out.trainingTestResults,refs.training_test_results);out.adaptationProfiles=merge(out.adaptationProfiles,refs.athlete_adaptation_profiles);out.coachResults=merge(out.coachResults,refs.coach_results);out.resultsEventHistory=merge(out.resultsEventHistory,refs.results_event_history);out.resultsPbBoard=merge(out.resultsPbBoard,refs.results_pb_board);out.courseConversions=merge(out.courseConversions,refs.xlr8_course_conversions);out.worldAquaticsBaseTimes=merge(out.worldAquaticsBaseTimes,refs.world_aquatics_base_times);ensureVerified(out);return out;}
  function pbRows(ath,state){const refs=state?._refs||{},ident=identityFor(ath,state),rows=[...(state?.resultsPbBoard||state?.results_pb_board||[]),...(state?.resultsEventHistory||state?.results_event_history||[]),...(state?.coachResults||state?.coach_results||[]),...(refs.results_pb_board||[]),...(refs.results_event_history||[]),...(refs.coach_results||[])];return rows.filter(r=>sameAthleteWithIdentity(r,ident)&&Number.isFinite(seconds(r))&&seconds(r)>0);}
  function resultDateMs(row){for(const v of [row?.result_date,row?.test_date,row?.performed_at,row?.date,row?.created_at]){if(!v)continue;const ms=Date.parse(v);if(Number.isFinite(ms))return ms;}return null;}
  function t400Rows(ath,state,wantedStroke='Freestyle'){const wanted=stroke(wantedStroke),refs=state?._refs||{},rows=[...(state?.trainingTestResults||state?.training_test_results||[]),...(refs.training_test_results||[])],ident=identityFor(ath,state);return rows.filter(r=>sameAthleteWithIdentity(r,ident)&&isT400(state,r)&&t400Stroke(state,r)===wanted&&r.valid_for_anchor!==false&&Number.isFinite(seconds(r))&&seconds(r)>0).sort((a,b)=>{const ad=resultDateMs(a),bd=resultDateMs(b);if(ad!=null||bd!=null){if(ad==null)return 1;if(bd==null)return-1;if(ad!==bd)return bd-ad;}return seconds(a)-seconds(b);});}
  return{VERSION,hydrate,merge,key,text,nameTokens,sameName,stroke,seconds,course,distance,rowStroke,rowName,points,athleteAliases,sameAthlete,pbRows,t400Rows,t400Stroke,isT400,ensureVerified,resultDateMs};
});