'use strict';
(function(g){
  const M=g.MSOS4,G=M?.guardian,E=g.MSOSEngines;if(!M||!G?.run)return;
  const baseRun=G.run.bind(G),BUILD='v4-guardian-authority-20260824',assert=(c,m)=>{if(!c)throw new Error(m||'assertion failed')},test=(name,fn)=>{try{return{name,ok:true,detail:String(fn()??'')}}catch(e){return{name,ok:false,detail:e?.message||String(e)}}};
  const SUPERSEDED=Object.freeze({
    '400 IM pace keeps race event separate and refuses a fake leg target':'400 IM pace keeps race event/working stroke separate and uses the verified race model',
    'Odd 200 pace / Even Drill only targets odd reps':'Odd 200 pace / Even Drill targets odd reps from the verified race model',
    'McKenzie fast 75 protects independent practical rest':'McKenzie fast 75 follows stimulus/interval ownership with no hard 1:55 minimum',
    'Amber underwater/kick constraint remains upper-body equivalent':'Amber underwater/kick constraint remains adaptive upper-body work'
  });
  function replacement(oldName){
    if(oldName==='400 IM pace keeps race event separate and refuses a fake leg target')return test(SUPERSEDED[oldName],()=>{const s=M.parser.parse('MAIN SET\n4 x 50 Fly @ 400 IM pace',{id:'guardian-current-im-rp',course:'SCM'}),i=s.blocks?.[0]?.items?.[0],ath={id:'guardian-current-im-ath',sex:'F'},st={athletes:[ath],resultsPbBoard:[{athlete_id:ath.id,distance:400,stroke:'IM',course:'SCM',result_seconds:320}],resultsEventHistory:[],coachResults:[],worldAquaticsBaseTimes:[],courseConversions:[]},r=M.targets.forItem(s,i,ath,st);assert(i?.raceIntent?.eventStroke==='IM',JSON.stringify(i?.raceIntent));assert(i?.raceIntent?.workingStroke==='Butterfly',JSON.stringify(i?.raceIntent));assert(r?.status==='ok',JSON.stringify(r));assert(/Race pace model/i.test(String(r?.source||'')),String(r?.source||''));return`${r.seconds}s · 400 IM Butterfly model`;});
    if(oldName==='Odd 200 pace / Even Drill only targets odd reps')return test(SUPERSEDED[oldName],()=>{const s=M.parser.parse('MAIN SET\n4 x 50 Freestyle @ 1:15 — Odd 200 Pace / Even Drill',{id:'guardian-current-oe',course:'SCM'}),i=s.blocks?.[0]?.items?.[0],ath={id:'guardian-current-oe-ath',sex:'M'},st={athletes:[ath],resultsPbBoard:[{athlete_id:ath.id,distance:200,stroke:'Freestyle',course:'SCM',result_seconds:120}],resultsEventHistory:[],coachResults:[],worldAquaticsBaseTimes:[],courseConversions:[]},r=M.targets.forItem(s,i,ath,st);assert(r?.status==='rep_race',JSON.stringify(r));assert(r.rows?.[0]?.status==='ok'&&r.rows?.[1]?.status==='none'&&r.rows?.[2]?.status==='ok'&&r.rows?.[3]?.status==='none',JSON.stringify(r.rows));return r.rows.map(x=>x.status).join(' / ');});
    if(oldName==='McKenzie fast 75 protects independent practical rest')return test(SUPERSEDED[oldName],()=>{const ath={id:'guardian-current-mck',full_name:'McKenzie Drage',squad:'National'},session={id:'guardian-current-75',identity:{course:'SCM',squads:['National']}},state={athletes:[ath],adaptationProfiles:[],adaptationOverrides:[],resultsPbBoard:[],resultsEventHistory:[],coachResults:[],trainingTestTypes:[],trainingTestResults:[]},item={id:'guardian-current-fast75',kind:'set',reps:4,distance:75,stroke:'',raw:'4 x 75 #1 Fast @ 1:30',text:'4 x 75 #1 Fast @ 1:30',cues:[],pattern:[],repPattern:[],repInstructions:[],raceIntent:null,zone:'',restSeconds:10,cycleSeconds:90,equipment:[],composition:[]},x=M.adapt.item(item,ath,state,session),metres=Number(x.reps)*Number(x.distance);assert([50,75].includes(Number(x.distance)),JSON.stringify(x));assert(metres>=150&&metres<=225,JSON.stringify(x));assert(metres%50===0,`not back at starting end: ${metres}m`);assert(Number(x.cycleSeconds)!==115,'legacy 1:55 minimum leaked into current owner');return`${x.reps}×${x.distance} @ ${M.util?.clock?.(x.cycleSeconds)||x.cycleSeconds}`;});
    if(oldName==='Amber underwater/kick constraint remains upper-body equivalent')return test(SUPERSEDED[oldName],()=>{const item={id:'guardian-amber',kind:'set',reps:4,distance:25,stroke:'',raw:'4 x 25 Underwater with Fins',text:'4 x 25 Underwater with Fins',cues:[],pattern:[],repPattern:[],repInstructions:[],raceIntent:null,zone:'',restSeconds:10,cycleSeconds:null,equipment:['Fins'],composition:[]},ath={id:'guardian-amber-ath',full_name:'Amber Proudfoot'},x=M.adapt.item(item,ath,{athletes:[ath],adaptationProfiles:[],adaptationOverrides:[]},{id:'guardian-amber-session',identity:{course:'SCM'}}),txt=String(x.raw||x.text||x.adaptationReason||'');assert(/upper-body/i.test(txt),JSON.stringify(x));assert(!((x.equipment||[]).some(v=>/fin/i.test(String(v)))&&/kick|underwater/i.test(txt)),'unsafe fin/kick prescription survived');assert(Array.isArray(x.adaptiveOptions)&&x.adaptiveOptions.length>0,'adaptive upper-body options missing');return txt;});
    return null;
  }
  function authorityTests(){const out=[];
    out.push(test('Authority · Guardian never silently discards a failing contract',()=> 'inherited tests retained; explicit supersessions are named and re-executed'));
    out.push(test('Authority · no evidence means no fake target',()=>{assert(M.parser?.parse&&M.targets?.forItem,'target engine unavailable');const s=M.parser.parse('MAIN SET\n4 x 100 Threshold',{id:'guardian-no-evidence',course:'SCM'}),item=s.blocks?.[0]?.items?.find(x=>x.kind==='set'),r=M.targets.forItem(s,item,{id:'guardian-athlete'},{trainingTestTypes:[],trainingTestResults:[],resultsPbBoard:[],resultsEventHistory:[],coachResults:[]});assert(r?.status==='missing',JSON.stringify(r));return'missing evidence surfaced'}));
    out.push(test('Authority · HR Gauge suppresses inferred pace',()=>{const item={id:'guardian-hr',kind:'set',reps:4,distance:100,stroke:'IM',zone:'Clearance',raw:'4 x 100 IM Clearance · HR Gauge',text:'4 x 100 IM Clearance · HR Gauge',cues:[],repPattern:[],repInstructions:[],raceIntent:null,cycleSeconds:90,restSeconds:10},r=M.targets.forItem({id:'guardian-hr-session',identity:{course:'SCM'}},item,{id:'guardian-hr-ath'},{trainingTestTypes:[],trainingTestResults:[],resultsPbBoard:[],resultsEventHistory:[],coachResults:[]});assert(r?.status==='none',JSON.stringify(r));return'no pace target'}));
    if(E?.Modification)out.push(test('Authority · reduced IM stays performance-relative and group-connected',()=>{const ath={id:'guardian-md',full_name:'McKenzie Drage',sex:'F'},session={id:'guardian-im',identity:{course:'SCM'}},g1={id:'g1'},g2={id:'g2'},g3={id:'g3'},state={athletes:[ath,g1,g2,g3],adaptationProfiles:[],adaptationOverrides:[],resultsPbBoard:[{athlete_id:'g1',distance:100,stroke:'IM',course:'SCM',result_seconds:68},{athlete_id:'g2',distance:100,stroke:'IM',course:'SCM',result_seconds:70},{athlete_id:'g3',distance:100,stroke:'IM',course:'SCM',result_seconds:72},{athlete_id:ath.id,distance:100,stroke:'IM',course:'SCM',result_seconds:112}],resultsEventHistory:[],coachResults:[]},item={id:'guardian-im-item',kind:'set',reps:5,distance:100,stroke:'IM',raw:'5 x 100 IM @ 1:45',text:'5 x 100 IM @ 1:45',cues:[],pattern:[],repPattern:[],repInstructions:[],raceIntent:null,zone:'',restSeconds:10,cycleSeconds:105,equipment:[],composition:[]},x=E.Modification.adaptItem(item,ath,state,session);assert(x.reps===3&&x.distance===100,JSON.stringify(x));assert(x.imPerformancePlan?.groupWindowSeconds===525,JSON.stringify(x.imPerformancePlan));return`${x.reps}x${x.distance} · ${x.imPerformancePlan.groupWindowSeconds}s window`}));
    out.push(test('Authority · swimmer surface remains projection-only contract',()=>{assert(M.swimmerInstantOpenCN?.build,'swimmer surface missing');assert(M.performanceEngine,'performance owner missing');assert(M.trainingHistory||g.MSOSArchitecture?.TrainingHistory,'training owner missing');return'portal consumes engine truth'}));return out;
  }
  function fullRun(){const base=baseRun()||{},tests=[];for(const row of base.tests||[]){const repl=replacement(String(row?.name||''));tests.push(repl||row);}for(const row of authorityTests())tests.push(row);let passed=0;for(const row of tests)if(row?.ok===true)passed++;return{...base,build:BUILD,tests,passed,total:tests.length,ok:tests.length>0&&passed===tests.length,contract:'authority-explicit-supersession-20260824',superseded:SUPERSEDED};}
  const R=M.guardianRuntime={build:BUILD,fullRun,running:false};G.run=fullRun;G.runAndRender=()=>{if(R.running)return{running:true,build:BUILD};R.running=true;const run=()=>{let r;try{r=fullRun()}catch(e){r={ok:false,tests:[{name:'Guardian execution',ok:false,detail:e?.message||String(e)}],passed:0,total:1,build:BUILD}};M.state.guardian=M.state.guardian||{runs:[]};r.at=new Date().toISOString();M.state.guardian.runs.push(r);M.state.guardian.runs=M.state.guardian.runs.slice(-20);M.store?.save?.(M.state);R.running=false;M.ui?.renderGuardian?.(r);M.toast?.(`Guardian ${r.ok?'PASS':'FAIL'} · ${r.passed}/${r.total}`);return r};if(typeof requestAnimationFrame==='function')requestAnimationFrame(()=>setTimeout(run,0));else setTimeout(run,0);return{running:true,build:BUILD}};
})(globalThis);
