'use strict';
(function(g){
  const M=g.MSOS4,G=M?.guardian,E=g.MSOSEngines;if(!M||!G?.run||!M.store?.save)return;
  const rawFullRun=G.run.bind(G),baseSave=M.store.save.bind(M.store),CONTRACT_BUILD='v4-guardian-live-contract-20260824cs';
  const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
  const retired=new Set([
    'No evidence means no fake target',
    'Swimmer hub is five simple tabs',
    'Swimmer pathway uses real milestones, never WA point bumps',
    'Coach Loop and swimmer tabs are both active over one canonical session',
    'Swimmer deck access is a header pill contract',
    'Poolside swimmer answer links real milestones to recent training area',
    'Poolside pathway answer is driven by loaded meet/benchmark milestones',
    'Phone acceptance · McKenzie 50 kick keeps authored cycle and Desc 1-3',
    'Engine · Reduced IM uses performance-relative send-off and stays connected to the group set window',
    'Reduced IM uses performance-relative send-off and stays connected to the group set window'
  ]);
  const assert=(c,m)=>{if(!c)throw new Error(m||'assertion failed')};
  const test=(name,fn)=>{try{return{name,ok:true,detail:String(fn()??'')}}catch(e){return{name,ok:false,detail:e?.message||String(e)}}};

  function currentContractTests(){const out=[];
    out.push(test('Current swimmer surface is four simple tabs with pathway inside Performance',()=>{assert(M.swimmerInstantOpenCN?.build,'single-owner swimmer surface missing');assert(M.swimmerTabsUI?.build==='v4-swimmer-deck-only-20260824cp',`legacy swimmer tabs still active: ${M.swimmerTabsUI?.build||'missing'}`);assert(typeof M.swimmerTabsUI?.installDeckPills==='function','Here-now deck pill installer missing');assert(M.swimmerExperienceCL?.disabled===true,'legacy swimmer experience still active');assert(M.performanceEngine?.pathwayUIck?.disabled===true,'standalone pathway renderer still active');return'Here pills · Performance · Training · Tests · Meet · pathway inside Performance';}));
    out.push(test('Current live target contract · no evidence means no fake target',()=>{assert(M.parser?.parse&&M.targets?.forItem,'target engine unavailable');const s=M.parser.parse('MAIN SET\n4 x 100 Threshold',{id:'gr-target',course:'SCM'}),item=s.blocks?.[0]?.items?.find(x=>x.kind==='set'),r=M.targets.forItem(s,item,{id:'gr-no-evidence'},{trainingTestTypes:[],trainingTestResults:[],resultsPbBoard:[],resultsEventHistory:[],coachResults:[]});assert(r?.status==='missing',JSON.stringify(r));return'missing evidence surfaced · no target generated';}));
    out.push(test('Current live target contract · HR Gauge suppresses pace even when Clearance is authored',()=>{assert(M.targets?.forItem,'target engine unavailable');const item={id:'gr-hr',kind:'set',reps:4,distance:100,stroke:'IM',zone:'Clearance',raw:'4 x 100 IM Clearance · HR Gauge',text:'4 x 100 IM Clearance · HR Gauge',cues:[],repPattern:[],repInstructions:[],raceIntent:null,cycleSeconds:90,restSeconds:10},r=M.targets.forItem({id:'gr-hr-session',identity:{course:'SCM'}},item,{id:'gr-hr-ath'},{trainingTestTypes:[],trainingTestResults:[],resultsPbBoard:[],resultsEventHistory:[],coachResults:[]});assert(r?.status==='none',JSON.stringify(r));assert(/HR Gauge/i.test(String(r?.reason||'')),JSON.stringify(r));return'HR Gauge owns the line · no T400 pace target';}));
    if(E?.Modification){
      out.push(test('Current phone contract · McKenzie 50 kick keeps authored cycle and repeating Desc 1-3',()=>{assert(typeof M.adapt?.item==='function','authoritative adaptation bridge unavailable');const ath={id:'gr-md',full_name:'McKenzie Drage',squad:'National'},session={id:'gr-kick',identity:{course:'SCM',squads:['National']}},state={athletes:[ath],adaptationProfiles:[],adaptationOverrides:[],resultsPbBoard:[],resultsEventHistory:[],coachResults:[],trainingTestTypes:[],trainingTestResults:[]},item={id:'gr-desc',kind:'set',reps:12,distance:50,stroke:'',raw:'12 x 50 Kick @ 1:10',text:'12 x 50 Kick @ 1:10',cues:['Desc 1-3 @ 1:10'],pattern:[],repPattern:[],repInstructions:[],raceIntent:null,zone:'',restSeconds:10,cycleSeconds:70,equipment:[],composition:[]},x=M.adapt.item(item,ath,state,session),cue=[x.raw,...(x.cues||[])].join(' | ');assert(x.reps===8&&x.distance===50,JSON.stringify(x));assert(x.cycleSeconds===70,`cycle ${x.cycleSeconds}`);assert(/Desc 1-3/i.test(cue),`cue lost: ${cue}`);assert(!/Desc 1-8/i.test((x.cues||[]).join(' | ')),JSON.stringify(x.cues));return'8×50 @ 1:10 · repeating Desc 1-3 preserved';}));
      out.push(test('Current reduced IM uses performance-relative send-off and stays connected to the group set window',()=>{const ath={id:'gr-md2',full_name:'McKenzie Drage',sex:'F'},session={id:'gr-im',identity:{course:'SCM'}},g1={id:'gr-g1',full_name:'Group One'},g2={id:'gr-g2',full_name:'Group Two'},g3={id:'gr-g3',full_name:'Group Three'},state={athletes:[ath,g1,g2,g3],adaptationProfiles:[],adaptationOverrides:[],resultsPbBoard:[{athlete_id:g1.id,distance:100,stroke:'IM',course:'SCM',result_seconds:68},{athlete_id:g2.id,distance:100,stroke:'IM',course:'SCM',result_seconds:70},{athlete_id:g3.id,distance:100,stroke:'IM',course:'SCM',result_seconds:72},{athlete_id:ath.id,distance:100,stroke:'IM',course:'SCM',result_seconds:112}],resultsEventHistory:[],coachResults:[]},item={id:'gr-im-item',kind:'set',reps:5,distance:100,stroke:'IM',raw:'5 x 100 IM @ 1:45',text:'5 x 100 IM @ 1:45',cues:[],pattern:[],repPattern:[],repInstructions:[],raceIntent:null,zone:'',restSeconds:10,cycleSeconds:105,equipment:[],composition:[]},x=E.Modification.adaptItem(item,ath,state,session);assert(x.reps===3&&x.distance===100,JSON.stringify(x));assert(x.cycleSeconds===175,`cycle ${x.cycleSeconds}`);assert(/2:55/.test(String(x.raw||'')),String(x.raw||''));assert(x.imPerformancePlan?.groupWindowSeconds===525,JSON.stringify(x.imPerformancePlan));assert(x.imPerformancePlan?.totalSeconds===525,JSON.stringify(x.imPerformancePlan));return'3×100 @ 2:55 · 525s group window';}));
    }
    return out;
  }
  const fullRun=()=>{const r=rawFullRun()||{},seen=new Set(),kept=[];for(const t of r.tests||[]){const n=clean(t?.name);if(retired.has(n)||seen.has(n))continue;seen.add(n);kept.push(t);}const tests=[...kept,...currentContractTests()],passed=tests.filter(x=>x.ok===true).length;return{...r,build:CONTRACT_BUILD,tests,passed,total:tests.length,ok:tests.length>0&&passed===tests.length,contract:'20260824cs',retiredTests:[...new Set([...(r.retiredTests||[]),...retired])]};};
  const R=M.guardianRuntime={build:CONTRACT_BUILD,fullRun,running:false};
  const latestReal=()=>[...(M.state?.guardian?.runs||[])].reverse().find(x=>Array.isArray(x?.tests)&&x.tests.length&&!x.deferred)||null;
  G.run=()=>({ok:false,tests:[],passed:0,total:0,at:new Date().toISOString(),build:CONTRACT_BUILD,deferred:true,startupSuppressed:true});
  M.store.save=state=>{const runs=state?.guardian?.runs,last=runs?.at?.(-1);if(state===M.state&&last?.deferred&&last?.startupSuppressed){runs.pop();R.startupRunSuppressed=true;M.storageEngine?.saveUi?.(state);return state;}return baseSave(state);};
  function renderRunning(){const h=document.querySelector('#guardianView');if(!h)return;h.innerHTML=`<section class="page-card"><div class="eyebrow">GUARDIAN · FULL CURRENT BUILD</div><h1>Running full Guardian…</h1><p><b>${M.util?.escape?.(CONTRACT_BUILD)||CONTRACT_BUILD}</b></p><p class="muted">Checking the complete runtime regression chain plus live device state.</p></section>`;}
  G.runAndRender=()=>{if(R.running)return{deferred:true,running:true,build:CONTRACT_BUILD};R.running=true;renderRunning();const run=()=>{let r;try{r=R.fullRun()}catch(e){r={ok:false,tests:[{name:'Guardian execution',ok:false,detail:e?.message||String(e)}],passed:0,total:1,at:new Date().toISOString(),build:CONTRACT_BUILD}};M.state.guardian=M.state.guardian||{runs:[]};M.state.guardian.runs.push(r);M.state.guardian.runs=M.state.guardian.runs.slice(-20);baseSave(M.state);R.running=false;M.ui?.renderGuardian?.(r);M.toast?.(`Guardian ${r.ok?'PASS':'FAIL'} · ${r.passed}/${r.total}`);return r;};if(typeof requestAnimationFrame==='function')requestAnimationFrame(()=>setTimeout(run,0));else setTimeout(run,0);return{deferred:true,running:true,build:CONTRACT_BUILD};};
  const oldRender=M.ui?.renderGuardian?.bind(M.ui);if(oldRender)M.ui.renderGuardian=r=>{if(R.running&&!r){renderRunning();return;}r=r||latestReal();if(r){oldRender(r);const h=document.querySelector('#guardianView');h?.insertAdjacentHTML('afterbegin',`<section class="page-card ${r.ok?'ok':'warning'}"><div class="eyebrow">FULL CURRENT-BUILD GUARDIAN</div><h2>${r.ok?'PASS':'FAIL'} · ${r.passed}/${r.total}</h2><p>${M.util?.escape?.(r.build)||r.build}</p><button id="rerunCurrentGuardian">Run full Guardian again</button></section>`);h?.querySelector('#rerunCurrentGuardian')?.addEventListener('click',()=>G.runAndRender());return;}const h=document.querySelector('#guardianView');if(h)h.innerHTML='<section class="page-card"><div class="eyebrow">GUARDIAN · FULL CURRENT BUILD</div><h1>Not run on this device yet</h1><button id="rerunGuardian">Run full Guardian</button></section>';h?.querySelector('#rerunGuardian')?.addEventListener('click',()=>G.runAndRender());};
  R.latestReal=latestReal;
})(globalThis);
