'use strict';
(function(g){
const M=g.MSOS4;if(!M?.ui)return;
const U=M.util||{},BUILD='v4-meet-ops-20260821aw',BACKUP_KEY='mclay_swimming_v4_meet_field_backup_v1';
const esc=v=>U.escape?U.escape(String(v??'')):String(v??''),txt=v=>U.text?U.text(v):String(v??'').trim(),uid=p=>U.uid?U.uid(p):`${p}-${Date.now()}-${Math.random().toString(36).slice(2)}`,now=()=>U.now?U.now():new Date().toISOString(),clock=s=>U.clock?U.clock(s):Number(s).toFixed(2);
let ticker=null,trainingHandlers=null,voiceRecorder=null,voiceRaceKey='',noteSaveTimer=null,restoring=false;
function parseTime(v){v=txt(v);if(!v)return null;const u=U.seconds?.(v);if(Number.isFinite(u))return u;const n=Number(v);return Number.isFinite(n)&&n>=0?n:null}
function clone(v){try{return JSON.parse(JSON.stringify(v))}catch{return null}}
function ensure(){if(!M.state)return null;if(!M.state.meetOps||typeof M.state.meetOps!=='object')M.state.meetOps={};const o=M.state.meetOps;if(!o.races||typeof o.races!=='object')o.races={};if(!Array.isArray(o.evidence))o.evidence=[];o.selectedAthleteId||='';o.selectedRaceKey||='';return o}
const deck=()=>M.state?.meetFieldDeck||null;
function backup(){if(restoring||!M.state||!deck())return;try{const s=M.state.settings||{},snap={version:1,saved_at:now(),meetFieldDeck:clone(M.state.meetFieldDeck),meetOps:clone(M.state.meetOps),meetImports:clone(M.state.meetImports||[]),meets:clone(M.state.meets||[]),meetEntries:clone(M.state.meetEntries||[]),meetRaces:clone(M.state.meetRaces||[]),meetEvidence:clone(M.state.meetEvidence||[]),currentMeetId:s.currentMeetId||''};localStorage.setItem(BACKUP_KEY,JSON.stringify(snap))}catch{}}
function save(){try{M.store?.save?.(M.state)}catch{}try{M.storageEngine?.saveUi?.(M.state)}catch{}backup()}
function restoreBackup(){if(!M.state||deck())return false;let snap=null;try{snap=JSON.parse(localStorage.getItem(BACKUP_KEY)||'null')}catch{}if(!snap?.meetFieldDeck?.races?.length)return false;restoring=true;try{M.state.meetFieldDeck=clone(snap.meetFieldDeck);if((!M.state.meetOps||!Object.keys(M.state.meetOps.races||{}).length)&&snap.meetOps)M.state.meetOps=clone(snap.meetOps);for(const k of ['meetImports','meets','meetEntries','meetRaces','meetEvidence'])if((!Array.isArray(M.state[k])||!M.state[k].length)&&Array.isArray(snap[k])&&snap[k].length)M.state[k]=clone(snap[k]);M.state.settings=M.state.settings||{};if(!M.state.settings.currentMeetId&&snap.currentMeetId)M.state.settings.currentMeetId=snap.currentMeetId;try{M.store?.save?.(M.state)}catch{}return true}finally{restoring=false}}
function clearBackup(){try{localStorage.removeItem(BACKUP_KEY)}catch{}}
function all(){return[...(deck()?.races||[])].sort((a,b)=>(a.event_number-b.event_number)||((a.heat||0)-(b.heat||0))||((a.lane||0)-(b.lane||0))||((a.relay_leg||0)-(b.relay_leg||0)))}
function relayMembers(r){if(!r?.relay)return[r].filter(Boolean);return all().filter(x=>x.relay&&x.event_number===r.event_number&&(x.heat||0)===(r.heat||0)&&(x.lane||0)===(r.lane||0)).sort((a,b)=>(a.relay_leg||0)-(b.relay_leg||0))}
function key(r){if(!r)return'';const base=[deck()?.source_id||'field',r.event_number||0,r.heat||0,r.lane||0];return r.relay?[...base,'relay'].join('|'):[...base,r.athlete_id||r.athlete_name||''].join('|')}
function uniqueRaces(){const seen=new Set(),out=[];for(const r of all()){const k=key(r);if(seen.has(k))continue;seen.add(k);out.push(r)}return out}
const raceDistance=r=>Number(r?.distance)||(r?.relay?200:0),splitStep=r=>r?.relay?50:25;
function rec(r,create=true){if(!r)return null;const o=ensure(),k=key(r);if(!o)return null;if(!o.races[k]&&create){const members=relayMembers(r);o.races[k]={race_key:k,relay:!!r.relay,athlete_id:r.relay?'':(r.athlete_id||''),athlete_ids:members.map(x=>x.athlete_id).filter(Boolean),athlete_name:r.relay?'AquaGym relay':(r.athlete_name||''),athlete_names:members.map(x=>x.athlete_name).filter(Boolean),event_number:r.event_number,distance:raceDistance(r),stroke:r.stroke,heat:r.heat,lane:r.lane,status:'scheduled',draft_time_seconds:null,splits:[],stroke_rate_notes:'',notes:'',created_at:now(),updated_at:now()};save()}return o.races[k]||null}
const done=r=>rec(r,false)?.status==='complete';
function athleteForId(id){return(M.state.athletes||[]).find(a=>a.id===id)||null}
function nextForAthlete(id){const rs=uniqueRaces().filter(r=>r.athlete_id===id||(r.relay&&relayMembers(r).some(x=>x.athlete_id===id)));return rs.find(r=>!done(r))||rs.at(-1)||null}
function selected(){const o=ensure(),rs=uniqueRaces();if(!o)return null;let r=rs.find(x=>key(x)===o.selectedRaceKey)||nextForAthlete(o.selectedAthleteId)||rs.find(x=>!done(x))||rs[0]||null;if(r){o.selectedRaceKey=key(r);if(!r.relay)o.selectedAthleteId=r.athlete_id||o.selectedAthleteId}return r}
function selectRace(r,{scroll=false}={}){if(!r)return;const o=ensure();o.selectedRaceKey=key(r);if(!r.relay)o.selectedAthleteId=r.athlete_id||'';save();render();if(scroll)setTimeout(()=>document.querySelector('[data-meet-ops-av]')?.scrollIntoView?.({block:'start',behavior:'smooth'}),20)}
function selectKey(k,opts={}){const r=uniqueRaces().find(x=>key(x)===k);if(r)selectRace(r,opts)}
function chooseAthlete(id){const r=nextForAthlete(id);const o=ensure();o.selectedAthleteId=id;o.selectedRaceKey=r?key(r):'';save();render()}
function companions(r){if(!r)return[];if(r.relay)return[r];const rows=uniqueRaces().filter(x=>!x.relay&&x.event_number===r.event_number&&(x.heat||0)===(r.heat||0));rows.sort((a,b)=>(a.lane||99)-(b.lane||99));if(rows.length<2)return[r];return rows}
const athlete=r=>athleteForId(r?.athlete_id),stroke=s=>{s=txt(s).toLowerCase();return s.startsWith('free')?'Freestyle':s.startsWith('back')?'Backstroke':s.startsWith('breast')?'Breaststroke':s.startsWith('butter')?'Butterfly':s==='im'||s.includes('medley')?'IM':txt(s)},course=r=>/LC Meter|LCM/i.test(r?.event||'')?'LCM':'SCM',isPara=r=>!!(r?.classification||M.pathway?.isPara?.(athlete(r))),paraClass=r=>txt(r?.classification||M.pathway?.paraClass?.(athlete(r),stroke(r?.stroke))||'');
function pb(r){if(r?.relay)return null;const a=athlete(r);if(!a||!M.performanceEngine?.rows)return null;try{return M.performanceEngine.rows(a,M.state,course(r)).filter(x=>Number(x.distance)===raceDistance(r)&&stroke(x.stroke)===stroke(r.stroke)).sort((a,b)=>a.seconds-b.seconds)[0]||null}catch{return null}}
function next25(r,p){if(r?.relay||!p||!Number.isFinite(p.points)||isPara(r)||!M.waPointsEngine?.equivalentTime)return null;try{const pts=Math.ceil((Number(p.points)+1)/25)*25,q=M.waPointsEngine.equivalentTime(athlete(r),{course:course(r),distance:raceDistance(r),stroke:stroke(r.stroke),points:pts},M.state);return q?.seconds?{points:pts,seconds:q.seconds}:null}catch{return null}}
const evidence=r=>ensure().evidence.filter(e=>e.race_key===key(r)),elapsed=x=>x?.timer_running&&x.timer_started_ms?Math.max(0,(Date.now()-x.timer_started_ms)/1000):Number(x?.timer_elapsed_seconds)||0;
function runningRecords(){return Object.values(ensure()?.races||{}).filter(x=>x?.timer_running&&x.timer_started_ms)}
function stopTick(){if(ticker){clearInterval(ticker);ticker=null}}
function paintClocks(){for(const n of document.querySelectorAll('[data-mo-clock-key]')){const x=ensure()?.races?.[n.dataset.moClockKey];if(x?.timer_running)n.textContent=clock(elapsed(x))}}
function startTick(){if(ticker)return;ticker=setInterval(()=>{paintClocks();if(!runningRecords().length)stopTick()},80)}
function start(r,sharedMs=null){const x=rec(r);if(!x||x.timer_running)return;x.timer_running=true;x.timer_started_ms=(sharedMs||Date.now())-Math.round((Number(x.timer_elapsed_seconds)||0)*1000);if(x.status==='complete')x.status='draft';x.updated_at=now();save();startTick();render()}
function startHeat(rows){const t=Date.now();for(const r of rows){const x=rec(r);if(!x||x.status==='complete'||x.timer_running)continue;x.timer_running=true;x.timer_started_ms=t-Math.round((Number(x.timer_elapsed_seconds)||0)*1000);x.updated_at=now()}save();startTick();render()}
function splitNow(r){const x=rec(r);if(!x?.timer_running)return;const total=raceDistance(r),step=splitStep(r),d=Math.min(total||step,((x.splits?.length||0)+1)*step);if(d>=total)return;x.splits.push({distance:d,cumulative_seconds:elapsed(x),source:'coach_timer'});x.updated_at=now();save();render()}
function finishTimer(r){const x=rec(r);if(!x?.timer_running)return;const s=elapsed(x);x.timer_running=false;x.timer_elapsed_seconds=s;x.draft_time_seconds=s;x.status='draft';const d=raceDistance(r);if(d&&x.splits.at(-1)?.distance!==d)x.splits.push({distance:d,cumulative_seconds:s,source:'coach_timer'});x.updated_at=now();save();if(!runningRecords().length)stopTick();render();M.toast?.(`Coach draft ${clock(s)} saved`)}
function reset(r){const x=rec(r);if(!x)return;Object.assign(x,{timer_running:false,timer_started_ms:null,timer_elapsed_seconds:0,draft_time_seconds:null,splits:[],status:x.status==='complete'?'draft':x.status,updated_at:now()});save();if(!runningRecords().length)stopTick();render()}
function manual(r,v){const s=parseTime(v),x=rec(r);if(s==null)return M.toast?.('Enter a time like 1:23.45 or 83.45');Object.assign(x,{draft_time_seconds:s,timer_elapsed_seconds:s,timer_running:false,status:'draft',updated_at:now()});save();if(!runningRecords().length)stopTick();render()}
function parseSplits(raw,max){const a=[];for(const line of String(raw||'').split(/[\n;]+/)){const m=txt(line).match(/^(\d+)\s*(?:m)?\s*[:=,-]?\s*(.+)$/i);if(!m)continue;const d=Number(m[1]),s=parseTime(m[2]);if(d>0&&d<=Number(max)&&s!=null)a.push({distance:d,cumulative_seconds:s,source:'coach_text'})}return a.sort((a,b)=>a.distance-b.distance)}
function closeModal(){document.querySelector('#modalHost').innerHTML='';M.nav?.dismissLayer?.()}
function raceTitle(r){if(r.relay){const m=relayMembers(r).map(x=>`${x.relay_leg||''} ${x.athlete_name}`).join(' · ');return`AquaGym relay · ${m}`}return r.athlete_name||'Swimmer'}
function eventLabel(r){return r.relay?`${raceDistance(r)} ${r.stroke} relay`:`${r.distance} ${r.stroke}`}
function editRace(r){if(!r)return;const x=rec(r),h=document.querySelector('#modalHost'),sp=(x.splits||[]).map(s=>`${s.distance} ${clock(s.cumulative_seconds)}`).join('\n');h.innerHTML=`<div class="modal-backdrop"><section class="modal"><header><h2>${esc(raceTitle(r))} · E${r.event_number}</h2><button data-mo-close>×</button></header><div class="modal-body"><p><b>${esc(eventLabel(r))}</b> · H${r.heat||'—'} L${r.lane||'—'}</p><label>Coach time<input data-mo-time value="${x.draft_time_seconds!=null?esc(clock(x.draft_time_seconds)):''}" placeholder="1:23.45"></label><label>Splits <small>one line: 25 16.20</small><textarea data-mo-splits rows="5">${esc(sp)}</textarea></label><label>Stroke rate / count<textarea data-mo-rate rows="3">${esc(x.stroke_rate_notes||'')}</textarea></label><label>Coach notes<textarea data-mo-notes rows="4">${esc(x.notes||'')}</textarea></label>${x.status==='complete'?'<p class="check-card ok">Race complete. Reopen only to correct or redo.</p>':''}</div><footer><button data-mo-save>Save race data</button>${x.status==='complete'?'<button data-mo-reopen>Reopen race</button>':''}<button data-mo-close>Close</button></footer></section></div>`;M.nav?.openLayer?.('modal');h.querySelectorAll('[data-mo-close]').forEach(b=>b.onclick=closeModal);h.querySelector('[data-mo-save]').onclick=()=>{const raw=h.querySelector('[data-mo-time]').value,s=raw.trim()?parseTime(raw):null;if(raw.trim()&&s==null)return M.toast?.('Time format not recognised');x.draft_time_seconds=s;x.timer_elapsed_seconds=s??x.timer_elapsed_seconds??0;x.splits=parseSplits(h.querySelector('[data-mo-splits]').value,raceDistance(r));x.stroke_rate_notes=txt(h.querySelector('[data-mo-rate]').value);x.notes=txt(h.querySelector('[data-mo-notes]').value);if(x.status!=='complete')x.status='draft';x.updated_at=now();save();closeModal();render()};h.querySelector('[data-mo-reopen]')?.addEventListener('click',()=>{x.status='draft';x.completed_at=null;x.updated_at=now();save();closeModal();render()})}
async function saveEv(r,type,text='',blob=null){let media_id=null;const members=relayMembers(r),ids=members.map(x=>x.athlete_id).filter(Boolean);if(blob&&M.media?.save)media_id=await M.media.save(blob,{type:`meet_${type}`,meetSourceId:deck()?.source_id||'',raceKey:key(r),athleteIds:ids});ensure().evidence.push({id:uid('meet-evidence'),race_key:key(r),athlete_id:r.relay?'':(r.athlete_id||''),athlete_ids:ids,athlete_name:raceTitle(r),event_number:r.event_number,capture_type:type,text_content:txt(text),media_id,mime_type:blob?.type||null,created_at:now()});save();render()}
async function quickVoice(r){const k=key(r);if(voiceRecorder){if(voiceRaceKey===k){try{voiceRecorder.stop()}catch{}return}return M.toast?.('Another race voice note is already recording')}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true}),chunks=[],q=new MediaRecorder(stream);voiceRecorder=q;voiceRaceKey=k;q.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};q.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());const rr=uniqueRaces().find(x=>key(x)===k)||r;voiceRecorder=null;voiceRaceKey='';await saveEv(rr,'voice','',new Blob(chunks,{type:q.mimeType||'audio/webm'}));M.toast?.(`Voice note saved · ${raceTitle(rr)}`)};q.start();render();M.toast?.('Voice note recording · tap Stop voice when done')}catch(e){voiceRecorder=null;voiceRaceKey='';M.toast?.(e.message||String(e))}}
function capture(r){if(!r)return;const h=document.querySelector('#modalHost');h.innerHTML=`<div class="modal-backdrop"><section class="modal"><header><h2>Meet capture · ${esc(raceTitle(r))}</h2><button data-mo-close>×</button></header><div class="modal-body"><div class="capture-truth"><b>E${r.event_number} · ${esc(eventLabel(r))}</b><span>H${r.heat||'—'} · L${r.lane||'—'}</span><span>Stopwatch keeps running behind this capture.</span></div><label>Coach note<textarea data-mo-note rows="4"></textarea></label><div class="capture-grid"><button data-mo-voice>Voice</button><label class="buttonlike">Photo<input data-mo-photo type="file" accept="image/*" capture="environment" hidden></label><label class="buttonlike">Video<input data-mo-video type="file" accept="video/*" capture="environment" hidden></label></div><div data-mo-status class="capture-status muted">Saved to this race.</div></div><footer><button data-mo-save-note>Save note</button><button data-mo-close>Close</button></footer></section></div>`;M.nav?.openLayer?.('modal');h.querySelectorAll('[data-mo-close]').forEach(b=>b.onclick=closeModal);const st=h.querySelector('[data-mo-status]');h.querySelector('[data-mo-save-note]').onclick=async()=>{const n=txt(h.querySelector('[data-mo-note]').value);if(!n)return M.toast?.('Add a note first');await saveEv(r,'note',n);closeModal()};const fs=async(e,t)=>{const f=e.target.files?.[0];if(!f)return;st.textContent=`Saving ${t}…`;await saveEv(r,t,'',f);st.textContent=`Saved ${t} · ${raceTitle(r)} · E${r.event_number}`};h.querySelector('[data-mo-photo]').onchange=e=>fs(e,'photo');h.querySelector('[data-mo-video]').onchange=e=>fs(e,'video');h.querySelector('[data-mo-voice]').onclick=()=>quickVoice(r)}
function complete(r){const x=rec(r);if(!x)return;if(x.status==='complete')return M.toast?.('Race already complete · reopen to edit');if(x.timer_running)return M.toast?.('Finish the stopwatch first');if(x.draft_time_seconds==null&&!x.notes&&!evidence(r).length)return M.toast?.('Add a time, note or capture first');x.status='complete';x.completed_at=now();x.updated_at=now();save();render()}
function pillAthletes(){const m=new Map();for(const r of all())for(const row of(r.relay?relayMembers(r):[r]))if(row.athlete_id&&!m.has(row.athlete_id))m.set(row.athlete_id,athleteForId(row.athlete_id)||{id:row.athlete_id,full_name:row.athlete_name});return[...m.values()]}
function pills(){const o=ensure();return`<div class="mo-pills">${pillAthletes().map(a=>{const n=nextForAthlete(a.id),rs=uniqueRaces().filter(r=>r.athlete_id===a.id||(r.relay&&relayMembers(r).some(x=>x.athlete_id===a.id))),d=rs.length&&rs.every(done),name=txt(a.preferred_name||a.nickname||a.board_name||a.full_name).split(' ')[0];return`<button data-mo-ath="${esc(a.id)}" class="${a.id===o.selectedAthleteId?'active':''}"><b>${esc(name)}</b><small>${d?'DONE':n?`E${n.event_number}`:'—'}</small></button>`}).join('')}</div>`}
function tabs(r){const seen=new Set(),rows=[];for(const x of uniqueRaces().filter(x=>x.athlete_id===r.athlete_id||(x.relay&&relayMembers(x).some(m=>m.athlete_id===r.athlete_id)))){if(seen.has(key(x)))continue;seen.add(key(x));rows.push(x)}return`<div class="mo-tabs">${rows.map(x=>`<button data-mo-race="${esc(key(x))}" class="${key(x)===key(r)?'active':''}">E${x.event_number}<small>${done(x)?'✓':x.relay?'RELAY':`${x.distance}${stroke(x.stroke).slice(0,2)}`}</small></button>`).join('')}</div>`}
function memberLine(r){if(!r.relay)return'';return`<div class="mo-relay-members">${relayMembers(r).map(x=>`<span><b>${x.relay_leg||'—'}</b> ${esc(x.athlete_name)}</span>`).join('')}</div>`}
function card(r,primary=false){const x=rec(r),p=pb(r),n=next25(r,p),ev=evidence(r),seed=Number.isFinite(r.seed_seconds)?clock(r.seed_seconds):(r.seed_time||'NT'),spl=(x.splits||[]).map((s,i)=>`<span><b>${s.distance}m</b> ${clock(s.cumulative_seconds)} <small>(+${clock(s.cumulative_seconds-(i?x.splits[i-1].cumulative_seconds:0))})</small></span>`).join(''),k=key(r),voice=voiceRaceKey===k;return`<section class="page-card mo-card ${primary?'primary':''}" data-mo-card="${esc(k)}"><div class="eyebrow">${companions(r).length>1?'THIS HEAT':'NEXT RACE / WORKING CARD'}</div><div class="mo-head"><div><h2>${esc(raceTitle(r))}</h2><strong>E${r.event_number} · ${esc(eventLabel(r))}</strong><p>Heat ${r.heat||'—'} · Lane ${r.lane||'—'}${r.start_time?` · ${esc(r.start_time)}`:''}</p></div><span>${esc(x.status)}</span></div>${memberLine(r)}${!r.relay?tabs(r):''}<div class="mo-metrics"><div><small>Seed</small><b>${esc(seed)}</b></div><div><small>${r.relay?'Race':'PB '+course(r)}</small><b>${r.relay?'4 × 50':(p?clock(p.seconds):'—')}</b></div><div><small>${r.relay?'Members':isPara(r)?'Para class':'Next +25'}</small><b>${r.relay?relayMembers(r).length:isPara(r)?esc(paraClass(r)||'class needed'):(n?`${n.points} · ${clock(n.seconds)}`:'—')}</b></div><div><small>Coach draft</small><b>${x.draft_time_seconds!=null?clock(x.draft_time_seconds):'—'}</b></div></div><div class="mo-timer"><div data-mo-clock-key="${esc(k)}">${clock(elapsed(x))}</div><div>${x.timer_running?`<button data-mo-split="${esc(k)}">Split ${splitStep(r)}m</button><button data-mo-stop="${esc(k)}">Finish timing</button>`:`<button data-mo-start="${esc(k)}">${x.timer_elapsed_seconds?'Resume':'Start timer'}</button><button data-mo-reset="${esc(k)}">Reset</button>`}</div></div><div class="mo-quick-note"><textarea data-mo-quick-note="${esc(k)}" rows="2" placeholder="Type a race note while you watch…">${esc(x.notes||'')}</textarea><button data-mo-quick-voice="${esc(k)}">${voice?'Stop voice':'Voice note'}</button></div><div class="mo-manual"><label>Manual coach time<input data-mo-manual="${esc(k)}" placeholder="1:23.45" value="${x.draft_time_seconds!=null?esc(clock(x.draft_time_seconds)):''}"></label><button data-mo-save-time="${esc(k)}">Save time</button></div>${spl?`<div class="mo-splits">${spl}</div>`:''}${x.stroke_rate_notes?`<p><b>Stroke rate/count:</b> ${esc(x.stroke_rate_notes)}</p>`:''}<div class="mo-actions"><button data-mo-cap="${esc(k)}">Capture</button><button data-mo-edit="${esc(k)}">Race data</button><button data-mo-complete="${esc(k)}" ${x.status==='complete'?'disabled':''}>${x.status==='complete'?'Race complete':'Complete race'}</button></div><div class="mo-ev">${ev.slice(-4).reverse().map(e=>`<span><b>${esc(e.capture_type)}</b> ${esc(e.text_content||'saved media')}</span>`).join('')||'<small class="muted">No race captures yet.</small>'}</div></section>`}
function heatHeader(rows){if(rows.length<2||rows[0]?.relay)return'';const running=rows.filter(r=>rec(r,false)?.timer_running).length;return`<section class="page-card mo-heat-head"><div><div class="eyebrow">AQUAGYM · SAME HEAT</div><b>E${rows[0].event_number} · Heat ${rows[0].heat||'—'} · ${rows.length} swimmers</b></div><button data-mo-start-heat ${running||rows.every(done)?'disabled':''}>${running?'Timing running':'Start all together'}</button></section>`}
function chrome(){const s=document.querySelector('.sticky-actions');if(!s)return;const meet=M.state?.settings?.view==='meet',c=s.querySelector('[data-sticky-note]'),e=s.querySelector('[data-sticky-edit]'),f=s.querySelector('[data-sticky-finish]');if(!trainingHandlers&&[c,e,f].some(x=>typeof x?.onclick==='function'))trainingHandlers={c:c?.onclick,e:e?.onclick,f:f?.onclick};if(!meet){if(c){c.textContent='Capture';if(trainingHandlers?.c)c.onclick=trainingHandlers.c}if(e){e.textContent='Edit';if(trainingHandlers?.e)e.onclick=trainingHandlers.e}if(f){f.textContent='Finish';f.disabled=false;if(trainingHandlers?.f)f.onclick=trainingHandlers.f}return}const r=selected(),x=rec(r,false);s.hidden=false;s.style.gridTemplateColumns='repeat(3,1fr)';if(c){c.hidden=false;c.textContent='Capture';c.onclick=()=>capture(r)}if(e){e.hidden=false;e.textContent='Race data';e.onclick=()=>editRace(r)}if(f){f.hidden=false;f.textContent=x?.status==='complete'?'Race complete':'Complete race';f.disabled=x?.status==='complete';f.onclick=()=>complete(r)}const u=document.querySelector('#undoBtn');if(u)u.hidden=true}
function decorateProgram(){const h=document.querySelector('#meetView'),d=deck();if(!h||!d?.races?.length)return;h.querySelector('[data-meet-intake-au]')?.remove();for(const empty of h.querySelectorAll('.empty-card'))if(/No meet loaded/i.test(empty.textContent||''))empty.remove();const nodes=[...h.querySelectorAll('[data-meet-field-deck-au] .mfa-race')],rows=all();let ni=0;const firstRelay=new Map();for(let i=0;i<rows.length&&ni<nodes.length;i++,ni++){const r=rows[i],node=nodes[ni],k=key(r);node.dataset.moProgramKey=k;node.classList.toggle('mo-program-active',k===ensure().selectedRaceKey);node.style.cursor='pointer';if(r.relay){if(firstRelay.has(k)){node.hidden=true;continue}firstRelay.set(k,node);const members=relayMembers(r),seed=Number.isFinite(r.seed_seconds)?clock(r.seed_seconds):(r.seed_time||'NT');node.innerHTML=`<strong>AquaGym relay</strong><span>H${r.heat||'—'} · L${r.lane||'—'}</span><small>${members.map(x=>`${x.relay_leg||'—'} ${esc(x.athlete_name)}`).join(' · ')}${seed?` · ${esc(seed)}`:''}</small>`}node.onclick=e=>{if(e.target.closest('input,textarea,button'))return;selectKey(k,{scroll:true})}}
const clear=h.querySelector('[data-mfa-clear]');if(clear&&!clear.dataset.moBackupClear){clear.dataset.moBackupClear='1';clear.addEventListener('click',()=>{clearBackup();if(M.state?.meetOps)M.state.meetOps={races:{},evidence:[],selectedAthleteId:'',selectedRaceKey:''};save()})}}
function bindCardEvents(root,rows){const byKey=k=>uniqueRaces().find(r=>key(r)===k);root.querySelectorAll('[data-mo-ath]').forEach(x=>x.onclick=()=>chooseAthlete(x.dataset.moAth));root.querySelectorAll('[data-mo-race]').forEach(x=>x.onclick=()=>selectKey(x.dataset.moRace));root.querySelectorAll('[data-mo-start]').forEach(x=>x.onclick=()=>start(byKey(x.dataset.moStart)));root.querySelectorAll('[data-mo-split]').forEach(x=>x.onclick=()=>splitNow(byKey(x.dataset.moSplit)));root.querySelectorAll('[data-mo-stop]').forEach(x=>x.onclick=()=>finishTimer(byKey(x.dataset.moStop)));root.querySelectorAll('[data-mo-reset]').forEach(x=>x.onclick=()=>reset(byKey(x.dataset.moReset)));root.querySelectorAll('[data-mo-save-time]').forEach(x=>x.onclick=()=>manual(byKey(x.dataset.moSaveTime),root.querySelector(`[data-mo-manual="${CSS.escape(x.dataset.moSaveTime)}"]`)?.value));root.querySelectorAll('[data-mo-cap]').forEach(x=>x.onclick=()=>capture(byKey(x.dataset.moCap)));root.querySelectorAll('[data-mo-edit]').forEach(x=>x.onclick=()=>editRace(byKey(x.dataset.moEdit)));root.querySelectorAll('[data-mo-complete]').forEach(x=>x.onclick=()=>complete(byKey(x.dataset.moComplete)));root.querySelectorAll('[data-mo-quick-voice]').forEach(x=>x.onclick=()=>quickVoice(byKey(x.dataset.moQuickVoice)));root.querySelectorAll('[data-mo-quick-note]').forEach(x=>x.addEventListener('input',()=>{const r=byKey(x.dataset.moQuickNote),q=rec(r);if(!q)return;q.notes=x.value;q.updated_at=now();clearTimeout(noteSaveTimer);noteSaveTimer=setTimeout(save,250)}));root.querySelector('[data-mo-start-heat]')?.addEventListener('click',()=>startHeat(rows))}
function render(){const h=document.querySelector('#meetView');if(!h)return;restoreBackup();h.querySelector('[data-meet-ops-av]')?.remove();if(!deck()?.races?.length){chrome();return}const r=selected();if(!r)return;const rows=companions(r),b=document.createElement('section');b.dataset.meetOpsAv='1';b.className='mo-shell';b.innerHTML=pills()+heatHeader(rows)+`<div class="mo-live-cards">${rows.map(x=>card(x,key(x)===key(r))).join('')}</div>`;const field=h.querySelector('[data-meet-field-deck-au]');field?h.insertBefore(b,field):h.prepend(b);bindCardEvents(b,rows);decorateProgram();backup();if(runningRecords().length)startTick();chrome()}
function style(){if(document.getElementById('meet-ops-av-style'))document.getElementById('meet-ops-av-style').remove();const s=document.createElement('style');s.id='meet-ops-av-style';s.textContent=`.mo-shell{display:grid;gap:.6rem}.mo-pills,.mo-tabs{display:flex;gap:.35rem;overflow-x:auto;padding:.1rem 0 .3rem}.mo-pills button,.mo-tabs button{flex:0 0 auto;display:grid;min-width:65px;padding:.45rem .55rem;border-radius:999px}.mo-pills .active,.mo-tabs .active{outline:2px solid currentColor}.mo-live-cards{display:grid;gap:.55rem}.mo-live-cards:has(>.mo-card:nth-child(2)){grid-template-columns:repeat(2,minmax(0,1fr))}.mo-card.primary{outline:2px solid rgba(13,69,102,.25)}.mo-head{display:flex;justify-content:space-between;gap:.5rem}.mo-card h2{margin:.1rem 0}.mo-relay-members{display:flex;flex-wrap:wrap;gap:.35rem;margin:.4rem 0}.mo-relay-members span{border:1px solid rgba(13,69,102,.16);border-radius:999px;padding:.28rem .45rem}.mo-metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:.35rem;margin:.5rem 0}.mo-metrics>div{border:1px solid rgba(13,69,102,.15);border-radius:10px;padding:.4rem;display:grid}.mo-timer{border:2px solid rgba(13,69,102,.22);border-radius:14px;padding:.6rem;display:grid;gap:.45rem}.mo-timer>[data-mo-clock-key]{font-size:2.25rem;font-weight:800;text-align:center;font-variant-numeric:tabular-nums}.mo-timer>div:last-child,.mo-actions{display:grid;grid-template-columns:repeat(2,1fr);gap:.35rem}.mo-timer button{min-height:52px}.mo-quick-note{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:.35rem;margin:.45rem 0}.mo-quick-note textarea{min-height:48px}.mo-manual{display:grid;grid-template-columns:1fr auto;gap:.4rem;align-items:end;margin:.45rem 0}.mo-manual label{display:grid}.mo-splits{display:flex;flex-wrap:wrap;gap:.3rem}.mo-splits span{border:1px solid rgba(13,69,102,.15);border-radius:999px;padding:.25rem .4rem}.mo-actions{grid-template-columns:repeat(3,1fr);margin-top:.45rem}.mo-ev{display:grid;gap:.25rem;margin-top:.35rem}.mo-heat-head{display:flex;align-items:center;justify-content:space-between;gap:.5rem}.mfa-race.mo-program-active{outline:2px solid rgba(13,69,102,.25);border-radius:8px}.mfa-race[hidden]{display:none!important}@media(max-width:760px){.mo-live-cards:has(>.mo-card:nth-child(2)){grid-template-columns:1fr}.mo-metrics{grid-template-columns:repeat(2,1fr)}.mo-head{display:grid}.mo-actions{grid-template-columns:1fr 1fr}.mo-actions [data-mo-complete]{grid-column:1/-1}.mo-manual,.mo-quick-note{grid-template-columns:1fr}.mo-manual button,.mo-quick-note button{width:100%}.mo-heat-head{align-items:stretch;display:grid}}`;document.head.appendChild(s)}
style();ensure();const prev=M.ui.renderMeet?.bind(M.ui);if(prev)M.ui.renderMeet=()=>{restoreBackup();prev();render()};const pc=M.ui.configureRoleChrome?.bind(M.ui);if(pc)M.ui.configureRoleChrome=()=>{const x=pc();chrome();return x};document.addEventListener('click',e=>{if(e.target.closest?.('[data-mfa-use]'))setTimeout(()=>{render();backup()},40)},true);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'){save();return}if(M.state?.settings?.view==='meet'){render();if(runningRecords().length)startTick()}});g.addEventListener?.('pagehide',()=>save());g.addEventListener?.('pageshow',()=>{if(M.state?.settings?.view==='meet')render()});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{if(M.state?.settings?.view==='meet')render()},{once:true});else if(M.state?.settings?.view==='meet')render();M.meetOpsEngine={build:BUILD,render,selectedRace:selected,recordFor:rec,startTimer:start,startHeat,splitTimer:splitNow,finishTimer,openCapture:capture,openRaceEdit:editRace,completeRace:complete,keyFor:key,selectRace,selectKey,backup,restoreBackup};
})(globalThis);
