'use strict';
(function(g){
  const M=g.MSOS4,U=M?.util;if(!M?.ui||!M?.performanceEngine||!M?.strokeBalance||!M?.pathway)return;
  const UI=M.ui,P=M.performanceEngine,SB=M.strokeBalance,DEV=M.developmentEngine,V=M.performanceUI={build:'v4-performance-ui-20260821ah'},evidenceAttempts=new Map();
  const esc=v=>U.escape(String(v??'')),clock=s=>U.clock(Number(s));
  const short=s=>String(s||'').replace('Freestyle','Fr').replace('Backstroke','Bk').replace('Breaststroke','Br').replace('Butterfly','Fly');
  function go(view){if(M.navigationEngine?.go)return M.navigationEngine.go(view,{restore:false});return M.nav?.show?.(view,{restoreScroll:false});}
  function athletes(){const role=M.access?.role?.()||'owner';let rows=(M.access?.visibleAthletes?.()||M.state.athletes||[]).filter(a=>a.active!==false);if(role==='swimmer'){const id=M.state.settings.activeUserAthleteId;rows=rows.filter(a=>a.id===id);}return rows.sort((a,b)=>String(a.full_name).localeCompare(String(b.full_name)));}
  function bars(sum,kind='weighted'){const map=sum?.[kind]||{},total=kind==='weighted'?sum?.totalWeighted:sum?.totalRaw;return SB.STROKES.map(st=>{const v=Number(map[st]||0),pct=total?v/total*100:0;return `<div class="perf-bar"><span>${esc(short(st))}</span><div><i style="width:${Math.max(0,pct)}%"></i></div><b>${pct.toFixed(0)}%${kind==='raw'?` · ${Math.round(v)}m`:''}</b></div>`}).join('');}
  function t400Rows(profile){const rows=Object.values(profile?.t400||{});return rows.length?rows.map(x=>`<div class="perf-evidence"><b>${esc(short(x.stroke))} T400</b><span>${clock(x.seconds)}</span></div>`).join(''):'<p class="muted">No matching T400 anchors loaded.</p>';}
  function timedRows(profile){const rows=profile?.timedSets||[];return rows.length?rows.slice(0,8).map(x=>`<div class="perf-evidence"><b>${esc(x.set_label||`${x.distance||''} ${x.stroke||''}`)}</b><span>${x.best?`Best ${clock(x.best)}`:'Saved'}${x.average?` · Avg ${clock(x.average)}`:''}</span></div>`).join(''):'<p class="muted">No recent timed-set evidence.</p>';}
  function eventRows(ath,profile,{pulling=false,unavailable=false,status=null}={}){const ranked=P.rankedEvents(ath,M.state,profile.course),pbs=P.rows(ath,M.state,profile.course);if(ranked.length)return ranked.slice(0,12).map((x,i)=>`<div class="perf-rank"><b>#${i+1} ${esc(`${x.distance} ${short(x.stroke)}`)}</b><span>${clock(x.seconds)}</span><strong>${Math.floor(x.points)} WA${x.pointVersion?` · ${esc(x.pointVersion)}`:''}</strong></div>`).join('');if(pbs.length)return pbs.slice(0,12).map(x=>`<div class="perf-rank"><b>${esc(`${x.distance} ${short(x.stroke)}`)}</b><span>${clock(x.seconds)}</span><strong>PB · WA rank unavailable</strong></div>`).join('');if(pulling)return'<p class="muted"><b>Checking connected PB/results…</b></p>';if(unavailable)return`<div class="context-note"><b>PB/result store unavailable.</b> ${esc(status?.message||'The system cannot currently verify this swimmer’s race evidence.')}</div>`;return'<p class="muted">No verified PB/result evidence loaded after the PB roster was checked.</p>';}
  function pathwayRows(ath,course,{pulling=false,unavailable=false,status=null}={}){let path=null;try{path=M.pathway.profile(ath,course)}catch{}if(path?.classificationNeeded)return'<div class="context-note"><b>Para classification needed.</b> Pathway ranking is held until S/SB/SM classification is complete.</div>';const rows=path?.events||[];return rows.length?rows.slice(0,10).map(ev=>{const pb=ev.pb,n=ev.nextNational,pt=ev.points,steps=M.pathway.pointSteps?.(ath,pb,4)||ev.pointSteps||[],stepHtml=steps.length?`<div class="perf-path-ladder">${steps.map(s=>{const gain=Math.max(0,Number(pb.result_seconds)-Number(s.seconds));return`<div class="perf-evidence"><b>${Math.round(s.points)} WA</b><span>${clock(s.seconds)}${gain>0?` · ${gain.toFixed(2)}s faster`:''}</span></div>`;}).join('')}</div>`:'<p class="muted">No WA performance-step ladder available for this event.</p>',qual=n?`<div class="context-note"><b>Relevant qualifier:</b> ${esc(n.row._label)} · ${clock(n.row._seconds)} · ${n.gap.seconds.toFixed(2)}s away</div>`:'';return `<details class="perf-path"><summary><b>${esc(`${pb.distance} ${short(pb.stroke)}`)}</b> · PB ${clock(pb.result_seconds)}${pt?.value?` · ${Math.floor(pt.value)} ${esc(pt.label)}`:''}</summary><p class="muted">Next performance bumps · 25 WA points per step</p>${stepHtml}${qual}</details>`}).join(''):pulling?'<p class="muted"><b>Checking connected pathway evidence…</b></p>':unavailable?`<div class="context-note"><b>Pathway waiting for PB/results.</b> ${esc(status?.message||'Race evidence is unavailable.')}</div>`:'<p class="muted">No pathway event rows for this course.</p>';}
  function rankMessage(profile,{pulling=false,unavailable=false,status=null}={}){if(profile.bestEvent)return `${Math.floor(profile.bestEvent.points)} WA${profile.bestEvent.pointVersion?` · ${profile.bestEvent.pointVersion}`:''}`;if(profile.pbs.length)return`${profile.pbs.length} PBs loaded · WA point table/match needed`;if(pulling)return'Checking connected PB/results…';if(unavailable)return status?.message||'PB/result store unavailable';return'No ranked PB evidence after roster check';}
  function developmentRows(dev){if(!dev)return'<p class="muted">Development coverage engine not loaded.</p>';if(!dev.pbEvents)return'<div class="context-note"><b>First race evidence needed.</b> MSOS will not invent an event target before the swimmer has useful PB/result evidence. Once results arrive, event-breadth opportunities can be suggested from what they have actually raced.</div>';const rows=dev.opportunities||[];const opp=rows.length?rows.slice(0,8).map(x=>`<div class="perf-evidence"><b>${esc(x.label)}</b><span>${esc(x.reason)}${x.modelSeconds?` · <strong>≈ ${clock(x.modelSeconds)}</strong>${x.modelPoints?` at ${Math.round(x.modelPoints)} WA-equivalent`:''}`:''}</span></div>`).join(''):'<p class="muted">No obvious adjacent-event gaps from the loaded PB evidence.</p>';const x=dev.xlr8;if(!x?.monitored)return opp;const cats=x.categories.map(c=>`<div class="perf-evidence"><b>${c.complete?'✓':'○'} ${esc(c.label)}</b><span>${esc(c.evidence||'Experience/result opportunity')}</span></div>`).join('');const age=x.ageKnown?`Age ${x.age}`:'Junior squad · DOB/age check needed';return`${opp}<div class="context-note"><b>XLR8 junior monitor · ${esc(age)}</b><div>${cats}</div><small>${esc(x.note)}</small></div>`;}
  function loadingCard(h,ath,role,course,list,id){h.innerHTML=`<section class="page-card perf-head"><div class="eyebrow">SWIMMER PERFORMANCE</div><h1>${esc(ath?.full_name||'Swimmer')}</h1><div class="path-controls">${role==='swimmer'?'':`<select id="perfAthlete">${list.map(a=>`<option value="${esc(a.id)}" ${a.id===id?'selected':''}>${esc(a.full_name)} · ${esc(a.squad||'')}</option>`).join('')}</select>`}<div class="course-toggle"><button data-perf-course="SCM" class="${course==='SCM'?'active':''}">SCM</button><button data-perf-course="LCM" class="${course==='LCM'?'active':''}">LCM</button></div></div><p class="muted">Runtime ${esc(M.BUILD||'loading')}</p></section><section class="page-card"><h2>Loading swimmer evidence…</h2><p class="muted">PBs, WA points, tests and pathway references are loading from the local evidence store.</p></section>`;h.querySelector('#perfAthlete')?.addEventListener('change',e=>{M.state.settings.selectedAthleteId=e.target.value;M.storageEngine?.saveUi?.(M.state);render();});h.querySelectorAll('[data-perf-course]').forEach(b=>b.onclick=()=>{M.state.settings.pathwayCourse=b.dataset.perfCourse;M.storageEngine?.saveUi?.(M.state);render();});}
  function evidenceKey(ath,course){return `${ath?.id||ath?.full_name}|${course}`;}
  function startEvidenceRecovery(ath,course){const key=evidenceKey(ath,course);if(evidenceAttempts.has(key)||!M.engineBridge?.ensureAthleteEvidence)return false;const p=Promise.resolve(M.engineBridge.ensureAthleteEvidence(ath,{course}));evidenceAttempts.set(key,{status:'running',promise:p});p.then(n=>{evidenceAttempts.set(key,{status:'done',rows:Number(n)||0});if((M.state?.settings?.view||'')==='athletes'&&M.state.settings.selectedAthleteId===ath.id)requestAnimationFrame(render);}).catch(err=>{evidenceAttempts.set(key,{status:'error',rows:0,error:String(err?.message||err)});if((M.state?.settings?.view||'')==='athletes')requestAnimationFrame(render);});return true;}
  function render(){const h=document.querySelector('#athletesView');if(!h)return;const list=athletes(),role=M.access?.role?.()||'owner';let id=role==='swimmer'?M.state.settings.activeUserAthleteId:M.state.settings.selectedAthleteId;if(!list.some(a=>a.id===id))id=list[0]?.id||'';M.state.settings.selectedAthleteId=id;const ath=list.find(a=>a.id===id),course=M.state.settings.pathwayCourse||'SCM';if(!ath){h.innerHTML='<section class="empty-card">No swimmers loaded.</section>';return;}if(M.engineBridge&&!M.engineBridge.hydrated){loadingCard(h,ath,role,course,list,id);Promise.resolve(M.engineBridge.hydrate()).finally(()=>{if((M.state?.settings?.view||'')==='athletes')requestAnimationFrame(render);});return;}let profile=P.profile(ath,M.state,course),key=evidenceKey(ath,course),attempt=evidenceAttempts.get(key),pulling=attempt?.status==='running';if(!profile.pbs.length&&!attempt&&startEvidenceRecovery(ath,course)){attempt=evidenceAttempts.get(key);pulling=true;}const evidenceStatus=M.engineBridge?.evidenceStatus?.(ath,course)||{status:profile.pbs.length?'ready':'idle',message:''},unavailable=!profile.pbs.length&&['error','unavailable'].includes(evidenceStatus.status),b7=SB.summary(ath,M.state,{days:7}),b28=SB.summary(ath,M.state,{days:28}),best=profile.bestEvent,bs=profile.bestStroke,bf=profile.bestFormStroke,ctx=profile.medleyPrimary?SB.recommendStroke(ath,M.state,M.currentSession?.(),{}):null,wa=profile.waPoints||{},qt=M.dataRegistry?.activeMeta?.('national_standards')||M.dataRegistry?.activeMeta?.('meet_qualifying'),identityLabel=x=>x?x:pulling?'Loading…':unavailable?'Unavailable':'#1 needed',development=DEV?.profile?.(ath,M.state,course)||null;
    h.innerHTML=`<section class="page-card perf-head"><div class="eyebrow">SWIMMER PERFORMANCE</div><h1>${esc(ath.full_name)}</h1><div class="path-controls">${role==='swimmer'?'':`<select id="perfAthlete">${list.map(a=>`<option value="${esc(a.id)}" ${a.id===id?'selected':''}>${esc(a.full_name)} · ${esc(a.squad||'')}</option>`).join('')}</select>`}<div class="course-toggle"><button data-perf-course="SCM" class="${course==='SCM'?'active':''}">SCM</button><button data-perf-course="LCM" class="${course==='LCM'?'active':''}">LCM</button></div></div><div class="hub-actions"><button id="perfTimes">Times / Tests / T400</button><button id="perfReports">Reports</button>${role==='swimmer'?'':'<button id="perfRefresh">Refresh PB / results</button><button data-msos-data>Data & References</button>'}</div><p class="muted">Runtime <b>${esc(M.BUILD||'')}</b> · WA points: ${wa.active?`${esc(wa.version||'active table')} · ${wa.rows} base times`:'no active base-time table'}${qt?` · Pathway standards ${esc(qt.version||'active')}`:''}</p></section>
    <section class="page-card"><div class="eyebrow">PERFORMANCE IDENTITY</div>${pulling?'<div class="context-note"><b>PB/results recovery:</b> checking the connected results store. Existing T400, training and stroke-balance evidence stays usable while this completes.</div>':unavailable?`<div class="context-note"><b>Race evidence system unavailable — not a swimmer evidence judgement.</b> ${esc(evidenceStatus.message)}</div>`:''}<div class="perf-kpis"><div><span>#1 event</span><b>${best?esc(`${best.distance} ${short(best.stroke)}`):identityLabel('')}</b><small>${esc(rankMessage(profile,{pulling,unavailable,status:evidenceStatus}))}</small></div><div><span>#1 stroke</span><b>${bs?esc(short(bs.stroke)):identityLabel('')}</b><small>${bs&&Number.isFinite(bs.points)?`${Math.floor(bs.points)} WA evidence`:profile.pbs.length?'PBs loaded · no WA stroke rank':pulling?'Checking PB evidence…':unavailable?'PB data unavailable':'No stroke rank'}</small></div><div><span>#1F</span><b>${bf?esc(short(bf.stroke)):pulling?'Loading…':unavailable?'Unavailable':'#1F needed'}</b><small>${bf&&Number.isFinite(bf.points)?`${Math.floor(bf.points)} WA evidence`:profile.pbs.length?'PBs loaded · no WA form rank':pulling?'Checking PB evidence…':unavailable?'PB data unavailable':'No form-stroke rank'}</small></div><div><span>PB events</span><b>${pulling&&!profile.pbs.length?'…':unavailable&&!profile.pbs.length?'—':profile.pbs.length}</b><small>${course}</small></div></div>${profile.medleyPrimary?`<div class="context-note"><b>IM-primary logic:</b> #1 event is ${esc(`${best.distance} ${best.stroke}`)}. Context stroke currently <b>${esc(short(ctx?.stroke||'needed'))}</b> · ${esc(ctx?.source||'insufficient evidence')}.</div>`:''}</section>
    <section class="page-card"><h2>Stroke exposure / focus</h2><p class="muted">Raw metres are retained. Weighted focus discounts incidental/easy Free and weights quality/technical work by training intent. Weighting is provisional methodology and remains auditable.</p><div class="perf-two"><div><h3>Last 7 days · weighted</h3>${bars(b7,'weighted')}<small>${b7.sessions} session${b7.sessions===1?'':'s'}${b7.assumedSessions?` · ${b7.assumedSessions} squad-assumed`:''}</small></div><div><h3>Last 28 days · weighted</h3>${bars(b28,'weighted')}<small>${b28.sessions} session${b28.sessions===1?'':'s'}</small></div></div><details><summary>Raw stroke metres</summary><h3>7 days</h3>${bars(b7,'raw')}<h3>28 days</h3>${bars(b28,'raw')}</details></section>
    <section class="page-card"><h2>PB / event ranking</h2>${eventRows(ath,{...profile,course},{pulling,unavailable,status:evidenceStatus})}</section>
    <section class="page-card"><h2>Event coverage / development</h2><p class="muted">This is a coaching opportunity layer over actual race evidence. A modeled time is marked ≈ and is never stored or displayed as a PB.</p>${developmentRows(development)}</section>
    <section class="page-card perf-two"><div><h2>T400 / test anchors</h2>${t400Rows(profile)}</div><div><h2>Recent timed-set evidence</h2>${timedRows(profile)}</div></section>
    <section class="page-card"><h2>Pathway</h2>${pathwayRows(ath,course,{pulling,unavailable,status:evidenceStatus})}</section>`;
    h.querySelector('#perfAthlete')?.addEventListener('change',e=>{M.state.settings.selectedAthleteId=e.target.value;M.storageEngine?.saveUi?.(M.state);render();});
    h.querySelectorAll('[data-perf-course]').forEach(b=>b.onclick=()=>{M.state.settings.pathwayCourse=b.dataset.perfCourse;M.storageEngine?.saveUi?.(M.state);render();});
    h.querySelector('#perfTimes')?.addEventListener('click',()=>{M.state.settings.t400PreferredAthleteId=ath.id;M.storageEngine?.saveUi?.(M.state);go('times');requestAnimationFrame(()=>{const s=document.querySelector('#t400Athlete');if(s)s.value=ath.id;});});
    h.querySelector('#perfReports')?.addEventListener('click',()=>{M.state.settings.reportAthleteId=ath.id;M.state.settings.reportScope='swimmer';M.storageEngine?.saveUi?.(M.state);go('reports');});
    h.querySelector('#perfRefresh')?.addEventListener('click',async()=>{try{evidenceAttempts.delete(key);const n=await M.engineBridge?.ensureAthleteEvidence?.(ath,{course,force:true});P.invalidate?.(M.state);render();const s=M.engineBridge?.evidenceStatus?.(ath,course);M.toast(n?`PB / results refreshed · ${n} ${course}`:(s?.message||'No PB results found'))}catch(e){M.toast(e.message||String(e));}});
    M.dataAdminUI?.ensureShortcut?.('athletes');
  }
  UI.renderAthletes=render;V.render=render;
  addEventListener('msos:data-updated',()=>{if((M.state?.settings?.view||'')==='athletes')render();});
  addEventListener('msos:evidence-ready',()=>{if((M.state?.settings?.view||'')==='athletes')requestAnimationFrame(render);});
})(globalThis);
