'use strict';
(function(g){
  const M=g.MSOS4,U=M?.util;if(!M?.ui||!M?.performanceEngine||!M?.strokeBalance||!M?.pathway)return;
  const UI=M.ui,P=M.performanceEngine,SB=M.strokeBalance,V=M.performanceUI={build:'v4-performance-ui-20260820q'};
  const esc=v=>U.escape(String(v??'')),clock=s=>U.clock(Number(s));
  const short=s=>String(s||'').replace('Freestyle','Fr').replace('Backstroke','Bk').replace('Breaststroke','Br').replace('Butterfly','Fly');
  function go(view){if(M.navigationEngine?.go)return M.navigationEngine.go(view,{restore:false});return M.nav?.show?.(view,{restoreScroll:false});}
  function athletes(){const role=M.access?.role?.()||'owner';let rows=(M.access?.visibleAthletes?.()||M.state.athletes||[]).filter(a=>a.active!==false);if(role==='swimmer'){const id=M.state.settings.activeUserAthleteId;rows=rows.filter(a=>a.id===id);}return rows.sort((a,b)=>String(a.full_name).localeCompare(String(b.full_name)));}
  function bars(sum,kind='weighted'){const map=sum?.[kind]||{},total=kind==='weighted'?sum?.totalWeighted:sum?.totalRaw;return SB.STROKES.map(st=>{const v=Number(map[st]||0),pct=total?v/total*100:0;return `<div class="perf-bar"><span>${esc(short(st))}</span><div><i style="width:${Math.max(0,pct)}%"></i></div><b>${pct.toFixed(0)}%${kind==='raw'?` · ${Math.round(v)}m`:''}</b></div>`}).join('');}
  function t400Rows(profile){const rows=Object.values(profile?.t400||{});return rows.length?rows.map(x=>`<div class="perf-evidence"><b>${esc(short(x.stroke))} T400</b><span>${clock(x.seconds)}</span></div>`).join(''):'<p class="muted">No matching T400 anchors loaded.</p>';}
  function timedRows(profile){const rows=profile?.timedSets||[];return rows.length?rows.slice(0,8).map(x=>`<div class="perf-evidence"><b>${esc(x.set_label||`${x.distance||''} ${x.stroke||''}`)}</b><span>${x.best?`Best ${clock(x.best)}`:'Saved'}${x.average?` · Avg ${clock(x.average)}`:''}</span></div>`).join(''):'<p class="muted">No recent timed-set evidence.</p>';}
  function eventRows(ath,profile){const ranked=P.rankedEvents(ath,M.state,profile.course),pbs=P.rows(ath,M.state,profile.course);if(ranked.length)return ranked.slice(0,12).map((x,i)=>`<div class="perf-rank"><b>#${i+1} ${esc(`${x.distance} ${short(x.stroke)}`)}</b><span>${clock(x.seconds)}</span><strong>${Math.round(x.points)} WA</strong></div>`).join('');return pbs.length?pbs.slice(0,12).map(x=>`<div class="perf-rank"><b>${esc(`${x.distance} ${short(x.stroke)}`)}</b><span>${clock(x.seconds)}</span><strong>PB · no point rank</strong></div>`).join(''):'<p class="muted">No verified PB/result evidence loaded.</p>';}
  function pathwayRows(ath,course){let path=null;try{path=M.pathway.profile(ath,course)}catch{}if(path?.classificationNeeded)return'<div class="context-note"><b>Para classification needed.</b> Pathway ranking is held until S/SB/SM classification is complete.</div>';const rows=path?.events||[];return rows.length?rows.slice(0,10).map(ev=>{const pb=ev.pb,n=ev.nextNational,pt=ev.points;return `<details class="perf-path"><summary><b>${esc(`${pb.distance} ${short(pb.stroke)}`)}</b> · PB ${clock(pb.result_seconds)}${pt?.value?` · ${Math.round(pt.value)} ${esc(pt.label)}`:''}</summary>${n?`<p>Next: <b>${esc(n.row._label)}</b> · ${clock(n.row._seconds)} · ${n.gap.seconds.toFixed(2)}s away</p>`:'<p class="muted">No unachieved national qualifier matched.</p>'}</details>`}).join(''):'<p class="muted">No pathway event rows for this course.</p>';}
  function render(){const h=document.querySelector('#athletesView');if(!h)return;const list=athletes(),role=M.access?.role?.()||'owner';let id=role==='swimmer'?M.state.settings.activeUserAthleteId:M.state.settings.selectedAthleteId;if(!list.some(a=>a.id===id))id=list[0]?.id||'';M.state.settings.selectedAthleteId=id;const ath=list.find(a=>a.id===id),course=M.state.settings.pathwayCourse||'SCM';if(!ath){h.innerHTML='<section class="empty-card">No swimmers loaded.</section>';return;}const profile=P.profile(ath,M.state,course),b7=SB.summary(ath,M.state,{days:7}),b28=SB.summary(ath,M.state,{days:28}),best=profile.bestEvent,bs=profile.bestStroke,bf=profile.bestFormStroke,ctx=profile.medleyPrimary?SB.recommendStroke(ath,M.state,M.currentSession?.(),{}):null;
    h.innerHTML=`<section class="page-card perf-head"><div class="eyebrow">SWIMMER PERFORMANCE</div><h1>${esc(ath.full_name)}</h1><div class="path-controls">${role==='swimmer'?'':`<select id="perfAthlete">${list.map(a=>`<option value="${esc(a.id)}" ${a.id===id?'selected':''}>${esc(a.full_name)} · ${esc(a.squad||'')}</option>`).join('')}</select>`}<div class="course-toggle"><button data-perf-course="SCM" class="${course==='SCM'?'active':''}">SCM</button><button data-perf-course="LCM" class="${course==='LCM'?'active':''}">LCM</button></div></div><div class="hub-actions"><button id="perfTimes">Times / Tests / T400</button><button id="perfReports">Reports</button>${role==='swimmer'?'':'<button id="perfRefresh">Refresh PB / results</button>'}</div></section>
    <section class="page-card"><div class="eyebrow">PERFORMANCE IDENTITY</div><div class="perf-kpis"><div><span>#1 event</span><b>${best?esc(`${best.distance} ${short(best.stroke)}`):'#1 needed'}</b><small>${best&&Number.isFinite(best.points)?`${Math.round(best.points)} WA`:'No ranked PB evidence'}</small></div><div><span>#1 stroke</span><b>${bs?esc(short(bs.stroke)):'#1 needed'}</b><small>${bs&&Number.isFinite(bs.points)?`${Math.round(bs.points)} WA evidence`:'No stroke rank'}</small></div><div><span>#1F</span><b>${bf?esc(short(bf.stroke)):'#1F needed'}</b><small>${bf&&Number.isFinite(bf.points)?`${Math.round(bf.points)} WA evidence`:'No form-stroke rank'}</small></div><div><span>PB events</span><b>${profile.pbs.length}</b><small>${course}</small></div></div>${profile.medleyPrimary?`<div class="context-note"><b>IM-primary logic:</b> #1 event is ${esc(`${best.distance} ${best.stroke}`)}. Context stroke currently <b>${esc(short(ctx?.stroke||'needed'))}</b> · ${esc(ctx?.source||'insufficient evidence')}.</div>`:''}</section>
    <section class="page-card"><h2>Stroke exposure / focus</h2><p class="muted">Raw metres are retained. Weighted focus discounts incidental/easy Free and weights quality/technical work by training intent. Weighting is provisional methodology and remains auditable.</p><div class="perf-two"><div><h3>Last 7 days · weighted</h3>${bars(b7,'weighted')}<small>${b7.sessions} session${b7.sessions===1?'':'s'}${b7.assumedSessions?` · ${b7.assumedSessions} squad-assumed`:''}</small></div><div><h3>Last 28 days · weighted</h3>${bars(b28,'weighted')}<small>${b28.sessions} session${b28.sessions===1?'':'s'}</small></div></div><details><summary>Raw stroke metres</summary><h3>7 days</h3>${bars(b7,'raw')}<h3>28 days</h3>${bars(b28,'raw')}</details></section>
    <section class="page-card"><h2>PB / event ranking</h2>${eventRows(ath,{...profile,course})}</section>
    <section class="page-card perf-two"><div><h2>T400 / test anchors</h2>${t400Rows(profile)}</div><div><h2>Recent timed-set evidence</h2>${timedRows(profile)}</div></section>
    <section class="page-card"><h2>Pathway</h2>${pathwayRows(ath,course)}</section>`;
    h.querySelector('#perfAthlete')?.addEventListener('change',e=>{M.state.settings.selectedAthleteId=e.target.value;M.storageEngine?.saveUi?.(M.state);render();});
    h.querySelectorAll('[data-perf-course]').forEach(b=>b.onclick=()=>{M.state.settings.pathwayCourse=b.dataset.perfCourse;M.storageEngine?.saveUi?.(M.state);render();});
    h.querySelector('#perfTimes')?.addEventListener('click',()=>{M.state.settings.t400PreferredAthleteId=ath.id;M.storageEngine?.saveUi?.(M.state);go('times');requestAnimationFrame(()=>{const s=document.querySelector('#t400Athlete');if(s)s.value=ath.id;});});
    h.querySelector('#perfReports')?.addEventListener('click',()=>{M.state.settings.reportAthleteId=ath.id;M.state.settings.reportScope='swimmer';M.storageEngine?.saveUi?.(M.state);go('reports');});
    h.querySelector('#perfRefresh')?.addEventListener('click',async()=>{try{await M.cloud?.pullAthletePathway?.(ath.id,{forceReferences:false});await M.engineBridge?.hydrate?.({force:true});render();M.toast('PB / results refreshed');}catch(e){M.toast(e.message||String(e));}});
  }
  UI.renderAthletes=render;V.render=render;
})(globalThis);
