'use strict';
(function(g){
  const M=g.MSOS4,E=g.MSOSEngines;if(!M||!E?.Evidence||!E?.RacePace)return;
  const P=M.performanceEngine={build:'v4-performance-20260823bx'};
  const text=v=>String(v??'').replace(/\s+/g,' ').trim();
  const STROKES=['Freestyle','Backstroke','Breaststroke','Butterfly'];
  const FORMS=['Backstroke','Breaststroke','Butterfly'];
  const rankCache=new WeakMap(),contextCache=new WeakMap(),modelCache=new WeakMap();
  const courseOf=r=>E.Evidence.course(r)||text(r?.course||r?.pool_course).toUpperCase();
  const rowKey=r=>r?.id||[E.Evidence.distance(r),E.Evidence.rowStroke(r),courseOf(r),E.Evidence.seconds(r)].join('|');
  const isPara=ath=>!!(M.pathway?.isPara?.(ath)||ath?.current_s_class||ath?.current_sb_class||ath?.current_sm_class);
  const scoreSystem=ath=>isPara(ath)?'WPS':'WA';
  const paraClass=(ath,stroke)=>text(M.pathway?.paraClass?.(ath,stroke)||(E.Evidence.stroke(stroke)==='Breaststroke'?ath?.current_sb_class:E.Evidence.stroke(stroke)==='IM'?ath?.current_sm_class:ath?.current_s_class));
  function scoreForRow(ath,row,state=M.state){
    if(isPara(ath)){
      let p=null;try{p=M.pathway?.points?.(ath,row)||null}catch{}
      const value=Number(p?.value??row?.world_para_points??row?.wps_points??row?.para_points);
      return Number.isFinite(value)&&value>0?{points:Math.floor(value),label:'WPS',source:p?.source||'Stored World Para result',class:paraClass(ath,E.Evidence.rowStroke(row))}:{points:null,label:'WPS',source:p?.source||'WPS unavailable',class:paraClass(ath,E.Evidence.rowStroke(row))};
    }
    let p=null;try{p=M.pathway?.points?.(ath,row)||null}catch{}
    const value=Number(p?.value);return Number.isFinite(value)&&value>0?{points:Math.floor(value),label:'WA',source:p?.source||'World Aquatics result'}:{points:null,label:'WA',source:p?.source||'WA unavailable'};
  }
  function revision(state=M.state){const wa=M.waPointsEngine?.tableInfo?.(state)||{};return`${Number(state?.settings?.storageRevision||0)}|${state?._evidenceBridge?.hydratedAt||''}|${wa.datasetId||wa.version||''}|${(state?.adaptationOverrides||[]).length}`;}
  function mapFor(cache,state){let m=cache.get(state);if(!m){m=new Map();cache.set(state,m);}return m;}
  function paraRankedEvents(ath,state=M.state,course=''){
    let src=[];try{src=E.Evidence.pbRows(ath,state)||[]}catch{}
    const wanted=text(course).toUpperCase(),same=src.filter(r=>!wanted||!courseOf(r)||courseOf(r)===wanted),pool=same.length?same:src,best=new Map();
    for(const r of pool){const distance=E.Evidence.distance(r),stroke=E.Evidence.rowStroke(r),crs=courseOf(r),seconds=E.Evidence.seconds(r),score=scoreForRow(ath,r,state);if(!distance||!stroke||!Number.isFinite(seconds)||seconds<=0||!Number.isFinite(Number(score.points))||Number(score.points)<=0)continue;const k=`${crs}|${distance}|${stroke}`,row={raw:r,distance,stroke,course:crs,seconds,points:Number(score.points),pointSource:score.source||'',pointVersion:'stored-wps',baseSeconds:null,pointSystem:'WPS',paraClass:score.class||paraClass(ath,stroke)},old=best.get(k);if(!old||row.points>old.points||(row.points===old.points&&row.seconds<old.seconds))best.set(k,row);}
    return[...best.values()].sort((a,b)=>b.points-a.points||a.seconds-b.seconds);
  }
  function rankedEvents(ath,state=M.state,course=''){
    if(!ath||!state)return[];const key=`${revision(state)}|${ath.id||E.Evidence.key?.(ath.full_name)||ath.full_name}|${text(course).toUpperCase()}|${scoreSystem(ath)}`,map=mapFor(rankCache,state);if(map.has(key))return map.get(key);
    const rows=isPara(ath)?paraRankedEvents(ath,state,course):E.RacePace.rankedEvents(ath,state,course).map(x=>({raw:x.row,distance:x.distance,stroke:x.stroke,course:x.course,seconds:x.seconds,points:x.score,pointSource:x.pointSource||'',pointVersion:x.pointVersion||'',baseSeconds:x.baseSeconds??null,pointSystem:'WA'}));
    map.set(key,rows);if(map.size>500)map.delete(map.keys().next().value);return rows;
  }
  function rows(ath,state=M.state,course=''){
    const wanted=text(course).toUpperCase(),ranked=rankedEvents(ath,state,course),scores=new Map(ranked.map(x=>[rowKey(x.raw),x]));let src=[];try{src=E.Evidence.pbRows(ath,state)||[]}catch{}
    return src.map(r=>{const rank=scores.get(rowKey(r)),score=rank||scoreForRow(ath,r,state);return{raw:r,distance:E.Evidence.distance(r),stroke:E.Evidence.rowStroke(r),course:courseOf(r),seconds:E.Evidence.seconds(r),points:Number(score?.points)>0?Number(score.points):null,pointSource:score?.pointSource||score?.source||'',pointVersion:score?.pointVersion||'',pointSystem:score?.pointSystem||score?.label||scoreSystem(ath),paraClass:isPara(ath)?paraClass(ath,E.Evidence.rowStroke(r)):''};}).filter(r=>r.distance&&r.stroke&&Number.isFinite(r.seconds)&&r.seconds>0&&(!wanted||!r.course||r.course===wanted));
  }
  function bestEvent(ath,state=M.state,course=''){return rankedEvents(ath,state,course)[0]||null;}
  function bestStroke(ath,state=M.state,course='',nonFree=false){const allowed=nonFree?FORMS:STROKES;return rankedEvents(ath,state,course).find(r=>allowed.includes(r.stroke))||null;}
  function bestFormStroke(ath,state=M.state,course=''){return bestStroke(ath,state,course,true);}
  function t400s(ath,state=M.state){const out={};for(const s of [...STROKES,'IM']){const r=E.Evidence.t400Rows?.(ath,state,s)?.[0];if(r)out[s]={stroke:s,seconds:E.Evidence.seconds(r),row:r};}return out;}
  function timed(ath,state=M.state,limit=12){return(state?.timedSets||[]).filter(x=>x.athlete_id===ath?.id).slice(-limit).reverse();}
  function selectedCoachStroke(ath,state=M.state,days=14){const now=Date.now(),cut=now-days*86400000,counts=new Map();for(const o of state?.adaptationOverrides||[]){if(o?.athleteId!==ath?.id||o?.active===false||!o?.patch?.stroke)continue;const ts=Date.parse(o.updatedAt||o.createdAt||'');if(Number.isFinite(ts)&&ts<cut)continue;const s=E.Evidence.stroke(o.patch.stroke);if(!STROKES.includes(s))continue;counts.set(s,(counts.get(s)||0)+1);}return[...counts].sort((a,b)=>b[1]-a[1])[0]?.[0]||'';}
  function modeledEvent(ath,state=M.state,{course='SCM',distance=0,stroke=''}={}){if(isPara(ath))return null;const c=text(course).toUpperCase()||'SCM',d=Number(distance),st=E.Evidence.stroke(stroke||'');if(!ath||!d||!STROKES.includes(st)||!M.waPointsEngine?.equivalentTime)return null;const key=`${revision(state)}|${ath.id||E.Evidence.key?.(ath.full_name)||ath.full_name}|${c}|${d}|${st}`,cache=mapFor(modelCache,state);if(cache.has(key))return cache.get(key);const all=rankedEvents(ath,state,'').filter(r=>r.stroke===st&&r.distance!==d&&Number.isFinite(r.points)&&r.points>0),sameCourse=all.filter(r=>!r.course||r.course===c),candidates=sameCourse.length?sameCourse:all;if(!candidates.length){cache.set(key,null);return null;}const gap=r=>Math.abs(Math.log2(Number(r.distance)/d)),minGap=Math.min(...candidates.map(gap)),nearest=candidates.filter(r=>Math.abs(gap(r)-minGap)<1e-9).sort((a,b)=>b.points-a.points).slice(0,2),points=Math.round(nearest.reduce((n,r)=>n+r.points,0)/nearest.length),eq=M.waPointsEngine.equivalentTime(ath,{course:c,distance:d,stroke:st,points},state);if(!eq){cache.set(key,null);return null;}const spread=nearest.length>1?Math.max(...nearest.map(r=>r.points))-Math.min(...nearest.map(r=>r.points)):0,sourceEvents=nearest.map(r=>({distance:r.distance,stroke:r.stroke,course:r.course,seconds:r.seconds,points:r.points})),labels=sourceEvents.map(r=>`${r.course||'course ?'} ${r.distance} ${r.stroke} ${r.points} WA`).join(' + '),out={seconds:eq.seconds,points,course:c,distance:d,stroke:st,sourceEvents,confidence:nearest.length===1?'medium':spread<=50?'medium':'low',model:'wa_performance_equivalent',tableVersion:eq.tableVersion||'',source:`Modeled ${c} ${d} ${st} · ${points} WA equivalent from ${labels}`};cache.set(key,out);if(cache.size>500)cache.delete(cache.keys().next().value);return out;}
  function selectStrokeForContext(ath,item,state=M.state,session=null,{formOnly=false}={}){if(!ath||!state)return{stroke:'',source:'No athlete evidence',confidence:'none'};const course=session?.identity?.course||'',key=`${revision(state)}|${ath.id||E.Evidence.key?.(ath.full_name)||ath.full_name}|${course}|${session?.id||''}|${formOnly?'F':'A'}|${scoreSystem(ath)}`,cache=mapFor(contextCache,state);if(cache.has(key))return cache.get(key);const event=bestEvent(ath,state,course),system=scoreSystem(ath);let out;if(!event)out={stroke:'',source:rows(ath,state,course).length?`PB evidence loaded but no ${system} rank`:`No ranked ${system} PB evidence`,confidence:'none'};else if(event.stroke==='IM'&&M.strokeBalance?.recommendStroke){const r=M.strokeBalance.recommendStroke(ath,state,session,{formOnly});out=r?.stroke?{...r,bestEvent:event}:null;}if(!out){const ranked=bestStroke(ath,state,course,formOnly);if(!ranked)out={stroke:'',source:`No ranked ${system} stroke PB evidence`,confidence:'none',bestEvent:event};else{const coach=selectedCoachStroke(ath,state);out=coach&&(!formOnly||coach!=='Freestyle')?{stroke:coach,source:'Recent coach stroke selections',confidence:'medium',bestEvent:event,event:ranked}:{stroke:ranked.stroke,source:`Highest ranked ${system} stroke PB`,confidence:'high',bestEvent:event,event:ranked};}}cache.set(key,out);if(cache.size>500)cache.delete(cache.keys().next().value);return out;}
  function profile(ath,state=M.state,course=''){const ev=bestEvent(ath,state,course),st=bestStroke(ath,state,course,false),form=bestFormStroke(ath,state,course),all=rows(ath,state,course),tests=t400s(ath,state),recent=timed(ath,state),wa=M.waPointsEngine?.tableInfo?.(state)||{active:false,rows:0,version:''},para=isPara(ath),system=scoreSystem(ath),medley=ev?.stroke==='IM',context=medley?selectStrokeForContext(ath,null,state,{identity:{course}},{}):null;return{athlete:ath,course,bestEvent:ev,bestStroke:st,bestFormStroke:form,medleyPrimary:medley,contextStroke:context,pbs:all,t400:tests,timedSets:recent,hasRankedEvidence:!!ev,waPoints:wa,pointStatus:ev?'ranked':all.length?'pbs_without_rank':'no_pbs',isPara:para,scoreSystem:system};}
  function invalidate(state=M.state){if(state&&typeof state==='object'){rankCache.delete(state);contextCache.delete(state);modelCache.delete(state);}}
  P.rows=rows;P.rankedEvents=rankedEvents;P.bestEvent=bestEvent;P.bestStroke=bestStroke;P.bestFormStroke=bestFormStroke;P.t400s=t400s;P.timed=timed;P.modeledEvent=modeledEvent;P.selectStrokeForContext=selectStrokeForContext;P.profile=profile;P.selectedCoachStroke=selectedCoachStroke;P.invalidate=invalidate;P.isPara=isPara;P.scoreSystem=scoreSystem;P.scoreForRow=scoreForRow;P.paraClass=paraClass;
  g.addEventListener?.('msos:evidence-ready',()=>invalidate());
  g.addEventListener?.('msos:data-updated',()=>invalidate());
})(globalThis);