'use strict';
(function(root,factory){const api=factory(root.MSOSEngines?.Evidence,root);if(typeof module==='object'&&module.exports)module.exports=api;else{root.MSOSEngines=root.MSOSEngines||{};root.MSOSEngines.RacePace=api;}})(typeof globalThis!=='undefined'?globalThis:this,function(E,root){
  const VERSION='2.9.2-bp';
  const CONVERSIONS=[[50,'Freestyle',.85],[50,'Backstroke',.85],[50,'Butterfly',.70],[50,'Breaststroke',1],[100,'Freestyle',1.70],[100,'Backstroke',1.70],[100,'Butterfly',1.40],[100,'Breaststroke',2],[200,'Freestyle',3.40],[200,'Backstroke',3.40],[200,'Butterfly',2.80],[200,'Breaststroke',4],[200,'IM',3.40],[400,'Freestyle',6.80],[400,'IM',6.80],[800,'Freestyle',13.60],[1500,'Freestyle',25.50]].map(([distance,stroke,seconds])=>({from:'SCM',to:'LCM',distance,stroke,seconds,source:'Swimming NZ official conversion table'}));
  const RACE_MODEL={
    M:{Freestyle:{100:{parts:[.4754,.5246],unit:50,dive25:.4554},200:{parts:[.2334,.2532,.2570,.2564],unit:50,dive25:.4487},400:{parts:[.2431,.2550,.2547,.2478],unit:100,dive50:.4798},1500:{parts:[.1970,.2012,.2013,.2014,.1991],unit:300,dive50:.1543}},Backstroke:{100:{parts:[.4858,.5142],unit:50,dive25:.4611},200:{parts:[.2359,.2517,.2567,.2554],unit:50,dive25:.4581}},Breaststroke:{100:{parts:[.4660,.5340],unit:50,dive25:.4525},200:{parts:[.2301,.2554,.2578,.2567],unit:50,dive25:.4539}},Butterfly:{100:{parts:[.4666,.5333],unit:50,dive25:.4572},200:{parts:[.2221,.2537,.2604,.2623],unit:50,dive25:.4522}},IM:{200:{parts:[.2159,.2523,.2917,.2401],unit:50,dive25:.4485},400:{parts:[.2255,.2561,.2814,.2370],unit:100,dive50:.4612}}},
    F:{Freestyle:{100:{parts:[.4797,.5197],unit:50,dive25:.4555},200:{parts:[.2343,.2526,.2570,.2560],unit:50,dive25:.4583},400:{parts:[.2415,.2535,.2542,.2505],unit:100,dive50:.4831},800:{parts:[.2450,.2525,.2530,.2498],unit:200,dive50:.2403}},Backstroke:{100:{parts:[.4851,.5149],unit:50,dive25:.4609},200:{parts:[.2354,.2519,.2555,.2572],unit:50,dive25:.4636}},Breaststroke:{100:{parts:[.4688,.5312],unit:50,dive25:.4573},200:{parts:[.2311,.2541,.2564,.2584],unit:50,dive25:.4562}},Butterfly:{100:{parts:[.4667,.5333],unit:50,dive25:.4580},200:{parts:[.2258,.2536,.2591,.2617],unit:50,dive25:.4555}},IM:{200:{parts:[.2161,.2543,.2902,.2394],unit:50,dive25:.4569},400:{parts:[.2298,.2573,.2842,.2287],unit:100,dive50:.4684}}}
  };
  const text=v=>String(v??'').replace(/\s+/g,' ').trim(),baseCache=new WeakMap(),pathwayEnsured=new WeakMap(),pbCache=new WeakMap();
  function convert(seconds,from,to,distance,stroke,state={}){if(!from||!to||from===to)return{seconds:Number(seconds),source:'Exact course'};const rows=[...(state?.courseConversions||state?.xlr8_course_conversions||[]),...CONVERSIONS],norm=x=>text(x).toUpperCase(),st=E.stroke(stroke);let r=rows.find(x=>norm(x.from_course||x.from)===norm(from)&&norm(x.to_course||x.to)===norm(to)&&Number(x.distance)===Number(distance)&&E.stroke(x.stroke)===st&&x.active!==false);if(r)return{seconds:Number(seconds)*Number(r.multiplier??1)+Number(r.seconds_adjustment??r.seconds??0),source:r.label||r.source_name||r.source||'Verified course conversion'};r=rows.find(x=>norm(x.from_course||x.from)===norm(to)&&norm(x.to_course||x.to)===norm(from)&&Number(x.distance)===Number(distance)&&E.stroke(x.stroke)===st&&x.active!==false);if(r)return{seconds:(Number(seconds)-Number(r.seconds_adjustment??r.seconds??0))/Number(r.multiplier??1),source:`Inverse · ${r.label||r.source_name||r.source||'verified course conversion'}`};return null;}
  function stateRevision(state){return`${Number(state?.settings?.storageRevision||0)}|${state?._evidenceBridge?.hydratedAt||''}|${state?.resultsPbBoard?.length||0}|${state?.resultsEventHistory?.length||0}|${state?.coachResults?.length||0}`;}
  function ensurePathway(ath,state,course){if(!ath||!state)return false;let row=pathwayEnsured.get(state);const rev=stateRevision(state);if(!row||row.rev!==rev){row={rev,set:new Set()};pathwayEnsured.set(state,row);}const k=`${ath.id||E.key?.(ath.full_name)||ath.full_name}|${text(course).toUpperCase()||'SCM'}`;if(row.set.has(k))return false;row.set.add(k);try{return Number(root.MSOS4?.engineBridge?.ensurePathwayAthlete?.(ath,text(course).toUpperCase()||'SCM')||0)>0;}catch{return false;}}
  function locatePb(rows,{distance,stroke,course},state){const wanted=E.stroke(stroke),c=text(course).toUpperCase();let hit=rows.filter(r=>E.distance(r)===Number(distance)&&E.rowStroke(r)===wanted&&(!c||!E.course(r)||E.course(r)===c)).sort((a,b)=>E.seconds(a)-E.seconds(b))[0];if(hit)return{...hit,_anchor_seconds:E.seconds(hit),_anchor_source:`${c||E.course(hit)||'Stored'} ${distance} ${wanted} PB`};const other=c==='SCM'?'LCM':c==='LCM'?'SCM':'';if(!other)return null;hit=rows.filter(r=>E.distance(r)===Number(distance)&&E.rowStroke(r)===wanted&&E.course(r)===other).sort((a,b)=>E.seconds(a)-E.seconds(b))[0];if(!hit)return null;const cv=convert(E.seconds(hit),other,c,distance,wanted,state);return cv?{...hit,_anchor_seconds:cv.seconds,_anchor_source:`${other} PB → ${c} · ${cv.source}`} : null;}
  function cacheFor(state){let row=pbCache.get(state),rev=stateRevision(state);if(!row||row.rev!==rev){row={rev,map:new Map()};pbCache.set(state,row);}return row.map;}
  function pb(ath,state,spec){const course=text(spec?.course).toUpperCase(),stroke=E.stroke(spec?.stroke),distance=Number(spec?.distance),key=`${ath?.id||E.key?.(ath?.full_name)||ath?.full_name}|${course}|${distance}|${stroke}`,map=cacheFor(state);if(map.has(key))return map.get(key);let rows=E.pbRows(ath,state),hit=locatePb(rows,{distance,stroke,course},state);if(!hit&&ensurePathway(ath,state,course)){rows=E.pbRows(ath,state);hit=locatePb(rows,{distance,stroke,course},state);}map.set(key,hit||null);return hit||null;}
  function modeledAnchor(ath,state,spec){try{const m=root.MSOS4?.performanceEngine?.modeledEvent?.(ath,state,{course:text(spec?.course).toUpperCase()||'SCM',distance:Number(spec?.distance),stroke:E.stroke(spec?.stroke||'')});if(!m?.seconds)return null;return{_anchor_seconds:m.seconds,_anchor_source:m.source,_modeled:true,_model:m,course:m.course,distance:m.distance,stroke:m.stroke,result_seconds:m.seconds};}catch{return null;}}
  function anchor(ath,state,spec){return pb(ath,state,spec)||modeledAnchor(ath,state,spec);}
  function baseTimes(state){return[...(state?.worldAquaticsBaseTimes||[]),...(state?._refs?.world_aquatics_base_times||[])];}
  function sexKey(v){const s=text(v).toUpperCase();if(/^(?:M|MALE|BOY|BOYS|MEN)$/.test(s))return'M';if(/^(?:F|FEMALE|GIRL|GIRLS|WOMEN)$/.test(s))return'F';if(/^(?:OPEN|MIXED|ALL)$/.test(s))return'OPEN';return'';}
  function baseIndex(state){if(!state||typeof state!=='object')return new Map();const rows=baseTimes(state),sig=`${state?.worldAquaticsBaseTimes?.length||0}|${state?._refs?.world_aquatics_base_times?.length||0}|${state?._evidenceBridge?.hydratedAt||''}`,old=baseCache.get(state);if(old?.sig===sig)return old.map;const map=new Map();for(const x of rows){if(!x||x.active===false)continue;const c=E.course(x),d=E.distance(x),st=E.rowStroke(x),sx=sexKey(x.sex||x.gender),b=Number(x.base_seconds??x.base_time_seconds??x.base_time);if(!c||!d||!st||!b)continue;const k=`${c}|${d}|${st}|${sx||'OPEN'}`;if(!map.has(k))map.set(k,{...x,base_seconds:b});}baseCache.set(state,{sig,map});return map;}
  function pointInfo(ath,row,state){try{const w=root.MSOS4?.waPointsEngine?.pointsFor?.(ath,row,state);if(w&&Number.isFinite(w.points)&&w.points>0)return w;}catch{}const t=E.seconds(row),d=E.distance(row),st=E.rowStroke(row),crs=E.course(row),sex=sexKey(ath?.sex||ath?.gender||row?.sex||row?.gender),idx=baseIndex(state),base=(sex&&idx.get(`${crs}|${d}|${st}|${sex}`))||idx.get(`${crs}|${d}|${st}|OPEN`);const b=Number(base?.base_seconds);if(b>0&&t>0)return{points:Math.floor(1000*Math.pow(b/t,3)),baseSeconds:b,tableVersion:base?.table_version||base?.version||'',source:base?.source||'WA base time',calculated:true};const p=E.points(row);return Number.isFinite(p)&&p>0?{points:Math.floor(p),tableVersion:'stored-result',source:'Stored result points',calculated:false}:null;}
  function inferredPoints(ath,row,state){return pointInfo(ath,row,state)?.points??NaN;}
  function rankedEvents(ath,state,course=''){let rows=E.pbRows(ath,state);if(!rows.length&&ensurePathway(ath,state,course))rows=E.pbRows(ath,state);const c=text(course).toUpperCase(),same=rows.filter(r=>!c||!E.course(r)||E.course(r)===c),pool=same.length?same:rows;return pool.map(r=>{const info=pointInfo(ath,r,state);return{row:r,distance:E.distance(r),stroke:E.rowStroke(r),course:E.course(r),score:info?.points??NaN,seconds:E.seconds(r),pointSource:info?.source||'',pointVersion:info?.tableVersion||'',baseSeconds:info?.baseSeconds??null};}).filter(x=>x.distance&&x.stroke&&Number.isFinite(x.score)&&x.score>0).sort((a,b)=>b.score-a.score||a.seconds-b.seconds);}
  function bestEvent(ath,state,course=''){return rankedEvents(ath,state,course)[0]||null;}
  function bestStroke(ath,state,course='',nonFree=false){const allowed=nonFree?['Backstroke','Breaststroke','Butterfly']:['Freestyle','Backstroke','Breaststroke','Butterfly'];return rankedEvents(ath,state,course).find(x=>allowed.includes(x.stroke))?.stroke||'';}
  function contextualStroke(item,ath,state,course,formOnly=false){try{const r=root.MSOS4?.performanceEngine?.selectStrokeForContext?.(ath,item,state,{identity:{course}},{formOnly});if(r?.stroke)return E.stroke(r.stroke);}catch{}return bestStroke(ath,state,course,formOnly);}
  function resolveStroke(item,ath,state,course,override=''){if(override&&override!=='AUTO')return E.stroke(override);const raw=text(item?.raw||item?.text);if(/#\s*1F\b/i.test(raw))return contextualStroke(item,ath,state,course,true);if(/#\s*1\b/i.test(raw))return contextualStroke(item,ath,state,course,false);const st=E.stroke(item?.stroke||'');return['Freestyle','Backstroke','Breaststroke','Butterfly','IM'].includes(st)?st:bestStroke(ath,state,course,false);}
  function effectiveIntentStroke(item,raceIntent,manualOverride='',extra=''){if(manualOverride&&manualOverride!=='AUTO')return manualOverride;const raw=text(`${item?.raw||item?.text||''} ${extra||''}`);if(/#\s*1F\b/i.test(raw)||/#\s*1\b/i.test(raw))return'';return raceIntent?.eventStroke||'';}
  function knownSegment(row,raw,eventDistance,workDistance){if(!row)return null;const n=k=>{const v=Number(row?.[k]);return Number.isFinite(v)&&v>0?v:null};if(eventDistance===200&&workDistance===100&&/\b(?:second|2nd|last|final)\s*100\b/i.test(raw)){const v=n('second_100_seconds')||n('second100_seconds')||n('last_100_seconds')||n('back_100_seconds');if(v)return{seconds:v,source:'Stored 200 race second-100 split'};return null;}if(eventDistance===200&&workDistance===100&&/\b(?:first|1st)\s*100\b/i.test(raw)){const v=n('first_100_seconds')||n('first100_seconds');if(v)return{seconds:v,source:'Stored 200 race first-100 split'};return null;}return null;}
  function modelFor(sex,distance,stroke){let model=RACE_MODEL[sex]?.[stroke]?.[Number(distance)];if(!model&&Number(distance)===800)model=RACE_MODEL.F.Freestyle[800];if(!model&&Number(distance)===1500)model=RACE_MODEL.M.Freestyle[1500];return model||null;}
  function fiftyProfile(total,sex,distance,stroke){const model=modelFor(sex,distance,stroke);if(!model||!Number.isFinite(Number(total)))return null;const groups=model.parts.map(part=>Number(total)*part),fifties=[];if(model.unit===50)fifties.push(...groups);else{const first=groups[0],first50=model.dive50?first*model.dive50:first/(model.unit/50);fifties.push(first50);const remainingCount=model.unit/50-1,remaining=Math.max(0,first-first50);for(let i=0;i<remainingCount;i++)fifties.push(remaining/remainingCount);for(const group of groups.slice(1)){const count=model.unit/50;for(let i=0;i<count;i++)fifties.push(group/count);}}const dive25=model.dive25&&fifties[0]?fifties[0]*model.dive25:null;return{fifties,dive25,model};}
  function raceCumulative(profile,distance){if(!profile?.fifties?.length)return 0;let d=Math.max(0,Number(distance)||0),seconds=0;if(d<=0)return 0;const first50=Number(profile.fifties[0])||0,dive25=Number(profile.dive25);if(d<=50){if(Number.isFinite(dive25)&&dive25>0){if(d<=25)return dive25*(d/25);return dive25+(first50-dive25)*((d-25)/25);}return first50*(d/50);}seconds=first50;d-=50;let index=1;while(d>0&&index<profile.fifties.length){const take=Math.min(50,d);seconds+=(Number(profile.fifties[index])||0)*(take/50);d-=take;index++;}return seconds;}
  function ordinalNumber(token){const t=text(token).toLowerCase(),word={first:1,second:2,third:3,fourth:4,fifth:5,sixth:6,seventh:7,eighth:8};return word[t]||Number(t.replace(/(?:st|nd|rd|th)$/,''))||null;}
  function namedSegment(line,eventDistance,repDistance){const t=text(line).toLowerCase(),max=Math.max(0,Number(eventDistance)||0),defaultLength=Math.max(0,Number(repDistance)||0);const last=t.match(/\blast\s+(5|10|15|20|25|35|50|65|75|100)\s*m?\b/);if(last){const length=Number(last[1]);return{start:Math.max(0,max-length),length,label:`last ${length}m`,derived:length<50};}const first=t.match(/\bfirst\s+(5|10|15|20|25|35|50|65|75|100)\s*m?\b/);if(first){const length=Number(first[1]);return{start:0,length,label:`first ${length}m`,derived:length!==25&&length!==50};}const ordinal=t.match(/\b(\d+(?:st|nd|rd|th)|first|second|third|fourth|fifth|sixth|seventh|eighth)\s*(25|50|100)\s*m?\b/);if(ordinal){const index=ordinalNumber(ordinal[1]),length=Number(ordinal[2]),start=(index-1)*length;if(index&&start<max)return{start,length:Math.min(length,max-start),label:`${ordinal[1]} ${length}m`,derived:length<50||(length===50&&start>0)};}const pair=t.match(/(\d+(?:\.5)?)\s*m?\s*(?:in|into)\s*(?:\+|\/|and)\s*(\d+(?:\.5)?)\s*m?\s*(?:out|off)/i),inOnly=t.match(/(\d+(?:\.5)?)\s*m?\s*(?:in|into)(?:\s+the)?\s+turn/i),outOnly=t.match(/(\d+(?:\.5)?)\s*m?\s*(?:out|off)(?:\s+of)?\s+(?:the\s+)?turn/i);if(pair||inOnly||outOnly||/\bturn\b/.test(t)){const explicit=t.match(/\bturn\s*#?\s*(\d+)\b|\b(\d+)(?:st|nd|rd|th)\s+turn\b/),turnIndex=explicit?Number(explicit[1]||explicit[2]):null;let turnDistance=turnIndex?turnIndex*25:Math.round((max/2)/25)*25;turnDistance=Math.max(25,Math.min(Math.max(25,max-25),turnDistance));const inD=pair?Number(pair[1]):inOnly?Number(inOnly[1]):0,outD=pair?Number(pair[2]):outOnly?Number(outOnly[1]):0;if(inD||outD)return{start:Math.max(0,turnDistance-inD),length:Math.min(max,turnDistance+outD)-Math.max(0,turnDistance-inD),label:`${inD?`${inD}m in`:''}${inD&&outD?' + ':''}${outD?`${outD}m out`:''} turn`,derived:true,turn:true};}if(/\b(?:goal\s+medal\s+finish|race\s+quality\s+finish|finish)\b/.test(t)&&defaultLength>0&&defaultLength<=25&&!/\bfins?\b/.test(t))return{start:Math.max(0,max-defaultLength),length:defaultLength,label:`last ${defaultLength}m`,derived:true};return null;}
  function imStrokeIndex(stroke){return{Butterfly:0,Backstroke:1,Breaststroke:2,Freestyle:3}[E.stroke(stroke)];}
  function pushFirst50(profile){return profile?.dive25!=null&&profile?.fifties?.[0]!=null?Math.max(0,(profile.fifties[0]-profile.dive25)*2):null;}
  function modelTarget(total,{sex,eventDistance,eventStroke,repDistance,line,resolvedStroke}){const profile=fiftyProfile(total,sex,eventDistance,eventStroke);if(!profile)return null;const t=text(line).toLowerCase(),named=namedSegment(t,eventDistance,repDistance),isIm=eventStroke==='IM',push=/\bpush(?:\s*start)?\b/.test(t),dive=/\bdive|race\s*start|from\s+blocks?\b/.test(t);if(named){const seconds=raceCumulative(profile,named.start+named.length)-raceCumulative(profile,named.start);return{seconds,source:named.turn?'Race pace model · turn-window estimate':named.derived?'Race pace model · derived segment':'Race pace model · race segment',label:named.label};}if(dive){const distance=Math.min(Number(repDistance)||0,Number(eventDistance)||0);return{seconds:raceCumulative(profile,distance),source:'Race pace model · start segment',label:`dive ${distance}m`};}if(push&&Number(repDistance)>0&&Number(repDistance)<=50){const push50=pushFirst50(profile);if(Number.isFinite(push50)&&push50>0)return{seconds:push50*(Number(repDistance)/50),source:'Race pace model · push-start estimate',label:`push ${repDistance}m`};}if(/\bmax(?:imum)?\b/.test(t)&&Number(repDistance)>0&&Number(repDistance)<=50){const distance=Number(repDistance),diveSeconds=raceCumulative(profile,distance),push50=pushFirst50(profile),pushSeconds=Number.isFinite(push50)&&push50>0?push50*(distance/50):null;if(Number.isFinite(diveSeconds)&&diveSeconds>0&&Number.isFinite(pushSeconds)&&pushSeconds>0)return{seconds:(diveSeconds+pushSeconds)/2,source:'Race pace model · dive/push blend',label:`max ${distance}m`};}if(isIm&&Number(eventDistance)===200){const index=imStrokeIndex(resolvedStroke);if(index==null)return null;let pace50=profile.fifties[index];if(index===0){const push50=pushFirst50(profile);if(push50!=null)pace50=push50;}return{seconds:pace50*(Number(repDistance)/50),source:`Race pace model · 200 IM ${E.stroke(resolvedStroke)} leg`,label:`${E.stroke(resolvedStroke)} leg`};}if(isIm&&Number(eventDistance)===400){const index=imStrokeIndex(resolvedStroke);if(index==null)return null;const first=profile.fifties[index*2],second=profile.fifties[index*2+1],pace50=index===0?second:(first+second)/2;return{seconds:pace50*(Number(repDistance)/50),source:`Race pace model · 400 IM ${E.stroke(resolvedStroke)} average`,label:`${E.stroke(resolvedStroke)} 400 IM pace`};}const nonDive=profile.fifties.slice(1),pace50=nonDive.length?nonDive.reduce((a,b)=>a+b,0)/nonDive.length:null;if(!pace50)return null;return{seconds:pace50*(Number(repDistance)/50),source:'Race pace model · non-dive average',label:`${eventDistance} pace`};}
  function racePace(pbSeconds,eventDistance,workDistance,{item,athlete,stroke,pbRow=null,course='SCM'}={}){const total=Number(pbSeconds),event=Number(eventDistance),work=Number(workDistance);if(!total||!event||!work)return null;const raw=text(item?.raw||item?.text),workStroke=E.stroke(item?.stroke||''),stored=knownSegment(pbRow,raw,event,work);if(stored)return stored;if(text(course).toUpperCase()!=='SCM')return{missing:true,message:'Race pace model is SCM-only · coach target required'};const sx=sexKey(athlete?.sex||athlete?.gender||pbRow?.sex||pbRow?.gender);if(!['M','F'].includes(sx))return{missing:true,message:'Sex required for Race pace model'};const eventStroke=E.stroke(stroke),resolvedStroke=eventStroke==='IM'&&workStroke&&workStroke!=='IM'?workStroke:eventStroke;if(!modelFor(sx,event,eventStroke))return{missing:true,message:`Race pace model not available for SCM ${event} ${eventStroke}`};const target=modelTarget(total,{sex:sx,eventDistance:event,eventStroke,repDistance:work,line:raw,resolvedStroke});return target||{missing:true,message:'Race pace model target unavailable'};}
  function forItem(session,item,ath,state,strokeOverride=''){
    const course=session?.identity?.course||'SCM';
    if(item?.repInstructions?.some(x=>x.raceIntent)){const rows=[],resolved=new Map(),anchors=new Map();for(const rep of item.repInstructions){if(!rep.raceIntent){rows.push({rep:rep.rep,status:'none',label:rep.label||'Build'});continue;}const extra=rep.label||'',intentOverride=effectiveIntentStroke(item,rep.raceIntent,strokeOverride,extra),specKey=`${rep.raceIntent.distance}|${intentOverride}|${strokeOverride||''}`;let st=resolved.get(specKey);if(st===undefined){st=resolveStroke({...item,raw:`${item.raw||''} ${extra}`},ath,state,course,intentOverride)||'';resolved.set(specKey,st);}if(!st){rows.push({rep:rep.rep,status:'missing',message:'#1 stroke needed'});continue;}const anchorKey=`${rep.raceIntent.distance}|${st}`;let p=anchors.get(anchorKey);if(p===undefined){p=anchor(ath,state,{distance:rep.raceIntent.distance,stroke:st,course})||null;anchors.set(anchorKey,p);}if(!p){rows.push({rep:rep.rep,status:'missing',message:`${st} PB needed`,stroke:st});continue;}const rp=racePace(p._anchor_seconds,rep.raceIntent.distance,item.distance,{item:{...item,raw:`${item.raw||''} ${extra}`},athlete:ath,stroke:st,pbRow:p,course});rows.push(rp?.missing?{rep:rep.rep,status:'missing',message:rp.message,stroke:st}:{rep:rep.rep,status:'ok',seconds:rp.seconds,sendOff:item.cycleSeconds||null,source:`${p._anchor_source} · ${rp.source}`,stroke:st,modeled:!!p._modeled,raceModel:true});}return{status:'rep_race',rows,stroke:rows.find(x=>x.stroke)?.stroke||''};}
    if(!item?.raceIntent)return{status:'none'};const intentOverride=effectiveIntentStroke(item,item.raceIntent,strokeOverride,''),st=resolveStroke(item,ath,state,course,intentOverride);if(!st)return{status:'missing',message:'#1 stroke needed'};const p=anchor(ath,state,{distance:item.raceIntent.distance,stroke:st,course});if(!p)return{status:'missing',message:`${st} PB needed`,stroke:st};const rp=racePace(p._anchor_seconds,item.raceIntent.distance,item.distance,{item,athlete:ath,stroke:st,pbRow:p,course});return rp?.missing?{status:'missing',message:rp.message,stroke:st}:{status:'ok',seconds:rp.seconds,sendOff:item.cycleSeconds||null,source:`${p._anchor_source} · ${rp.source}`,stroke:st,modeled:!!p._modeled,raceModel:true};
  }
  function invalidate(state){if(state&&typeof state==='object'){pbCache.delete(state);pathwayEnsured.delete(state);baseCache.delete(state);}}
  return{VERSION,convert,pb,anchor,modeledAnchor,pointInfo,inferredPoints,rankedEvents,bestEvent,bestStroke,resolveStroke,racePace,forItem,ensurePathway,invalidate,modelFor,fiftyProfile,raceCumulative,namedSegment,pushFirst50,RACE_MODEL};
});
