'use strict';
(function(root,factory){const api=factory(root.MSOSEngines?.Evidence,root);if(typeof module==='object'&&module.exports)module.exports=api;else{root.MSOSEngines=root.MSOSEngines||{};root.MSOSEngines.RacePace=api;}})(typeof globalThis!=='undefined'?globalThis:this,function(E,root){
  const VERSION='2.8.0';
  const CONVERSIONS=[[50,'Freestyle',.85],[50,'Backstroke',.85],[50,'Butterfly',.70],[50,'Breaststroke',1],[100,'Freestyle',1.70],[100,'Backstroke',1.70],[100,'Butterfly',1.40],[100,'Breaststroke',2],[200,'Freestyle',3.40],[200,'Backstroke',3.40],[200,'Butterfly',2.80],[200,'Breaststroke',4],[200,'IM',3.40],[400,'Freestyle',6.80],[400,'IM',6.80],[800,'Freestyle',13.60],[1500,'Freestyle',25.50]].map(([distance,stroke,seconds])=>({from:'SCM',to:'LCM',distance,stroke,seconds,source:'Swimming NZ official conversion table'}));
  const text=v=>String(v??'').replace(/\s+/g,' ').trim(),baseCache=new WeakMap(),pathwayEnsured=new WeakMap(),pbCache=new WeakMap();
  function convert(seconds,from,to,distance,stroke,state={}){if(!from||!to||from===to)return{seconds:Number(seconds),source:'Exact course'};const rows=[...(state?.courseConversions||state?.xlr8_course_conversions||[]),...CONVERSIONS],norm=x=>text(x).toUpperCase(),st=E.stroke(stroke);let r=rows.find(x=>norm(x.from_course||x.from)===norm(from)&&norm(x.to_course||x.to)===norm(to)&&Number(x.distance)===Number(distance)&&E.stroke(x.stroke)===st&&x.active!==false);if(r)return{seconds:Number(seconds)*Number(r.multiplier??1)+Number(r.seconds_adjustment??r.seconds??0),source:r.label||r.source_name||r.source||'Verified course conversion'};r=rows.find(x=>norm(x.from_course||x.from)===norm(to)&&norm(x.to_course||x.to)===norm(from)&&Number(x.distance)===Number(distance)&&E.stroke(x.stroke)===st&&x.active!==false);if(r)return{seconds:(Number(seconds)-Number(r.seconds_adjustment??r.seconds??0))/Number(r.multiplier??1),source:`Inverse · ${r.label||r.source_name||r.source||'verified course conversion'}`};return null;}
  function stateRevision(state){return`${Number(state?.settings?.storageRevision||0)}|${state?._evidenceBridge?.hydratedAt||''}|${state?.resultsPbBoard?.length||0}|${state?.resultsEventHistory?.length||0}|${state?.coachResults?.length||0}`;}
  function ensurePathway(ath,state,course){if(!ath||!state)return false;let row=pathwayEnsured.get(state);const rev=stateRevision(state);if(!row||row.rev!==rev){row={rev,set:new Set()};pathwayEnsured.set(state,row);}const k=`${ath.id||E.key?.(ath.full_name)||ath.full_name}|${text(course).toUpperCase()||'SCM'}`;if(row.set.has(k))return false;row.set.add(k);try{return Number(root.MSOS4?.engineBridge?.ensurePathwayAthlete?.(ath,text(course).toUpperCase()||'SCM')||0)>0;}catch{return false;}}
  function locatePb(rows,{distance,stroke,course},state){const wanted=E.stroke(stroke),c=text(course).toUpperCase();let hit=rows.filter(r=>E.distance(r)===Number(distance)&&E.rowStroke(r)===wanted&&(!c||!E.course(r)||E.course(r)===c)).sort((a,b)=>E.seconds(a)-E.seconds(b))[0];if(hit)return{...hit,_anchor_seconds:E.seconds(hit),_anchor_source:`${c||E.course(hit)||'Stored'} ${distance} ${wanted} PB`};const other=c==='SCM'?'LCM':c==='LCM'?'SCM':'';if(!other)return null;hit=rows.filter(r=>E.distance(r)===Number(distance)&&E.rowStroke(r)===wanted&&E.course(r)===other).sort((a,b)=>E.seconds(a)-E.seconds(b))[0];if(!hit)return null;const cv=convert(E.seconds(hit),other,c,distance,wanted,state);return cv?{...hit,_anchor_seconds:cv.seconds,_anchor_source:`${other} PB → ${c} · ${cv.source}`} : null;}
  function cacheFor(state){let row=pbCache.get(state),rev=stateRevision(state);if(!row||row.rev!==rev){row={rev,map:new Map()};pbCache.set(state,row);}return row.map;}
  function pb(ath,state,spec){const course=text(spec?.course).toUpperCase(),stroke=E.stroke(spec?.stroke),distance=Number(spec?.distance),key=`${ath?.id||E.key?.(ath?.full_name)||ath?.full_name}|${course}|${distance}|${stroke}`,map=cacheFor(state);if(map.has(key))return map.get(key);let rows=E.pbRows(ath,state),hit=locatePb(rows,{distance,stroke,course},state);if(!hit&&ensurePathway(ath,state,course)){rows=E.pbRows(ath,state);hit=locatePb(rows,{distance,stroke,course},state);}map.set(key,hit||null);return hit||null;}
  function modeledAnchor(ath,state,spec){try{const m=root.MSOS4?.performanceEngine?.modeledEvent?.(ath,state,{course:text(spec?.course).toUpperCase()||'SCM',distance:Number(spec?.distance),stroke:E.stroke(spec?.stroke||'')});if(!m?.seconds)return null;return{_anchor_seconds:m.seconds,_anchor_source:m.source,_modeled:true,_model:m,course:m.course,distance:m.distance,stroke:m.stroke,result_seconds:m.seconds};}catch{return null;}}
  function anchor(ath,state,spec){return pb(ath,state,spec)||modeledAnchor(ath,state,spec);}
  function baseTimes(state){return[...(state?.worldAquaticsBaseTimes||[]),...(state?._refs?.world_aquatics_base_times||[])];}
  function sexKey(v){const s=text(v).toUpperCase();if(/^(?:M|MALE|BOY|BOYS|MEN)$/.test(s))return'M';if(/^(?:F|FEMALE|GIRL|GIRLS|WOMEN)$/.test(s))return'F';if(/^(?:OPEN|MIXED|ALL)$/.test(s))return'OPEN';return'';}
  function baseIndex(state){if(!state||typeof state!=='object')return new Map();const rows=baseTimes(state),sig=`${state?.worldAquaticsBaseTimes?.length||0}|${state?._refs?.world_aquatics_base_times?.length||0}|${state?._evidenceBridge?.hydratedAt||''}`,old=baseCache.get(state);if(old?.sig===sig)return old.map;const map=new Map();for(const x of rows){if(!x||x.active===false)continue;const c=E.course(x),d=E.distance(x),st=E.rowStroke(x),sx=sexKey(x.sex||x.gender),b=Number(x.base_seconds??x.base_time_seconds??x.base_time);if(!c||!d||!st||!b)continue;const k=`${c}|${d}|${st}|${sx||'OPEN'}`;if(!map.has(k))map.set(k,{...x,base_seconds:b});}baseCache.set(state,{sig,map});return map;}
  function pointInfo(ath,row,state){try{const w=root.MSOS4?.waPointsEngine?.pointsFor?.(ath,row,state);if(w&&Number.isFinite(w.points)&&w.points>0)return w;}catch{}const t=E.seconds(row),d=E.distance(row),st=E.rowStroke(row),crs=E.course(row),sex=sexKey(ath?.sex||ath?.gender||row?.sex||row?.gender),idx=baseIndex(state),base=(sex&&idx.get(`${crs}|${d}|${st}|${sex}`))||idx.get(`${crs}|${d}|${st}|OPEN`);const b=Number(base?.base_seconds);if(b>0&&t>0)return{points:Math.floor(1000*Math.pow(b/t,3)),baseSeconds:b,tableVersion:base?.table_version||base?.version||'',source:base?.source||'WA base time',calculated:true};const p=E.points(row);return Number.isFinite(p)&&p>0?{points:Math.floor(p),tableVersion:'stored-result',source:'Stored result points',calculated:false}:null;}
  function inferredPoints(ath,row,state){return pointInfo(ath,row,state)?.points??NaN;}
  function rankedEvents(ath,state,course=''){let rows=E.pbRows(ath,state);if(!rows.length&&ensurePathway(ath,state,course))rows=E.pbRows(ath,state);const c=text(course).toUpperCase(),same=rows.filter(r=>!c||!E.course(r)||E.course(r)===c),pool=same.length?same:rows;return pool.map(r=>{const info=pointInfo(ath,r,state);return{row:r,distance:E.distance(r),stroke:E.rowStroke(r),course:E.course(r),score:info?.points??NaN,seconds:E.seconds(r),pointSource:info?.source||'',pointVersion:info?.tableVersion||'',baseSeconds:info?.baseSeconds??null};}).filter(x=>x.distance&&x.stroke&&Number.isFinite(x.score)&&x.score>0).sort((a,b)=>b.score-a.score||a.seconds-b.seconds);}
  function bestEvent(ath,state,course=''){return rankedEvents(ath,state,course)[0]||null;}
  function bestStroke(ath,state,course='',nonFree=false){const allowed=nonFree?['Backstroke','Breaststroke','Butterfly']:['Freestyle','Backstroke','Breaststroke','Butterfly'];return rankedEvents(ath,state,course).find(x=>allowed.includes(x.stroke))?.stroke||'';}
  function contextualStroke(item,ath,state,course,formOnly=false){try{const r=root.MSOS4?.performanceEngine?.selectStrokeForContext?.(ath,item,state,{identity:{course}},{formOnly});if(r?.stroke)return E.stroke(r.stroke);}catch{}return bestStroke(ath,state,course,formOnly);}
  function resolveStroke(item,ath,state,course,override=''){if(override&&override!=='AUTO')return E.stroke(override);const raw=text(item?.raw||item?.text);if(/#\s*1F\b/i.test(raw))return contextualStroke(item,ath,state,course,true);if(/#\s*1\b/i.test(raw))return contextualStroke(item,ath,state,course,false);const st=E.stroke(item?.stroke||'');return['Freestyle','Backstroke','Breaststroke','Butterfly','IM'].includes(st)?st:bestStroke(ath,state,course,false);}
  function knownSegment(row,raw,eventDistance,workDistance){if(!row)return null;const n=k=>{const v=Number(row?.[k]);return Number.isFinite(v)&&v>0?v:null};if(eventDistance===200&&workDistance===100&&/\b(?:second|2nd|last|final)\s*100\b/i.test(raw)){const v=n('second_100_seconds')||n('second100_seconds')||n('last_100_seconds')||n('back_100_seconds');if(v)return{seconds:v,source:'Stored 200 race second-100 split'};return{missing:true,message:'200 race second-100 split needed'};}if(eventDistance===200&&workDistance===100&&/\b(?:first|1st)\s*100\b/i.test(raw)){const v=n('first_100_seconds')||n('first100_seconds');if(v)return{seconds:v,source:'Stored 200 race first-100 split'};return{missing:true,message:'200 race first-100 split needed'};}return null;}
  function racePace(pbSeconds,eventDistance,workDistance,{item,athlete,stroke,pbRow=null}={}){const total=Number(pbSeconds),event=Number(eventDistance),work=Number(workDistance);if(!total||!event||!work)return null;const raw=text(item?.raw||item?.text),workStroke=E.stroke(item?.stroke||'');if(stroke==='IM'&&workStroke&&workStroke!=='IM')return{missing:true,message:'Exact IM leg race model not loaded'};const stored=knownSegment(pbRow,raw,event,work);if(stored)return stored;const sx=text(athlete?.sex||athlete?.gender).toUpperCase();if(event===100&&stroke==='Freestyle'&&/^M/.test(sx)){if(/\b(?:first|1st)\s*50\b/i.test(raw))return{seconds:total*.4754,source:'100 Free first 50 model'};if(/\b(?:second|2nd|last)\s*50\b/i.test(raw))return{seconds:total*.5246,source:'100 Free second 50 model'};if(/\b(?:dive|race\s*start|start)\b/i.test(raw)&&work<=25){const first=total*.4754,dive=first*.4554;return{seconds:dive*(work/25),source:'100 Free start model'};}}
    if(/\b(?:first|1st|second|2nd|last|final|dive|race\s*start|start|push|turn|finish)\b/i.test(raw))return{missing:true,message:'Exact race segment evidence/model needed'};return{seconds:total*(work/event),source:'PB race-pace average'};}
  function forItem(session,item,ath,state,strokeOverride=''){
    const course=session?.identity?.course||'SCM';
    if(item?.repInstructions?.some(x=>x.raceIntent)){const rows=[],resolved=new Map(),anchors=new Map();for(const rep of item.repInstructions){if(!rep.raceIntent){rows.push({rep:rep.rep,status:'none',label:rep.label||'Build'});continue;}const specKey=`${rep.raceIntent.distance}|${rep.raceIntent.eventStroke||item.raceIntent?.eventStroke||''}|${strokeOverride||''}`;let st=resolved.get(specKey);if(st===undefined){st=resolveStroke({...item,raw:`${item.raw||''} ${rep.label||''}`},ath,state,course,strokeOverride||rep.raceIntent.eventStroke||item.raceIntent?.eventStroke||'')||'';resolved.set(specKey,st);}if(!st){rows.push({rep:rep.rep,status:'missing',message:'#1 stroke needed'});continue;}const anchorKey=`${rep.raceIntent.distance}|${st}`;let p=anchors.get(anchorKey);if(p===undefined){p=anchor(ath,state,{distance:rep.raceIntent.distance,stroke:st,course})||null;anchors.set(anchorKey,p);}if(!p){rows.push({rep:rep.rep,status:'missing',message:`${st} PB needed`,stroke:st});continue;}const rp=racePace(p._anchor_seconds,rep.raceIntent.distance,item.distance,{item:{...item,raw:`${item.raw||''} ${rep.label||''}`},athlete:ath,stroke:st,pbRow:p});rows.push(rp?.missing?{rep:rep.rep,status:'missing',message:rp.message,stroke:st}:{rep:rep.rep,status:'ok',seconds:rp.seconds,sendOff:item.cycleSeconds||null,source:`${p._anchor_source} · ${rp.source}`,stroke:st,modeled:!!p._modeled});}return{status:'rep_race',rows,stroke:rows.find(x=>x.stroke)?.stroke||''};}
    if(!item?.raceIntent)return{status:'none'};const st=resolveStroke(item,ath,state,course,strokeOverride||item.raceIntent.eventStroke||'');if(!st)return{status:'missing',message:'#1 stroke needed'};const p=anchor(ath,state,{distance:item.raceIntent.distance,stroke:st,course});if(!p)return{status:'missing',message:`${st} PB needed`,stroke:st};const rp=racePace(p._anchor_seconds,item.raceIntent.distance,item.distance,{item,athlete:ath,stroke:st,pbRow:p});return rp?.missing?{status:'missing',message:rp.message,stroke:st}:{status:'ok',seconds:rp.seconds,sendOff:item.cycleSeconds||null,source:`${p._anchor_source} · ${rp.source}`,stroke:st,modeled:!!p._modeled};
  }
  function invalidate(state){if(state&&typeof state==='object'){pbCache.delete(state);pathwayEnsured.delete(state);baseCache.delete(state);}}
  return{VERSION,convert,pb,anchor,modeledAnchor,pointInfo,inferredPoints,rankedEvents,bestEvent,bestStroke,resolveStroke,racePace,forItem,ensurePathway,invalidate};
});
