'use strict';
(function(g){
  const M=g.MSOS4,U=M?.util;if(!M?.reportingEngine||!M?.strokeBalance)return;
  const R=M.reportingEngine,UI=M.reportingUI={build:'v4-reporting-ui-20260820p'};
  const esc=v=>U.escape(String(v??'')),clock=s=>U.clock(Number(s)),short=s=>String(s||'').replace('Freestyle','Fr').replace('Backstroke','Bk').replace('Breaststroke','Br').replace('Butterfly','Fly');
  function go(view){if(M.navigationEngine?.go)return M.navigationEngine.go(view,{restore:false});return M.nav?.show?.(view,{restoreScroll:false});}
  function bars(sum,kind='weighted'){const map=sum?.[kind]||{},total=kind==='weighted'?sum?.totalWeighted:sum?.totalRaw;return M.strokeBalance.STROKES.map(st=>{const v=Number(map[st]||0),pct=total?v/total*100:0;return `<div class="perf-bar"><span>${esc(short(st))}</span><div><i style="width:${Math.max(0,pct)}%"></i></div><b>${pct.toFixed(0)}%${kind==='raw'?` · ${Math.round(v)}m`:''}</b></div>`}).join('');}
  function selectedMetrics(){return[...document.querySelectorAll('#reportsView [data-report-metric]:checked')].map(x=>x.value);}
  function renderResults(h,spec){const report=R.run(spec,M.state),show=new Set(report.spec.metrics);let html=`<section class="page-card"><div class="eyebrow">REPORT OUTPUT</div><div class="perf-kpis"><div><span>Swimmers</span><b>${report.summary.athletes}</b></div><div><span>Raw metres</span><b>${Math.round(report.summary.rawMetres).toLocaleString()}m</b></div><div><span>T400 anchors</span><b>${report.summary.t400Anchors}</b></div><div><span>Timed / captures</span><b>${report.summary.recentTimedSets} / ${report.summary.captures}</b></div></div></section>`;
    if(show.has('stroke_focus'))html+=`<section class="page-card"><h2>Stroke focus · ${report.spec.days||'all'} day${report.spec.days===1?'':'s'}</h2><div class="perf-two"><div><h3>Weighted focus</h3>${bars(report.aggregate,'weighted')}</div><div><h3>Raw metres</h3>${bars(report.aggregate,'raw')}</div></div><p class="muted">Weighted focus is an exposure measure, not a causal claim. Raw metres remain beside it so the methodology is auditable.</p></section>`;
    html+=`<section class="page-card"><h2>${report.spec.scope==='swimmer'?'Swimmer detail':'Squad detail'}</h2><div class="report-table">${report.rows.map(r=>`<button class="report-row" data-report-ath="${esc(r.athleteId)}"><span><b>${esc(r.name)}</b><small>${esc(r.squad)}</small></span>${show.has('performance')?`<span><b>${esc(r.bestEvent)}</b><small>${r.bestEventPoints?`${r.bestEventPoints} WA`:r.pbCount?'PBs · no rank':'#1 needed'}</small></span>`:''}${show.has('stroke_focus')?`<span><b>${esc(r.medleyPrimary?`IM · ${short(r.contextStroke||'stroke needed')}`:short(r.bestStroke||'#1 needed'))}</b><small>${M.strokeBalance.STROKES.map(s=>`${short(s)} ${Math.round(r.strokeBalance.share[s]||0)}%`).join(' · ')}</small></span>`:''}${show.has('tests')?`<span><b>${Object.keys(r.t400||{}).length} T400</b><small>${Object.values(r.t400||{}).map(x=>`${short(x.stroke)} ${clock(x.seconds)}`).join(' · ')||'No anchors'}</small></span>`:''}${show.has('timed')?`<span><b>${r.timedSets.length} timed</b><small>${r.timedSets[0]?esc(r.timedSets[0].set_label||'latest saved'):'No recent timing'}</small></span>`:''}${show.has('volume')?`<span><b>${Math.round(r.strokeBalance.totalRaw).toLocaleString()}m</b><small>${r.sessionCount} session${r.sessionCount===1?'':'s'}</small></span>`:''}${show.has('evidence')?`<span><b>${r.captureCount} captures</b><small>${r.modifiedSessions} modified session${r.modifiedSessions===1?'':'s'}</small></span>`:''}</button>`).join('')||'<p class="muted">No swimmers matched this report.</p>'}</div></section>`;
    h.querySelector('#reportOutput').innerHTML=html;h.querySelectorAll('[data-report-ath]').forEach(b=>b.onclick=()=>{M.state.settings.selectedAthleteId=b.dataset.reportAth;M.storageEngine?.saveUi?.(M.state);go('athletes');});
  }
  function render(){const h=document.querySelector('#reportsView');if(!h)return;const role=M.access?.role?.()||'owner',squads=R.squads(M.state),athletes=R.visibleAthletes(M.state).sort((a,b)=>String(a.full_name).localeCompare(String(b.full_name))),own=role==='swimmer'?M.state.settings.activeUserAthleteId:'',scope=role==='swimmer'?'swimmer':(M.state.settings.reportScope||'squad'),days=Number(M.state.settings.reportDays||7),athId=own||M.state.settings.reportAthleteId||M.state.settings.selectedAthleteId||'',squad=M.state.settings.reportSquad||M.currentSession?.()?.identity?.squads?.[0]||'';h.innerHTML=`<section class="page-card"><div class="eyebrow">REPORTING ENGINE</div><h1>Reports</h1><p>Build reports from the engines that own session truth, performance, tests, timing, attendance, evidence and stroke exposure. Reporting selects and groups those facts; it does not invent them.</p><div class="report-controls"><label>Scope<select id="reportScope" ${role==='swimmer'?'disabled':''}><option value="squad" ${scope==='squad'?'selected':''}>Squad</option><option value="swimmer" ${scope==='swimmer'?'selected':''}>Swimmer</option></select></label><label>Window<select id="reportDays"><option value="7" ${days===7?'selected':''}>7 days</option><option value="14" ${days===14?'selected':''}>14 days</option><option value="28" ${days===28?'selected':''}>28 days</option><option value="0" ${days===0?'selected':''}>All loaded</option></select></label><label>Squad<select id="reportSquad" ${role==='swimmer'?'disabled':''}><option value="">All squads</option>${squads.map(x=>`<option value="${esc(x)}" ${x===squad?'selected':''}>${esc(x)}</option>`).join('')}</select></label><label>Swimmer<select id="reportAthlete" ${role==='swimmer'?'disabled':''}><option value="">All swimmers</option>${athletes.map(a=>`<option value="${esc(a.id)}" ${a.id===athId?'selected':''}>${esc(a.full_name)}</option>`).join('')}</select></label></div><div class="report-metrics">${R.METRICS.map(m=>`<label><input type="checkbox" data-report-metric value="${esc(m.id)}" checked> ${esc(m.label)}</label>`).join('')}</div><div class="hub-actions"><button id="runReport">Run report</button><button id="reportBackPerformance">Swimmer performance</button><button id="reportTimes">Times / T400</button></div><details><summary>Available report fields</summary>${R.FIELDS.map(f=>`<div class="perf-evidence"><b>${esc(f.label)}</b><span>${esc(f.source)}</span></div>`).join('')}</details></section><div id="reportOutput"></div>`;
    const run=()=>{const nextScope=role==='swimmer'?'swimmer':h.querySelector('#reportScope').value,nextDays=Number(h.querySelector('#reportDays').value),nextSquad=role==='swimmer'?'':h.querySelector('#reportSquad').value,nextAth=role==='swimmer'?own:h.querySelector('#reportAthlete').value;M.state.settings.reportScope=nextScope;M.state.settings.reportDays=nextDays;M.state.settings.reportSquad=nextSquad;M.state.settings.reportAthleteId=nextAth;M.storageEngine?.saveUi?.(M.state);renderResults(h,{scope:nextScope,days:nextDays,squad:nextScope==='squad'?nextSquad:'',athleteId:nextScope==='swimmer'?nextAth:'',metrics:selectedMetrics()});};
    h.querySelector('#runReport').onclick=run;h.querySelector('#reportBackPerformance').onclick=()=>{const id=role==='swimmer'?own:(h.querySelector('#reportAthlete').value||athId);if(id)M.state.settings.selectedAthleteId=id;go('athletes');};h.querySelector('#reportTimes').onclick=()=>go('times');run();
  }
  UI.render=render;M.renderReports=render;
})(globalThis);
