'use strict';
(function(g){
  const M=g.MSOS4,U=M?.util;if(!M?.reportingEngine||!M?.strokeBalance)return;
  const R=M.reportingEngine,UI=M.reportingUI={build:'v4-reporting-ui-20260820u'};
  const esc=v=>U.escape(String(v??'')),clock=s=>U.clock(Number(s)),short=s=>String(s||'').replace('Freestyle','Fr').replace('Backstroke','Bk').replace('Breaststroke','Br').replace('Butterfly','Fly');
  function go(view){if(M.navigationEngine?.go)return M.navigationEngine.go(view,{restore:false});return M.nav?.show?.(view,{restoreScroll:false});}
  function bars(sum,kind='weighted'){const map=sum?.[kind]||{},total=kind==='weighted'?sum?.totalWeighted:sum?.totalRaw;return M.strokeBalance.STROKES.map(st=>{const v=Number(map[st]||0),pct=total?v/total*100:0;return `<div class="perf-bar"><span>${esc(short(st))}</span><div><i style="width:${Math.max(0,pct)}%"></i></div><b>${pct.toFixed(0)}%${kind==='raw'?` · ${Math.round(v)}m`:''}</b></div>`}).join('');}
  function selectedMetrics(){return[...document.querySelectorAll('#reportsView [data-report-metric]:checked')].map(x=>x.value);}
  function refLine(report){const wa=report.references?.wa,std=report.references?.standards;return`WA points: ${wa?.active?`${esc(wa.version||'active')} · ${wa.rows} rows`:'not active'} · Pathway standards: ${std?esc(std.version||'active'):'registry version not active'}`;}
  function renderResults(h,spec){const report=R.run(spec,M.state),show=new Set(report.spec.metrics);let html=`<section class="page-card"><div class="eyebrow">REPORT OUTPUT</div><div class="perf-kpis"><div><span>Swimmers</span><b>${report.summary.athletes}</b></div><div><span>WA ranked</span><b>${report.summary.rankedAthletes}</b></div><div><span>Pathway matched</span><b>${report.summary.pathwayMatched}</b></div><div><span>T400 / timed</span><b>${report.summary.t400Anchors} / ${report.summary.recentTimedSets}</b></div></div><p class="muted">${refLine(report)}</p></section>`;
    if(show.has('stroke_focus'))html+=`<section class="page-card"><h2>Stroke focus · ${report.spec.days||'all'} day${report.spec.days===1?'':'s'}</h2><div class="perf-two"><div><h3>Weighted focus</h3>${bars(report.aggregate,'weighted')}</div><div><h3>Raw metres</h3>${bars(report.aggregate,'raw')}</div></div><p class="muted">Weighted focus is an exposure measure, not a causal claim. Raw metres remain beside it so the methodology is auditable.</p></section>`;
    if(show.has('reference_data'))html+=`<section class="page-card"><h2>Reference versions used</h2><div class="summary-grid"><span>WA points</span><b>${esc(report.references?.wa?.version||'No active table')}</b><span>National standards</span><b>${esc(report.references?.nationalStandards?.version||'No registry version')}</b><span>Meet QTs</span><b>${esc(report.references?.meetQualifying?.version||'No registry version')}</b><span>Last data update</span><b>${esc(report.references?.lastImport?.label||'—')}</b></div><p class="muted">Changing an active reference version recalculates dependent performance/pathway reporting; historical result times remain unchanged.</p></section>`;
    html+=`<section class="page-card"><h2>${report.spec.scope==='swimmer'?'Swimmer detail':'Squad detail'} · ${esc(report.spec.course)}</h2><div class="report-table">${report.rows.map(r=>`<button class="report-row" data-report-ath="${esc(r.athleteId)}"><span><b>${esc(r.name)}</b><small>${esc(r.squad)}</small></span>${show.has('performance')?`<span><b>${esc(r.bestEvent)}</b><small>${r.bestEventPoints!=null?`${r.bestEventPoints} WA${r.bestEventPointVersion?` · ${esc(r.bestEventPointVersion)}`:''}`:r.pbCount?`${r.pbCount} PBs · WA rank unavailable`:'#1 needed'}</small></span>`:''}${show.has('pathway')?`<span><b>${esc(r.pathway?.event||'Pathway target needed')}</b><small>${r.pathway?.event?`${esc(r.pathway.label||'Next standard')} · ${Number.isFinite(r.pathway.gapSeconds)?`${r.pathway.gapSeconds.toFixed(2)}s`:''}${Number.isFinite(r.pathway.gapPercent)?` · ${r.pathway.gapPercent.toFixed(1)}%`:''}`:r.pathway?.classificationNeeded?'Classification needed':'No matched target'}</small></span>`:''}${show.has('stroke_focus')?`<span><b>${esc(r.medleyPrimary?`IM · ${short(r.contextStroke||'stroke needed')}`:short(r.bestStroke||'#1 needed'))}</b><small>${M.strokeBalance.STROKES.map(s=>`${short(s)} ${Math.round(r.strokeBalance.share[s]||0)}%`).join(' · ')}</small></span>`:''}${show.has('tests')?`<span><b>${Object.keys(r.t400||{}).length} T400</b><small>${Object.values(r.t400||{}).map(x=>`${short(x.stroke)} ${clock(x.seconds)}`).join(' · ')||'No anchors'}</small></span>`:''}${show.has('timed')?`<span><b>${r.timedSets.length} timed</b><small>${r.timedSets[0]?esc(r.timedSets[0].set_label||'latest saved'):'No recent timing'}</small></span>`:''}${show.has('volume')?`<span><b>${Math.round(r.strokeBalance.totalRaw).toLocaleString()}m</b><small>${r.sessionCount} session${r.sessionCount===1?'':'s'}</small></span>`:''}${show.has('evidence')?`<span><b>${r.captureCount} captures</b><small>${r.modifiedSessions} modified session${r.modifiedSessions===1?'':'s'}</small></span>`:''}</button>`).join('')||'<p class="muted">No swimmers matched this report.</p>'}</div></section>`;
    h.querySelector('#reportOutput').innerHTML=html;h.querySelectorAll('[data-report-ath]').forEach(b=>b.onclick=()=>{M.state.settings.selectedAthleteId=b.dataset.reportAth;M.storageEngine?.saveUi?.(M.state);go('athletes');});
  }
  function render(){const h=document.querySelector('#reportsView');if(!h)return;const role=M.access?.role?.()||'owner',squads=R.squads(M.state),athletes=R.visibleAthletes(M.state).sort((a,b)=>String(a.full_name).localeCompare(String(b.full_name))),own=role==='swimmer'?M.state.settings.activeUserAthleteId:'',scope=role==='swimmer'?'swimmer':(M.state.settings.reportScope||'squad'),days=M.state.settings.reportDays===undefined?7:Number(M.state.settings.reportDays),course=M.state.settings.reportCourse||M.state.settings.pathwayCourse||'SCM';let athId=own||M.state.settings.reportAthleteId||M.state.settings.selectedAthleteId||'';if(scope==='swimmer'&&!athId)athId=athletes[0]?.id||'';const squad=M.state.settings.reportSquad||M.currentSession?.()?.identity?.squads?.[0]||'';h.innerHTML=`<section class="page-card"><div class="eyebrow">REPORTING ENGINE</div><h1>Reports</h1><p>Reporting pulls facts from the engines that own them. Reference updates such as WA base times or new qualifying standards flow through the dependent engines and change the report without rewriting historical results.</p><div class="report-controls"><label>Scope<select id="reportScope" ${role==='swimmer'?'disabled':''}><option value="squad" ${scope==='squad'?'selected':''}>Squad</option><option value="swimmer" ${scope==='swimmer'?'selected':''}>Swimmer</option></select></label><label>Window<select id="reportDays"><option value="7" ${days===7?'selected':''}>7 days</option><option value="14" ${days===14?'selected':''}>14 days</option><option value="28" ${days===28?'selected':''}>28 days</option><option value="0" ${days===0?'selected':''}>All loaded</option></select></label><label>Course<select id="reportCourse"><option value="SCM" ${course==='SCM'?'selected':''}>SCM</option><option value="LCM" ${course==='LCM'?'selected':''}>LCM</option></select></label><label>Squad<select id="reportSquad" ${role==='swimmer'?'disabled':''}><option value="">All squads</option>${squads.map(x=>`<option value="${esc(x)}" ${x===squad?'selected':''}>${esc(x)}</option>`).join('')}</select></label><label>Swimmer<select id="reportAthlete" ${role==='swimmer'?'disabled':''}><option value="">All swimmers</option>${athletes.map(a=>`<option value="${esc(a.id)}" ${a.id===athId?'selected':''}>${esc(a.full_name)}</option>`).join('')}</select></label></div><div class="report-metrics">${R.METRICS.map(m=>`<label><input type="checkbox" data-report-metric value="${esc(m.id)}" checked> ${esc(m.label)}</label>`).join('')}</div><div class="hub-actions"><button id="runReport">Run report</button><button id="reportBackPerformance">Swimmer performance</button><button id="reportTimes">Times / Tests / T400</button><button data-msos-data>Data & References</button></div><details><summary>Available report fields</summary>${R.FIELDS.map(f=>`<div class="perf-evidence"><b>${esc(f.label)}</b><span>${esc(f.source)}</span></div>`).join('')}</details></section><div id="reportOutput"></div>`;
    const run=()=>{const nextScope=role==='swimmer'?'swimmer':h.querySelector('#reportScope').value,nextDays=Number(h.querySelector('#reportDays').value),nextCourse=h.querySelector('#reportCourse').value,nextSquad=role==='swimmer'?'':h.querySelector('#reportSquad').value;let nextAth=role==='swimmer'?own:h.querySelector('#reportAthlete').value;if(nextScope==='swimmer'&&!nextAth)nextAth=athletes[0]?.id||'';M.state.settings.reportScope=nextScope;M.state.settings.reportDays=nextDays;M.state.settings.reportCourse=nextCourse;M.state.settings.reportSquad=nextSquad;M.state.settings.reportAthleteId=nextAth;M.storageEngine?.saveUi?.(M.state);renderResults(h,{scope:nextScope,days:nextDays,course:nextCourse,squad:nextScope==='squad'?nextSquad:'',athleteId:nextScope==='swimmer'?nextAth:'',metrics:selectedMetrics()});};
    h.querySelector('#runReport').onclick=run;h.querySelector('#reportBackPerformance').onclick=()=>{const id=role==='swimmer'?own:(h.querySelector('#reportAthlete').value||athId);if(id)M.state.settings.selectedAthleteId=id;go('athletes');};h.querySelector('#reportTimes').onclick=()=>go('times');run();M.dataAdminUI?.ensureShortcut?.('reports');
  }
  UI.render=render;M.renderReports=render;
  const baseHub=M.ui?.renderHub?.bind(M.ui);if(baseHub)M.ui.renderHub=(...a)=>{const out=baseHub(...a),host=document.querySelector('#hubView');if(host&&!host.querySelector('[data-msos-reports]'))host.insertAdjacentHTML('afterbegin','<section class="page-card"><div class="eyebrow">REPORTING</div><div class="hub-actions"><button data-msos-reports>Reports · squad / swimmer / evidence</button></div></section>');M.dataAdminUI?.ensureShortcut?.('hub');return out;};
  const boot=()=>{if(M.state?.settings?.view==='reports'){render();M.nav?.activateView?.('reports');}};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
  addEventListener('msos:data-updated',()=>{if((M.state?.settings?.view||'')==='reports')render();});
})(globalThis);
