'use strict';
(function(g){
  const M=g.MSOS4;if(!M?.store)return;
  const S=M.storageEngine={build:'v4-storage-authority-20260825-boot-readonly'};
  const DB='mclay_swimming_v4_operational_state',STORE='state',KEY='latest',UI_KEY='mclay_swimming_os_v4_ui',GUARDIAN_KEY='mclay_swimming_os_v4_guardian',UI_DB_KEY='ui',GUARDIAN_DB_KEY='guardian',LOCAL_LIMIT=3200000;
  let writeChain=Promise.resolve(),metaWriteChain=Promise.resolve(),knownAttendance=new Map(),indexedMode=false,uiCache=null,guardianCache=null;
  const clone=v=>{try{return structuredClone(v)}catch{try{return JSON.parse(JSON.stringify(v))}catch{return v}}},selectedSession=s=>s?.settings?.selectedSessionId||'',currentMeet=s=>s?.settings?.currentMeetId||'',sessionCount=s=>Object.keys(s?.canonicalSessions||{}).length,now=()=>M.util?.now?.()||new Date().toISOString();
  const attendanceKey=r=>`${r.session_id}|${r.athlete_id}`;
  const guardianRun=r=>({ok:r?.ok===true,passed:Number(r?.passed)||0,total:Number(r?.total)||0,at:r?.at||'',build:r?.build||'',contract:r?.contract||'',tests:Array.isArray(r?.tests)?r.tests.slice(0,20).map(t=>({name:String(t?.name||''),ok:t?.ok===true,detail:String(t?.detail||'').slice(0,240)})):[]});
  function normalizeGuardian(state){if(!state)return state;state.guardian=state.guardian&&typeof state.guardian==='object'?state.guardian:{runs:[]};state.guardian.runs=(Array.isArray(state.guardian.runs)?state.guardian.runs:[]).slice(-3).map(guardianRun);return state}
  function normalizeRestorableUi(state){if(!state)return state;state.settings=state.settings||{};if(state.settings.view==='guardian')state.settings.view='board';return state}
  function legacyRead(key){try{return JSON.parse(localStorage.getItem(key)||'null')}catch{return null}}
  function readGuardian(){const x=guardianCache||legacyRead(GUARDIAN_KEY);return Array.isArray(x?.runs)?x.runs.slice(-3).map(guardianRun):[]}
  function applyGuardian(state){if(!state)return;normalizeGuardian(state);const saved=readGuardian();if(saved.length)state.guardian.runs=saved}
  function saveGuardianResult(result){if(!M.state)return result;normalizeGuardian(M.state);M.state.guardian.runs=[...(M.state.guardian.runs||[]),guardianRun(result)].slice(-3);guardianCache={runs:M.state.guardian.runs,savedAt:Date.now()};queueMeta(GUARDIAN_DB_KEY,guardianCache);return M.state.guardian.runs.at(-1)}
  function ensurePresence(state){state.attendance=state.attendance||[];state.presenceEvents=state.presenceEvents||[];state.attendanceSnapshots=state.attendanceSnapshots||{};const next=new Map(),touched=new Set();for(const r of state.attendance){if(!r?.session_id||!r?.athlete_id)continue;const k=attendanceKey(r),sig=`${r.status||''}|${r.updated_at||''}`;next.set(k,sig);if(knownAttendance.get(k)!==sig){state.presenceEvents.push({id:M.util?.uid?.('presence')||`presence-${Date.now()}-${Math.random()}`,session_id:r.session_id,athlete_id:r.athlete_id,status:r.status||'absent',at:r.updated_at||now(),source:'attendance_change'});touched.add(r.session_id)}}knownAttendance=next;for(const sid of touched){const rows=state.attendance.filter(x=>x.session_id===sid),present=rows.filter(x=>['present','modified','late'].includes(String(x.status||'').toLowerCase()));state.attendanceSnapshots[sid]={session_id:sid,rows:clone(rows),present_ids:present.map(x=>x.athlete_id),count:present.length,source:'attendance_change',updated_at:now()}}}
  function openDb(){return new Promise((resolve,reject)=>{try{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error||new Error('IndexedDB open failed'))}catch(e){reject(e)}})}
  async function putRecord(key,payload){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(payload,key);tx.oncomplete=()=>{db.close();resolve(true)};tx.onerror=()=>{const e=tx.error;db.close();reject(e||new Error('IndexedDB write failed'))};tx.onabort=()=>{const e=tx.error;db.close();reject(e||new Error('IndexedDB write aborted'))}})}
  async function getRecord(key){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly'),q=tx.objectStore(STORE).get(key);q.onsuccess=()=>{const v=q.result||null;db.close();resolve(v)};q.onerror=()=>{const e=q.error;db.close();reject(e||new Error('IndexedDB read failed'))}})}
  async function putFull(snap){return putRecord(KEY,{savedAt:Date.now(),revision:Number(snap?.settings?.storageRevision||0),payload:snap})}
  async function getFull(){return getRecord(KEY)}
  function queueMeta(key,payload){const snap=clone(payload);metaWriteChain=metaWriteChain.catch(()=>{}).then(()=>putRecord(key,{savedAt:Date.now(),payload:snap})).then(()=>{S.lastMetaPersistedAt=Date.now();S.lastMetaError='';return true}).catch(e=>{S.lastMetaError=String(e?.message||e);return false});return true}
  async function loadMeta(){try{const [uiRow,guardianRow]=await Promise.all([getRecord(UI_DB_KEY),getRecord(GUARDIAN_DB_KEY)]);if(uiRow?.payload)uiCache=uiRow.payload;else{const legacy=legacyRead(UI_KEY);if(legacy){uiCache=legacy;queueMeta(UI_DB_KEY,legacy)}}if(guardianRow?.payload)guardianCache=guardianRow.payload;else{const legacy=legacyRead(GUARDIAN_KEY);if(legacy){guardianCache=legacy;queueMeta(GUARDIAN_DB_KEY,legacy)}}}catch(e){S.lastMetaError=String(e?.message||e);uiCache=legacyRead(UI_KEY);guardianCache=legacyRead(GUARDIAN_KEY)}}
  function compact(state){const sid=selectedSession(state),mid=currentMeet(state),sessions={};if(sid&&state?.canonicalSessions?.[sid])sessions[sid]=state.canonicalSessions[sid];const attendance=(state?.attendance||[]).filter(x=>!sid||x.sessionId===sid||x.session_id===sid).slice(-300),overrides=(state?.adaptationOverrides||[]).filter(x=>x?.active!==false&&(!sid||!x.sessionId||x.sessionId===sid)).slice(-300),meetEntries=(state?.meetEntries||[]).filter(x=>!mid||x.meetId===mid||x.meet_id===mid).slice(-300),meetRaces=(state?.meetRaces||[]).filter(x=>!mid||x.meetId===mid||x.meet_id===mid).slice(-300);return normalizeGuardian({schema:4,build:M.BUILD,canonicalSessions:sessions,athletes:state?.athletes||[],attendance,presenceEvents:(state?.presenceEvents||[]).slice(-500),attendanceSnapshots:state?.attendanceSnapshots||{},captures:[],timedSets:(state?.timedSets||[]).slice(-20),trainingTestTypes:state?.trainingTestTypes||state?.training_test_types||[],trainingTestResults:(state?.trainingTestResults||state?.training_test_results||[]).slice(-80),adaptationProfiles:state?.adaptationProfiles||state?.athlete_adaptation_profiles||[],adaptationOverrides:overrides,coachResults:[],athleteAchievements:(state?.athleteAchievements||[]).slice(-50),meets:mid?(state?.meets||[]).filter(x=>x.id===mid):(state?.meets||[]).slice(-5),meetEntries,meetRaces,meetEvidence:[],settings:{...(state?.settings||{}),storageMode:'indexeddb',storageCompacted:true},pending:[],guardian:clone(state?.guardian||{runs:[]})})}
  function writeLocalCompact(state){const payload=JSON.stringify(compact(state));try{localStorage.setItem(M.STORAGE_KEY,payload);return true}catch(e){try{localStorage.removeItem(M.STORAGE_KEY);localStorage.setItem(M.STORAGE_KEY,payload);return true}catch{return false}}}
  function uiSnapshot(state){const s=state?.settings||{},view=s.view==='guardian'?'board':(s.view||'board');return{view,selectedSessionId:s.selectedSessionId||'',selectedAthleteId:s.selectedAthleteId||'',selectedSwimmerId:s.selectedSwimmerId||'',loopAthleteTab:s.loopAthleteTab||'performance',pathwayCourse:s.pathwayCourse||'SCM',boardExpandedTargetId:s.boardExpandedTargetId||'',boardFocusMode:s.boardFocusMode!==false,boardBlockBySession:s.boardBlockBySession||{},t400Stroke:s.t400Stroke||'Freestyle',t400PreferredAthleteId:s.t400PreferredAthleteId||'',v4TimingMode:s.v4TimingMode||'t400',reportScope:s.reportScope||'squad',reportDays:s.reportDays===undefined?7:Number(s.reportDays),reportCourse:s.reportCourse||s.pathwayCourse||'SCM',reportSquad:s.reportSquad||'',reportAthleteId:s.reportAthleteId||'',currentMeetId:s.currentMeetId||'',sessionScroll:s.sessionScroll||{},viewScroll:s.viewScroll||{},savedAt:Date.now()}}
  function saveUi(state=M.state){try{uiCache=uiSnapshot(state);queueMeta(UI_DB_KEY,uiCache);return true}catch(e){S.lastUiError=String(e?.message||e);return false}}
  function readUi(){return uiCache||legacyRead(UI_KEY)||null}
  function applyUi(state){const ui=readUi();if(!state)return;state.settings=state.settings||{};if(ui)for(const[k,v]of Object.entries(ui))if(k!=='savedAt'&&v!==undefined)state.settings[k]=v;normalizeRestorableUi(state)}
  function publish(state){try{M.live?.publishState?.(state)}catch{}}
  function queueFull(state,{compactAfter=false}={}){const snap=clone(normalizeGuardian(state));writeChain=writeChain.catch(()=>{}).then(()=>putFull(snap)).then(()=>{if(compactAfter)writeLocalCompact(snap);S.lastPersistedAt=Date.now();S.lastError='';return true}).catch(e=>{S.lastError=String(e?.message||e);return false});return writeChain}
  M.store.save=state=>{if(state!==M.state){S.blockedForeignStateSaves=Number(S.blockedForeignStateSaves||0)+1;return state}state.build=M.BUILD;state.settings=state.settings||{};normalizeGuardian(state);ensurePresence(state);if(!S.ready){S.preHydrationSaveRequests=Number(S.preHydrationSaveRequests||0)+1;saveUi(state);return state}if(M.live&&!M.live.suppress)state.settings.liveRevision=Number(state.settings.liveRevision||0)+1;state.settings.storageRevision=Number(state.settings.storageRevision||0)+1;
    const useIndexed=indexedMode||state.settings.storageMode==='indexeddb';
    if(useIndexed){indexedMode=true;state.settings.storageMode='indexeddb';queueFull(state);saveUi(state);publish(state);return state}
    let json='';try{json=JSON.stringify(state)}catch{}
    const oversized=json.length>LOCAL_LIMIT;
    if(!oversized){try{localStorage.setItem(M.STORAGE_KEY,json)}catch{indexedMode=true;state.settings.storageMode='indexeddb';queueFull(state,{compactAfter:true});saveUi(state);publish(state);return state}}
    else{indexedMode=true;state.settings.storageMode='indexeddb';queueFull(state,{compactAfter:true})}
    if(!oversized)queueFull(state);
    saveUi(state);publish(state);return state};
  S.save=M.store.save;S.saveUi=saveUi;S.readUi=readUi;S.applyUi=applyUi;S.compact=compact;S.putFull=putFull;S.getFull=getFull;S.ensurePresence=ensurePresence;S.normalizeGuardian=normalizeGuardian;S.normalizeRestorableUi=normalizeRestorableUi;S.saveGuardianResult=saveGuardianResult;S.readGuardian=readGuardian;S.loadMeta=loadMeta;
  async function hydrate(){try{await loadMeta();const row=await getFull();if(!row?.payload){applyUi(M.state);normalizeGuardian(M.state);applyGuardian(M.state);normalizeRestorableUi(M.state);knownAttendance=new Map((M.state.attendance||[]).filter(x=>x?.session_id&&x?.athlete_id).map(x=>[attendanceKey(x),`${x.status||''}|${x.updated_at||''}`]));indexedMode=M.state?.settings?.storageMode==='indexeddb';S.ready=true;requestAnimationFrame(()=>M.ui?.renderCurrent?.());return}const local=M.state||{},full=normalizeGuardian(row.payload),localRev=Number(local?.settings?.storageRevision||0),fullRev=Number(row.revision||full?.settings?.storageRevision||0),localSessions=sessionCount(local),fullSessions=sessionCount(full),localRicher=localSessions>fullSessions,useFull=(local?.settings?.storageMode==='indexeddb'||fullRev>=localRev)&&!localRicher;if(useFull){const preserved={...(full.settings||{}),...(local.settings||{})};for(const k of Object.keys(local))delete local[k];Object.assign(local,clone(full));local.settings=preserved;M.state=local;M.release?.ensure?.();S.hydratedFromIndexedDb=true}else if(localRicher)S.recoveredRicherLocalState=true;applyUi(M.state);normalizeGuardian(M.state);applyGuardian(M.state);normalizeRestorableUi(M.state);indexedMode=useFull||M.state?.settings?.storageMode==='indexeddb';if(indexedMode)M.state.settings.storageMode='indexeddb';knownAttendance=new Map((M.state.attendance||[]).filter(x=>x?.session_id&&x?.athlete_id).map(x=>[attendanceKey(x),`${x.status||''}|${x.updated_at||''}`]));S.ready=true;requestAnimationFrame(()=>M.ui?.renderCurrent?.())}catch(e){S.lastError=String(e?.message||e);applyUi(M.state);normalizeGuardian(M.state);applyGuardian(M.state);normalizeRestorableUi(M.state);indexedMode=M.state?.settings?.storageMode==='indexeddb';S.ready=true;requestAnimationFrame(()=>M.ui?.renderCurrent?.())}}
  S.ready=false;S.readyPromise=hydrate();
})(globalThis);
