'use strict';
(function(g){
  const M=g.MSOS4;if(!M?.store)return;
  const S=M.storageEngine={build:'v4-storage-authority-20260825-guardian-suppress'};
  const DB='mclay_swimming_v4_operational_state',STORE='state',KEY='latest',UI_KEY='mclay_swimming_os_v4_ui',LOCAL_LIMIT=3200000;
  let writeChain=Promise.resolve(),deferredLiveSave=false,knownAttendance=new Map(),suppressDepth=0;
  const clone=v=>{try{return structuredClone(v)}catch{try{return JSON.parse(JSON.stringify(v))}catch{return v}}},selectedSession=s=>s?.settings?.selectedSessionId||'',currentMeet=s=>s?.settings?.currentMeetId||'',sessionCount=s=>Object.keys(s?.canonicalSessions||{}).length,now=()=>M.util?.now?.()||new Date().toISOString();
  const attendanceKey=r=>`${r.session_id}|${r.athlete_id}`;
  function ensurePresence(state){state.attendance=state.attendance||[];state.presenceEvents=state.presenceEvents||[];state.attendanceSnapshots=state.attendanceSnapshots||{};const next=new Map(),touched=new Set();for(const r of state.attendance){if(!r?.session_id||!r?.athlete_id)continue;const k=attendanceKey(r),sig=`${r.status||''}|${r.updated_at||''}`;next.set(k,sig);if(knownAttendance.get(k)!==sig){state.presenceEvents.push({id:M.util?.uid?.('presence')||`presence-${Date.now()}-${Math.random()}`,session_id:r.session_id,athlete_id:r.athlete_id,status:r.status||'absent',at:r.updated_at||now(),source:'attendance_change'});touched.add(r.session_id)}}knownAttendance=next;for(const sid of touched){const rows=state.attendance.filter(x=>x.session_id===sid),present=rows.filter(x=>['present','modified','late'].includes(String(x.status||'').toLowerCase()));state.attendanceSnapshots[sid]={session_id:sid,rows:clone(rows),present_ids:present.map(x=>x.athlete_id),count:present.length,source:'attendance_change',updated_at:now()}}}
  function openDb(){return new Promise((resolve,reject)=>{try{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error||new Error('IndexedDB open failed'))}catch(e){reject(e)}})}
  async function putFull(state){const snap=clone(state),db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put({savedAt:Date.now(),revision:Number(state?.settings?.storageRevision||0),payload:snap},KEY);tx.oncomplete=()=>{db.close();resolve(true)};tx.onerror=()=>{const e=tx.error;db.close();reject(e||new Error('IndexedDB write failed'))};tx.onabort=()=>{const e=tx.error;db.close();reject(e||new Error('IndexedDB write aborted'))}})}
  async function getFull(){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly'),q=tx.objectStore(STORE).get(KEY);q.onsuccess=()=>{const v=q.result||null;db.close();resolve(v)};q.onerror=()=>{const e=q.error;db.close();reject(e||new Error('IndexedDB read failed'))}})}
  function compact(state){const sid=selectedSession(state),mid=currentMeet(state),sessions={};if(sid&&state?.canonicalSessions?.[sid])sessions[sid]=state.canonicalSessions[sid];const attendance=(state?.attendance||[]).filter(x=>!sid||x.sessionId===sid||x.session_id===sid).slice(-300),overrides=(state?.adaptationOverrides||[]).filter(x=>x?.active!==false&&(!sid||!x.sessionId||x.sessionId===sid)).slice(-300),meetEntries=(state?.meetEntries||[]).filter(x=>!mid||x.meetId===mid||x.meet_id===mid).slice(-300),meetRaces=(state?.meetRaces||[]).filter(x=>!mid||x.meetId===mid||x.meet_id===mid).slice(-300);return{schema:4,build:M.BUILD,canonicalSessions:sessions,athletes:state?.athletes||[],attendance,presenceEvents:(state?.presenceEvents||[]).slice(-500),attendanceSnapshots:state?.attendanceSnapshots||{},captures:[],timedSets:(state?.timedSets||[]).slice(-20),trainingTestTypes:state?.trainingTestTypes||state?.training_test_types||[],trainingTestResults:(state?.trainingTestResults||state?.training_test_results||[]).slice(-80),adaptationProfiles:state?.adaptationProfiles||state?.athlete_adaptation_profiles||[],adaptationOverrides:overrides,coachResults:[],athleteAchievements:(state?.athleteAchievements||[]).slice(-50),meets:mid?(state?.meets||[]).filter(x=>x.id===mid):(state?.meets||[]).slice(-5),meetEntries,meetRaces,meetEvidence:[],settings:{...(state?.settings||{}),storageMode:'indexeddb',storageCompacted:true},pending:[],guardian:{runs:(state?.guardian?.runs||[]).slice(-3)}}}
  function writeLocalCompact(state){const payload=JSON.stringify(compact(state));try{localStorage.setItem(M.STORAGE_KEY,payload);return true}catch(e){try{localStorage.removeItem(M.STORAGE_KEY);localStorage.setItem(M.STORAGE_KEY,payload);return true}catch{return false}}}
  function uiSnapshot(state){const s=state?.settings||{};return{view:s.view||'board',selectedSessionId:s.selectedSessionId||'',selectedAthleteId:s.selectedAthleteId||'',selectedSwimmerId:s.selectedSwimmerId||'',loopAthleteTab:s.loopAthleteTab||'performance',pathwayCourse:s.pathwayCourse||'SCM',boardExpandedTargetId:s.boardExpandedTargetId||'',boardFocusMode:s.boardFocusMode!==false,boardBlockBySession:s.boardBlockBySession||{},t400Stroke:s.t400Stroke||'Freestyle',t400PreferredAthleteId:s.t400PreferredAthleteId||'',v4TimingMode:s.v4TimingMode||'t400',reportScope:s.reportScope||'squad',reportDays:s.reportDays===undefined?7:Number(s.reportDays),reportCourse:s.reportCourse||s.pathwayCourse||'SCM',reportSquad:s.reportSquad||'',reportAthleteId:s.reportAthleteId||'',currentMeetId:s.currentMeetId||'',sessionScroll:s.sessionScroll||{},viewScroll:s.viewScroll||{},savedAt:Date.now()}}
  function saveUi(state=M.state){try{localStorage.setItem(UI_KEY,JSON.stringify(uiSnapshot(state)));S.lastUiPersistedAt=Date.now();return true}catch{return false}}function readUi(){try{return JSON.parse(localStorage.getItem(UI_KEY)||'null')||null}catch{return null}}function applyUi(state){const ui=readUi();if(!ui||!state)return;state.settings=state.settings||{};for(const[k,v]of Object.entries(ui))if(k!=='savedAt'&&v!==undefined)state.settings[k]=v}function publish(state){try{M.live?.publishState?.(state)}catch{}}
  function queueFull(state,{compactAfter=false}={}){const snap=clone(state);writeChain=writeChain.catch(()=>{}).then(()=>putFull(snap)).then(()=>{if(compactAfter)writeLocalCompact(snap);S.lastPersistedAt=Date.now();S.lastError='';return true}).catch(e=>{S.lastError=String(e?.message||e);return false});return writeChain}
  M.store.save=state=>{if(state!==M.state){S.blockedForeignStateSaves=Number(S.blockedForeignStateSaves||0)+1;return state}if(suppressDepth>0){S.suppressedSaves=Number(S.suppressedSaves||0)+1;return state}state.build=M.BUILD;state.settings=state.settings||{};ensurePresence(state);if(!S.ready){deferredLiveSave=true;saveUi(state);return state}if(M.live&&!M.live.suppress)state.settings.liveRevision=Number(state.settings.liveRevision||0)+1;state.settings.storageRevision=Number(state.settings.storageRevision||0)+1;let json='';try{json=JSON.stringify(state)}catch{}const oversized=json.length>LOCAL_LIMIT;if(!oversized){try{localStorage.setItem(M.STORAGE_KEY,json)}catch{queueFull(state,{compactAfter:true});saveUi(state);publish(state);return state}}else queueFull(state,{compactAfter:true});if(!oversized)queueFull(state,{compactAfter:false});saveUi(state);publish(state);return state};
  S.withSuppressedWrites=fn=>{suppressDepth++;try{return fn()}finally{suppressDepth=Math.max(0,suppressDepth-1)}};
  S.save=M.store.save;S.saveUi=saveUi;S.readUi=readUi;S.applyUi=applyUi;S.compact=compact;S.putFull=putFull;S.getFull=getFull;S.ensurePresence=ensurePresence;
  async function hydrate(){try{const row=await getFull();if(!row?.payload){applyUi(M.state);knownAttendance=new Map((M.state.attendance||[]).filter(x=>x?.session_id&&x?.athlete_id).map(x=>[attendanceKey(x),`${x.status||''}|${x.updated_at||''}`]));S.ready=true;M.store.save(M.state);return}const local=M.state||{},full=row.payload,localRev=Number(local?.settings?.storageRevision||0),fullRev=Number(row.revision||full?.settings?.storageRevision||0),localSessions=sessionCount(local),fullSessions=sessionCount(full),localRicher=localSessions>fullSessions,useFull=(local?.settings?.storageMode==='indexeddb'||fullRev>=localRev)&&!localRicher;if(useFull){const preserved={...(full.settings||{}),...(local.settings||{})};for(const k of Object.keys(local))delete local[k];Object.assign(local,clone(full));local.settings=preserved;M.state=local;M.release?.ensure?.();S.hydratedFromIndexedDb=true}else if(localRicher)S.recoveredRicherLocalState=true;applyUi(M.state);knownAttendance=new Map((M.state.attendance||[]).filter(x=>x?.session_id&&x?.athlete_id).map(x=>[attendanceKey(x),`${x.status||''}|${x.updated_at||''}`]));S.ready=true;if(deferredLiveSave||localRicher)M.store.save(M.state);requestAnimationFrame(()=>M.ui?.renderCurrent?.())}catch(e){S.lastError=String(e?.message||e);applyUi(M.state);S.ready=true;if(deferredLiveSave)M.store.save(M.state)}}
  S.ready=false;S.readyPromise=hydrate();
})(globalThis);
