'use strict';
(function(g){
  const M=g.MSOS4,E=g.MSOSEngines;if(!M||!E?.Evidence||!E?.Modification)return;
  const B=M.strokeBalance={build:'v4-stroke-balance-20260820p'};
  const STROKES=['Freestyle','Backstroke','Breaststroke','Butterfly'];
  const WEIGHTS=Object.freeze({easy:.25,regeneration:.25,development:.45,overload:.70,threshold:.85,clearance:1,race:1,sprint:1.10,technical:.70,default:.35,incidentalFree:.20});
  const text=v=>String(v??'').replace(/\s+/g,' ').trim();
  const dayMs=86400000;
  const dateOf=s=>Date.parse(`${s?.identity?.date||''}T12:00:00`)||0;
  function attendance(session,ath,state){const rows=(state?.attendance||[]).filter(x=>x.session_id===session?.id||x.sessionId===session?.id);if(rows.length){const r=rows.find(x=>(x.athlete_id||x.athleteId)===ath?.id);return{included:!!r&&['present','modified','late'].includes(String(r.status||'').toLowerCase()),source:'attendance',status:r?.status||'absent'};}const squads=session?.identity?.squads||[];return{included:!!ath?.squad&&squads.includes(ath.squad),source:'squad_assumption',status:'assumed'};}
  function weight(item){const raw=text([item?.zone,item?.raw,item?.text,...(item?.cues||[]),...(item?.repInstructions||[]).map(x=>x.label||'')].join(' ')).toLowerCase();if(/\b(?:max|sprint)\b/.test(raw))return WEIGHTS.sprint;if(/race\s*(?:pace|quality)|\b(?:50|100|200|400|800|1500)\s*(?:m\s*)?(?:race\s*)?pace\b/.test(raw))return WEIGHTS.race;if(/clearance|\bcl\b/.test(raw))return WEIGHTS.clearance;if(/threshold|\bthr\b|\bat\b/.test(raw))return WEIGHTS.threshold;if(/overload|\bol\b/.test(raw))return WEIGHTS.overload;if(/development|\bdev\b/.test(raw))return WEIGHTS.development;if(/regeneration|\bregen\b|\breg\b|\beasy\b|recovery|reset|warm.?down|cool.?down/.test(raw))return WEIGHTS.easy;if(/drill|scull|technique|skill|stroke count/.test(raw))return WEIGHTS.technical;const st=E.Evidence.stroke(item?.stroke||'');if(st==='Freestyle')return WEIGHTS.incidentalFree;return WEIGHTS.default;}
  function splitStroke(item,total){const out=[];const comp=item?.composition||[];if(comp.length){for(const c of comp){const st=E.Evidence.stroke(c?.stroke||c?.text||'');if(STROKES.includes(st))out.push({stroke:st,metres:Number(c.distance)||0});else if(/\bIM\b/i.test(text(c?.text)))for(const s of STROKES)out.push({stroke:s,metres:(Number(c.distance)||0)/4});}const sum=out.reduce((n,x)=>n+x.metres,0);if(sum>0){const scale=total/sum;return out.map(x=>({...x,metres:x.metres*scale}));}}
    const st=E.Evidence.stroke(item?.stroke||'');if(st==='IM'||/\bIM\b/i.test(text(item?.raw||item?.text)))return STROKES.map(s=>({stroke:s,metres:total/4}));if(STROKES.includes(st))return[{stroke:st,metres:total}];const raw=text(item?.raw||item?.text);for(const s of STROKES){const token=s==='Freestyle'?/\b(?:free|freestyle|fr)\b/i:s==='Backstroke'?/\b(?:back|backstroke|bk)\b/i:s==='Breaststroke'?/\b(?:breast|breaststroke|br)\b/i:/\b(?:fly|butterfly)\b/i;if(token.test(raw))return[{stroke:s,metres:total}];}return[];
  }
  function walk(items,mult,fn){for(const n of items||[]){if(n?.kind==='group'){walk(n.items||[],mult*Math.max(1,Number(n.rounds)||1),fn);continue;}if(n?.kind==='set')fn(n,mult);}}
  function sessionDose(session,ath,state=M.state){const att=attendance(session,ath,state),raw=Object.fromEntries(STROKES.map(s=>[s,0])),weighted=Object.fromEntries(STROKES.map(s=>[s,0]));if(!att.included)return{included:false,raw,weighted,totalRaw:0,totalWeighted:0,attendance:att};for(const block of session?.blocks||[])walk(block.items||[],1,(item,mult)=>{let actual=item;try{actual=E.Modification.adaptItem(item,ath,state,session)||item}catch{}const metres=Math.max(1,Number(actual.reps)||1)*Math.max(0,Number(actual.distance)||0)*mult,w=weight(actual);for(const x of splitStroke(actual,metres)){raw[x.stroke]+=x.metres;weighted[x.stroke]+=x.metres*w;}});return{included:true,raw,weighted,totalRaw:Object.values(raw).reduce((a,b)=>a+b,0),totalWeighted:Object.values(weighted).reduce((a,b)=>a+b,0),attendance:att};}
  function rangeSessions(state,days=7,anchorDate=''){const all=Object.values(state?.canonicalSessions||{}),anchor=anchorDate?Date.parse(`${anchorDate}T23:59:59`):Math.max(Date.now(),...all.map(dateOf));if(!days)return all.filter(s=>dateOf(s)<=anchor);const cut=anchor-days*dayMs;return all.filter(s=>{const d=dateOf(s);return d&&d<=anchor&&d>cut;});}
  function summary(ath,state=M.state,{days=7,anchorDate=''}={}){const raw=Object.fromEntries(STROKES.map(s=>[s,0])),weighted=Object.fromEntries(STROKES.map(s=>[s,0]));let sessions=0,assumedSessions=0;for(const s of rangeSessions(state,days,anchorDate)){const d=sessionDose(s,ath,state);if(!d.included)continue;sessions++;if(d.attendance.source==='squad_assumption')assumedSessions++;for(const st of STROKES){raw[st]+=d.raw[st];weighted[st]+=d.weighted[st];}}const tr=Object.values(raw).reduce((a,b)=>a+b,0),tw=Object.values(weighted).reduce((a,b)=>a+b,0),share=Object.fromEntries(STROKES.map(s=>[s,tw?weighted[s]/tw*100:0]));return{athleteId:ath?.id,days,sessions,assumedSessions,raw,weighted,share,totalRaw:tr,totalWeighted:tw,weights:WEIGHTS};}
  function weeklyEmphasis(state=M.state,anchorDate=''){const scores=new Map(),sessions=rangeSessions(state,7,anchorDate).sort((a,b)=>dateOf(b)-dateOf(a));for(const s of sessions){const meta=text([s?.metadata?.technicalFocus,s?.metadata?.planCue,s?.metadata?.primarySystem,s?.identity?.title].join(' '));for(const st of STROKES){const re=st==='Freestyle'?/\b(?:free|freestyle)\b/i:st==='Backstroke'?/\bback/i:st==='Breaststroke'?/\bbreast/i:/\b(?:fly|butterfly)\b/i;if(re.test(meta))scores.set(st,(scores.get(st)||0)+1);}}return[...scores].sort((a,b)=>b[1]-a[1])[0]?.[0]||'';}
  function recommendStroke(ath,state=M.state,session=null,{formOnly=false}={}){const perf=M.performanceEngine,course=session?.identity?.course||'',event=perf?.bestEvent?.(ath,state,course),ranked=perf?.rankedEvents?.(ath,state,course)||[],allowed=(formOnly?['Backstroke','Breaststroke','Butterfly']:STROKES).filter(st=>ranked.some(r=>r.stroke===st));if(!allowed.length)return{stroke:'',source:'No ranked PB evidence for an applicable stroke',confidence:'none'};if(event?.stroke!=='IM'){const best=ranked.find(r=>allowed.includes(r.stroke));return best?{stroke:best.stroke,source:'Highest ranked stroke PB',confidence:'high',bestEvent:event}:null;}
    const emphasis=weeklyEmphasis(state,session?.identity?.date||'');if(emphasis&&allowed.includes(emphasis))return{stroke:emphasis,source:`IM balance · weekly ${emphasis} emphasis`,confidence:'high',bestEvent:event};
    const coach=perf?.selectedCoachStroke?.(ath,state,14);if(coach&&allowed.includes(coach))return{stroke:coach,source:`IM balance · recent coach ${coach} selections`,confidence:'medium',bestEvent:event};
    const bal=summary(ath,state,{days:7,anchorDate:session?.identity?.date||''}),ordered=allowed.map(st=>({stroke:st,share:bal.share[st]||0})).sort((a,b)=>a.share-b.share);return{stroke:ordered[0].stroke,source:`IM balance · lowest 7-day weighted exposure (${ordered[0].share.toFixed(0)}%)`,confidence:bal.sessions>=2?'medium':'low',bestEvent:event,balance:bal};
  }
  B.STROKES=STROKES;B.WEIGHTS=WEIGHTS;B.weight=weight;B.sessionDose=sessionDose;B.summary=summary;B.weeklyEmphasis=weeklyEmphasis;B.recommendStroke=recommendStroke;B.rangeSessions=rangeSessions;
})(globalThis);
