'use strict';
(function(g){
  const M=g.MSOS4;if(!M?.ui||!M?.state)return;
  const UI=M.ui,U=M.util||{},S=M.swimmerTabsUI={build:'v4-swimmer-tabs-20260821aj'};
  const text=v=>U.text?U.text(v):String(v??'').replace(/\s+/g,' ').trim();
  const esc=v=>U.escape?U.escape(String(v??'')):String(v??'');
  const clock=v=>U.clock?U.clock(Number(v)):String(v??'—');
  const norm=v=>text(v).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
  const currentSession=()=>M.currentSession?.()||null;
  const save=()=>{try{M.storageEngine?.saveUi?.(M.state)}catch{}try{M.store?.save?.(M.state)}catch{}};
  const go=(view,opts={})=>M.navigationEngine?.go?M.navigationEngine.go(view,{restore:false,...opts}):M.nav?.show?.(view,{restoreScroll:false,...opts});
  M.BUILD='v4-swimmer-tabs-20260821aj';M.CORE='20260821-swimmer-tabs-aj';
  M.RELEASE_ATTESTATION=Object.freeze({...(M.RELEASE_ATTESTATION||{}),build:M.BUILD,softwareReady:false,generatedAt:new Date().toISOString(),note:'Swimmer tabs field build over accepted coach-loop branch. Real-phone acceptance required.'});

  function captureBelongs(c,ath){const ids=[...(c?.athlete_ids||c?.swimmer_ids||[])];if(c?.athlete_id&&!ids.includes(c.athlete_id))ids.push(c.athlete_id);return ids.includes(ath?.id)}
  function attending(session=currentSession()){
    const ids=new Set((M.state.attendance||[]).filter(x=>x.session_id===session?.id&&['present','modified','late'].includes(norm(x.status))).map(x=>x.athlete_id));
    const explicit=(M.state.athletes||[]).filter(a=>a.active!==false&&ids.has(a.id));if(explicit.length)return explicit;
    return(UI.presentAthletes?.()||[]).filter(a=>a?.active!==false);
  }
  function boardName(a,pool){return M.boardEngine?.name?.(a,pool)||text(a?.preferred_name||a?.nickname||a?.full_name).split(' ')[0]||'Swimmer'}
  function openAthlete(ath){const s=currentSession();if(!ath||!s)return;M.state.settings.selectedAthleteId=ath.id;M.state.settings.loopAthleteTab='today';M.state.settings.loopAthleteOrigin={sessionId:s.id,blockId:M.state.settings.boardBlockBySession?.[s.id]||'',scrollY:window.scrollY,openedAt:new Date().toISOString()};save();if(M.state.settings.view==='athletes')UI.renderAthletes?.();else go('athletes');}
  function installDeckPills(){
    document.querySelector('#boardView [data-loop-attendees]')?.remove();
    document.querySelector('[data-msos-deck-athletes]')?.remove();
    const s=currentSession(),header=document.querySelector('.app-header');if(!s||!header)return;
    const rows=attending(s);if(!rows.length)return;
    const box=document.createElement('section');box.dataset.msosDeckAthletes='1';box.className='msos-deck-athletes';
    box.innerHTML=`<div class="msos-deck-label"><b>Here</b><small>tap swimmer</small></div><div class="msos-deck-scroll">${rows.map(a=>{const n=(M.state.captures||[]).filter(c=>c.session_id===s.id&&captureBelongs(c,a)).length;return`<button data-msos-deck-ath="${esc(a.id)}"><span>${esc(boardName(a,rows))}</span>${n?`<small>${n}</small>`:''}</button>`}).join('')}</div>`;
    const anchor=header.querySelector('.squad-row');if(anchor)anchor.insertAdjacentElement('afterend',box);else header.append(box);
    box.querySelectorAll('[data-msos-deck-ath]').forEach(b=>b.onclick=()=>openAthlete(rows.find(a=>a.id===b.dataset.msosDeckAth)));
  }

  function realMilestones(event){
    const pb=event?.pb,pbSeconds=Number(pb?.result_seconds);if(!pb||!Number.isFinite(pbSeconds))return[];
    const rows=[...(event?.qualifying||[]),...(event?.deeper||[])].map(r=>({...r,_seconds:Number(r?._seconds??M.pathway?.seconds?.(r)),_kind:r?._kind||M.pathway?.kind?.(r)||'performance',_label:text(r?._label||M.pathway?.standardLabel?.(r)||r?.name||'Milestone')})).filter(r=>Number.isFinite(r._seconds)&&r._seconds>0);
    const seen=new Set(),out=[];for(const r of rows){const k=`${norm(r._label)}|${r._seconds.toFixed(2)}`;if(seen.has(k))continue;seen.add(k);out.push(r)}
    out.sort((a,b)=>b._seconds-a._seconds||(Number(a.progression_order)||999)-(Number(b.progression_order)||999));
    return out.map(r=>({...r,achieved:pbSeconds<=r._seconds,gapSeconds:Math.max(0,pbSeconds-r._seconds),gapPercentage:r._seconds>0?Math.max(0,(pbSeconds-r._seconds)/r._seconds*100):0}));
  }
  function milestoneKind(r){const k=norm(r?._kind),l=norm(r?._label);if(k==='record'||/record/.test(l))return'Record';if(/medal|3rd|bronze|silver|gold/.test(l))return'Medal';if(/winner|1st/.test(l))return'Winner';if(/finalist|final|8th/.test(l))return'Final';if(k==='qualifying'||/qualif|champ|nags|nzsc|division/.test(l))return'Qualifying';if(k==='squad')return'Target';return'Milestone'}
  function pathwayEvents(ath,course){let p=null;try{p=M.pathway?.profile?.(ath,course)}catch{}const rows=(p?.events||[]).filter(e=>e?.pb);return rows.sort((a,b)=>{const an=realMilestones(a).find(x=>!x.achieved),bn=realMilestones(b).find(x=>!x.achieved),ag=an?an.gapPercentage:Infinity,bg=bn?bn.gapPercentage:Infinity;return ag-bg||Number(a.pb.distance||0)-Number(b.pb.distance||0)||String(a.pb.stroke||'').localeCompare(String(b.pb.stroke||''))})}
  function pathEventCard(event){const pb=event.pb,pbSeconds=Number(pb.result_seconds),steps=realMilestones(event),next=steps.find(x=>!x.achieved)||null,seq=[...steps.map(x=>({type:'step',seconds:x._seconds,row:x})),{type:'pb',seconds:pbSeconds}].sort((a,b)=>b.seconds-a.seconds);return `<section class="page-card msos-path-event"><div class="msos-path-head"><div><div class="eyebrow">${esc(`${pb.course||''} ${pb.distance} ${pb.stroke}`.trim())}</div><h3>PB ${clock(pbSeconds)}</h3></div>${next?`<strong>Next · ${esc(next._label)}</strong>`:'<strong>All loaded steps achieved</strong>'}</div>${next?`<p><b>${esc(milestoneKind(next))}</b> · ${clock(next._seconds)} · ${next.gapSeconds.toFixed(2)}s (${next.gapPercentage.toFixed(1)}%)</p>`:'<p class="muted">No faster loaded meet/benchmark milestone is ahead of this PB.</p>'}<div class="msos-path-ladder">${seq.map(x=>x.type==='pb'?`<div class="msos-path-step current"><small>Current PB</small><b>${clock(pbSeconds)}</b></div>`:`<div class="msos-path-step ${x.row.achieved?'achieved':'upcoming'}"><small>${esc(milestoneKind(x.row))}</small><b>${esc(x.row._label)}</b><span>${clock(x.row._seconds)}</span>${x.row.achieved?'<em>✓ achieved</em>':''}</div>`).join('')}</div></section>`}
  function buildPathway(ath,course){const wrap=document.createElement('div'),events=pathwayEvents(ath,course);wrap.className='msos-pathway';if(!events.length){wrap.innerHTML='<section class="page-card"><h2>Pathway</h2><p class="muted">No verified PB-to-standard pathway is loaded for this swimmer/course.</p></section>';return wrap}const latest=(M.state.captures||[]).filter(c=>captureBelongs(c,ath)).sort((a,b)=>String(b.created_at||'').localeCompare(String(a.created_at||'')))[0],source=norm([latest?.title,latest?.text_content,latest?.capture_note,latest?.context_label].join(' '));let stroke='';if(/butterfly|\bfly\b/.test(source))stroke='Butterfly';else if(/breaststroke|\bbreast\b/.test(source))stroke='Breaststroke';else if(/backstroke|\bback\b/.test(source))stroke='Backstroke';else if(/freestyle|\bfree\b/.test(source))stroke='Freestyle';const preferred=events.find(e=>stroke&&text(e.pb.stroke)===stroke)||events[0];wrap.innerHTML=`<section class="page-card msos-pathway-head"><div class="eyebrow">PERFORMANCE PATHWAY</div><h2>Real milestones in performance order</h2><p class="muted">Meet qualifying times, finalist/medal benchmarks and records.</p><div class="msos-event-tabs">${events.map(e=>`<button data-msos-path-event="${esc(`${e.pb.distance}|${e.pb.stroke}`)}" class="${e===preferred?'active':''}">${esc(`${e.pb.distance} ${e.pb.stroke}`)}</button>`).join('')}</div></section><div data-msos-path-host></div>`;const host=wrap.querySelector('[data-msos-path-host]');const render=e=>{host.innerHTML=pathEventCard(e);wrap.querySelectorAll('[data-msos-path-event]').forEach(b=>b.classList.toggle('active',b.dataset.msosPathEvent===`${e.pb.distance}|${e.pb.stroke}`))};wrap.querySelectorAll('[data-msos-path-event]').forEach(b=>b.onclick=()=>{const [d,st]=b.dataset.msosPathEvent.split('|'),e=events.find(x=>String(x.pb.distance)===d&&String(x.pb.stroke)===st);if(e)render(e)});render(preferred);return wrap}

  function allRaces(ath){const entries=new Map((M.state.meetEntries||[]).map(e=>[e.id,e])),meets=new Map((M.state.meets||[]).map(m=>[m.id,m]));return(M.state.meetRaces||[]).filter(r=>r.athlete_id===ath.id&&r.status==='complete').sort((a,b)=>String(b.completed_at||b.updated_at||'').localeCompare(String(a.completed_at||a.updated_at||''))).map(r=>({race:r,entry:entries.get(r.entry_id)||{},meet:meets.get(r.meet_id)||{}}))}
  function upcoming(ath){const meets=new Map((M.state.meets||[]).map(m=>[m.id,m])),today=currentSession()?.identity?.date||new Date().toISOString().slice(0,10);return(M.state.meetEntries||[]).filter(e=>e.athlete_id===ath.id&&!['complete','scratched'].includes(norm(e.status))).map(e=>({entry:e,meet:meets.get(e.meet_id)||{}})).filter(x=>!x.meet.date||x.meet.date>=today).sort((a,b)=>String(a.meet.date||'9999').localeCompare(String(b.meet.date||'9999'))||(Number(a.entry.event_number)||9999)-(Number(b.entry.event_number)||9999))}
  function buildMeet(ath){const wrap=document.createElement('div'),up=upcoming(ath),races=allRaces(ath),ev=(M.state.meetEvidence||[]).filter(x=>x.athlete_id===ath.id).sort((a,b)=>String(b.created_at||'').localeCompare(String(a.created_at||'')));wrap.innerHTML=`<section class="page-card"><div class="eyebrow">MEET / RACE HISTORY</div><h2>${esc(ath.full_name)}</h2>${up.length?`<h3>Upcoming</h3><div class="loop-capture-list">${up.map(x=>`<article><button data-msos-meet-entry="${esc(x.entry.id)}"><b>${esc(x.entry.event||`${x.entry.distance||''} ${x.entry.stroke||''}`)}</b><span>${esc([x.meet.title||x.meet.name,x.meet.date,x.entry.round].filter(Boolean).join(' · '))}</span></button></article>`).join('')}</div>`:'<p class="muted">No upcoming loaded entries.</p>'}${races.length?`<h3>Race history</h3><div class="loop-capture-list">${races.map(x=>`<article><button data-msos-meet-entry="${esc(x.entry.id||'')}"><b>${esc(x.entry.event||`${x.entry.distance||''} ${x.entry.stroke||''}`)}</b><span>${esc(x.meet.title||x.meet.name||'Meet')} · ${x.race.result_seconds?clock(x.race.result_seconds):'Result saved'}</span><small>${esc([x.race.place?`Place ${x.race.place}`:'',x.race.notes||x.race.round_result||''].filter(Boolean).join(' · '))}</small></button></article>`).join('')}</div>`:''}${ev.length?`<details><summary>Meet evidence · ${ev.length}</summary>${ev.map(x=>`<div class="msos-meet-note"><b>${esc(x.evidence_type||x.type||'Evidence')}</b><small>${esc(x.text||'')}</small></div>`).join('')}</details>`:''}</section>`;wrap.querySelectorAll('[data-msos-meet-entry]').forEach(b=>b.onclick=()=>{if(b.dataset.msosMeetEntry)M.state.settings.currentMeetEntryId=b.dataset.msosMeetEntry;save();go('meet')});return wrap}

  function profileCard(ath,course){const age=M.pathway?.age?.(ath,currentSession()?.identity?.date||new Date().toISOString().slice(0,10)),classes=[ath.current_s_class,ath.current_sb_class,ath.current_sm_class].filter(Boolean).join(' / '),events=[];for(const v of [ath.primary_event,ath.primary_events,ath.preferred_event,ath.preferred_events,ath.events,ath.specialty]){if(Array.isArray(v))events.push(...v.map(text).filter(Boolean));else if(text(v))events.push(text(v))}const rows=[['Squad',ath.squad],['Course',course],['Age',Number.isFinite(age)?age:''],['DOB',ath.date_of_birth],['Classification',classes],['Primary events',[...new Set(events)].join(' · ')]].filter(([,v])=>v!==''&&v!=null),card=document.createElement('section');card.className='page-card msos-profile-card';card.innerHTML=`<div class="eyebrow">SWIMMER PROFILE</div><div class="msos-profile-grid">${rows.map(([k,v])=>`<span><small>${esc(k)}</small><b>${esc(v)}</b></span>`).join('')}</div>`;return card}
  function trainingStatus(ath){try{const today=M.swimmerTrainingBG?.viewFor?.(ath)?.today;if(today){const delivered=Number(today.deliveredMetres),prescribed=Number(today.prescribedMetres);if(['ended-early','delivered-prescription'].includes(today.delivery)&&Number.isFinite(delivered))return`${delivered.toLocaleString()}m recorded`;if(Number.isFinite(prescribed)&&prescribed>0)return`${prescribed.toLocaleString()}m current prescription`;}}catch{}return'Individual prescription';}
  function trainingCard(ath){const s=currentSession(),blockId=M.state.settings.loopAthleteOrigin?.blockId||M.state.settings.boardBlockBySession?.[s?.id],block=(s?.blocks||[]).find(b=>b.id===blockId)||(s?.blocks||[]).find(b=>b.type==='main_set')||(s?.blocks||[])[0],goals=[];for(const v of [ath.primary_goal,ath.goal,ath.goals,ath.target]){if(Array.isArray(v))goals.push(...v.map(text).filter(Boolean));else if(text(v))goals.push(text(v))}const card=document.createElement('section');card.className='page-card msos-training-card';card.innerHTML=`<div class="eyebrow">CURRENT TRAINING</div><h2>${esc(block?.title||'Current session')}</h2><div class="loop-kpis"><span>${esc(trainingStatus(ath))}</span></div>${goals.length?`<h3>Goals / targets</h3><div class="loop-chip-row">${[...new Set(goals)].map(x=>`<span>${esc(x)}</span>`).join('')}</div>`:''}`;return card}

  function classify(node){const t=norm(node?.textContent||'');if(/pathway/.test(t))return'pathway-old';if(/stroke exposure|t400|timed set/.test(t))return'training';if(/performance identity|pb event ranking|event coverage|development/.test(t))return'performance';if(node?.matches?.('[data-loop-athlete-today]'))return'today';return'performance'}
  function activate(shell,tab){const chosen=['today','performance','training','pathway','meet'].includes(tab)?tab:'today';M.state.settings.loopAthleteTab=chosen;shell.querySelectorAll('[data-msos-ath-tab]').forEach(b=>b.classList.toggle('active',b.dataset.msosAthTab===chosen));shell.querySelectorAll('[data-msos-ath-panel]').forEach(p=>p.hidden=p.dataset.msosAthPanel!==chosen)}
  function buildTabs(){
    const h=document.querySelector('#athletesView');if(!h||h.querySelector('[data-msos-ath-shell]'))return;const id=M.state.settings.selectedAthleteId,ath=(M.state.athletes||[]).find(a=>a.id===id);if(!ath)return;
    const head=h.querySelector('.perf-head')||h.firstElementChild,course=M.state.settings.pathwayCourse||currentSession()?.identity?.course||'SCM',nodes=[...h.children].filter(n=>n!==head),shell=document.createElement('section');shell.dataset.msosAthShell='1';shell.className='msos-ath-shell';shell.innerHTML=`<nav class="msos-ath-tabs"><button data-msos-ath-tab="today">Today</button><button data-msos-ath-tab="performance">Performance</button><button data-msos-ath-tab="training">Training</button><button data-msos-ath-tab="pathway">Pathway</button><button data-msos-ath-tab="meet">Meet</button></nav><div class="msos-ath-panels"><div data-msos-ath-panel="today"></div><div data-msos-ath-panel="performance" hidden></div><div data-msos-ath-panel="training" hidden></div><div data-msos-ath-panel="pathway" hidden></div><div data-msos-ath-panel="meet" hidden></div></div>`;if(head)head.insertAdjacentElement('afterend',shell);else h.prepend(shell);
    shell.querySelector('[data-msos-ath-panel="performance"]').append(profileCard(ath,course));shell.querySelector('[data-msos-ath-panel="training"]').append(trainingCard(ath));
    for(const n of nodes){const k=classify(n);if(k==='pathway-old'){n.remove();continue}shell.querySelector(`[data-msos-ath-panel="${k}"]`)?.append(n)}
    if(!shell.querySelector('[data-msos-ath-panel="today"]')?.children.length){const fallback=document.createElement('section');fallback.className='page-card';fallback.innerHTML=`<div class="eyebrow">TODAY</div><h2>${esc(ath.full_name)}</h2><p class="muted">No session-specific swimmer evidence is loaded for the selected session.</p>`;shell.querySelector('[data-msos-ath-panel="today"]').append(fallback)}
    shell.querySelector('[data-msos-ath-panel="pathway"]').append(buildPathway(ath,course));shell.querySelector('[data-msos-ath-panel="meet"]').append(buildMeet(ath));
    shell.querySelectorAll('[data-msos-ath-tab]').forEach(b=>b.onclick=()=>activate(shell,b.dataset.msosAthTab));
    const today=shell.querySelector('[data-msos-ath-panel="today"]');today?.querySelector('[data-loop-performance]')?.addEventListener('click',e=>{e.preventDefault();activate(shell,'performance')});today?.querySelector('[data-loop-training]')?.addEventListener('click',e=>{e.preventDefault();activate(shell,'training')});today?.querySelector('[data-loop-ath-meet]')?.addEventListener('click',e=>{e.preventDefault();activate(shell,'meet')});
    const origin=M.state.settings.loopAthleteOrigin||{},fromBoard=!!(origin.sessionId&&currentSession()?.id===origin.sessionId&&Date.now()-Date.parse(origin.openedAt||0)<6*60*60*1000);activate(shell,fromBoard?'today':(M.state.settings.loopAthleteTab||'performance'));
  }

  S.realMilestones=realMilestones;S.pathwayEvents=pathwayEvents;
  S.poolsidePathwayAnswer=(ath,event)=>{const pb=event?.pb;if(!ath||!pb)return null;const pbSeconds=Number(pb.result_seconds),milestones=realMilestones(event);return Number.isFinite(pbSeconds)?{event:`${pb.course||''} ${pb.distance} ${pb.stroke}`.trim(),pbSeconds,milestones,next:milestones.find(x=>!x.achieved)||null}:null};
  if(M.correct)M.correct.poolsidePathwayAnswer=S.poolsidePathwayAnswer;

  const baseBoard=UI.renderBoard?.bind(UI),baseAthletes=UI.renderAthletes?.bind(UI);
  if(baseBoard)UI.renderBoard=()=>{baseBoard();installDeckPills()};
  if(baseAthletes)UI.renderAthletes=()=>{baseAthletes();installDeckPills();buildTabs()};
  if(M.performanceUI)M.performanceUI.render=UI.renderAthletes;
  let obs=null;const watch=()=>{const h=document.querySelector('#athletesView');if(!h||obs)return;obs=new MutationObserver(()=>queueMicrotask(buildTabs));obs.observe(h,{childList:true,subtree:false})};watch();
  addEventListener('msos:evidence-ready',()=>{if(M.state.settings.view==='athletes')queueMicrotask(buildTabs)});
  addEventListener('msos:data-updated',()=>{if(M.state.settings.view==='athletes')queueMicrotask(buildTabs)});
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{if(M.state.settings.view==='board')installDeckPills();watch()},{once:true});else if(M.state.settings.view==='board')installDeckPills();
  S.checks=()=>({build:M.BUILD,deckPills:'header',tabs:['today','performance','training','pathway','meet'],pathway:'real standards only',preservesCoachLoop:true});
})(globalThis);
