'use strict';
(function(g){
  const M=g.MSOS4,E=g.MSOSEngines?.Evidence;if(!M||!E)return;
  const W=M.waPointsEngine={build:'v4-wa-points-20260820aa'};
  const cache=new WeakMap(),sexCache=new WeakMap(),text=v=>String(v??'').replace(/\s+/g,' ').trim();
  const sexKey=v=>{const s=text(v).toUpperCase();if(/^(?:M|MALE|BOY|BOYS|MEN)$/.test(s))return'M';if(/^(?:F|FEMALE|GIRL|GIRLS|WOMEN)$/.test(s))return'F';if(/^(?:OPEN|MIXED|ALL)$/.test(s))return'OPEN';return'';};
  function activeRows(state=M.state){const registry=M.dataRegistry?.activeRowsSync?.('wa_points')||[];if(registry.length&&M.dataRegistry?.activeMeta?.('wa_points'))return registry;const seed=M.waBaseTimesSeed?.rows||[];if(seed.length)return seed;return[...(state?.worldAquaticsBaseTimes||[]),...(state?._refs?.world_aquatics_base_times||[])];}
  function activeMeta(){return M.dataRegistry?.activeMeta?.('wa_points')||null;}
  function signature(state){const a=activeMeta(),rows=activeRows(state);return`${a?.id||M.waBaseTimesSeed?.version||'legacy'}|${a?.version||''}|${rows.length}|${state?._evidenceBridge?.hydratedAt||''}`;}
  function index(state=M.state){const sig=signature(state),old=cache.get(state);if(old?.sig===sig)return old;const map=new Map(),rows=activeRows(state);for(const r of rows){if(!r||r.active===false)continue;const c=E.course(r)||text(r.course||r.pool_course).toUpperCase(),d=E.distance(r)||Number(r.distance||r.event_distance),st=E.rowStroke(r)||E.stroke(r.stroke||r.event_stroke),sx=sexKey(r.sex||r.gender),b=Number(r.base_seconds??r.base_time_seconds??r.base_time??r.seconds);if(!c||!d||!st||!b)continue;const row={...r,course:c,distance:d,stroke:st,sex:sx||'OPEN',base_seconds:b};const k=`${c}|${d}|${st}|${sx||'OPEN'}`;if(!map.has(k))map.set(k,row);}const out={sig,map,rows};cache.set(state,out);return out;}
  function calculate(baseSeconds,resultSeconds){const b=Number(baseSeconds),t=Number(resultSeconds);if(!(b>0&&t>0))return null;return Math.floor(1000*Math.pow(b/t,3));}
  function timeForPoints(baseSeconds,points){const b=Number(baseSeconds),p=Number(points);if(!(b>0&&p>0))return null;const t=b/Math.cbrt(p/1000);return Number.isFinite(t)&&t>0?t:null;}
  function athleteSex(ath,row,state=M.state){let sx=sexKey(ath?.sex||ath?.gender||ath?.gender_code||row?.sex||row?.gender||row?.gender_code||row?.source_sex);if(sx)return sx;if(!state||!ath)return'';let byState=sexCache.get(state);if(!byState){byState=new Map();sexCache.set(state,byState);}const k=String(ath.id||ath.athlete_id||E.key?.(ath.full_name)||'');if(k&&byState.has(k))return byState.get(k);try{for(const r of E.pbRows?.(ath,state)||[]){sx=sexKey(r?.sex||r?.gender||r?.gender_code||r?.source_sex);if(sx)break;}}catch{}if(k)byState.set(k,sx||'');return sx||'';}
  function baseFor(ath,row,state=M.state){const c=E.course(row)||text(row?.course||row?.pool_course).toUpperCase(),d=E.distance(row)||Number(row?.distance||row?.event_distance),st=E.rowStroke(row)||E.stroke(row?.stroke||row?.event_stroke),sx=athleteSex(ath,row,state),idx=index(state).map;return(sx&&idx.get(`${c}|${d}|${st}|${sx}`))||idx.get(`${c}|${d}|${st}|OPEN`)||null;}
  function pointsFor(ath,row,state=M.state){const t=E.seconds(row),base=baseFor(ath,row,state),meta=activeMeta();if(base){const points=calculate(base.base_seconds,t);return Number.isFinite(points)?{points,baseSeconds:Number(base.base_seconds),tableVersion:meta?.version||base.table_version||base.version||M.waBaseTimesSeed?.version||'',datasetId:meta?.id||'',source:meta?.source||base.source||base.source_name||'World Aquatics base time',calculated:true,sex:athleteSex(ath,row,state)}:null;}const stored=E.points(row);return Number.isFinite(stored)&&stored>0?{points:Math.floor(stored),baseSeconds:null,tableVersion:'stored-result',datasetId:'',source:'Stored result points',calculated:false,sex:athleteSex(ath,row,state)}:null;}
  function equivalentTime(ath,{course,distance,stroke,points}={},state=M.state){const row={course:String(course||'').toUpperCase(),distance:Number(distance),stroke:E.stroke(stroke||'')},base=baseFor(ath,row,state),seconds=base?timeForPoints(base.base_seconds,points):null,meta=activeMeta();return seconds?{seconds,points:Number(points),baseSeconds:Number(base.base_seconds),course:row.course,distance:row.distance,stroke:row.stroke,tableVersion:meta?.version||base.table_version||base.version||M.waBaseTimesSeed?.version||'',datasetId:meta?.id||'',source:meta?.source||base.source||base.source_name||'World Aquatics base time',sex:athleteSex(ath,row,state)}:null;}
  function tableInfo(state=M.state){const meta=activeMeta(),rows=activeRows(state);return{active:!!rows.length,datasetId:meta?.id||'',version:meta?.version||rows[0]?.table_version||rows[0]?.version||M.waBaseTimesSeed?.version||'',effectiveFrom:meta?.effectiveFrom||rows[0]?.effective_from||'',source:meta?.source||rows[0]?.source||M.waBaseTimesSeed?.source||'',rows:rows.length,builtIn:!meta&&!!M.waBaseTimesSeed?.rows?.length};}
  function invalidate(state=M.state){if(state&&typeof state==='object'){cache.delete(state);sexCache.delete(state);}}
  function installPathway(){const P=M.pathway;if(!P)return;P._waPointsEngineInstalled=true;P.base=(ath,pb)=>baseFor(ath,pb,M.state);P.points=(ath,pb)=>{const para=Number(pb?.world_para_points||pb?.para_points);if(para>0)return{value:Math.floor(para),label:'World Para',source:'result'};if(P.isPara?.(ath))return{value:null,label:'World Para',source:'classification-specific point model required'};const info=pointsFor(ath,pb,M.state);return info?{value:info.points,label:'WA',source:info.calculated?'MSOS WA calculator':'stored result',baseSeconds:info.baseSeconds,tableVersion:info.tableVersion,referenceSource:info.source}:{value:null,label:'WA',source:'base time not loaded'};};P.pointSteps=(ath,pb,count=2)=>{const pt=P.points(ath,pb);if(pt.label!=='WA'||!pt.value||!pt.baseSeconds)return[];const first=Math.ceil((pt.value+1)/25)*25,steps=[];for(let i=0;i<count;i++){const points=first+i*25,seconds=timeForPoints(pt.baseSeconds,points);steps.push({points,seconds})}return steps;};}
  W.activeRows=activeRows;W.activeMeta=activeMeta;W.index=index;W.calculate=calculate;W.timeForPoints=timeForPoints;W.baseFor=baseFor;W.pointsFor=pointsFor;W.equivalentTime=equivalentTime;W.tableInfo=tableInfo;W.invalidate=invalidate;W.sexKey=sexKey;W.athleteSex=athleteSex;W.installPathway=installPathway;
  installPathway();g.addEventListener?.('msos:data-updated',e=>{if(!e.detail?.type||e.detail.type==='wa_points'){invalidate();installPathway();}});g.addEventListener?.('msos:evidence-ready',()=>invalidate());
})(globalThis);
