'use strict';
(function(root){
  const M=root.MSOSEngines||{},App=root.MSOSAppComposition,Nav=root.MSOSNavigationState,Storage=root.MSOSAssemblyStorage,Loader=root.MSOSAssemblyDataLoader,ProgrammeData=root.MSOSAssemblyProgrammeData,Shell=root.MSOSAssemblyShellModel,Renderer=root.MSOSAssemblyRenderer,BoardRenderer=root.MSOSUI?.BoardRenderer,BoardController=root.MSOSUI?.BoardController,CommandOwners=root.MSOSBoardCommandOwners,PoolsideActions=root.MSOSPoolsideActions,PoolsideRuntime=root.MSOSAssemblyPoolsideRuntime,PoolsidePresenter=root.MSOSAssemblyPoolsidePresenter,Programme=root.MSOS_ASSEMBLY_PROGRAMME;
  const VERSION='1.4.0';
  const state={app:null,nav:null,shell:null,navStore:null,root:null,panelRoot:null,poolRuntime:null,poolActions:null,commandOwners:null,boardController:null,presenter:null,programmeData:null,notice:'',booted:false,backGuard:false};
  const localDate=()=>{const d=new Date(),parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Pacific/Auckland',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(d),get=t=>parts.find(x=>x.type===t)?.value||'';return`${get('year')}-${get('month')}-${get('day')}`};
  function requireDeps(){const missing=[];for(const [k,v] of Object.entries({App,Nav,Storage,Loader,ProgrammeData,Shell,Renderer,BoardRenderer,BoardController,CommandOwners,PoolsideActions,PoolsideRuntime,PoolsidePresenter,Programme,EntityRegistry:M.EntityRegistry,SessionSchedule:M.SessionSchedule,SessionTruth:M.SessionTruth,SessionLifecycle:M.SessionLifecycle,SessionEdit:M.SessionEdit,DeliveredSession:M.DeliveredSession,EvidenceRetrieval:M.EvidenceRetrieval,EvidencePublication:M.EvidencePublication,Timing:M.Timing,TestProtocol:M.TestProtocol,TestResultInput:M.TestResultInput,StandardsRecords:M.StandardsRecords,ResultsPathway:M.ResultsPathway,Targets:M.Targets,Adaptation:M.Adaptation,Attendance:M.Attendance,CaptureEvidence:M.CaptureEvidence,BoardProjection:M.BoardProjection}))if(!v)missing.push(k);if(missing.length)throw new Error(`Assembly browser missing modules: ${missing.join(', ')}`)}
  function persistNavigation(){if(state.navStore&&state.nav)state.navStore.save(state.nav.snapshot())}
  function setNotice(message=''){state.notice=String(message||'');render()}
  function scheduleApi(){return{day:d=>state.app.day(d)}}
  function armBrowserBack(){if(state.backGuard)return;history.replaceState({msosAssemblyRoot:true},'');history.pushState({msosAssemblyGuard:true},'');state.backGuard=true}
  function rearmBrowserBack(){history.pushState({msosAssemblyGuard:true},'');state.backGuard=true}
  function setupPoolside(){state.poolRuntime=PoolsideRuntime.create({app:state.app});state.presenter=PoolsidePresenter.create({host:state.panelRoot});state.poolActions=PoolsideActions.create({runtime:state.poolRuntime,onChange:()=>render(),present:panel=>state.presenter.show(panel)});state.commandOwners=CommandOwners.create({runtime:state.poolRuntime,openers:state.poolActions.openers()});state.boardController=BoardController.create({root:state.root,commands:state.commandOwners.commands(),onError:error=>setNotice(error.message)}).bind()}
  async function boot(){
    requireDeps();state.root=document.getElementById('assembly-root');state.panelRoot=document.getElementById('assembly-panel-root');if(!state.root||!state.panelRoot)throw new Error('Assembly root element missing');
    const keys=Storage.keys('msos.assembly.v1'),resourceCache=new Storage.ResourceCache({storage:localStorage,key:keys.resources});
    const [calendar,programmeData]=await Promise.all([Loader.loadCalendar({fetchImpl:fetch.bind(root),cache:resourceCache,url:'../monthly_calendar.json'}),ProgrammeData.loadProgrammeData({fetchImpl:fetch.bind(root),cache:resourceCache,storage:localStorage,config:root.MCLAY_CONFIG||{}})]);
    state.programmeData=programmeData;state.notice=[calendar.warning,programmeData.warning].filter(Boolean).join(' ');
    const scheduleStorage=new Storage.JsonStorageAdapter({storage:localStorage,key:keys.schedule}),lifecycleStorage=new Storage.JsonStorageAdapter({storage:localStorage,key:keys.lifecycle}),attendanceStorage=new Storage.JsonStorageAdapter({storage:localStorage,key:keys.attendance}),captureStorage=new Storage.JsonStorageAdapter({storage:localStorage,key:keys.capture}),deliveryStorage=new Storage.JsonStorageAdapter({storage:localStorage,key:keys.delivery}),timingStorage=new Storage.JsonStorageAdapter({storage:localStorage,key:keys.timing}),protocolStorage=new Storage.JsonStorageAdapter({storage:localStorage,key:keys.protocols}),testResultStorage=new Storage.JsonStorageAdapter({storage:localStorage,key:keys.testResults});state.navStore=new Storage.JsonStorageAdapter({storage:localStorage,key:keys.navigation});
    let navState=null;try{navState=state.navStore.load()}catch(error){throw new Error(`Navigation state could not be restored safely: ${error.message}`)}state.nav=Nav.create({state:navState,month:localDate().slice(0,7)});
    state.app=App.create({scheduleStorage,lifecycleStorage,attendanceStorage,captureStorage,deliveryStorage,timingStorage,protocolStorage,testResultStorage,calendarSources:[calendar.value],evidenceSources:programmeData.evidenceSources,profiles:programmeData.profiles,standards:programmeData.standards,baseTimes:programmeData.baseTimes,clubs:[Programme.club],squads:Programme.squads,clock:()=>new Date().toISOString()});
    state.shell=Shell.create({schedule:scheduleApi(),navigation:state.nav,today:localDate});setupPoolside();state.root.addEventListener('click',onClick);root.addEventListener('popstate',onBrowserBack);document.addEventListener('visibilitychange',onVisibility);armBrowserBack();state.nav.markInteractive();persistNavigation();state.booted=true;render();
  }
  function wrap(body,subtitle){const route=state.nav.route();state.root.innerHTML=Renderer.shell({subtitle,body,route,notice:state.notice})}
  function render(){if(!state.root||!state.nav||!state.shell)return;try{const route=state.nav.route();if(route.type!=='board'&&state.presenter?.panel)state.presenter.close();if(route.type==='calendar')return wrap(Renderer.renderCalendar(state.shell.calendar(route.month)),'Coach · Calendar');if(route.type==='day')return wrap(Renderer.renderDay(state.shell.day(route.date)),'Coach · Day');if(route.type==='board'){const occ=state.app.occurrenceForSession(route.sessionId);if(!occ||occ.id!==route.occurrenceId)throw new Error('Board route no longer matches its scheduled occurrence');const selected=state.app.selectedSession();if(selected?.id!==route.sessionId)throw new Error('Board route does not match selected session; reopen it from the Day view');const model=state.app.boardForSession(route.sessionId),html=BoardRenderer.renderBoard(model),delivery=state.app.deliveryForSession(route.sessionId);return wrap(Renderer.renderBoard({boardHtml:html,occurrence:occ,delivery}),'Coach · Board')}if(route.type==='detail'){const frame=state.nav.current();if(frame.detailType==='session-intake'){const day=state.shell.day(frame.date),item=day.items.find(x=>x.id===frame.detailId);if(!item)throw new Error('Session intake item is no longer on this date');return wrap(Renderer.renderIntake({item,availableDaySlots:frame.meta.availableDaySlots||[],selectedSlotIds:frame.meta.selectedSlotIds||[] }),'Coach · Session intake')}if(frame.detailType==='session-source'){const draft=state.app.portal.client('calendar-surface').query('session-lifecycle','getDraft',{args:[frame.detailId]});if(!draft)throw new Error('Session draft is no longer available');return wrap(Renderer.renderTextEntry({draftId:draft.id,title:draft.identity?.title,source:draft.source}),'Coach · Session entry')}}wrap(Renderer.renderError(`Unsupported assembly route: ${route.type}`),'Coach')}catch(error){wrap(Renderer.renderError(error.message),'Coach · Error')}}
  function selectedSlotIds(){return [...state.root.querySelectorAll('input[name="slot"]:checked')].map(x=>x.value)}
  function selectedDaySlots(){const day=state.shell.day(state.nav.route().date);return day.items.filter(x=>x.type==='slot').map(x=>({id:x.id,squadEntries:x.squadEntries,start:x.start,end:x.end,venue:x.venue,course:x.course,dayPart:x.dayPart,kind:x.kind}))}
  function openUnboundItem(result){const route=state.nav.route(),available=result.availableDaySlots||selectedDaySlots(),ids=result.candidateSlots||[result.item.id];state.nav.openDetail({detailType:'session-intake',detailId:result.item.id,date:route.date,meta:{availableDaySlots:available,selectedSlotIds:ids}});persistNavigation();render()}
  function backToDay(){while(state.nav.route().type!=='day'&&state.nav.canBack())state.nav.back()}
  function internalBack(){if(state.presenter?.panel){state.presenter.close();return{handled:true,panel:true}}const result=state.nav.back();if(result.handled){persistNavigation();render()}return result}
  function onClick(event){const button=event.target.closest('[data-app-action]');if(!button)return;const action=button.dataset.appAction;try{if(action==='back')return internalBack();if(action==='calendar'){state.nav.openCalendar({month:state.nav.route().month||localDate().slice(0,7)});persistNavigation();return render()}if(action==='current-board'){const rec=state.app.selectedSession(),sessionId=rec?.id,occ=sessionId?state.app.occurrenceForSession(sessionId):null;if(!sessionId||!occ)return setNotice('No accepted session is selected yet.');state.nav.openCalendar({month:occ.date.slice(0,7)});state.nav.openDate(occ.date);state.nav.openBoard({date:occ.date,occurrenceId:occ.id,sessionId});persistNavigation();return render()}if(action==='month'){state.shell.changeMonth(button.dataset.month);persistNavigation();return render()}if(action==='open-date'){state.shell.selectDate(button.dataset.date);persistNavigation();return render()}if(action==='open-item'){const result=state.shell.openItem(button.dataset.itemId);if(result.action==='board')state.app.selectSession(result.item.sessionId);persistNavigation();return result.action==='board'?render():openUnboundItem(result)}if(action==='intake-text'){const ids=selectedSlotIds();if(!ids.length)throw new Error('Choose at least one squad/session slot');const frame=state.nav.current(),day=state.shell.day(frame.date),first=day.items.find(x=>ids.includes(x.id)),title=`${first?.dayPart||''} · ${(ids.map(id=>day.items.find(x=>x.id===id)?.squadEntries?.[0]?.squadLabel).filter(Boolean)).join('+')}`.trim();const begun=state.app.beginFromSlots(ids,{inputMode:'text',title});state.nav.openDetail({detailType:'session-source',detailId:begun.draft.id,date:frame.date,occurrenceId:begun.occurrence.id,meta:{}});persistNavigation();return render()}if(action==='cancel-draft'){const frame=state.nav.current();if(frame.detailType==='session-source')state.app.discardDraft(frame.detailId,{retireOccurrence:true,note:'Coach cancelled session intake'});backToDay();persistNavigation();return render()}if(action==='accept-draft'){const draftId=button.dataset.draftId,source=state.root.querySelector('#assembly-session-source')?.value||'';state.app.updateDraft(draftId,{source});const accepted=state.app.acceptDraft(draftId);backToDay();state.nav.openBoard({date:state.nav.route().date,occurrenceId:accepted.bound.id,sessionId:accepted.record.id});persistNavigation();state.notice='';return render()}if(action==='add-custom')return setNotice('Custom calendar slot authoring is not connected in this assembly yet. Published schedule truth has not been changed.')}catch(error){setNotice(error.message)}}
  function onBrowserBack(){if(!state.nav)return;state.backGuard=false;if(state.presenter?.panel){state.presenter.close();rearmBrowserBack();return}if(state.nav.canBack()){state.nav.back();persistNavigation();render();rearmBrowserBack();return}history.back()}
  function onVisibility(){if(document.visibilityState==='visible'&&state.nav){state.nav.resume();render()}}
  function fatal(error){const rootEl=document.getElementById('assembly-root');if(rootEl)rootEl.innerHTML=Renderer?.shell?Renderer.shell({subtitle:'Assembly stopped',body:Renderer.renderError(error.message),route:{type:'calendar'}}):`<pre>${String(error.stack||error)}</pre>`;console.error(error)}
  root.addEventListener('DOMContentLoaded',()=>boot().catch(fatal),{once:true});root.MSOSAssemblyBrowser={VERSION,state,boot,render,internalBack,onBrowserBack,setupPoolside};
})(typeof globalThis!=='undefined'?globalThis:this);
